# -*- coding: utf-8 -*-
"""
scripts/course2_data_bai4.py
Exhaustive Deep-Curriculum Slide Blueprints for BÀI 4 (Make Slide Pro V9.1).
30%-50% High-Resolution Visual Illustrations, Native Charts, Zero AI Slop, Zero Watermarks.
"""

from typing import Any, Dict, List


def get_slides_bai_4() -> List[Dict[str, Any]]:
    return [ { 'slide_id': 'SLIDE_01',
    'role': 'COVER',
    'section': 'TỔNG QUAN CHUYÊN ĐỀ',
    'assertion_title': 'BÀI 4: DỊCH VỤ CHĂM SÓC SỨC KHỎE SINH SẢN VỊ THÀNH NIÊN, THANH NIÊN',
    'primary_claim': 'Khung nghiệp vụ y tế dân số toàn diện về chăm sóc sức khỏe sinh sản thân thiện, giáo dục giới '
                     'tính học đường và can thiệp giảm mang thai ngoài ý muốn.',
    'visual_job': 'HERO_TITLE',
    'visual_anchor': 'BRAND_COVER',
    'transition': 'fade',
    'transition_duration': 0.65,
    'illustration': 'illustration_bai_4.jpg',
    'speaker_notes': 'Kính chào quý học viên, hôm nay chúng ta nghiên cứu chuyên đề Bài 4: Dịch vụ chăm sóc sức khỏe '
                     'sinh sản vị thành niên, thanh niên.',
    'source_footer': 'Tài liệu đào tạo chuẩn hóa: Bài 4. Dịch vụ CSSKSS vị thành niên-thanh niên.docx',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_02',
    'role': 'CONTENT',
    'section': 'MỤC TIÊU BÀI HỌC',
    'assertion_title': 'Chuẩn Đầu Ra 4 Khối Năng Lực Cốt Lõi Về Chăm Sóc SKSS Vị Thành Niên & Thanh Niên',
    'primary_claim': 'Trang bị phương pháp luận tiếp cận thân thiện, làm chủ 9 chủ đề truyền thông can thiệp và kỹ '
                     'năng điều hành đa tuyến.',
    'visual_job': 'CONTAINER_BENTO_COMPLEX',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Khái Niệm & Mô Hình Thân Thiện',
                 'text': 'Trình bày chuẩn xác khái niệm SKSS, độ tuổi VTN (10-18), TN (16-24) và tiêu chuẩn dịch vụ y '
                         'tế thân thiện (AFHS) của WHO.',
                 'icon': 'book-open'},
               { 'title': '2. Khách Hàng & Năng Lực Cung Cấp',
                 'text': 'Phân tích biến đổi tâm sinh lý 4 giai đoạn phát triển và chuẩn kỹ năng giao tiếp thấu cảm, '
                         'không phán xét của cán bộ y tế.',
                 'icon': 'users'},
               { 'title': '3. Làm Chủ 9 Chủ Đề Chuyên Môn',
                 'text': 'Thực hành thuần thục nội dung giáo dục: tuổi dậy thì, tình bạn tình yêu, tình dục an toàn, '
                         'tránh thai, STIs/HIV, tảo hôn, xâm hại và kỹ năng sống.',
                 'icon': 'activity'},
               { 'title': '4. Quản Lý & Mục Tiêu Chiến Lược 2030',
                 'text': 'Triển khai hiệu quả Đề án QĐ 5914/QĐ-BYT và Luật Dân số số 113/2025/QH15 nhằm giảm 2/3 số ca '
                         'mang thai ngoài ý muốn ở VTN.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Khung chuẩn đầu ra chuyên đề đào tạo SKSS VTN-TN',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_03',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Khái Niệm Sức Khỏe Sinh Sản: Từ Pháp Lệnh Dân Số Đến Tuyên Bố Cairo 1994',
    'primary_claim': 'SKSS là trạng thái hài hòa toàn diện về thể chất, tinh thần và xã hội chứ không đơn thuần là '
                     'không có bệnh tật.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Định Nghĩa Hội Nghị Cairo 1994 (ICPD)',
                 'text': 'Sức khỏe sinh sản là một trạng thái khỏe mạnh, hài hòa về thể chất, tinh thần và xã hội '
                         'trong tất cả mọi khía cạnh liên quan đến hoạt động và chức năng của hệ thống sinh sản.',
                 'icon': 'globe'},
               { 'title': 'Pháp Lệnh Dân Số Việt Nam',
                 'text': 'Sức khỏe sinh sản là sự thể hiện các trạng thái về thể chất, tinh thần và xã hội liên quan '
                         'đến hoạt động và chức năng sinh sản của mỗi người trong mọi chu kỳ vòng đời.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tuyên bố ICPD Cairo 1994 & Pháp lệnh Dân số Việt Nam',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_04',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Phân Định Nhóm Tuổi: Vị Thành Niên (10-18) & Thanh Niên Trẻ (16-24)',
    'primary_claim': 'Khung phân định độ tuổi y tế dân số tại Quyết định số 4128/QĐ-BYT giúp xác định chính xác đối '
                     'tượng can thiệp.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Vị Thành Niên (10 - 18 Tuổi)',
                 'text': 'Thời kỳ quá độ từ trẻ em sang người lớn; các em trải qua bước nhảy vọt về thể chất, biến đổi '
                         'sinh lý sâu sắc nhưng nhận thức xã hội chưa hoàn thiện.',
                 'icon': 'users'},
               { 'title': 'Thanh Niên Trẻ (16 - 24 Tuổi)',
                 'text': 'Giai đoạn bắt đầu độc lập kinh tế, học tập đại học hoặc đi làm; mở rộng quan hệ xã hội, bước '
                         'vào tình yêu đôi lứa và chuẩn bị xác lập hôn nhân pháp lý.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quyết định số 4128/QĐ-BYT ngày 29/07/2016 của Bộ Y tế',
    'illustration': 'illustration_bai_4.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_05',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Bản Chất Của Dịch Vụ Chăm Sóc Sức Khỏe Sinh Sản Vị Thành Niên, Thanh Niên',
    'primary_claim': 'Là tập hợp có hệ thống các biện pháp kỹ thuật, truyền thông và tư vấn y tế chuyên biệt cho tuổi '
                     'trẻ.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Phòng Ngừa Nguy Cơ (Prevention)',
                 'text': 'Chủ động trang bị kiến thức, kỹ năng sống giúp thanh thiếu niên tự phòng tránh mang thai '
                         'sớm, phá thai không an toàn và STIs/HIV.',
                 'icon': 'shield'},
               { 'title': 'Giải Quyết Khủng Hoảng (Resolution)',
                 'text': 'Thăm khám, tư vấn giải tỏa sang chấn tâm lý, điều trị viêm nhiễm sinh dục và hỗ trợ y tế '
                         'khẩn cấp khi có rủi ro xảy ra.',
                 'icon': 'activity'},
               { 'title': 'Nâng Cao Chất Lượng Sống (Wellness)',
                 'text': 'Xây dựng lối sống lành mạnh, quan hệ tình bạn trong sáng, tình dục đồng thuận an toàn và tôn '
                         'trọng bình đẳng giới.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 4. Mục 1 - Khái niệm dịch vụ CSSKSS VTN-TN',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_06',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Đặc Điểm Tâm Sinh Lý Tuổi Mới Lớn: Năng Động Song Hành Cùng Rủi Ro',
    'primary_claim': 'Đặc tính thích khám phá, tò mò thử nghiệm khiến các bạn trẻ dễ bị tổn thương nếu thiếu sự đồng '
                     'hành y tế.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Thích Thử Nghiệm Khám Phá',
                 'text': 'Muốn khẳng định cái tôi cá nhân, tò mò về cơ thể bạn khác giới và dễ bị cuốn vào các trào '
                         'lưu quan hệ tình dục sớm.',
                 'icon': 'activity'},
               { 'title': 'Nhạy Cảm & Dễ Tự Ái',
                 'text': 'Tâm lý dao động, lo âu về ngoại hình (mụn trứng cá, cân nặng), dễ mặc cảm và khép kín khi bị '
                         'người lớn chỉ trích.',
                 'icon': 'heart'},
               { 'title': 'Áp Lực Từ Nhóm Bạn Cùng Lứa',
                 'text': 'Ý kiến của bạn bè cùng trang lứa trở nên quan trọng hơn lời khuyên cha mẹ; nguy cơ a dua '
                         'theo các hành vi thiếu an toàn.',
                 'icon': 'users'},
               { 'title': 'Nhu Cầu Môi Trường Hỗ Trợ',
                 'text': 'Cần môi trường an toàn, thông tin chính xác, kỹ năng sống vững vàng và dịch vụ y tế tư vấn '
                         'bảo mật, không phán xét.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Đặc điểm tâm lý học lứa tuổi - BÀI 4. Mục 1',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_07',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': "Tiêu Chuẩn 'Dịch Vụ Sức Khỏe Thân Thiện' (AFHS) Theo Chuẩn Tổ Chức Y Tế Thế Giới",
    'primary_claim': 'Dịch vụ thân thiện là dịch vụ dễ tiếp cận, chi phí hợp lý, an toàn và đáp ứng tối đa sự chấp '
                     'nhận của giới trẻ.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Dễ Tiếp Cận (Accessible)',
                 'text': 'Vị trí cơ sở thuận tiện, giờ mở cửa linh hoạt ngoài giờ học/giờ làm việc, thủ tục tiếp đón '
                         'đơn giản và nhanh chóng.',
                 'icon': 'map-pin'},
               { 'title': 'Chi Phí Phù Hợp (Affordable)',
                 'text': 'Cung cấp miễn phí hoặc mức phí phù hợp với khả năng tài chính của học sinh, sinh viên; không '
                         'phân biệt giàu nghèo.',
                 'icon': 'award'},
               { 'title': 'Bảo Mật & Riêng Tư (Confidential)',
                 'text': 'Bảo đảm tuyệt đối quyền riêng tư; thông tin thăm khám không bị tiết lộ cho nhà trường hay '
                         'gia đình nếu không có sự đồng ý.',
                 'icon': 'lock'},
               { 'title': 'Phương Cách Chấp Nhận (Acceptable)',
                 'text': 'Không gian trang trí trẻ trung, tài liệu truyền thông sinh động, cán bộ y tế niềm nở, thân '
                         'tình như người anh/chị đi trước.',
                 'icon': 'smile'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'WHO - Adolescent Friendly Health Services Standards',
    'illustration': 'ai_bai_4_distribution.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_08',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Yêu Cầu Năng Lực Cán Bộ: Thái Độ Tích Cực, Cởi Mở & Bảo Vệ Quyền Trẻ Em',
    'primary_claim': 'Kỹ năng thấu cảm và nhạy cảm giới của người cung cấp dịch vụ quyết định sự thành bại của can '
                     'thiệp.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Xóa Bỏ Định Kiến & Phán Xét',
                 'text': 'Không chỉ trích, không lên án khi trẻ vị thành niên trót quan hệ tình dục sớm hay mang thai; '
                         'lắng nghe với trái tim bao dung.',
                 'icon': 'heart'},
               { 'title': 'Nhạy Cảm Với Nhóm Yếu Thế',
                 'text': 'Đặc biệt quan tâm, hỗ trợ tế nhị cho thanh thiếu niên khuyết tật, thanh niên di cư làm công '
                         'nhân, trẻ em đường phố và nhóm LGBTQ+.',
                 'icon': 'users'},
               { 'title': 'Bảo Đảm Quyền Khách Hàng',
                 'text': 'Tôn trọng quyền được cung cấp thông tin, quyền được bảo mật đời tư và quyền tự chủ đưa ra '
                         'quyết định chăm sóc sức khỏe.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 4. Mục 1 - Yêu cầu đối với người cung cấp dịch vụ',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_09',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Khung Phân Loại 3 Chiều Hệ Thống Dịch Vụ SKSS Vị Thành Niên',
    'primary_claim': 'Hệ thống hóa dịch vụ theo độ tuổi sinh học, giới tính và danh mục chuyên đề can thiệp.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': '1. Theo Độ Tuổi Phát Triển',
                 'text': 'Chia tách 4 phân kỳ: 10-13 tuổi (đầu dậy thì), 14-16 tuổi (giữa dậy thì), 17-18 tuổi (cuối '
                         'dậy thì), 19-24 tuổi (thanh niên trẻ).',
                 'icon': 'clock'},
               { 'title': '2. Theo Giới Tính Tiếp Cận',
                 'text': 'Dịch vụ dành riêng cho bạn nam (chăm sóc cơ quan sinh dục nam, mộng tinh) và bạn nữ (kinh '
                         'nguyệt, vệ sinh phụ khoa).',
                 'icon': 'users'},
               { 'title': '3. Theo Nội Dung Can Thiệp',
                 'text': '9 chủ đề nghiệp vụ chuẩn hóa ban hành theo Quyết định số 2885/QĐ-BYT của Bộ Y tế.',
                 'icon': 'layers'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Phân loại dịch vụ SKSS VTN-TN - BÀI 4. Mục 2',
    'illustration': 'ai_bai_4_industrial.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_10',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Phân Loại Theo 4 Giai Đoạn Tuổi: Tương Thích Nhu Cầu Phát Triển Tự Nhiên',
    'primary_claim': 'Mỗi giai đoạn tuổi có đặc thù nhận thức và sinh học riêng biệt, đòi hỏi nội dung giáo dục tương '
                     'ứng.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Giai Đoạn 10 - 13 Tuổi',
                 'text': 'Khởi đầu dậy thì; nội dung trọng tâm là giải thích biến đổi cơ thể, hướng dẫn vệ sinh kinh '
                         'nguyệt và mộng tinh.',
                 'icon': 'heart'},
               { 'title': 'Giai Đoạn 14 - 16 Tuổi',
                 'text': 'Bùng nổ cảm xúc; trọng tâm là kỹ năng xây dựng tình bạn, tình yêu trong sáng, tình dục an '
                         'toàn và phòng tránh xâm hại.',
                 'icon': 'activity'},
               { 'title': 'Giai Đoạn 17 - 18 Tuổi',
                 'text': 'Chuẩn bị bước vào đời; trọng tâm là định hướng nghề nghiệp, phòng tránh mang thai ngoài ý '
                         'muốn, phá thai an toàn.',
                 'icon': 'book-open'},
               { 'title': 'Giai Đoạn 19 - 24 Tuổi',
                 'text': 'Thanh niên độc lập; trọng tâm là khám sức khỏe tiền hôn nhân, các biện pháp tránh thai hiện '
                         'đại và lập kế hoạch gia đình.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Khung can thiệp theo lứa tuổi - BÀI 4',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_11',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Phân Loại Theo Giới Tính: Tiếp Cận Nhạy Cảm Nam & Nữ Vị Thành Niên',
    'primary_claim': 'Tháo gỡ những băn khoăn thầm kín riêng biệt của từng giới bằng không gian tư vấn chuyên biệt.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Góc Tư Vấn Dành Cho Bạn Nam',
                 'text': 'Tư vấn hiện tượng xuất tinh lần đầu (mộng tinh), thủ dâm an toàn, vệ sinh bao quy đầu, kích '
                         'thước dương vật, phòng ngừa bạo lực học đường và xây dựng bản lĩnh phái mạnh có trách nhiệm.',
                 'icon': 'shield'},
               { 'title': 'Góc Tư Vấn Dành Cho Bạn Nữ',
                 'text': 'Tư vấn hiện tượng hành kinh đầu tiên (menarche), theo dõi chu kỳ kinh nguyệt, cách dùng băng '
                         'vệ sinh đúng cách, bảo vệ cơ quan sinh dục ngoài và phòng chống quấy rối, xâm hại tình dục.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tư vấn SKSS theo giới tính - BÀI 4',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_12',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Khung 9 Chủ Đề Chuyên Môn Cốt Lõi (Quyết Định 2885/QĐ-BYT)',
    'primary_claim': 'Khung chương trình chuẩn hóa quốc gia định hình toàn diện nội dung truyền thông và can thiệp lâm '
                     'sàng.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Nhóm 1: Phát Triển Thể Chất & Tâm Lý',
                 'text': 'Chủ đề 1. Tuổi dậy thì; Chủ đề 2. Tình bạn và tình yêu đôi lứa; Chủ đề 8. Một số khái niệm '
                         'về giới tính và giới.',
                 'icon': 'heart'},
               { 'title': 'Nhóm 2: Tình Dục & Phòng Ngừa Rủi Ro',
                 'text': 'Chủ đề 3. Tình dục an toàn và đồng thuận; Chủ đề 4. Mang thai, tránh thai; Chủ đề 5. Nhiễm '
                         'khuẩn lây truyền qua đường tình dục.',
                 'icon': 'shield'},
               { 'title': 'Nhóm 3: Pháp Luật & Kỹ Năng Sống',
                 'text': 'Chủ đề 6. Tảo hôn và hôn nhân cận huyết; Chủ đề 7. Phòng chống xâm hại tình dục trẻ em; Chủ '
                         'đề 9. Kỹ năng sống liên quan SKSS.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quyết định số 2885/QĐ-BYT của Bộ Y tế',
    'illustration': 'cinematic_bai_4_urban.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_13',
    'role': 'CONTENT',
    'section': '3. ĐẶC ĐIỂM KHÁCH HÀNG',
    'assertion_title': 'Giai Đoạn 10-13 Tuổi: Khởi Đầu Dậy Thì & Sự Hoang Mang Thể Xác',
    'primary_claim': 'Những biến đổi cơ thể diễn ra nhanh chóng làm các em ngỡ ngàng, bối rối và rất cần sự định hướng '
                     'khoa học.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Bước Nhảy Vọt Thể Chất',
                 'text': 'Chiều cao và cân nặng tăng nhanh đột biến; xuất hiện các đặc tính sinh dục thứ phát: ngực '
                         'nhú ở nữ, vỡ giọng và lông mu ở nam.',
                 'icon': 'trending-up'},
               { 'title': 'Tâm Lý Bối Rối & E Thẹn',
                 'text': 'Tự ti về sự phát triển không đồng đều cơ thể; lo lắng không biết bạn bè suy nghĩ gì về mình, '
                         'có xu hướng giấu giếm cha mẹ.',
                 'icon': 'alert-circle'},
               { 'title': 'Nhu Cầu Giải Đáp Nhẹ Nhàng',
                 'text': 'Cần cha mẹ và thầy cô giải thích bình tĩnh đây là hiện tượng sinh lý hoàn toàn tự nhiên để '
                         'các em tự hào và an tâm.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Đặc điểm giai đoạn 10-13 tuổi - BÀI 4. Mục 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_14',
    'role': 'CONTENT',
    'section': '3. ĐẶC ĐIỂM KHÁCH HÀNG',
    'assertion_title': 'Giai Đoạn 14-16 Tuổi: Tự Cảm Nhận Người Lớn & Khám Phá Tính Dục',
    'primary_claim': 'Giai đoạn bản lề hình thành nhu cầu tình yêu đôi lứa và khao khát khẳng định cái tôi trước nhóm '
                     'bạn thân.',
    'visual_job': 'CHART_AND_INSIGHTS',
    'visual_anchor': 'CHART_AND_INSIGHTS',
    'atoms': [ { 'title': 'Cảm Nhận Làm Người Lớn',
                 'text': 'Tự thấy mình không còn là trẻ con; muốn tự quyết định các vấn đề cá nhân và không thích sự '
                         'quản lý quá chặt chẽ từ gia đình.',
                 'icon': 'user-check'},
               { 'title': 'Xuất Hiện Nhu Cầu Tình Yêu & Tính Dục',
                 'text': 'Bắt đầu rung động, nảy sinh tình cảm khác giới, có nhu cầu tìm hiểu về tình dục và tò mò xem '
                         'các nội dung trên mạng internet.',
                 'icon': 'heart'},
               { 'title': 'Nhóm Bạn Thân Định Hình Phong Cách',
                 'text': 'Kết nhóm bạn thân theo sở thích riêng; chịu ảnh hưởng rất lớn từ chuẩn mực và thái độ của '
                         'nhóm bạn cùng chơi.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Đặc điểm giai đoạn 14-16 tuổi - BÀI 4. Mục 3',
    'chart_type': 'STACKED_AREA',
    'chart_file': 'chart_demographic_dividend_stacked_area_dark.png',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_15',
    'role': 'CONTENT',
    'section': '3. ĐẶC ĐIỂM KHÁCH HÀNG',
    'assertion_title': 'Giai Đoạn 17-18 Tuổi: Tư Duy Độc Lập & Định Hình Giá Trị Đạo Đức',
    'primary_claim': 'Các em có quan niệm thực tế hơn về tình yêu, cái đẹp và bắt đầu chuẩn bị bước vào cuộc sống '
                     'trưởng thành.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Tư Duy Độc Lập & Chọn Lọc Bạn',
                 'text': 'Biết chọn lọc bạn bè phù hợp với mục tiêu tương lai; có quan điểm rõ ràng về cách ứng xử và '
                         'phẩm giá đạo đức cá nhân.',
                 'icon': 'check-circle'},
               { 'title': 'Yêu Đương Thực Tế',
                 'text': 'Nhận thức rõ hơn về trách nhiệm trong tình yêu, ranh giới an toàn và hệ lụy của việc quan hệ '
                         'tình dục sớm ngoài ý muốn.',
                 'icon': 'heart'},
               { 'title': 'Đối Mặt Áp Lực Tốt Nghiệp',
                 'text': 'Căng thẳng trước kỳ thi tốt nghiệp, chọn trường, chọn nghề; rất cần các kỹ năng giải tỏa '
                         'căng thẳng (stress) lành mạnh.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Đặc điểm giai đoạn 17-18 tuổi - BÀI 4. Mục 3',
    'illustration': 'cinematic_bai_4_megacity.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_16',
    'role': 'CONTENT',
    'section': '3. ĐẶC ĐIỂM KHÁCH HÀNG',
    'assertion_title': 'Giai Đoạn 19-24 Tuổi: Trưởng Thành Toàn Diện & Chuẩn Bị Xây Dựng Gia Đình',
    'primary_claim': 'Thanh niên bước vào môi trường lao động, tự chủ tài chính và có nhu cầu cấp thiết về KHHGĐ tiền '
                     'hôn nhân.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Đầy Đủ Năng Lực Pháp Lý',
                 'text': 'Đã đủ tuổi kết hôn theo Luật Hôn nhân & Gia đình (Nữ đủ 18, Nam đủ 20); tự chịu trách nhiệm '
                         'pháp lý về mọi hành vi sinh sản.',
                 'icon': 'shield-check'},
               { 'title': 'Nhu Cầu Tránh Thai Hiện Đại',
                 'text': 'Cần tiếp cận các biện pháp tránh thai chất lượng cao (thuốc viên hàng ngày, bao cao su, que '
                         'cấy) để học tập và phát triển sự nghiệp.',
                 'icon': 'award'},
               { 'title': 'Khám Sức Khỏe Tiền Hôn Nhân',
                 'text': 'Ý thức chủ động kiểm tra sức khỏe sinh sản, sàng lọc bệnh di truyền trước khi bước vào cuộc '
                         'sống vợ chồng bền vững.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Đặc điểm giai đoạn 19-24 tuổi - BÀI 4. Mục 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_17',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ & CUNG CẤP',
    'assertion_title': 'Mạng Lưới Y Tế Công Lập Cung Cấp Dịch Vụ SKSS Vị Thành Niên',
    'primary_claim': 'Hệ thống y tế Nhà nước giữ vai trò chủ đạo từ tuyến cơ sở đến các bệnh viện chuyên khoa Trung '
                     'ương.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Tuyến Xã / Phường: Trạm Y Tế',
                 'text': 'Tư vấn sức khỏe ban đầu, góc truyền thông học đường, phát bao cao su, thuốc viên tránh thai '
                         'và sơ cứu ban đầu.',
                 'icon': 'home'},
               { 'title': 'Tuyến Huyện: Trung Tâm Y Tế / BVĐK',
                 'text': 'Khoa Chăm sóc SKSS, phòng khám tư vấn thân thiện VTN, thực hiện thủ thuật KHHGĐ và điều trị '
                         'nhiễm khuẩn sinh dục.',
                 'icon': 'activity'},
               { 'title': 'Tuyến Tỉnh: BV Phụ Sản / BV Sản Nhi',
                 'text': 'Khoa Phụ sản, Trung tâm CDC tỉnh tiếp nhận các ca bệnh phức tạp, thai ngoài ý muốn tuổi VTN '
                         'và đào tạo kỹ thuật.',
                 'icon': 'layers'},
               { 'title': 'Tuyến Trung Ương: BV Phụ Sản TƯ',
                 'text': 'Đơn vị đầu ngành chỉ đạo tuyến, nghiên cứu khoa học, điều trị các dị tật bẩm sinh đường sinh '
                         'dục phức tạp và ca bệnh nặng.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 4. Mục 4 - Cơ sở Nhà nước',
    'illustration': 'illustration_bai_4.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_18',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ & CUNG CẤP',
    'assertion_title': 'Vai Trò Của Y Tế Tư Nhân & Các Tổ Chức Quốc Tế (DKT, Gedon-Richter)',
    'primary_claim': 'Huy động nguồn lực phi chính phủ đa dạng hóa kênh phân phối phương tiện tránh thai cho thanh '
                     'niên.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Hệ Thống Phòng Khám & Nhà Thuốc Tư Nhân',
                 'text': 'Cung cấp dịch vụ linh hoạt, ngoài giờ hành chính; hệ thống nhà thuốc bán lẻ là kênh tiếp cận '
                         'bao cao su và thuốc tránh thai khẩn cấp nhanh nhất cho thanh niên.',
                 'icon': 'check-circle'},
               { 'title': 'Các Tổ Chức Phi Chính Phủ Quốc Tế (DKT, Organon...)',
                 'text': 'Tài trợ các chiến dịch truyền thông sáng tạo, cung cấp phương tiện tránh thai chất lượng cao '
                         'với giá tiếp thị xã hội và hỗ trợ kỹ thuật góc tư vấn thân thiện.',
                 'icon': 'globe'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 4. Mục 4 - Cơ sở tư nhân và tổ chức nước ngoài',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_19',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ & CUNG CẤP',
    'assertion_title': "Mô Hình 'Góc Thân Thiện' Tại Trạm Y Tế Xã & Điểm Tư Vấn Học Đường",
    'primary_claim': 'Tạo dựng không gian ấm áp, tin cậy giúp các bạn trẻ xóa bỏ hoàn toàn rào cản e ngại khi đi khám.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Thiết Kế Không Gian Riêng Tư',
                 'text': 'Bố trí góc phòng riêng, có rèm che, ghế sofa thoải mái, âm nhạc nhẹ nhàng và hòm thư góp ý / '
                         'câu hỏi ẩn danh.',
                 'icon': 'heart'},
               { 'title': 'Tài Liệu Đồ Họa Hấp Dẫn',
                 'text': 'Trang bị tranh gấp, poster, infographic, video hoạt hình giáo dục sinh động giải thích cơ '
                         'thể người và chu kỳ kinh.',
                 'icon': 'book-open'},
               { 'title': 'Tủ Phương Tiện Tránh Thai Miễn Phí',
                 'text': 'Bố trí góc kín đáo để các bạn trẻ có thể tự lấy bao cao su và tài liệu hướng dẫn sử dụng mà '
                         'không phải đối mặt nhân viên.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Mô hình dịch vụ y tế thân thiện chuẩn Bộ Y tế',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_20',
    'role': 'CONTENT',
    'section': '5. NỘI DUNG DỊCH VỤ',
    'assertion_title': 'Khung Nghiệp Vụ 9 Chủ Đề Chăm Sóc SKSS Vị Thành Niên Theo Quyết Định 2885',
    'primary_claim': 'Bộ công cụ sư phạm y tế chuẩn hóa trang bị kiến thức toàn diện từ phát triển cơ thể đến bảo vệ '
                     'pháp lý.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Trụ Cột 1: Cơ Thể & Cảm Xúc',
                 'text': 'Chủ đề 1 (Tuổi dậy thì), Chủ đề 2 (Tình bạn tình yêu), Chủ đề 8 (Giới tính và giới).',
                 'icon': 'heart'},
               { 'title': 'Trụ Cột 2: Sức Khỏe & An Toàn',
                 'text': 'Chủ đề 3 (Tình dục an toàn), Chủ đề 4 (Mang thai - tránh thai), Chủ đề 5 (Nhiễm khuẩn '
                         'STIs/HIV).',
                 'icon': 'shield-check'},
               { 'title': 'Trụ Cột 3: Pháp Luật & Kỹ Năng',
                 'text': 'Chủ đề 6 (Tảo hôn), Chủ đề 7 (Phòng xâm hại), Chủ đề 9 (Kỹ năng sống SKSS).',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 4. Mục 5 - Nội dung 9 chủ đề chuyên môn',
    'illustration': 'ai_bai_4_distribution.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_21',
    'role': 'CONTENT',
    'section': '5.1. CHỦ ĐỀ 1: TUỔI DẬY THÌ',
    'assertion_title': 'Biến Đổi Sinh Lý & Dấu Hiệu Trưởng Thành Giới Tính Ở Nam Và Nữ',
    'primary_claim': 'Dậy thì là cột mốc sinh học kỳ diệu đánh dấu sự thức tỉnh của hệ trục Hạ đồi - Tuyến yên - Tuyến '
                     'sinh dục.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Dấu Mốc Dậy Thì Ở Nữ Giới (Thường 10-14 Tuổi)',
                 'text': 'Tuyến vú phát triển nở nang, xuất hiện lông mu và lông nách, khung chậu nở rộng, tích lũy mỡ '
                         'vùng hông đùi; ĐỈNH CAO là hiện tượng HÀNH KINH LẦN ĐẦU (Menarche) đánh dấu noãn bào bắt đầu '
                         'rụng.',
                 'icon': 'heart'},
               { 'title': 'Dấu Mốc Dậy Thì Ở Nam Giới (Thường 12-16 Tuổi)',
                 'text': 'Tinh hoàn và bìu to dần, thanh quản phát triển vỡ giọng (giọng trầm ồm), mọc ria mép và lông '
                         'mu, cơ bắp cuồn cuộn; ĐỈNH CAO là hiện tượng XUẤT TINH LẦN ĐẦU (thường qua mộng tinh vào ban '
                         'đêm).',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chủ đề 1: Tuổi dậy thì - Quyết định 2885/QĐ-BYT',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_22',
    'role': 'CONTENT',
    'section': '5.1. CHỦ ĐỀ 1: TUỔI DẬY THÌ',
    'assertion_title': 'Vệ Sinh Cơ Thể & Chăm Sóc Sức Khỏe Tuổi Dậy Thì Chuẩn Khoa Học',
    'primary_claim': 'Rèn luyện thói quen vệ sinh hằng ngày ngăn chặn tận gốc các bệnh viêm nhiễm da và đường sinh '
                     'dục.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Vệ Sinh Kinh Nguyệt Ở Nữ',
                 'text': 'Thay băng vệ sinh mỗi 4-6 giờ; rửa vùng kín bằng nước sạch từ trước ra sau (tránh vi khuẩn '
                         'hậu môn tràn sang âm đạo); giữ khô ráo.',
                 'icon': 'check-circle'},
               { 'title': 'Vệ Sinh Bộ Phận Sinh Dục Nam',
                 'text': 'Lộn nhẹ bao quy đầu để rửa sạch cặn trắng sinh dục (smegma) bằng xà phòng dịu nhẹ mỗi khi '
                         'tắm; mặc đồ lót cotton thoáng mát.',
                 'icon': 'shield'},
               { 'title': 'Chăm Sóc Da & Mụn Trứng Cá',
                 'text': 'Tuyến bã nhờn hoạt động mạnh gây mụn trứng cá; rửa mặt 2 lần/ngày, uống đủ 2 lít nước, hạn '
                         'chế thức khuya và đồ cay nóng.',
                 'icon': 'smile'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Hướng dẫn thực hành vệ sinh tuổi dậy thì - BÀI 4',
    'illustration': 'ai_bai_4_industrial.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_23',
    'role': 'CONTENT',
    'section': '5.2. CHỦ ĐỀ 2: TÌNH BẠN & TÌNH YÊU',
    'assertion_title': 'Phân Biệt Ranh Giới Giữa Tình Bạn Trong Sáng Và Tình Yêu Đôi Lứa',
    'primary_claim': 'Giúp thanh thiếu niên hiểu rõ quy luật tình cảm để không ngộ nhận cảm xúc thoáng qua với tình '
                     'yêu đích thực.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Đặc Trưng Tình Bạn Trong Sáng',
                 'text': 'Dựa trên sự đồng điệu về sở thích, học tập, vô tư, bình đẳng, không vụ lợi và không có yếu '
                         'tố khao khát tiếp xúc thể xác mang tính dục.',
                 'icon': 'users'},
               { 'title': 'Đặc Trưng Tình Yêu Chân Chính',
                 'text': 'Sự kết hợp giữa 3 yếu tố: Thấu hiểu tâm hồn (Intimacy), Say mê cảm xúc thể xác (Passion) và '
                         'Cam kết gắn bó trách nhiệm (Commitment).',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chủ đề 2: Tình bạn và tình yêu - Quyết định 2885/QĐ-BYT',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_24',
    'role': 'CONTENT',
    'section': '5.2. CHỦ ĐỀ 2: TÌNH BẠN & TÌNH YÊU',
    'assertion_title': 'Kỹ Năng Ứng Xử Văn Minh & Giải Quyết Bất Đồng Tình Cảm Tuổi Học Trò',
    'primary_claim': 'Tình yêu tuổi học trò cần sự tôn trọng lẫn nhau, cùng giúp nhau tiến bộ trong học tập và rèn '
                     'luyện đạo đức.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tôn Trọng Không Gian Riêng',
                 'text': 'Không kiểm soát ghen tuông mù quáng, không đọc trộm tin nhắn điện thoại; tôn trọng các mối '
                         'quan hệ bạn bè của đối phương.',
                 'icon': 'user-check'},
               { 'title': 'Cùng Nhau Tiến Bộ',
                 'text': 'Lấy tình cảm làm động lực thi đua học tập, giúp đỡ nhau giải bài tập khó, cùng hướng tới mục '
                         'tiêu đỗ đạt đại học.',
                 'icon': 'award'},
               { 'title': 'Kỹ Năng Chia Tay Văn Minh',
                 'text': 'Khi tình cảm không còn: Nói chuyện thẳng thắn, tôn trọng, không bôi nhọ trên mạng xã hội, '
                         'không có hành vi bạo lực trả thù.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Kỹ năng sống tuổi học trò - BÀI 4',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_25',
    'role': 'CONTENT',
    'section': '5.3. CHỦ ĐỀ 3: TÌNH DỤC AN TOÀN',
    'assertion_title': 'Nguyên Tắc Cốt Lõi: Tình Dục Đồng Thuận & Quyền Tự Chủ Thân Thể',
    'primary_claim': 'Đồng thuận phải là sự tự nguyện hoàn toàn, tỉnh táo và có thể rút lại bất kỳ lúc nào mà không sợ '
                     'hãi.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Tự Nguyện Tỉnh Táo (Freely Given)',
                 'text': 'Chỉ có giá trị khi không bị ép buộc, đe dọa, thao túng tâm lý hoặc trong trạng thái say xỉn '
                         'rượu bia, chất kích thích.',
                 'icon': 'check-circle'},
               { 'title': 'Có Thể Đổi Ý (Reversible)',
                 'text': 'Mỗi cá nhân có quyền dừng lại bất kỳ lúc nào ngay cả khi hành vi quan hệ tình dục đã bắt '
                         'đầu; đối phương bắt buộc phải tôn trọng.',
                 'icon': 'shield'},
               { 'title': 'Biết Rõ Điều Mình Làm (Informed)',
                 'text': 'Cả hai đều hiểu rõ về nguy cơ mang thai và bệnh lây truyền, đã thống nhất sử dụng biện pháp '
                         'bảo vệ trước khi nhập cuộc.',
                 'icon': 'book-open'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chủ đề 3: Tình dục an toàn và đồng thuận - QĐ 2885',
    'illustration': 'cinematic_bai_4_urban.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_26',
    'role': 'CONTENT',
    'section': '5.3. CHỦ ĐỀ 3: TÌNH DỤC AN TOÀN',
    'assertion_title': 'Trách Nhiệm Sử Dụng Bao Cao Su Trong Mọi Lần Quan Hệ Tình Dục',
    'primary_claim': 'Bao cao su là người bảo vệ thầm lặng cho tương lai và ước mơ học tập của các bạn trẻ.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Bảo Vệ Kép Hoàn Hảo',
                 'text': 'Không để xảy ra tình trạng có thai ngoài ý muốn phá hỏng việc học; đồng thời ngăn chặn 100% '
                         'các bệnh lây truyền qua dịch thể nguy hiểm như HIV, lậu, giang mai.',
                 'icon': 'shield-check'},
               { 'title': 'Bản Lĩnh Trách Nhiệm Của Phái Mạnh',
                 'text': 'Người bạn trai thực sự yêu thương bạn gái sẽ luôn chủ động chuẩn bị và mang bao cao su, '
                         'không ép bạn gái phải quan hệ trần không bảo vệ.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Bản lĩnh tình dục an toàn - BÀI 4',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_27',
    'role': 'CONTENT',
    'section': '5.4. CHỦ ĐỀ 4: MANG THAI & TRÁNH THAI',
    'assertion_title': 'Hệ Lụy Nặng Nề Của Mang Thai Ở Lứa Tuổi Vị Thành Niên',
    'primary_claim': 'Cơ thể chưa hoàn thiện khung chậu dẫn đến nguy cơ đẻ khó, băng huyết, tử vong mẹ và đứt gãy '
                     'tương lai học tập.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tai Biến Sản Khoa Trầm Trọng',
                 'text': 'Tử vong mẹ ở tuổi VTN cao gấp đôi so với tuổi 20-24 do tiền sản giật, sản giật, khung chậu '
                         'hẹp gây vỡ tử cung và rách tầng sinh môn.',
                 'icon': 'alert-circle'},
               { 'title': 'Trẻ Sinh Ra Yếu Ớt',
                 'text': 'Nguy cơ sinh non, thai nhẹ cân (<2.500g), ngạt sau sinh và tử vong chu sinh cao gấp 3 lần do '
                         'dinh dưỡng của mẹ chưa hoàn thiện.',
                 'icon': 'activity'},
               { 'title': 'Chấm Dứt Cơ Hội Học Tập',
                 'text': 'Phần lớn các em phải bỏ học giữa chừng, mất cơ hội nghề nghiệp tốt, rơi vào vòng luẩn quẩn '
                         'của sự nghèo đói và phụ thuộc.',
                 'icon': 'book-open'},
               { 'title': 'Sang Chấn Tâm Lý Nặng Nề',
                 'text': 'Mặc cảm với bạn bè, định kiến xã hội, trầm cảm sau sinh và nguy cơ tự sát ở các bà mẹ vị '
                         'thành niên rất cao.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Báo cáo thực trạng mang thai VTN - Bộ Y tế',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_28',
    'role': 'CONTENT',
    'section': '5.4. CHỦ ĐỀ 4: MANG THAI & TRÁNH THAI',
    'assertion_title': 'Lựa Chọn Biện Pháp Tránh Thai Thích Hợp Cho Thanh Thiếu Niên',
    'primary_claim': 'Ưu tiên các biện pháp kín đáo, hiệu quả cao, dễ sử dụng và không ảnh hưởng đến khả năng sinh sản '
                     'sau này.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Ưu Tiên 1: Bao Cao Su',
                 'text': 'Lựa chọn số một cho vị thành niên; vừa ngừa thai hiệu quả, vừa phòng chống STIs/HIV, dễ mua '
                         'và hoàn toàn không ảnh hưởng nội tiết.',
                 'icon': 'shield-check'},
               { 'title': 'Ưu Tiên 2: Thuốc Viên Kết Hợp (COC)',
                 'text': 'Thích hợp cho thanh niên có quan hệ tình dục thường xuyên; giúp kinh nguyệt đều, giảm mụn '
                         'trứng cá và hồi phục rụng trứng ngay sau ngừng.',
                 'icon': 'check-circle'},
               { 'title': 'Cứu Cánh Khẩn Cấp: Viên ECP',
                 'text': 'Chỉ dùng trong vòng 72h khi bị rách bao cao su hoặc bị ép buộc quan hệ; không được xem là '
                         'biện pháp tránh thai định kỳ.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chủ đề 4: Mang thai và tránh thai - QĐ 2885',
    'illustration': 'cinematic_bai_4_megacity.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_29',
    'role': 'CONTENT',
    'section': '5.4. CHỦ ĐỀ 4: PHÁ THAI AN TOÀN',
    'assertion_title': 'Tư Vấn Phá Thai An Toàn & Cảnh Báo Hiểm Họa Phá Thai Chui',
    'primary_claim': 'Tự ý mua thuốc phá thai trên mạng hoặc đến cơ sở bất hợp pháp có thể cướp đi tính mạng và khả '
                     'năng làm mẹ.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Hiểm Họa Phá Thai Chui & Tự Phá Thai',
                 'text': 'Uống thuốc phá thai bừa bãi hoặc phá thai tại cơ sở chui dẫn đến băng huyết ồ ạt, sót rau, '
                         'nhiễm trùng huyết, thủng tử cung, dính buồng tử cung gây vô sinh vĩnh viễn hoặc tử vong.',
                 'icon': 'alert-circle'},
               { 'title': 'Tiếp Cận Cơ Sở Y Tế Hợp Pháp',
                 'text': 'Nếu buộc phải đình chỉ thai: Phải đến bệnh viện công lập hoặc phòng khám có giấy phép để '
                         'được siêu âm xác định vị trí thai, tư vấn phá thai nội khoa an toàn và chăm sóc tâm lý.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Hướng dẫn quốc gia phá thai an toàn - Bộ Y tế',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_30',
    'role': 'CONTENT',
    'section': '5.5. CHỦ ĐỀ 5: NHIỄM KHUẨN STIs',
    'assertion_title': 'Tầm Soát & Điều Trị Các Nhiễm Khuẩn Lây Truyền Qua Đường Tình Dục',
    'primary_claim': 'Phần lớn các bệnh STIs ở nữ giới không có triệu chứng rõ ràng, âm thầm gây vô sinh nếu không '
                     'phát hiện sớm.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Bệnh Lậu (Gonorrhea)',
                 'text': 'Tiểu buốt, tiểu rắt, chảy mủ niệu đạo đặc màu vàng xanh ở nam; ở nữ thường kín đáo nhưng gây '
                         'viêm tắc vòi trứng.',
                 'icon': 'alert-circle'},
               { 'title': 'Bệnh Giang Mai (Syphilis)',
                 'text': 'Xuất hiện vết loét tròn không đau (săng giang mai); nếu không chữa trị sẽ ăn sâu vào tim '
                         'mạch và hệ thần kinh trung ương.',
                 'icon': 'activity'},
               { 'title': 'Sùi Mào Gà (Vi-rút HPV)',
                 'text': 'U nhú sinh dục hình súp lơ gà; các chủng HPV 16, 18 nguy cơ cao gây ung thư cổ tử cung ở nữ '
                         'và ung thư dương vật ở nam.',
                 'icon': 'shield'},
               { 'title': 'Nguyên Tắc Điều Trị Cặp Đôi',
                 'text': 'BẮT BUỘC PHẢI ĐIỀU TRỊ ĐỒNG THỜI CẢ BẠN TÌNH để tránh hiện tượng lây nhiễm bóng bàn '
                         '(ping-pong) tái phát liên tục.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chủ đề 5: Nhiễm khuẩn STIs - Quyết định 2885/QĐ-BYT',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_31',
    'role': 'CONTENT',
    'section': '5.5. CHỦ ĐỀ 5: HIV/AIDS & THANH NIÊN',
    'assertion_title': 'HIV/AIDS Trong Thanh Niên: Phòng Ngừa Trước Phơi Nhiễm (PrEP) & K=K',
    'primary_claim': 'Tiến bộ y học hiện đại biến HIV thành bệnh mạn tính kiểm soát được hoàn toàn nhờ thuốc ARV.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Dự Phòng Trước Phơi Nhiễm (PrEP)',
                 'text': 'Uống 1 viên thuốc kháng vi-rút mỗi ngày giúp người chưa nhiễm HIV giảm đến 99% nguy cơ lây '
                         'truyền qua quan hệ tình dục.',
                 'icon': 'shield-check'},
               { 'title': 'Thông Điệp Khoa Học K=K',
                 'text': 'Không phát hiện = Không lây truyền (Undetectable = Untransmittable); người nhiễm HIV uống '
                         'ARV đạt tải lượng dưới 200 bản sao sẽ không lây cho bạn tình.',
                 'icon': 'award'},
               { 'title': 'Chống Kỳ Thị & Phân Biệt Đối Xử',
                 'text': 'HIV không lây qua tiếp xúc thông thường (bắt tay, ăn chung, ôm); mở rộng vòng tay yêu thương '
                         'giúp người bệnh hòa nhập.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Thông điệp PrEP và K=K - Cục Phòng chống HIV/AIDS',
    'illustration': 'illustration_bai_4.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_32',
    'role': 'CONTENT',
    'section': '5.6. CHỦ ĐỀ 6: TẢO HÔN & CẬN HUYẾT',
    'assertion_title': 'Thực Trạng Tảo Hôn & Khung Chế Tài Pháp Luật Xử Phạt Nghiêm Khắc',
    'primary_claim': 'Tảo hôn là hành vi vi phạm pháp luật nghiêm trọng, tước đoạt quyền trẻ em và kéo lùi sự phát '
                     'triển xã hội.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Hành Vi Tảo Hôn Bị Nghiêm Cấm',
                 'text': 'Luật Hôn nhân và Gia đình 2014 nghiêm cấm kết hôn khi nam chưa đủ 20 tuổi, nữ chưa đủ 18 '
                         'tuổi; thường xảy ra tại vùng đồng bào dân tộc thiểu số và miền núi.',
                 'icon': 'alert-circle'},
               { 'title': 'Chế Tài Hành Chính & Hình Sự',
                 'text': 'Xử phạt hành chính lên tới hàng chục triệu đồng; hành vi cố ý duy trì quan hệ hôn nhân trái '
                         'pháp luật với người chưa đủ tuổi có thể bị xử lý hình sự theo Bộ luật Hình sự.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chủ đề 6: Tảo hôn và hôn nhân cận huyết - QĐ 2885',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_33',
    'role': 'CONTENT',
    'section': '5.6. CHỦ ĐỀ 6: TẢO HÔN & CẬN HUYẾT',
    'assertion_title': 'Tác Hại Di Truyền Nặng Nề Của Hôn Nhân Cận Huyết Thống',
    'primary_claim': 'Kết hôn giữa những người có cùng dòng máu trực hệ làm gia tăng đột biến tỷ lệ bệnh tật di truyền '
                     'thể lặn.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tăng Tỷ Lệ Đồng Hợp Tử Gen Lặn',
                 'text': 'Hôn nhân giữa anh chị em họ đời thứ 3 làm xác suất gặp nhau của các gen lặn đột biến nguy '
                         'hiểm tăng vọt gấp hàng chục lần.',
                 'icon': 'activity'},
               { 'title': 'Hàng Loạt Dị Tật Bẩm Sinh',
                 'text': 'Con sinh ra dễ mắc bệnh Tan máu bẩm sinh (Thalassemia), bệnh mù màu, câm điếc bẩm sinh, bạch '
                         'tạng, lùn bẩm sinh, dị dạng chi.',
                 'icon': 'alert-circle'},
               { 'title': 'Suy Thoái Giống Nòi Dân Tộc',
                 'text': 'Làm suy giảm thể lực, chiều cao, trí tuệ và gây suy giảm dân số nghiêm trọng ở các cộng đồng '
                         'thiểu số có tập quán cận huyết.',
                 'icon': 'trending-down'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tác hại hôn nhân cận huyết - BÀI 4',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_34',
    'role': 'CONTENT',
    'section': '5.7. CHỦ ĐỀ 7: PHÒNG CHỐNG XÂM HẠI',
    'assertion_title': 'Nhận Diện Các Hình Thức Xâm Hại Tình Dục Trẻ Em',
    'primary_claim': 'Xâm hại tình dục không chỉ là hành vi giao cấu mà bao gồm mọi hành vi quấy rối, đụng chạm hoặc '
                     'phơi bày đồi trụy.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Xâm Hại Thể Xác (Đụng Chạm)',
                 'text': 'Hành vi sờ mó, hôn hít, vuốt ve các vùng nhạy cảm trên cơ thể trẻ em hoặc ép buộc trẻ sờ vào '
                         'cơ quan sinh dục của kẻ xấu.',
                 'icon': 'alert-circle'},
               { 'title': 'Xâm Hại Bằng Lời Nói',
                 'text': 'Bình phẩm khiếm nhã về thân thể, kể chuyện tình dục dung tục, gạ gẫm hoặc đe dọa ép buộc '
                         'quan hệ tình cảm.',
                 'icon': 'message-circle'},
               { 'title': 'Xâm Hại Phi Tiếp Xúc (Nhìn Ngắm)',
                 'text': 'Kẻ xấu tự phơi bày bộ phận sinh dục trước mặt trẻ, nhìn trộm khi trẻ tắm, thay đồ hoặc quay '
                         'lén hình ảnh nhạy cảm.',
                 'icon': 'eye'},
               { 'title': 'Xâm Hại Qua Mạng Internet',
                 'text': 'Dụ dỗ gửi hình ảnh, video khỏa thân trên mạng xã hội rồi đe dọa tống tiền hoặc cưỡng ép quan '
                         'hệ tình dục thực tế.',
                 'icon': 'globe'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chủ đề 7: Phòng chống xâm hại tình dục - QĐ 2885',
    'illustration': 'ai_bai_4_distribution.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_35',
    'role': 'CONTENT',
    'section': '5.7. CHỦ ĐỀ 7: PHÒNG CHỐNG XÂM HẠI',
    'assertion_title': "Quy Tắc '5 Ngón Tay' & Kỹ Năng Tự Vệ Thoát Hiểm Cho Học Sinh",
    'primary_claim': 'Bộ quy tắc trực quan sinh động giúp trẻ em ghi nhớ ranh giới an toàn của các mối quan hệ giao '
                     'tiếp.',
    'visual_job': 'CHART_AND_INSIGHTS',
    'visual_anchor': 'CHART_AND_INSIGHTS',
    'atoms': [ { 'title': 'Ngón Cái: Ôm Hôn Người Thân',
                 'text': 'Chỉ dành cho bố mẹ, ông bà ruột thịt, anh chị em ruột được ôm hôn và chăm sóc thân thể khi '
                         'tắm rửa lúc nhỏ.',
                 'icon': 'heart'},
               { 'title': 'Ngón Trỏ: Nắm Tay Bạn Bè',
                 'text': 'Thầy cô giáo, bạn bè, họ hàng chỉ được nắm tay, khoác vai chào hỏi lịch sự.',
                 'icon': 'users'},
               { 'title': 'Ngón Giữa: Bắt Tay Người Quen',
                 'text': 'Hàng xóm, bạn bè của cha mẹ chỉ chào hỏi và bắt tay lịch thiệp trong giao tiếp xã hội.',
                 'icon': 'smile'},
               { 'title': 'Ngón Út: Xua Tay Từ Chối Người Lạ',
                 'text': 'Người lạ tuyệt đối không được chạm vào cơ thể; nếu có hành vi khả nghi: HÉT TO - BỎ CHẠY - '
                         'KỂ LẠI CHO BỐ MẸ.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy tắc 5 ngón tay phòng chống xâm hại - BÀI 4',
    'chart_type': 'SCATTER_BUBBLE',
    'chart_file': 'chart_urban_rural_divergence_bubble_dark.png',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_36',
    'role': 'CONTENT',
    'section': '5.8. CHỦ ĐỀ 8: GIỚI TÍNH & GIỚI',
    'assertion_title': 'Phân Biệt Rành Mạch Giới Tính Sinh Học (Sex) Và Giới Xã Hội (Gender)',
    'primary_claim': 'Giới tính sinh học là bẩm sinh cố định, trong khi giới xã hội do văn hóa giáo dục hình thành và '
                     'có thể thay đổi.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Giới Tính Sinh Học (Sex - Bẩm Sinh)',
                 'text': 'Đặc điểm sinh học bẩm sinh gắn liền với nhiễm sắc thể (XX ở nữ, XY ở nam), hormone nội tiết '
                         'và giải phẫu cơ quan sinh sản; không thay đổi theo thời gian và không gian.',
                 'icon': 'activity'},
               { 'title': 'Giới Xã Hội (Gender - Tập Nhiễm)',
                 'text': 'Vai trò, trách nhiệm, hành vi và chuẩn mực xã hội kỳ vọng đối với nam và nữ (ví dụ quan niệm '
                         'nam phải làm trụ cột kinh tế, nữ phải nội trợ); có thể thay đổi theo tiến trình văn minh.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chủ đề 8: Khái niệm về giới tính và giới - QĐ 2885',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_37',
    'role': 'CONTENT',
    'section': '5.8. CHỦ ĐỀ 8: GIỚI TÍNH & GIỚI',
    'assertion_title': 'Tôn Trọng Sự Đa Dạng Tính Dục (LGBTQ+) & Thúc Đẩy Bình Đẳng Giới',
    'primary_claim': 'Mọi thanh thiếu niên đều bình đẳng về nhân phẩm và quyền được tiếp cận dịch vụ y tế không phân '
                     'biệt xu hướng tính dục.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Hiểu Về Xu Hướng Tính Dục',
                 'text': 'Sự hấp dẫn tình cảm, tình dục hướng về người khác giới (Heterosexual), cùng giới '
                         '(Homosexual) hay cả hai giới (Bisexual).',
                 'icon': 'heart'},
               { 'title': 'Bản Dạng Giới (Gender Identity)',
                 'text': 'Cảm nhận sâu sắc bên trong của một người về giới của mình; có thể trùng khớp hoặc khác biệt '
                         'với giới tính sinh học (chuyển giới).',
                 'icon': 'user-check'},
               { 'title': 'Xóa Bỏ Định Kiến & Kỳ Thị',
                 'text': 'Tạo môi trường học đường và y tế an toàn, tôn trọng sự khác biệt, không bắt nạt hay kỳ thị '
                         'học sinh cộng đồng cầu vồng.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Giáo dục hòa nhập và đa dạng tính dục - BÀI 4',
    'illustration': 'ai_bai_4_industrial.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_38',
    'role': 'CONTENT',
    'section': '5.9. CHỦ ĐỀ 9: KỸ NĂNG SỐNG SKSS',
    'assertion_title': 'Kỹ Năng Từ Chối (Say No): Bản Lĩnh Bảo Vệ Ranh Giới Cá Nhân',
    'primary_claim': 'Biết nói lời từ chối quyết đoán trước những lời gạ gẫm quan hệ tình dục sớm là kỹ năng sinh tồn '
                     'thiết yếu.',
    'visual_job': 'PROCESS_DEVSECOPS_PIPELINE',
    'visual_anchor': 'PROCESS_CARDS',
    'atoms': [ { 'title': '1. Lắng Nghe Trực Giác',
                 'text': 'Nhận biết các tình huống nguy hiểm khi ở một mình trong không gian kín với bạn khác giới.',
                 'icon': 'alert-circle'},
               { 'title': '2. Khẳng Định Rõ Ràng',
                 'text': "Nói 'KHÔNG' dứt khoát với ánh mắt nhìn thẳng; không dùng lời lẽ ngập ngừng khiến đối phương "
                         'hiểu lầm.',
                 'icon': 'shield'},
               { 'title': '3. Nêu Rõ Lý Do',
                 'text': "Giải thích ngắn gọn: 'Mình chưa sẵn sàng, mình muốn tập trung học tập và giữ gìn tương lai "
                         "cho cả hai'.",
                 'icon': 'book-open'},
               { 'title': '4. Rời Khỏi Hiện Trường',
                 'text': 'Nếu đối phương tiếp tục ép buộc: Lập tức đứng dậy, mở cửa và đi ngay đến nơi đông người để '
                         'bảo đảm an toàn.',
                 'icon': 'user-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chủ đề 9: Kỹ năng sống SKSS - Quyết định 2885/QĐ-BYT',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_39',
    'role': 'CONTENT',
    'section': '5.9. CHỦ ĐỀ 9: KỸ NĂNG SỐNG SKSS',
    'assertion_title': 'Kỹ Năng Tìm Kiếm Sự Trợ Giúp Y Tế & Hỗ Trợ Khủng Hoảng Tâm Lý',
    'primary_claim': 'Hướng dẫn các bạn trẻ biết cách tìm đến đúng địa chỉ tin cậy khi gặp sự cố sức khỏe sinh sản.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Đường Dây Nóng Quốc Gia 111',
                 'text': 'Tổng đài quốc gia bảo vệ trẻ em trực 24/7 tư vấn tâm lý, can thiệp khẩn cấp các vụ việc bạo '
                         'lực, xâm hại tình dục trẻ em.',
                 'icon': 'phone'},
               { 'title': 'Góc Tư Vấn Trạm Y Tế',
                 'text': 'Đến gặp trực tiếp cán bộ y tế dân số xã để được bảo mật danh tính, cấp phát bao cao su và tư '
                         'vấn các biện pháp tránh thai.',
                 'icon': 'home'},
               { 'title': 'Phòng Tham Vấn Học Đường',
                 'text': 'Tìm gặp thầy cô giáo phụ trách tâm lý học đường hoặc cán bộ Đoàn trường để chia sẻ khó khăn '
                         'tình cảm lứa tuổi.',
                 'icon': 'book-open'},
               { 'title': 'Ứng Dụng Tư Vấn Số',
                 'text': 'Sử dụng các ứng dụng di động y tế uy tín, cổng thông tin điện tử của Cục Dân số để tra cứu '
                         'kiến thức chuẩn xác.',
                 'icon': 'globe'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Mạng lưới hỗ trợ khẩn cấp SKSS vị thành niên',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_40',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Mục Tiêu Đột Phá: Nghị Quyết 21-NQ/TW & Chiến Lược Dân Số Đến Năm 2030',
    'primary_claim': 'Chỉ tiêu pháp lệnh đòi hỏi giảm 2/3 số ca mang thai ngoài ý muốn ở VTN và ngăn chặn triệt để tảo '
                     'hôn.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Giảm 2/3 Số VTN Mang Thai',
                 'text': 'Chỉ tiêu trọng tâm quốc gia: Giảm 2/3 số vị thành niên, thanh niên có thai ngoài ý muốn vào '
                         'năm 2030 so với mốc năm 2020.',
                 'icon': 'target'},
               { 'title': 'Chấm Dứt Tảo Hôn & Cận Huyết',
                 'text': 'Cơ bản ngăn chặn tình trạng tảo hôn và hôn nhân cận huyết thống trong vùng đồng bào dân tộc '
                         'thiểu số và miền núi.',
                 'icon': 'shield-check'},
               { 'title': 'Bảo Đảm Quyền Tiếp Cận Dịch Vụ',
                 'text': '100% cơ sở y tế tuyến huyện và tối thiểu 80% trạm y tế tuyến xã cung cấp dịch vụ chăm sóc '
                         'SKSS thân thiện cho thanh niên.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Nghị quyết số 21-NQ/TW và Chiến lược Dân số Việt Nam đến 2030',
    'illustration': 'cinematic_bai_4_urban.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_41',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Đề Án Chăm Sóc SKSS, SKTD Vị Thành Niên, Thanh Niên (Quyết Định 5914)',
    'primary_claim': 'Kế hoạch hành động 2021-2025 của Bộ Y tế cụ thể hóa 3 mục tiêu chiến lược với hệ thống chỉ tiêu '
                     'đo lường.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Mục Tiêu 1: Cam Kết Chính Sách',
                 'text': 'Tăng cường sự cam kết của các nhà hoạch định chính sách, tạo môi trường pháp lý và ngân sách '
                         'thuận lợi cho chăm sóc SKSS/SKTD thanh niên.',
                 'icon': 'shield'},
               { 'title': 'Mục Tiêu 2: Nâng Cao Nhận Thức',
                 'text': 'Nâng cao hiểu biết, thay đổi hành vi cho thanh niên và các bên liên quan (cha mẹ, thầy cô, '
                         'chủ doanh nghiệp có công nhân trẻ).',
                 'icon': 'book-open'},
               { 'title': 'Mục Tiêu 3: Mở Rộng Dịch Vụ Thân Thiện',
                 'text': 'Tăng cường tiếp cận, nâng cao chất lượng dịch vụ thân thiện, đặc biệt ưu tiên cho thanh niên '
                         'nông thôn, di cư, khuyết tật.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quyết định số 5914/QĐ-BYT ngày 29/11/2021 của Bộ Y tế',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_42',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Luật Dân Số Số 113/2025/QH15: Khung Pháp Lý Mới Về Quyền Sinh Sản',
    'primary_claim': 'Luật Dân số có hiệu lực từ ngày 01/7/2026 khẳng định quyền bình đẳng tự quyết về sinh sản của '
                     'mỗi cá nhân.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Quyền Tự Quyết Sinh Sản (Điều 13)',
                 'text': 'Quyền và nghĩa vụ của mỗi cá nhân, cặp vợ chồng trong việc quyết định thời gian sinh con, số '
                         'con và khoảng cách sinh con phù hợp với lứa tuổi, sức khỏe, điều kiện học tập và thu nhập '
                         'trên cơ sở bình đẳng.',
                 'icon': 'award'},
               { 'title': 'Trách Nhiệm Của Nhà Nước & Xã Hội',
                 'text': 'Bảo đảm cung ứng đầy đủ dịch vụ tư vấn, truyền thông giáo dục dân số, chăm sóc sức khỏe sinh '
                         'sản cho vị thành niên, thanh niên nhằm nâng cao toàn diện chất lượng giống nòi.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Luật Dân số số 113/2025/QH15 (Có hiệu lực từ 01/7/2026)',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_43',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Phân Cấp Quản Lý Và Tác Nghiệp Hệ Thống Y Tế Dân Số 4 Tuyến',
    'primary_claim': 'Sự hiệp đồng chặt chẽ giữa Vụ Sức khỏe bà mẹ - Trẻ em, Cục Dân số và mạng lưới cơ sở.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Tuyến Trung Ương: Vụ SKBM-TE & Cục Dân Số',
                 'text': 'Chủ trì xây dựng kế hoạch quốc gia, bố trí nhân lực, hướng dẫn kiểm tra, giám sát và tổng '
                         'kết chương trình toàn quốc.',
                 'icon': 'shield-check'},
               { 'title': 'Tuyến Tỉnh: Sở Y Tế (CDC & Chi Cục Dân Số)',
                 'text': 'Tổ chức đào tạo kỹ thuật, kiểm tra giám sát, tổ chức các chiến dịch truyền thông cấp tỉnh và '
                         'điều phối phân bổ vật tư.',
                 'icon': 'layers'},
               { 'title': 'Tuyến Huyện: TTYT (Phòng/Khoa Dân Số)',
                 'text': 'Hướng dẫn trường học tổ chức thi tìm hiểu SKSS (Rung chuông vàng, hùng biện); giám sát hoạt '
                         'động góc thân thiện.',
                 'icon': 'activity'},
               { 'title': 'Tuyến Xã: Trạm Y Tế & CTV Thôn Bản',
                 'text': 'Trực tiếp tư vấn tại góc thân thiện trạm y tế; CTV dân số đến từng hộ gia đình nắm bắt nhu '
                         'cầu thanh niên và vận động truyền thông.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 4. Mục 6 - Phân cấp quản lý 4 tuyến',
    'illustration': 'cinematic_bai_4_megacity.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_44',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Mô Hình Câu Lạc Bộ VTN Thân Thiện & Hoạt Động Ngoại Khóa Học Đường',
    'primary_claim': 'Phương pháp giáo dục đồng đẳng phát huy tối đa tính chủ động, hào hứng của học sinh.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Giáo Dục Viên Đồng Đẳng',
                 'text': 'Tập huấn cho các cán bộ Đoàn, lớp trưởng kỹ năng tư vấn để chính các em trò chuyện, gỡ rối '
                         'cho bạn bè cùng trang lứa.',
                 'icon': 'users'},
               { 'title': 'Sân Khấu Hóa Truyền Thông',
                 'text': 'Tổ chức các cuộc thi kịch tương tác, hội thi vẽ tranh cổ động, cuộc thi Rung chuông vàng tìm '
                         'hiểu kiến thức SKSS vui nhộn.',
                 'icon': 'award'},
               { 'title': 'Sinh Hoạt Câu Lạc Bộ Định Kỳ',
                 'text': "Duy trì CLB 'Tiền hôn nhân', CLB 'Bạn gái tuổi mới lớn' sinh hoạt mỗi tháng một lần theo các "
                         'chủ đề thiết thực của lứa tuổi.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Kinh nghiệm mô hình CLB thân thiện - BÀI 4',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_45',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 1: Đánh Giá Thực Trạng Đáp Ứng 9 Chủ Đề SKSS Vị Thành Niên',
    'primary_claim': 'Phân tích khoảng trống giữa nhu cầu thực tế của thanh niên và khả năng cung cấp của hệ thống '
                     'dịch vụ.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Chủ Đề Được Đáp Ứng Tốt Nhất',
                 'text': 'Chủ đề 1 (Tuổi dậy thì) và Chủ đề 2 (Tình bạn, tình yêu): Nội dung mang tính phổ thông, đã '
                         'được đưa vào sách giáo khoa sinh học, xã hội cởi mở đón nhận, ít rào cản nhạy cảm văn hóa.',
                 'icon': 'check-circle'},
               { 'title': 'Chủ Đề Còn Nhiều Hạn Chế Nhất',
                 'text': 'Chủ đề 3 (Tình dục an toàn & đồng thuận) và Chủ đề 4 (Tránh thai & phá thai): Nhiều phụ '
                         "huynh và thầy cô còn e ngại 'vẽ đường cho hươu chạy', cán bộ y tế cơ sở thiếu kỹ năng tư vấn "
                         'chuyên sâu.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Câu hỏi lượng giá số 1 - BÀI 4',
    'illustration': 'illustration_bai_4.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_46',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 2: Tháo Gỡ Thuận Lợi, Khó Khăn Khi Triển Khai Dịch Vụ Địa Phương',
    'primary_claim': 'Tổng hợp bài học kinh nghiệm thực địa để nâng cao chất lượng hoạt động của trạm y tế xã.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Thuận Lợi Nền Tảng',
                 'text': 'Sự quan tâm của cấp ủy, chính quyền; mạng lưới y tế cơ sở rộng khắp; thanh niên ngày nay '
                         'năng động, làm quen nhanh với internet và các nền tảng mạng xã hội.',
                 'icon': 'trending-up'},
               { 'title': 'Khó Khăn Thực Tế & Giải Pháp',
                 'text': 'Tâm lý e ngại, sợ người quen bắt gặp khi đến trạm y tế; kinh phí chương trình còn eo hẹp. '
                         'Giải pháp: Hẹn khám online, tư vấn qua Zalo, tổ chức truyền thông trực tiếp tại trường học.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Câu hỏi lượng giá số 2 - BÀI 4',
    'illustration': 'ai_bai_4_distribution.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_47',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': "Câu Hỏi 3: Đột Phá Đạt Mục Tiêu 'Giảm 2/3 VTN Mang Thai Ngoài Ý Muốn'",
    'primary_claim': 'Đề xuất nhóm giải pháp tích hợp y tế, giáo dục và chuyển đổi số truyền thông tiếp cận giới trẻ.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Giáo Dục Giới Tính Toàn Diện',
                 'text': 'Đưa giáo dục giới tính và tình dục an toàn vào chương trình chính khóa từ cấp Trung học cơ '
                         'sở, không né tránh chủ đề tránh thai.',
                 'icon': 'book-open'},
               { 'title': 'Tiếp Cận Bao Cao Su Thân Thiện',
                 'text': 'Đặt máy bán bao cao su tự động hoặc hộp bao cao su miễn phí tại ký túc xá, khu công nghiệp '
                         'và các điểm sinh hoạt thanh niên.',
                 'icon': 'shield-check'},
               { 'title': 'Tư Vấn Số & Tổng Đài AI',
                 'text': 'Xây dựng chatbot tư vấn SKSS ẩn danh trên Zalo, TikTok giải đáp tức thì các băn khoăn thầm '
                         'kín của học sinh 24/7.',
                 'icon': 'globe'},
               { 'title': 'Cung Ứng Tránh Thai Khẩn Cấp',
                 'text': 'Tập huấn cho hệ thống nhà thuốc bán lẻ tư vấn sử dụng thuốc viên tránh thai khẩn cấp chuẩn '
                         'quy trình, bảo vệ khách hàng trẻ.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chiến lược giảm thai ngoài ý muốn - BÀI 4 Câu 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_48',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 4: Kế Hoạch Phối Hợp Liên Ngành Y Tế - Giáo Dục - Đoàn Thanh Niên',
    'primary_claim': 'Sức mạnh tổng hợp từ cơ chế phối hợp 3 bên bảo đảm sự bao phủ toàn diện học sinh trong và ngoài '
                     'nhà trường.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Ngành Y Tế (Nòng Cốt Kỹ Thuật)',
                 'text': 'Cung cấp chuyên gia báo cáo viên, xây dựng tài liệu chuẩn y khoa, tổ chức góc thân thiện và '
                         'khám chữa bệnh phụ sản an toàn.',
                 'icon': 'shield-check'},
               { 'title': 'Ngành Giáo Dục (Môi Trường Sư Phạm)',
                 'text': 'Bố trí thời lượng ngoại khóa, phối hợp tổ chức các hội thi, lồng ghép vào môn Sinh học và '
                         'quản lý học sinh nền nếp.',
                 'icon': 'book-open'},
               { 'title': 'Đoàn Thanh Niên (Cầu Nối Đồng Đẳng)',
                 'text': 'Tổ chức các diễn đàn tuổi trẻ, sinh hoạt hè tại khu dân cư, tiếp cận nhóm thanh niên công '
                         'nhân tại khu công nghiệp.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Kế hoạch phối hợp liên ngành thanh thiếu niên - BÀI 4',
    'v91_compliant': True}]
