# -*- coding: utf-8 -*-
"""
scripts/course2_data_bai3.py
Exhaustive Deep-Curriculum Slide Blueprints for BÀI 3 (Make Slide Pro V9.1).
30%-50% High-Resolution Visual Illustrations, Native Charts, Zero AI Slop, Zero Watermarks.
"""

from typing import Any, Dict, List


def get_slides_bai_3() -> List[Dict[str, Any]]:
    return [ { 'slide_id': 'SLIDE_01',
    'role': 'COVER',
    'section': 'TỔNG QUAN CHUYÊN ĐỀ',
    'assertion_title': 'BÀI 3: DỊCH VỤ KẾ HOẠCH HÓA GIA ĐÌNH',
    'primary_claim': 'Hệ thống chuyên khảo toàn diện về 12 biện pháp tránh thai lâm sàng, kỹ thuật y tế an toàn, quản '
                     'trị chuỗi cung ứng và tổ chức dịch vụ đa tuyến.',
    'visual_job': 'HERO_TITLE',
    'visual_anchor': 'BRAND_COVER',
    'transition': 'fade',
    'transition_duration': 0.65,
    'illustration': 'illustration_bai_3.jpg',
    'speaker_notes': 'Kính chào quý học viên, hôm nay chúng ta nghiên cứu chuyên đề Bài 3: Dịch vụ Kế hoạch hóa gia '
                     'đình với 12 biện pháp tránh thai cốt lõi.',
    'source_footer': 'Tài liệu đào tạo chuẩn hóa: Bài 3. Dịch vụ DS KHHGĐ.docx',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_02',
    'role': 'CONTENT',
    'section': 'MỤC TIÊU BÀI HỌC',
    'assertion_title': 'Chuẩn Đầu Ra 5 Khối Năng Lực Cốt Lõi Về Dịch Vụ Kế Hoạch Hóa Gia Đình',
    'primary_claim': 'Trang bị cho học viên năng lực thực hành lâm sàng, tư vấn lựa chọn sáng suốt và quản lý chuỗi '
                     'cung ứng phương tiện tránh thai.',
    'visual_job': 'CONTAINER_BENTO_COMPLEX',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Khái Niệm & Phân Loại',
                 'text': 'Trình bày chuẩn xác khái niệm KHHGĐ và phân loại hệ thống các biện pháp tránh thai hiện đại, '
                         'truyền thống, nội tiết và phi nội tiết.',
                 'icon': 'book-open'},
               { 'title': '2. Khách Hàng & Tiếp Cận',
                 'text': 'Xác định nhu cầu đa dạng của các nhóm dân số sinh sản (15-49 tuổi) và nguyên tắc tôn trọng '
                         'quyền lựa chọn tự nguyện có hiểu biết.',
                 'icon': 'users'},
               { 'title': '3. Năng Lực Cơ Sở Cung Ứng',
                 'text': 'Nắm vững tiêu chuẩn phòng thủ thuật vô khuẩn, trang thiết bị lâm sàng và chuẩn kỹ năng của '
                         'người cung cấp dịch vụ.',
                 'icon': 'shield-check'},
               { 'title': '4. Làm Chủ 12 Biện Pháp Tránh Thai',
                 'text': 'Thực hành thuần thục cơ chế, chỉ định, chống chỉ định, quy trình kỹ thuật và xử trí biến '
                         'chứng của 12 biện pháp tránh thai lâm sàng.',
                 'icon': 'activity'},
               { 'title': '5. Quản Lý & Lập Kế Hoạch Logistics',
                 'text': 'Vận hành hệ thống quản lý 4 tuyến, phương pháp dự báo nhu cầu phương tiện tránh thai và chỉ '
                         'số bảo vệ cặp vợ chồng (CYP).',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Khung chuẩn đầu ra chuyên đề đào tạo KHHGĐ',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_03',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Bản Chất Nhân Văn Và Khoa Học Của Kế Hoạch Hóa Gia Đình',
    'primary_claim': 'KHHGĐ là nỗ lực có ý thức của cá nhân và cặp vợ chồng nhằm chủ động quyết định số con, thời điểm '
                     'và khoảng cách sinh con.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Quyền Tự Quyết Sinh Sản',
                 'text': 'Trao quyền cho các cặp vợ chồng chủ động lựa chọn thời điểm sinh con khi đã sẵn sàng về tâm '
                         'lý, sức khỏe và kinh tế.',
                 'icon': 'check-circle'},
               { 'title': 'Khoảng Cách Sinh Hợp Lý',
                 'text': 'Bảo đảm khoảng cách giữa hai lần sinh từ 3 đến 5 năm giúp cơ thể người mẹ hồi phục và trẻ sơ '
                         'sinh được chăm sóc chu đáo.',
                 'icon': 'calendar'},
               { 'title': 'Quy Mô Gia Đình Hạnh Phúc',
                 'text': 'Duy trì quy mô gia đình ít con (mỗi cặp vợ chồng sinh đủ 2 con) để có điều kiện nuôi dạy con '
                         'cái thành đạt.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tài liệu đào tạo KHHGĐ - Mục 1. Khái niệm',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_04',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Tác Động Sâu Rộng Của KHHGĐ Đến Sức Khỏe Và Phát Triển Đất Nước',
    'primary_claim': 'KHHGĐ là khoản đầu tư mang lại lợi ích kép cho sức khỏe bà mẹ trẻ em và tăng trưởng kinh tế xã '
                     'hội.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Bảo Vệ Tính Mạng Bà Mẹ',
                 'text': 'Giảm thiểu trên 30% tỷ lệ tử vong mẹ nhờ loại trừ các ca mang thai quá sớm, quá muộn, quá '
                         'dày hoặc mang thai ngoài ý muốn.',
                 'icon': 'shield-check'},
               { 'title': 'Giảm Tử Vong Trẻ Sơ Sinh',
                 'text': 'Trẻ em sinh ra đủ tháng, đủ cân nặng, giảm tỷ lệ suy dinh dưỡng và dị tật do được chăm sóc '
                         'dinh dưỡng đầy đủ.',
                 'icon': 'award'},
               { 'title': 'Giải Phóng Phụ Nữ',
                 'text': 'Giúp người phụ nữ có cơ hội học tập, nâng cao trình độ chuyên môn, tham gia hoạt động kinh '
                         'tế xã hội và bình đẳng giới.',
                 'icon': 'users'},
               { 'title': 'Tận Dụng Dân Số Vàng',
                 'text': 'Hạ thấp tỷ lệ phụ thuộc, tăng tỷ lệ người trong độ tuổi lao động, tích lũy nguồn lực tài '
                         'chính cho công nghiệp hóa quốc gia.',
                 'icon': 'trending-up'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Báo cáo dân số và phát triển quốc gia',
    'illustration': 'illustration_bai_3.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_05',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI BIỆN PHÁP',
    'assertion_title': 'Khung Phân Loại Đa Chiều Các Biện Pháp Tránh Thai Hiện Hành',
    'primary_claim': 'Việc phân nhóm biện pháp giúp cán bộ y tế dễ dàng định hướng tư vấn phù hợp với từng đối tượng.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Theo Tính Hiện Đại',
                 'text': 'Biện pháp hiện đại (DCTC, thuốc nội tiết, bao cao su, triệt sản) vs Biện pháp truyền thống '
                         '(tính ngày, xuất tinh ngoài).',
                 'icon': 'layers'},
               { 'title': 'Theo Thời Gian Tác Dụng',
                 'text': 'Biện pháp tạm thời (có thể phục hồi khả năng sinh sản ngay sau ngừng dùng) vs Biện pháp vĩnh '
                         'viễn (triệt sản nam/nữ).',
                 'icon': 'clock'},
               { 'title': 'Theo Cơ Chế Dược Lý',
                 'text': 'Biện pháp chứa nội tiết (thuốc viên kết hợp, thuốc cấy, thuốc tiêm, vòng Mirena) vs Biện '
                         'pháp phi nội tiết (TCu 380A, bao cao su).',
                 'icon': 'activity'},
               { 'title': 'Theo Đối Tượng Sử Dụng',
                 'text': 'Biện pháp dành cho nữ giới (chiếm đại đa số danh mục) vs Biện pháp dành cho nam giới (bao '
                         'cao su, triệt sản nam, xuất tinh ngoài).',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Phân loại biện pháp KHHGĐ - Mục 2',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_06',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI BIỆN PHÁP',
    'assertion_title': 'Thước Đo Hiệu Quả Lâm Sàng: Chỉ Số Pearl Index Và Tỷ Lệ Thất Bại',
    'primary_claim': 'Pearl Index phản ánh số trường hợp có thai ngoài ý muốn trên 100 phụ nữ sử dụng biện pháp trong '
                     'vòng 1 năm.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Hiệu Quả Hoàn Hảo (Perfect Use)',
                 'text': 'Tỷ lệ thất bại khi biện pháp được sử dụng tuyệt đối chính xác và đều đặn theo đúng chỉ dẫn '
                         'của nhà sản xuất.',
                 'icon': 'check-circle'},
               { 'title': 'Hiệu Quả Thực Tế (Typical Use)',
                 'text': 'Tỷ lệ thất bại trong đời sống thực tế khi người dùng có thể quên thuốc, dùng sai quy cách '
                         'hoặc bảo quản sai tiêu chuẩn.',
                 'icon': 'alert-circle'},
               { 'title': 'Bậc Thang Hiệu Quả Cao Nhất',
                 'text': 'Que cấy tránh thai (thất bại <0.05%), Triệt sản nam (<0.15%), Triệt sản nữ (<0.5%), Dụng cụ '
                         'tử cung (<0.8%).',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tổ chức Y tế Thế giới (WHO) - Medical Eligibility Criteria',
    'illustration': 'ai_bai_3_fertility.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_07',
    'role': 'CONTENT',
    'section': '3. ĐẶC ĐIỂM KHÁCH HÀNG',
    'assertion_title': 'Khách Hàng Mục Tiêu: Cặp Vợ Chồng Trong Độ Tuổi Sinh Đẻ 15-49',
    'primary_claim': 'Nhóm khách hàng rộng lớn đòi hỏi sự phân khúc nhu cầu theo từng chu kỳ sinh sản cụ thể.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Cặp Đôi Trẻ Mới Cưới',
                 'text': 'Mong muốn trì hoãn lần sinh đầu tiên để ổn định sự nghiệp; ưu tiên các biện pháp phục hồi '
                         'sinh sản nhanh như viên uống, bao cao su.',
                 'icon': 'heart'},
               { 'title': 'Phụ Nữ Sau Sinh & Cho Con Bú',
                 'text': 'Cần biện pháp không ức chế tiết sữa và không ảnh hưởng sự phát triển của trẻ: que cấy, thuốc '
                         'tiêm DMPA, thuốc viên POP, DCTC.',
                 'icon': 'award'},
               { 'title': 'Cặp Đôi Đã Sinh Đủ 2 Con',
                 'text': 'Có nhu cầu tránh thai dài hạn hoặc vĩnh viễn: dụng cụ tử cung TCu 380A, cấy que 3-5 năm hoặc '
                         'triệt sản nam/nữ.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Phân tích khách hàng KHHGĐ - Mục 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_08',
    'role': 'CONTENT',
    'section': '3. ĐẶC ĐIỂM KHÁCH HÀNG',
    'assertion_title': 'Nguyên Tắc Tiếp Cận: Lựa Chọn Sáng Suốt (Informed Choice)',
    'primary_claim': 'Tuyệt đối không ép buộc hoặc áp đặt biện pháp; khách hàng có quyền được thông tin đầy đủ và tự '
                     'quyết.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': '1. Lắng Nghe Nguyện Vọng',
                 'text': 'Tìm hiểu nhu cầu sinh con, tiền sử bệnh tật và thói quen sinh hoạt của khách hàng.',
                 'icon': 'user-check'},
               { 'title': '2. Cung Cấp Thông Tin 2 Mặt',
                 'text': 'Nêu rõ cơ chế tác dụng, tỷ lệ hiệu quả, các tác dụng phụ thường gặp và chi phí của từng biện '
                         'pháp.',
                 'icon': 'book-open'},
               { 'title': '3. Tự Do Lựa Chọn',
                 'text': 'Khách hàng tự quyết định biện pháp phù hợp nhất với thể trạng và hoàn cảnh gia đình của '
                         'mình.',
                 'icon': 'check-circle'},
               { 'title': '4. Hỗ Trợ Đổi Biện Pháp',
                 'text': 'Sẵn sàng hỗ trợ khách hàng chuyển đổi sang biện pháp khác nếu gặp tác dụng phụ không dung '
                         'nạp.',
                 'icon': 'refresh-cw'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Nguyên tắc tư vấn Informed Choice - Quyết định 25/QĐ-BYT',
    'illustration': 'cinematic_bai_3_health.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_09',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ & CÁN BỘ',
    'assertion_title': 'Tiêu Chuẩn Cơ Sở & Đội Ngũ Cung Cấp Dịch Vụ KHHGĐ',
    'primary_claim': 'Cơ sở vật chất chuẩn hóa và cán bộ có chứng chỉ hành nghề là điều kiện tiên quyết bảo đảm an '
                     'toàn thủ thuật.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Môi Trường Vô Khuẩn Chuẩn',
                 'text': 'Phòng thủ thuật đặt vòng, cấy que, triệt sản bảo đảm quy chế kiểm soát nhiễm khuẩn, có bồn '
                         'rửa tay vô khuẩn và máy hấp sấy dụng cụ.',
                 'icon': 'shield-check'},
               { 'title': 'Cơ Số Thuốc Cấp Cứu Sốc Phản Vệ',
                 'text': 'Trang bị đầy đủ hộp thuốc cấp cứu chống sốc phản vệ (Adrenalin), bình oxy, bóng bóp Ambu và '
                         'cáng cứu thương sẵn sàng.',
                 'icon': 'alert-circle'},
               { 'title': 'Chứng Chỉ Chuyên Môn Bắt Buộc',
                 'text': 'Bác sĩ, nữ hộ sinh hoặc y sĩ sản nhi phải được đào tạo bài bản và có chứng chỉ kỹ thuật đặt '
                         'DCTC, cấy que hoặc thắt ống dẫn tinh.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy chế cung ứng dịch vụ y tế KHHGĐ - Mục 4',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_10',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ & CÁN BỘ',
    'assertion_title': 'Nguyên Tắc An Toàn Người Bệnh Trong Thực Hành Thủ Thuật KHHGĐ',
    'primary_claim': 'Tuân thủ nghiêm ngặt quy trình kỹ thuật để loại trừ hoàn toàn tai biến nhiễm trùng và tổn thương '
                     'thực thể.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Khám Sàng Lọc Trước Thủ Thuật',
                 'text': 'Khám phụ khoa/nam khoa loại trừ viêm nhiễm cấp tính, loại trừ có thai và đánh giá tiền sử dị '
                         'ứng thuốc gây tê.',
                 'icon': 'activity'},
               { 'title': 'Vô Khuẩn Tuyệt Đối',
                 'text': 'Sát khuẩn vùng da/niêm mạc đúng nồng độ, sử dụng găng tay vô khuẩn và bộ dụng cụ tiệt trùng '
                         'đóng gói riêng biệt cho từng ca.',
                 'icon': 'shield'},
               { 'title': 'Thao Tác Nhẹ Nhàng Chuẩn Xác',
                 'text': 'Tuân thủ lực kéo đẩy phù hợp, tránh gây thủng tử cung khi đặt DCTC hoặc tổn thương bó mạch '
                         'thừng tinh khi triệt sản.',
                 'icon': 'check-circle'},
               { 'title': 'Theo Dõi Hậu Phẫu Đầy Đủ',
                 'text': 'Theo dõi mạch, huyết áp, chảy máu tại cơ sở y tế ít nhất 30 phút đối với đặt DCTC/cấy que và '
                         '2 giờ đối với triệt sản.',
                 'icon': 'clock'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình kiểm soát nhiễm khuẩn Bộ Y tế',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_11',
    'role': 'CONTENT',
    'section': '5.1. DỤNG CỤ TỬ CUNG (DCTC)',
    'assertion_title': 'Khái Niệm, Cơ Chế Hoạt Động & Hiệu Quả Của DCTC TCu 380A',
    'primary_claim': 'DCTC là biện pháp tránh thai hồi phục dài hạn phổ biến nhất tại Việt Nam với hiệu quả bảo vệ '
                     'trên 99%.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Cấu Tạo Chữ T Cuộn Dây Đồng',
                 'text': 'DCTC TCu 380A làm bằng nhựa dẻo phủ đồng diện tích 380 mm2, có hai sợi dây nylon ở đuôi giúp '
                         'kiểm tra vị trí.',
                 'icon': 'shield'},
               { 'title': 'Cơ Chế Diệt Tinh Trùng & Ngăn Làm Tổ',
                 'text': 'Ion đồng (Cu2+) phóng thích liên tục làm bất hoạt tinh trùng, đồng thời gây phản ứng viêm vô '
                         'khuẩn nội mạc ngăn trứng thụ tinh làm tổ.',
                 'icon': 'activity'},
               { 'title': 'Thời Gian Bảo Vệ Đến 10 Năm',
                 'text': 'Hiệu quả tránh thai đạt 99.2 - 99.4%, kéo dài liên tục 10-12 năm, không ảnh hưởng nội tiết '
                         'và hồi phục sinh sản ngay sau tháo.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.1 - Đặt dụng cụ tử cung',
    'illustration': 'ai_bai_2_golden.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_12',
    'role': 'CONTENT',
    'section': '5.1. DỤNG CỤ TỬ CUNG (DCTC)',
    'assertion_title': 'Chỉ Định, Chống Chỉ Định Tuyệt Đối & Tương Đối Của DCTC',
    'primary_claim': 'Phải sàng lọc cẩn trọng để bảo đảm an toàn, tuyệt đối không đặt cho bệnh nhân có nguy cơ viêm '
                     'nhiễm vùng chậu.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Chỉ Định Rộng Rãi',
                 'text': 'Phụ nữ trong độ tuổi sinh đẻ muốn tránh thai dài hạn, phụ nữ đang cho con bú, phụ nữ có '
                         'chống chỉ định với estrogen (tăng huyết áp, tiểu đường).',
                 'icon': 'check-circle'},
               { 'title': 'Chống Chỉ Định Tuyệt Đối (Cấm Đặt)',
                 'text': 'Có thai hoặc nghi ngờ có thai; đang mắc viêm nhiễm đường sinh dục cấp tính, viêm vùng chậu '
                         '(PID); dị dạng tử cung nặng; ung thư cổ tử cung hoặc buồng tử cung; chảy máu âm đạo bất '
                         'thường chưa rõ nguyên nhân.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.1 - Chỉ định và chống chỉ định DCTC',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_13',
    'role': 'CONTENT',
    'section': '5.1. DỤNG CỤ TỬ CUNG (DCTC)',
    'assertion_title': 'Thời Điểm Đặt DCTC Lý Tưởng & Quy Trình Kỹ Thuật Chuẩn',
    'primary_claim': 'Lựa chọn đúng thời điểm giúp thủ thuật diễn ra dễ dàng, ít đau và loại trừ hoàn toàn nguy cơ có '
                     'thai.',
    'visual_job': 'CHART_AND_INSIGHTS',
    'visual_anchor': 'CHART_AND_INSIGHTS',
    'atoms': [ { 'title': '1. Ngay Sau Sạch Kinh',
                 'text': 'Ngày thứ 3 đến ngày thứ 7 của chu kỳ kinh nguyệt (lỗ cổ tử cung hơi hé mở, chắc chắn không '
                         'có thai).',
                 'icon': 'calendar'},
               { 'title': '2. Thời Kỳ Hậu Sản',
                 'text': 'Ngay sau đẻ thường trong vòng 48h, hoặc sau đẻ 6 tuần trở đi khi tử cung đã hồi phục hoàn '
                         'toàn kích thước.',
                 'icon': 'clock'},
               { 'title': '3. Sau Hút Nạo Phá Thai',
                 'text': 'Đặt ngay sau khi phá thai an toàn nếu lòng tử cung sạch, không nhiễm trùng và không có ứ '
                         'máu.',
                 'icon': 'shield'},
               { 'title': '4. Tránh Thai Khẩn Cấp',
                 'text': 'Có thể đặt trong vòng 5 ngày (120h) sau khi quan hệ không bảo vệ để làm biện pháp tránh thai '
                         'khẩn cấp.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Thời điểm đặt DCTC - BÀI 3. Mục 5.1',
    'chart_type': 'COLUMN_CLUSTERED',
    'chart_file': 'chart_fertility_by_region_bar_dark.png',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_14',
    'role': 'CONTENT',
    'section': '5.1. DỤNG CỤ TỬ CUNG (DCTC)',
    'assertion_title': 'Xử Trí Tác Dụng Phụ, Tụt Vòng & Dấu Hiệu Nhiễm Khuẩn DCTC',
    'primary_claim': 'Tư vấn trước giúp khách hàng an tâm với các biến động kinh nguyệt nhẹ và nhận diện kịp thời biến '
                     'chứng.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Đau Trằn Bụng Dưới & Đau Lưng',
                 'text': 'Thường giảm dần sau vài ngày; hướng dẫn dùng thuốc giảm đau Paracetamol hoặc chống co thắt '
                         'cơ trơn (Spasfon).',
                 'icon': 'activity'},
               { 'title': 'Tăng Lượng Máu Kinh & Ra Máu Nhẹ',
                 'text': 'Kinh nguyệt nhiều hơn trong 2-3 chu kỳ đầu do phản ứng nội mạc; tư vấn uống bổ sung viên sắt '
                         'dự phòng thiếu máu.',
                 'icon': 'heart'},
               { 'title': 'Kiểm Tra Dây Vòng & Tụt Vòng',
                 'text': 'Hướng dẫn khách hàng tự kiểm tra dây vòng sau mỗi kỳ hành kinh; nếu mất dây hoặc sờ thấy '
                         'thân vòng phải đi khám ngay.',
                 'icon': 'search'},
               { 'title': 'Nhiễm Khuẩn Vùng Chậu (PID)',
                 'text': 'Sốt cao, đau bụng hạ vị dữ dội, khí hư hôi bẩn: Cần tháo DCTC ngay, cấy vi khuẩn và điều trị '
                         'kháng sinh toàn thân liều cao.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Xử trí biến chứng DCTC - BÀI 3',
    'illustration': 'illustration_bai_3.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_15',
    'role': 'CONTENT',
    'section': '5.2. TRIỆT SẢN NAM',
    'assertion_title': 'Bản Chất Thắt & Cắt Ống Dẫn Tinh: Phương Pháp Không Dao (NSV)',
    'primary_claim': 'Triệt sản nam là phương pháp phẫu thuật nhỏ, cực kỳ an toàn, nhẹ nhàng và chia sẻ trách nhiệm '
                     'của phái mạnh.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Kỹ Thuật Không Dao (NSV)',
                 'text': 'Sử dụng kẹp cố định thừng tinh và panh đầu nhọn chọc lỗ nhỏ 2-3mm trên bìu, không rạch da, '
                         'không cần khâu, không để sẹo.',
                 'icon': 'shield-check'},
               { 'title': 'Thời Gian Thủ Thuật 15 Phút',
                 'text': 'Tiến hành dưới gây tê tại chỗ, thao tác nhanh gọn trong 10-15 phút, người đàn ông có thể đi '
                         'lại và về nhà ngay trong ngày.',
                 'icon': 'clock'},
               { 'title': 'Hiệu Quả Triệt Để >99.85%',
                 'text': 'Ngăn chặn vĩnh viễn đường di chuyển của tinh trùng từ tinh hoàn lên túi tinh, loại bỏ hoàn '
                         'toàn khả năng thụ thai.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.2 - Triệt sản nam',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_16',
    'role': 'CONTENT',
    'section': '5.2. TRIỆT SẢN NAM',
    'assertion_title': 'Cơ Chế Sinh Học & Bảo Tồn Bản Lĩnh Phái Mạnh Sau Triệt Sản',
    'primary_claim': 'Thắt ống dẫn tinh hoàn toàn không ảnh hưởng đến nội tiết tố, cương dương hay cảm giác khoái cảm '
                     'tình dục.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Nội Tiết Tố Testosterone Giữ Nguyên',
                 'text': 'Hormone sinh dục nam do tế bào kẽ Leydig tiết trực tiếp vào mạch máu, không đi qua ống dẫn '
                         'tinh; do đó ham muốn và nam tính được bảo tồn 100%.',
                 'icon': 'activity'},
               { 'title': 'Hiện Tượng Xuất Tinh Vẫn Bình Thường',
                 'text': 'Tinh trùng chỉ chiếm 1-2% thể tích tinh dịch (phần lớn do tuyến tiền liệt và túi tinh tiết '
                         'ra); nam giới sau triệt sản vẫn xuất tinh và đạt khoái cảm như cũ.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Giải phẫu sinh lý triệt sản nam - BÀI 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_17',
    'role': 'CONTENT',
    'section': '5.2. TRIỆT SẢN NAM',
    'assertion_title': 'Chỉ Định, Tư Vấn Đồng Thuận & Chuẩn Bị Thủ Thuật Triệt Sản Nam',
    'primary_claim': 'Bắt buộc phải có sự tự nguyện đồng thuận bằng văn bản của cả hai vợ chồng trước khi tiến hành '
                     'can thiệp.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Tiêu Chí Lựa Chọn',
                 'text': 'Nam giới đã có đủ số con mong muốn (từ 2 con khỏe mạnh trở lên), con nhỏ nhất trên 2 tuổi và '
                         'vợ chồng hoàn toàn đồng thuận.',
                 'icon': 'users'},
               { 'title': 'Tư Vấn Tính Bất Khả Hồi',
                 'text': 'Nhấn mạnh đây là biện pháp vĩnh viễn; việc nối lại ống dẫn tinh vô cùng phức tạp, chi phí '
                         'cao và tỷ lệ thành công thấp.',
                 'icon': 'alert-circle'},
               { 'title': 'Khám Sàng Lọc Lâm Sàng',
                 'text': 'Khám bìu loại trừ viêm tinh hoàn, mào tinh hoàn, thoát vị bẹn, tinh hoàn lạc chỗ hoặc rối '
                         'loạn đông máu trước khi mổ.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình tư vấn triệt sản nam - BÀI 3. Mục 5.2',
    'illustration': 'ai_bai_3_fertility.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_18',
    'role': 'CONTENT',
    'section': '5.2. TRIỆT SẢN NAM',
    'assertion_title': "Lưu Ý 'Cửa Sổ Vàng' 3 Tháng Sau Triệt Sản Nam: Bắt Buộc Dùng BCS",
    'primary_claim': 'Sau thắt ống dẫn tinh, tinh trùng tồn lưu trong túi tinh vẫn có khả năng thụ thai trong 20 lần '
                     'xuất tinh đầu.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Nguy Cơ Tinh Trùng Tồn Lưu',
                 'text': 'Đoạn trên của ống dẫn tinh và bóng túi tinh vẫn còn chứa hàng triệu tinh trùng sống sót sau '
                         'khi thắt cắt ống.',
                 'icon': 'alert-circle'},
               { 'title': 'Quy Tắc 20 Lần / 3 Tháng',
                 'text': 'Bắt buộc phải sử dụng bao cao su hoặc biện pháp tránh thai hỗ trợ khác trong ít nhất 3 tháng '
                         'hoặc qua 20 lần xuất tinh.',
                 'icon': 'clock'},
               { 'title': 'Xét Nghiệm Tinh Dịch Đồ (Azoospermia)',
                 'text': 'Chỉ được tuyên bố hết khả năng sinh sản khi xét nghiệm tinh dịch đồ chứng minh không còn '
                         'tinh trùng di động (0 tinh trùng).',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Khuyến cáo lâm sàng sau triệt sản nam - BÀI 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_19',
    'role': 'CONTENT',
    'section': '5.3. TRIỆT SẢN NỮ',
    'assertion_title': 'Bản Chất Phương Pháp Thắt & Cắt Vòi Tử Cung (Ống Dẫn Trứng)',
    'primary_claim': 'Triệt sản nữ là biện pháp tránh thai vĩnh viễn thông qua việc ngăn cản sự gặp gỡ giữa noãn bào '
                     'và tinh trùng.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Cơ Chế Làm Tắc Vòi Tử Cung',
                 'text': 'Thắt và cắt một đoạn vòi tử cung (phương pháp Pomeroy) hoặc kẹp clip, đốt điện làm bít tắc '
                         'hoàn toàn lòng vòi trứng hai bên.',
                 'icon': 'shield-check'},
               { 'title': 'Bảo Toàn Chu Kỳ Kinh Nguyệt',
                 'text': 'Buồng trứng vẫn tiếp tục rụng noãn và tiết hormone estrogen, progesterone bình thường; máu '
                         'kinh nguyệt vẫn hành kinh đều đặn.',
                 'icon': 'activity'},
               { 'title': 'Hiệu Quả Vĩnh Viễn >99.5%',
                 'text': 'Hiệu quả tránh thai trọn đời, tỷ lệ thất bại chỉ khoảng 0.5% (do tái thông tự nhiên cực hiếm '
                         'gặp).',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.3 - Triệt sản nữ',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_20',
    'role': 'CONTENT',
    'section': '5.3. TRIỆT SẢN NỮ',
    'assertion_title': 'Hai Kỹ Thuật Can Thiệp: Mổ Nhỏ (Minilaparotomy) & Phẫu Thuật Nội Soi',
    'primary_claim': 'Tùy thuộc điều kiện trang thiết bị và thời điểm sau sinh để lựa chọn phương thức phẫu thuật tối '
                     'ưu.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Đường Mở Nhỏ Dưới Rốn (Minilap)',
                 'text': 'Thực hiện đường rạch nhỏ 2-3cm ở nếp dưới rốn (sau sinh) hoặc trên xương mu (thời kỳ một); '
                         'áp dụng rộng rãi tại bệnh viện tuyến huyện với chi phí hợp lý.',
                 'icon': 'activity'},
               { 'title': 'Phẫu Thuật Nội Soi Ổ Bụng (Laparoscopy)',
                 'text': 'Thực hiện qua 2-3 lỗ trocar siêu nhỏ 5mm dưới hướng dẫn camera độ nét cao; ít đau, tính thẩm '
                         'mỹ tuyệt đối, hồi phục nhanh sau 24 giờ.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Kỹ thuật ngoại khoa triệt sản nữ - BÀI 3',
    'illustration': 'cinematic_bai_3_health.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_21',
    'role': 'CONTENT',
    'section': '5.3. TRIỆT SẢN NỮ',
    'assertion_title': 'Thời Điểm Can Thiệp & Chống Chỉ Định Của Triệt Sản Nữ',
    'primary_claim': 'Lựa chọn thời điểm sau sinh hoặc kết hợp mổ lấy thai giúp tiết kiệm thời gian phẫu thuật và giảm '
                     'đau đớn.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Sau Đẻ Thường (24-48 Giờ)',
                 'text': 'Đáy tử cung còn ở vị trí cao ngang rốn, dễ dàng tìm và đưa vòi tử cung ra ngoài vết mổ dưới '
                         'rốn.',
                 'icon': 'clock'},
               { 'title': 'Kết Hợp Mổ Lấy Thai',
                 'text': 'Tiến hành thắt vòi trứng ngay sau khi đã lấy thai và sổ rau xong, không cần tạo thêm vết mổ '
                         'mới.',
                 'icon': 'shield-check'},
               { 'title': 'Triệt Sản Thời Kỳ Một (Phi Hậu Sản)',
                 'text': 'Thực hiện vào nửa đầu chu kỳ kinh nguyệt sau khi sạch kinh để chắc chắn không mang thai.',
                 'icon': 'calendar'},
               { 'title': 'Chống Chỉ Định Lâm Sàng',
                 'text': 'Nhiễm khuẩn hậu sản, viêm phúc mạc, bệnh lý tim phổi mất bù, thiếu máu nặng hoặc ung thư '
                         'tiến triển.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.3 - Thời điểm và chống chỉ định',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_22',
    'role': 'CONTENT',
    'section': '5.3. TRIỆT SẢN NỮ',
    'assertion_title': 'Chăm Sóc Sau Mổ & Theo Dõi Phục Hồi Triệt Sản Nữ',
    'primary_claim': 'Theo dõi sát trong 24-48 giờ đầu giúp phát hiện sớm nguy cơ chảy máu trong hoặc tổn thương tạng '
                     'lân cận.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Theo Dõi Dấu Hiệu Sinh Tồn',
                 'text': 'Đo mạch, huyết áp, nhiệt độ, kiểm tra băng vết mổ xem có rỉ máu tươi hay không mỗi 4-6 giờ.',
                 'icon': 'activity'},
               { 'title': 'Dinh Dưỡng & Vận Động Sớm',
                 'text': 'Khuyến khích ngồi dậy và vận động nhẹ sau 6-8 giờ để kích thích nhu động ruột, tránh dính '
                         'sau mổ.',
                 'icon': 'user-check'},
               { 'title': 'Hướng Dẫn Khi Xuất Viện',
                 'text': 'Nghỉ ngơi lao động nặng trong 2 tuần, kiêng quan hệ tình dục ít nhất 1 tháng và giữ khô sạch '
                         'vết mổ.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình chăm sóc hậu phẫu triệt sản nữ - BÀI 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_23',
    'role': 'CONTENT',
    'section': '5.4. THUỐC CẤY TRÁNH THAI',
    'assertion_title': 'Bản Chất & Cơ Chế Hoạt Động Của Hệ Thống Cấy Que Tránh Thai',
    'primary_claim': 'Que cấy là biện pháp tránh thai nội tiết tác dụng kéo dài hàng đầu với tỷ lệ thất bại thấp nhất '
                     '(<0.05%).',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Que Nhựa Phóng Thích Progestin',
                 'text': 'Chứa hormone Levonorgestrel hoặc Etonogestrel, được cấy dưới da mặt trong cánh tay không '
                         'thuận qua kim dẫn chuyên dụng.',
                 'icon': 'shield'},
               { 'title': '3 Cơ Chế Dược Lý Bổ Trợ',
                 'text': '1. Ức chế hoàn toàn quá trình rụng trứng; 2. Làm đặc quánh chất nhầy cổ tử cung ngăn tinh '
                         'trùng; 3. Làm teo nội mạc tử cung.',
                 'icon': 'activity'},
               { 'title': 'Hiệu Quả Cao Nhất Lâm Sàng',
                 'text': 'Chỉ 1 ca có thai trên 2.000 phụ nữ sử dụng; giải phóng phụ nữ khỏi nỗi lo nhớ uống thuốc mỗi '
                         'ngày.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.4 - Thuốc cấy tránh thai',
    'illustration': 'ai_bai_2_golden.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_24',
    'role': 'CONTENT',
    'section': '5.4. THUỐC CẤY TRÁNH THAI',
    'assertion_title': 'So Sánh Hai Dòng Que Cấy Phổ Biến: Implanon (1 Que) & Jadelle (2 Que)',
    'primary_claim': 'Hiểu rõ sự khác biệt về số lượng que, loại hoạt chất và thời hạn bảo vệ giúp cá nhân hóa tư vấn.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Implanon NXT (1 Que - 3 Năm)',
                 'text': 'Chứa 68mg Etonogestrel, que cấy đơn chiếc dài 4cm, thủ thuật cấy và tháo que cực kỳ nhanh '
                         'gọn trong 2-3 phút, thời hạn bảo vệ liên tục 3 năm.',
                 'icon': 'check-circle'},
               { 'title': 'Jadelle / Norplant (2 Que - 5 Năm)',
                 'text': 'Mỗi que chứa 75mg Levonorgestrel (tổng 150mg), cấy theo hình chữ V dưới da, bảo vệ tránh '
                         'thai kéo dài lên tới 5 năm, kinh tế hơn cho phụ nữ nông thôn.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'So sánh thông số kỹ thuật que cấy - BÀI 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_25',
    'role': 'CONTENT',
    'section': '5.4. THUỐC CẤY TRÁNH THAI',
    'assertion_title': 'Chỉ Định, Thời Điểm Cấy & Chống Chỉ Định Que Cấy',
    'primary_claim': 'Không chứa estrogen nên an toàn cho phụ nữ cho con bú và người có bệnh tim mạch nhẹ.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Chỉ Định Tối Ưu',
                 'text': 'Phụ nữ muốn tránh thai hiệu quả cao dài hạn, phụ nữ đang nuôi con bú từ 6 tuần sau sinh, '
                         'người không dùng được estrogen.',
                 'icon': 'check-circle'},
               { 'title': 'Thời Điểm Cấy Que Chuẩn',
                 'text': 'Trong 5 ngày đầu tiên của chu kỳ kinh nguyệt; nếu cấy vào ngày khác phải dùng thêm bao cao '
                         'su trong 7 ngày đầu.',
                 'icon': 'calendar'},
               { 'title': 'Chống Chỉ Định',
                 'text': 'Có thai; ung thư vú hoặc tiền sử ung thư vú; bệnh gan nặng tiến triển (xơ gan, u gan); '
                         'thuyên tắc huyết khối tĩnh mạch sâu.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.4 - Chỉ định và thời điểm cấy',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_26',
    'role': 'CONTENT',
    'section': '5.4. THUỐC CẤY TRÁNH THAI',
    'assertion_title': 'Biến Đổi Mẫu Hình Chảy Máu Kinh & Hướng Dẫn Trấn An Khách Hàng',
    'primary_claim': 'Rối loạn kinh nguyệt là hiện tượng sinh lý dự đoán trước, hoàn toàn không gây hại cho sức khỏe '
                     'phụ nữ.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Hiện Tượng Vô Kinh (Amenorrhea)',
                 'text': 'Chiếm 20-30% khách hàng sau vài tháng cấy; giải thích rõ: máu kinh không bị ứ đọng trong '
                         'bụng mà do niêm mạc mỏng không bong.',
                 'icon': 'info'},
               { 'title': 'Kinh Ít Hoặc Ra Máu Rỉ Rả',
                 'text': 'Ra máu thấm giọt giữa chu kỳ thường gặp trong 3-6 tháng đầu; tư vấn kiên nhẫn theo dõi, dùng '
                         'thuốc cầm máu nếu kéo dài.',
                 'icon': 'activity'},
               { 'title': 'Hồi Phục Khả Năng Thụ Thai',
                 'text': 'Hàm lượng progestin biến mất khỏi cơ thể sau 48-72h tháo que; chu kỳ rụng trứng và khả năng '
                         'thụ thai trở lại hoàn toàn bình thường.',
                 'icon': 'refresh-cw'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tư vấn tác dụng phụ que cấy - BÀI 3',
    'illustration': 'illustration_bai_3.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_27',
    'role': 'CONTENT',
    'section': '5.5. THUỐC TIÊM TRÁNH THAI',
    'assertion_title': 'Bản Chất & Cơ Chế Tác Dụng Của Thuốc Tiêm Tránh Thai DMPA 150mg',
    'primary_claim': 'Biện pháp tiêm bắp tác dụng kéo dài 3 tháng một lần, bảo đảm tính kín đáo và hiệu quả trên 99%.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'DMPA 150mg (Depo-Provera)',
                 'text': 'Hỗn dịch tiêm bắp chứa 150mg Medroxyprogesterone Acetate, giải phóng vi hạt nội tiết hấp thu '
                         'chậm vào tuần hoàn máu.',
                 'icon': 'shield'},
               { 'title': 'Cơ Chế Ức Chế Đỉnh LH',
                 'text': 'Ngăn cản tuyến yên tiết LH và FSH làm buồng trứng không thể giải phóng noãn bào; đồng thời '
                         'làm đặc quánh nút nhầy cổ tử cung.',
                 'icon': 'activity'},
               { 'title': 'Hiệu Quả 99.7%',
                 'text': 'Tỷ lệ có thai ngoài ý muốn chỉ 0.3% khi tiêm đúng hẹn; cực kỳ thuận tiện cho phụ nữ vùng '
                         'sâu, vùng xa.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.5 - Thuốc tiêm tránh thai',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_28',
    'role': 'CONTENT',
    'section': '5.5. THUỐC TIÊM TRÁNH THAI',
    'assertion_title': 'Ưu Điểm Vượt Trội Của DMPA: An Toàn Cho Bà Mẹ Nuôi Con Bú',
    'primary_claim': 'Là giải pháp lý tưởng cho thời kỳ hậu sản nhờ hoàn toàn không chứa estrogen gây giảm sữa mẹ.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Không Ảm Ảnh Lượng & Chất Sữa',
                 'text': 'Thuốc tiêm chỉ có progestin không làm suy giảm thể tích sữa, không làm thay đổi hàm lượng '
                         'protein, lipid trong sữa mẹ, em bé tăng cân bình thường.',
                 'icon': 'heart'},
               { 'title': 'Tính Riêng Tư & Kín Đáo Tuyệt Đối',
                 'text': 'Không cần lưu giữ thuốc hay phương tiện tránh thai tại nhà; tránh được sự phản đối hoặc định '
                         'kiến từ gia đình hay bạn đời.',
                 'icon': 'lock'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Lợi thế lâm sàng của DMPA - BÀI 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_29',
    'role': 'CONTENT',
    'section': '5.5. THUỐC TIÊM TRÁNH THAI',
    'assertion_title': 'Lịch Tiêm Định Kỳ Mỗi 3 Tháng & Khoảng Dao Động Cho Phép',
    'primary_claim': 'Khách hàng cần tuân thủ đúng hẹn tiêm nhắc lại để duy trì nồng độ thuốc bảo vệ liên tục.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Khoảng Cách 12 Tuần (3 Tháng)',
                 'text': 'Tiêm mũi tiếp theo sau 12 tuần kể từ mũi tiêm trước; ghi rõ ngày hẹn vào sổ theo dõi sức '
                         'khỏe của khách hàng.',
                 'icon': 'calendar'},
               { 'title': 'Khoảng Dao Động Cho Phép',
                 'text': 'Có thể tiêm sớm hơn 2 tuần hoặc muộn hơn tối đa 4 tuần (trong vòng 16 tuần kể từ mũi trước) '
                         'mà vẫn giữ được hiệu quả.',
                 'icon': 'clock'},
               { 'title': 'Xử Trí Khi Đến Quá Muộn (>16 Tuần)',
                 'text': 'Bắt buộc thử thai loại trừ có thai trước khi tiêm mũi tiếp theo và phải dùng bao cao su hỗ '
                         'trợ trong 7 ngày đầu.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Lịch trình tiêm phòng thai - BÀI 3. Mục 5.5',
    'illustration': 'ai_bai_3_fertility.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_30',
    'role': 'CONTENT',
    'section': '5.5. THUỐC TIÊM TRÁNH THAI',
    'assertion_title': 'Tác Dụng Phụ Vô Kinh, Tăng Cân & Độ Trễ Phục Hồi Thụ Thai Sau Tiêm',
    'primary_claim': 'Cần tư vấn rõ độ trễ sinh sản trung bình 6-9 tháng sau khi ngừng tiêm để khách hàng chủ động kế '
                     'hoạch có con.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Vô Kinh Tỷ Lệ Cao (>50%)',
                 'text': 'Sau 1 năm sử dụng, trên 50% phụ nữ vô kinh hoàn toàn; điều này là bình thường và không gây '
                         'tích tụ máu độc.',
                 'icon': 'activity'},
               { 'title': 'Tăng Cân Nhẹ (1-2 kg/Năm)',
                 'text': 'Do tác dụng giữ nước nhẹ và kích thích cảm giác ngon miệng; tư vấn điều chỉnh chế độ ăn giảm '
                         'tinh bột và tập luyện thể thao.',
                 'icon': 'trending-up'},
               { 'title': 'Độ Trễ Phục Hồi Khả Năng Có Thai',
                 'text': 'Sau khi ngừng tiêm, thuốc tan dần từ mô mỡ; thời gian mang thai trở lại trung bình từ 6 đến '
                         '10 tháng (không gây vô sinh vĩnh viễn).',
                 'icon': 'refresh-cw'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tư vấn tác dụng phụ thuốc tiêm - BÀI 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_31',
    'role': 'CONTENT',
    'section': '5.6. VIÊN THUỐC TRÁNH THAI KẾT HỢP (COC)',
    'assertion_title': 'Thành Phần Estrogen + Progestin & Cơ Chế 3 Tác Động Của Thuốc Viên COC',
    'primary_claim': 'Viên thuốc uống kết hợp là biện pháp phổ biến toàn cầu nhờ độ tin cậy cao và kiểm soát chu kỳ '
                     'kinh hoàn hảo.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Thành Phần Hoạt Chất',
                 'text': 'Phối hợp giữa Ethinyl Estradiol (Estrogen tổng hợp) và một dẫn xuất Progestin '
                         '(Levonorgestrel, Desogestrel, Drospirenone).',
                 'icon': 'shield'},
               { 'title': '3 Tầng Cơ Chế Bảo Vệ',
                 'text': '1. Ức chế đỉnh LH ngăn phóng noãn; 2. Làm đặc nút nhầy cổ tử cung; 3. Làm teo mỏng niêm mạc '
                         'tử cung ngăn trứng làm tổ.',
                 'icon': 'activity'},
               { 'title': 'Lợi Ích Sức Khỏe Bổ Sung',
                 'text': 'Giúp kinh nguyệt đều đặn, giảm đau bụng kinh, giảm lượng máu mất (chống thiếu máu), giảm mụn '
                         'trứng cá và giảm nguy cơ ung thư buồng trứng, nội mạc tử cung.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.6 - Viên thuốc tránh thai kết hợp',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_32',
    'role': 'CONTENT',
    'section': '5.6. VIÊN THUỐC TRÁNH THAI KẾT HỢP (COC)',
    'assertion_title': 'Phân Biệt Quy Cách Vỉ 21 Viên Và Vỉ 28 Viên Tránh Thai Kết Hợp',
    'primary_claim': 'Vỉ 28 viên bổ sung 7 viên giả dược nhằm giúp phụ nữ hình thành phản xạ uống thuốc liên tục mỗi '
                     'ngày.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Quy Cách Vỉ 21 Viên',
                 'text': 'Chứa 21 viên đều có hoạt chất nội tiết; uống mỗi ngày 1 viên theo chiều mũi tên trong 21 '
                         'ngày liên tiếp, sau đó nghỉ 7 ngày không uống thuốc (kinh nguyệt sẽ xuất hiện trong 7 ngày '
                         'này), ngày thứ 8 bắt đầu vỉ mới.',
                 'icon': 'calendar'},
               { 'title': 'Quy Cách Vỉ 28 Viên (21 + 7)',
                 'text': 'Chứa 21 viên hoạt chất (màu trắng) + 7 viên giả dược chứa sắt/đường (màu nâu/khác màu); uống '
                         'liên tục mỗi ngày 1 viên không nghỉ ngày nào, hết vỉ này chuyển sang vỉ kế tiếp ngay lập '
                         'tức.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Hướng dẫn sử dụng vỉ 21 và 28 viên - BÀI 3',
    'illustration': 'cinematic_bai_3_health.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_33',
    'role': 'CONTENT',
    'section': '5.6. VIÊN THUỐC TRÁNH THAI KẾT HỢP (COC)',
    'assertion_title': 'Quy Tắc Uống Thuốc Hàng Ngày & Hướng Dẫn Xử Trí Khi Quên Thuốc',
    'primary_claim': 'Uống thuốc vào một khung giờ cố định là nguyên tắc vàng; xử trí quên thuốc phụ thuộc số viên bị '
                     'quên.',
    'visual_job': 'PROCESS_DEVSECOPS_PIPELINE',
    'visual_anchor': 'PROCESS_CARDS',
    'atoms': [ { 'title': '1. Khung Giờ Cố Định',
                 'text': 'Uống 1 viên mỗi ngày vào một giờ nhất định (ví dụ trước khi đi ngủ hoặc sau bữa tối) để tạo '
                         'thói quen.',
                 'icon': 'clock'},
               { 'title': '2. Quên 1 Viên (<24h)',
                 'text': 'Uống ngay viên quên khi nhớ ra, viên kế tiếp uống vào giờ thường lệ (có thể uống 2 viên '
                         'trong 1 ngày). Không cần biện pháp hỗ trợ.',
                 'icon': 'check-circle'},
               { 'title': '3. Quên 2 Viên Liên Tiếp',
                 'text': 'Uống ngay 2 viên khi nhớ ra, hôm sau uống 2 viên tiếp; BẮT BUỘC dùng bao cao su trong 7 ngày '
                         'tiếp theo.',
                 'icon': 'alert-circle'},
               { 'title': '4. Quên Từ 3 Viên Trở Lên',
                 'text': 'Bỏ vỉ cũ, bắt đầu vỉ mới ngay; dùng bao cao su liên tục 7 ngày và thử thai nếu có giao hợp '
                         'trong những ngày quên.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Xử trí quên thuốc COC - BÀI 3. Mục 5.6',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_34',
    'role': 'CONTENT',
    'section': '5.6. VIÊN THUỐC TRÁNH THAI KẾT HỢP (COC)',
    'assertion_title': 'Chống Chỉ Định Tuyệt Đối & Cảnh Báo Huyết Khối Tĩnh Mạch Của COC',
    'primary_claim': 'Estrogen có nguy cơ tăng đông máu; tuyệt đối cấm dùng cho phụ nữ hút thuốc lá trên 35 tuổi.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Hút Thuốc Lá Trên 35 Tuổi',
                 'text': 'Phụ nữ >=35 tuổi hút thuốc lá >=15 điếu/ngày có nguy cơ đột quỵ và nhồi máu cơ tim tăng gấp '
                         '20 lần khi dùng COC.',
                 'icon': 'alert-circle'},
               { 'title': 'Tiền Sử Huyết Khối Tắc Mạch',
                 'text': 'Đã hoặc đang bị huyết khối tĩnh mạch sâu (DVT), thuyên tắc phổi, tai biến mạch máu não hoặc '
                         'bệnh van tim có biến chứng.',
                 'icon': 'heart'},
               { 'title': 'Tăng Huyết Áp Nặng',
                 'text': 'Huyết áp tâm thu >= 160 mmHg hoặc tâm trương >= 100 mmHg; đái tháo đường có biến chứng mạch '
                         'máu.',
                 'icon': 'activity'},
               { 'title': 'Bệnh Gan Nặng & Ung Thư Vú',
                 'text': 'Viêm gan cấp, xơ gan mất bù, u gan nguyên phát hoặc ung thư vú nhạy cảm với thụ thể nội '
                         'tiết.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tiêu chuẩn lựa chọn y tế WHO - Chống chỉ định COC',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_35',
    'role': 'CONTENT',
    'section': '5.7. VIÊN THUỐC CHỈ CÓ PROGESTIN (POP)',
    'assertion_title': 'Viên Tránh Thai Đơn Thuần (POP): Giải Pháp Cho Bà Mẹ Đang Nuôi Con Bú',
    'primary_claim': 'Viên thuốc Minipill không chứa estrogen nên không ảnh hưởng đến số lượng và chất lượng sữa mẹ.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Chỉ Chứa Progestin Liều Thấp',
                 'text': 'Thường chứa Levonorgestrel 0.03mg hoặc Desogestrel 0.075mg; thích hợp ngay từ tuần thứ 6 sau '
                         'sinh cho phụ nữ cho con bú.',
                 'icon': 'shield'},
               { 'title': 'Cơ Chế Làm Đặc Nút Nhầy',
                 'text': 'Làm đặc nút nhầy cổ tử cung suốt 24 giờ ngăn tinh trùng xâm nhập buồng tử cung và làm mỏng '
                         'niêm mạc tử cung.',
                 'icon': 'activity'},
               { 'title': 'Thay Thế An Toàn Cho COC',
                 'text': 'Dành cho những người có chống chỉ định với estrogen: tăng huyết áp, tiền sử đau nửa đầu '
                         'Migraine, phụ nữ lớn tuổi.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.7 - Viên thuốc chỉ có Progestin',
    'illustration': 'ai_bai_2_golden.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_36',
    'role': 'CONTENT',
    'section': '5.7. VIÊN THUỐC CHỈ CÓ PROGESTIN (POP)',
    'assertion_title': 'Quy Tắc Giờ Uống Cực Kỳ Nghiêm Ngặt Của Viên Tránh Thai POP (+/- 3 Giờ)',
    'primary_claim': 'Thời gian bán thải ngắn đòi hỏi sự chính xác tuyệt đối; trễ quá 3 giờ được coi như quên thuốc.',
    'visual_job': 'CHART_AND_INSIGHTS',
    'visual_anchor': 'CHART_AND_INSIGHTS',
    'atoms': [ { 'title': 'Đặc Tính Dược Động Học Ngắn',
                 'text': 'Nút nhầy cổ tử cung chỉ đặc quánh tối đa trong 22-24 giờ sau uống. Uống trễ hơn 3 giờ (đối '
                         'với Levonorgestrel) sẽ làm nút nhầy loãng ra và tinh trùng có thể vượt qua.',
                 'icon': 'clock'},
               { 'title': 'Xử Trí Khi Uống Trễ Quá 3 Giờ',
                 'text': 'Uống ngay 1 viên khi nhớ ra và tiếp tục uống viên sau theo giờ thường lệ. BẮT BUỘC PHẢI DÙNG '
                         'BAO CAO SU TRONG 48 GIỜ TIẾP THEO nếu có quan hệ tình dục.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Dược lý lâm sàng viên tránh thai POP - BÀI 3',
    'chart_type': 'LINE_MARKERS',
    'chart_file': 'chart_demo_transition_stages_dark.png',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_37',
    'role': 'CONTENT',
    'section': '5.8. VIÊN TRÁNH THAI KHẨN CẤP (ECP)',
    'assertion_title': "Bản Chất & 'Cửa Sổ Vàng' 72-120 Giờ Của Thuốc Tránh Thai Khẩn Cấp",
    'primary_claim': 'ECP là biện pháp cứu cánh sau giao hợp không an toàn; uống càng sớm hiệu quả bảo vệ càng cao.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Cơ Chế Trì Hoãn Phóng Noãn',
                 'text': 'Chứa Levonorgestrel 1.5mg (uống 1 liều duy nhất) hoặc Ulipristal acetate 30mg; ngăn chặn '
                         'đỉnh LH để trì hoãn rụng trứng.',
                 'icon': 'shield'},
               { 'title': 'Hiệu Quả Giảm Dần Theo Giờ',
                 'text': 'Uống trong 24h đầu hiệu quả 95%; từ 25-48h giảm còn 85%; từ 49-72h giảm xuống 58%; sau 72h '
                         'hiệu quả rất thấp.',
                 'icon': 'clock'},
               { 'title': 'Không Phải Thuốc Phá Thai',
                 'text': 'Nếu trứng đã thụ tinh và làm tổ vững chắc trong tử cung, thuốc ECP hoàn toàn không có tác '
                         'dụng làm sảy thai hay dị tật thai.',
                 'icon': 'info'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.8 - Viên thuốc tránh thai khẩn cấp',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_38',
    'role': 'CONTENT',
    'section': '5.8. VIÊN TRÁNH THAI KHẨN CẤP (ECP)',
    'assertion_title': 'Cảnh Báo Lâm Sàng: Tuyệt Đối Không Lạm Dụng Viên Tránh Thai Khẩn Cấp',
    'primary_claim': 'Lạm dụng ECP gây đảo lộn chu kỳ kinh nguyệt, teo niêm mạc tử cung và làm tăng nguy cơ mang thai '
                     'ngoài ý muốn.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Giới Hạn Tối Đa 2 Lần / Tháng',
                 'text': 'Hàm lượng hormone trong 1 liều ECP cao gấp 4-5 lần viên thuốc hàng ngày; không được uống quá '
                         '2 lần trong 1 tháng hoặc quá 3 lần trong 1 năm.',
                 'icon': 'alert-circle'},
               { 'title': 'Tác Dụng Phụ Nghiêm Trọng',
                 'text': 'Gây rong kinh, rong huyết bất thường, buồn nôn, rối loạn nội tiết tố kéo dài và dễ dẫn đến '
                         'tâm lý chủ quan không dùng biện pháp bảo vệ thường xuyên.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Khuyến cáo an toàn sử dụng ECP - BÀI 3',
    'illustration': 'illustration_bai_3.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_39',
    'role': 'CONTENT',
    'section': '5.9. BAO CAO SU NAM & NỮ',
    'assertion_title': 'Bao Cao Su: Biện Pháp Kép Duy Nhất Vừa Tránh Thai Vừa Ngăn STIs/HIV',
    'primary_claim': 'Không có biện pháp tránh thai nào khác có khả năng bảo vệ người dùng trước các bệnh lây truyền '
                     'qua đường tình dục.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Bảo Vệ Kép (Dual Protection)',
                 'text': 'Vừa đạt hiệu quả tránh thai 98% khi dùng đúng cách, vừa tạo màng chắn cơ học ngăn 100% '
                         'vi-rút HIV, lậu, giang mai, Chlamydia.',
                 'icon': 'shield-check'},
               { 'title': 'Sẵn Có & Tiện Dụng',
                 'text': 'Không cần kê đơn bác sĩ, không cần can thiệp y tế, dễ dàng mua tại hiệu thuốc, cửa hàng tiện '
                         'lợi hoặc nhận miễn phí.',
                 'icon': 'check-circle'},
               { 'title': 'Bao Cao Su Nữ (Chủ Động Nữ Giới)',
                 'text': 'Túi màng mỏng đặt trong âm đạo trước khi giao hợp, giúp phụ nữ chủ động bảo vệ bản thân khi '
                         'bạn tình không chịu dùng bao.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.9 - Bao cao su',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_40',
    'role': 'CONTENT',
    'section': '5.9. BAO CAO SU',
    'assertion_title': 'Kỹ Thuật Sử Dụng Bao Cao Su Chuẩn 7 Bước & Nguyên Tắc Bảo Quản',
    'primary_claim': 'Phần lớn các ca rách bao hoặc mang thai là do kỹ thuật xé bao sai và không bóp đuổi bọt khí.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Kiểm Tra Hạn & Túi Khí',
                 'text': 'Kiểm tra hạn sử dụng trên vỏ bao; bóp nhẹ thấy túi bao còn phồng êm, vỏ không bị rách hay '
                         'giòn vỡ.',
                 'icon': 'check-circle'},
               { 'title': '2. Xé Dọc Rãnh Viền Cẩn Thận',
                 'text': 'Đẩy bao về một góc, xé bằng tay theo rãnh khía; tuyệt đối không dùng kéo, dao hoặc răng cắn '
                         'rách bao.',
                 'icon': 'alert-circle'},
               { 'title': '3. Bóp Xẹp Đuôi Bao Đuổi Khí',
                 'text': 'Bóp xẹp núm nhỏ ở đầu bao để đuổi hết không khí ra ngoài, tránh áp lực gây nổ rách bao khi '
                         'phóng tinh.',
                 'icon': 'shield'},
               { 'title': '4. Tháo Bao Đúng Lúc Rút Dương Vật',
                 'text': 'Rút dương vật ra khi còn cương, giữ chặt vành bao ở gốc để tinh dịch không tràn ra ngoài âm '
                         'đạo.',
                 'icon': 'user-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Hướng dẫn kỹ thuật sử dụng bao cao su - BÀI 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_41',
    'role': 'CONTENT',
    'section': '5.10. TÍNH NGÀY RỤNG TRỨNG',
    'assertion_title': 'Phương Pháp Tính Ngày Rụng Trứng: Cơ Sở Sinh Học & Giới Hạn Áp Dụng',
    'primary_claim': 'Chỉ áp dụng cho phụ nữ có chu kỳ kinh nguyệt đều đặn; tỷ lệ thất bại thực tế lên tới 15-24%.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Tuổi Thọ Noãn & Tinh Trùng',
                 'text': 'Noãn sau khi rụng chỉ sống được 12-24 giờ; tinh trùng có thể sống sót và thụ tinh trong '
                         'đường sinh dục nữ từ 3 đến 5 ngày.',
                 'icon': 'clock'},
               { 'title': 'Công Thức Ogino-Knaus',
                 'text': 'Theo dõi kinh nguyệt 6-8 tháng: Ngày bắt đầu kiêng = Chu kỳ ngắn nhất - 18 ngày; Ngày kết '
                         'thúc kiêng = Chu kỳ dài nhất - 11 ngày.',
                 'icon': 'calendar'},
               { 'title': 'Phương Pháp Billings (Chất Nhầy)',
                 'text': 'Quan sát chất nhầy cổ tử cung: giai đoạn rụng trứng chất nhầy trong suốt, dai quánh, kéo sợi '
                         'như lòng trắng trứng gà.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.10 - Tính ngày rụng trứng',
    'illustration': 'ai_bai_3_fertility.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_42',
    'role': 'CONTENT',
    'section': '5.11. XUẤT TINH NGOÀI ÂM ĐẠO',
    'assertion_title': 'Xuất Tinh Ra Ngoài Âm Đạo: Biện Pháp Truyền Thống Đầy Rủi Ro',
    'primary_claim': 'Phụ thuộc hoàn toàn vào sự tự chủ của nam giới và có tỷ lệ thất bại thực tế lên tới 22%.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Cơ Chế Rủi Ro Sinh Học',
                 'text': 'Trong quá trình hưng phấn trước khi xuất tinh, tuyến hành niệu đạo tiết ra dịch nhờn bôi '
                         'trơn; dịch này đã có thể chứa hàng triệu tinh trùng khỏe mạnh gây thụ thai ngoài ý muốn.',
                 'icon': 'alert-circle'},
               { 'title': 'Hệ Lụy Tâm Lý & Căng Thẳng',
                 'text': 'Đòi hỏi người đàn ông phải tập trung cao độ để rút dương vật đúng thời điểm, gây ức chế tâm '
                         'lý, giảm sút khoái cảm tình dục và tiềm ẩn nguy cơ rối loạn cương dương.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.11 - Xuất tinh ngoài âm đạo',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_43',
    'role': 'CONTENT',
    'section': '5.12. CHO CON BÚ VÔ KINH (LAM)',
    'assertion_title': 'Cho Con Bú Vô Kinh (LAM): 3 Điều Kiện Vàng Tiên Quyết Đạt Hiệu Quả 98%',
    'primary_claim': 'Là biện pháp tránh thai tự nhiên tuyệt vời nhưng BẮT BUỘC phải thỏa mãn đồng thời cả 3 điều '
                     'kiện.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Điều Kiện 1: Trẻ Dưới 6 Tháng Tuổi',
                 'text': 'Chỉ có tác dụng trong 6 tháng đầu đời sau khi sinh; khi trẻ bắt đầu ăn dặm hiệu quả tránh '
                         'thai suy giảm nghiêm trọng.',
                 'icon': 'clock'},
               { 'title': 'Điều Kiện 2: Bú Mẹ Hoàn Toàn',
                 'text': 'Cho trẻ bú trực tiếp cả ngày lẫn đêm, ít nhất 8-10 lần/ngày, không cách quá 4h ban ngày và '
                         'không quá 6h ban đêm; không ăn dặm hay uống nước.',
                 'icon': 'award'},
               { 'title': 'Điều Kiện 3: Chưa Có Kinh Trở Lại',
                 'text': 'Người mẹ hoàn toàn chưa xuất hiện bất kỳ dấu hiệu hành kinh nào kể từ tuần thứ 8 sau khi '
                         'sinh con.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 5.12 - Cho con bú vô kinh',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_44',
    'role': 'CONTENT',
    'section': 'TỔNG HỢP HIỆU QUẢ',
    'assertion_title': 'Ma Trận So Sánh Hiệu Quả, Thời Hạn & Đối Tượng 12 Biện Pháp Tránh Thai',
    'primary_claim': 'Bảng tổng hợp đối sánh khoa học giúp cán bộ y tế dân số tư vấn chính xác cho từng trường hợp.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Nhóm 1: Hiệu Quả Rất Cao (>99%)',
                 'text': 'Que cấy Implanon (3 năm), Triệt sản nam (vĩnh viễn), Triệt sản nữ (vĩnh viễn), Dụng cụ tử '
                         'cung TCu 380A (10 năm).',
                 'icon': 'award'},
               { 'title': 'Nhóm 2: Hiệu Quả Cao (92 - 97%)',
                 'text': 'Thuốc tiêm DMPA (3 tháng), Viên tránh thai kết hợp COC (uống hàng ngày), Viên tránh thai POP '
                         '(bú mẹ), Bao cao su nam/nữ.',
                 'icon': 'check-circle'},
               { 'title': 'Nhóm 3: Hiệu Quả Trung Bình / Thấp (<85%)',
                 'text': 'Tính ngày rụng trứng (thất bại 15-24%), Xuất tinh ngoài âm đạo (thất bại 22%), Viên khẩn cấp '
                         'ECP (chỉ dùng cứu cánh).',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tổng hợp chỉ số Pearl Index - WHO & Bộ Y tế',
    'illustration': 'cinematic_bai_3_health.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_45',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Quản Lý Nhà Nước Về KHHGĐ Tại Tuyến Trung Ương & Tuyến Tỉnh',
    'primary_claim': 'Cục Dân số giữ vai trò kiến tạo chính sách và điều phối cân đối cung ứng phương tiện tránh thai '
                     'quốc gia.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tuyến Trung Ương: Bộ Y Tế (Cục Dân Số)',
                 'text': 'Xây dựng chiến lược, tiêu chuẩn chất lượng phương tiện tránh thai; dự toán ngân sách Nhà '
                         'nước mua sắm PTTT cấp miễn phí; điều phối các chương trình tiếp thị xã hội và kiểm tra giám '
                         'sát toàn quốc.',
                 'icon': 'shield-check'},
               { 'title': 'Tuyến Tỉnh: Sở Y Tế (Chi Cục Dân Số)',
                 'text': 'Xây dựng chỉ tiêu kế hoạch năm của tỉnh; quản lý kho bãi bảo quản PTTT; phân bổ hàng hóa cho '
                         'các huyện; tổ chức đào tạo chuyển giao kỹ thuật đặt vòng, cấy que cho cán bộ y tế tuyến '
                         'dưới.',
                 'icon': 'layers'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 6.1 & 6.2 - Quản lý Trung ương và Tỉnh',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_46',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Tổ Chức Dịch Vụ Thực Địa Tại Tuyến Huyện, Tuyến Xã & Thôn Bản',
    'primary_claim': 'Trạm y tế và mạng lưới cộng tác viên dân số là mũi nhọn trực tiếp cung ứng dịch vụ đến từng hộ '
                     'dân.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tuyến Huyện: TTYT / Đội Lưu Động',
                 'text': 'Thực hiện thủ thuật KHHGĐ chuyên sâu (đặt DCTC, cấy que, triệt sản); tổ chức các chiến dịch '
                         'truyền thông lồng ghép cung ứng dịch vụ chăm sóc SKSS/KHHGĐ lưu động đến các xã khó khăn.',
                 'icon': 'activity'},
               { 'title': 'Tuyến Xã & CTV Thôn Bản',
                 'text': 'Trạm y tế trực tiếp đặt DCTC, cấp phát thuốc viên, thuốc tiêm, bao cao su; CTV dân số đi '
                         'từng ngõ, gõ từng nhà quản lý phiếu hộ gia đình, tư vấn trực tiếp và phân phối PTTT tiếp thị '
                         'xã hội.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 6.3 & 6.4 - Tuyến Huyện, Xã và Cộng tác viên',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_47',
    'role': 'CONTENT',
    'section': '6.5. LẬP KẾ HOẠCH DỊCH VỤ',
    'assertion_title': 'Dự Báo Nhu Cầu & Quản Trị Chuỗi Cung Ứng Phương Tiện Tránh Thai',
    'primary_claim': 'Sử dụng chỉ số CYP (Couple Years of Protection) để tính toán chính xác số lượng phương tiện cần '
                     'mua sắm.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Chỉ Số Cặp Vợ Chồng Sinh Đẻ (CPR)',
                 'text': 'Tỷ lệ sử dụng biện pháp tránh thai chung và tỷ lệ sử dụng biện pháp hiện đại (mục tiêu quốc '
                         'gia duy trì trên 70%).',
                 'icon': 'trending-up'},
               { 'title': 'Hệ Số Quy Đổi CYP',
                 'text': '1 DCTC TCu 380A = 4.6 CYP; 1 Que cấy = 3.2 CYP; 1 Lọ tiêm DMPA = 0.25 CYP (4 lọ/năm); 1 Vỉ '
                         'viên uống = 0.077 CYP (15 vỉ/năm); 120 BCS = 1 CYP.',
                 'icon': 'activity'},
               { 'title': 'Dự Báo Logistics Chống Hết Hàng',
                 'text': 'Thiết lập mức tồn kho an toàn tối thiểu 3 tháng tại trạm y tế và 6 tháng tại kho huyện; '
                         'chống đứt gãy nguồn cung cấp.',
                 'icon': 'shield'},
               { 'title': 'Xã Hội Hóa & Tiếp Thị Xã Hội',
                 'text': 'Chuyển dần từ cấp phát miễn phí bao cấp sang tiếp thị xã hội đa dạng mẫu mã, chia sẻ gánh '
                         'nặng với ngân sách.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 3. Mục 6.5 - Lập kế hoạch cung cấp dịch vụ KHHGĐ',
    'illustration': 'ai_bai_2_golden.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_48',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 1: Phác Đồ Lựa Chọn Biện Pháp Tránh Thai Cho Mẹ Nuôi Con Bú',
    'primary_claim': 'Phân tích thứ tự ưu tiên các biện pháp nhằm bảo vệ nguồn sữa mẹ quý giá và bảo đảm an toàn thai '
                     'nghén.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Các Biện Pháp Được Ưu Tiên Hàng Đầu',
                 'text': '1. Cho con bú vô kinh (LAM) trong 6 tháng đầu nếu đủ điều kiện; 2. Dụng cụ tử cung (đặt từ '
                         'tuần thứ 6 sau sinh); 3. Bao cao su; 4. Thuốc cấy Implanon hoặc thuốc tiêm DMPA hoặc thuốc '
                         'uống chỉ có progestin (POP).',
                 'icon': 'check-circle'},
               { 'title': 'Biện Pháp Tuyệt Đối Tránh',
                 'text': 'Không được dùng thuốc viên tránh thai kết hợp (COC) trong 6 tháng đầu sau sinh vì hormone '
                         'Estrogen gây teo tuyến sữa, làm giảm lượng sữa mẹ nghiêm trọng.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Câu hỏi lượng giá số 1 - BÀI 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_49',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 2: Kỹ Năng Tư Vấn Tình Huống Khách Hàng Quên Uống Thuốc Viên',
    'primary_claim': 'Tình huống giao tiếp thực địa rèn luyện khả năng giải thích bình tĩnh, chính xác và giảm âu lo '
                     'cho người dân.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Quên 1 Viên (<24 Giờ)',
                 'text': 'Uống ngay viên quên, uống viên ngày đó đúng giờ. Giải thích không cần hoảng hốt, hiệu quả '
                         'bảo vệ chưa suy giảm.',
                 'icon': 'check-circle'},
               { 'title': 'Quên 2 Viên Liên Tiếp',
                 'text': 'Uống 2 viên ngày hôm nay, 2 viên ngày mai. Nhấn mạnh bắt buộc phải sử dụng bao cao su trong '
                         '7 ngày tới.',
                 'icon': 'alert-circle'},
               { 'title': 'Khai Thác Quan Hệ Gần Đây',
                 'text': 'Hỏi xem trong 5 ngày qua có quan hệ không bảo vệ không; nếu có và quên ở tuần 1 của vỉ thuốc '
                         'thì cân nhắc uống thuốc tránh thai khẩn cấp.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tình huống thực hành lâm sàng - BÀI 3 Câu 2',
    'illustration': 'illustration_bai_3.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_50',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 3: Đề Án Phát Triển Tiếp Thị Xã Hội PTTT Tại Tuyến Cơ Sở',
    'primary_claim': 'Chiến lược chuyển đổi tư duy từ bao cấp sang tự nguyện chi trả, bảo đảm tính bền vững của công '
                     'tác dân số.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Phân Loại Đối Tượng Đích Thực',
                 'text': 'Nhà nước bảo đảm cấp miễn phí 100% cho hộ nghèo, cận nghèo, gia đình chính sách; các đối '
                         'tượng còn lại tham gia mua tiếp thị xã hội.',
                 'icon': 'users'},
               { 'title': 'Mở Rộng Kênh Phân Phối',
                 'text': 'Đưa bao cao su, thuốc viên tránh thai vào hệ thống nhà thuốc tư nhân, trạm y tế, siêu thị '
                         'mini và cửa hàng tiện lợi tại xã.',
                 'icon': 'home'},
               { 'title': 'Chính Sách Khuyến Khích CTV',
                 'text': 'Trích hoa hồng phần trăm hợp lý từ doanh thu tiếp thị xã hội cho cộng tác viên dân số để tạo '
                         'động lực duy trì mạng lưới.',
                 'icon': 'award'},
               { 'title': 'Nâng Cao Định Vị Thương Hiệu',
                 'text': 'Truyền thông nhấn mạnh chất lượng cao, bao bì đẹp, nâng niu sức khỏe để người dân tự hào khi '
                         'chủ động mua phương tiện tránh thai.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Kế hoạch hành động KHHGĐ bền vững - BÀI 3 Câu 3',
    'v91_compliant': True}]
