# -*- coding: utf-8 -*-
"""
scripts/course2_data_bai5.py
Exhaustive Deep-Curriculum Slide Blueprints for BÀI 5 (Make Slide Pro V9.1).
30%-50% High-Resolution Visual Illustrations, Native Charts, Zero AI Slop, Zero Watermarks.
"""

from typing import Any, Dict, List


def get_slides_bai_5() -> List[Dict[str, Any]]:
    return [ { 'slide_id': 'SLIDE_01',
    'role': 'COVER',
    'section': 'TỔNG QUAN CHUYÊN ĐỀ',
    'assertion_title': 'BÀI 5: DỊCH VỤ TƯ VẤN, TẦM SOÁT, CHẨN ĐOÁN BỆNH TẬT TRƯỚC SINH & SƠ SINH',
    'primary_claim': 'Khung nghiệp vụ y tế dân số toàn diện về sàng lọc trước sinh và sơ sinh theo Quyết định số '
                     '1807/QĐ-BYT, can thiệp sớm bệnh di truyền và nâng cao chất lượng dân số.',
    'visual_job': 'HERO_TITLE',
    'visual_anchor': 'BRAND_COVER',
    'transition': 'fade',
    'transition_duration': 0.65,
    'illustration': 'illustration_bai_5.jpg',
    'speaker_notes': 'Kính chào quý học viên, hôm nay chúng ta nghiên cứu chuyên đề Bài 5: Dịch vụ tư vấn, tầm soát, '
                     'chẩn đoán bệnh, tật trước sinh và sơ sinh.',
    'source_footer': 'Tài liệu đào tạo chuẩn hóa: BÀI 5. Dịch vụ tư vấn-tầm soát-chẩn đoán trước sinh và sơ sinh.docx',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_02',
    'role': 'CONTENT',
    'section': 'MỤC TIÊU BÀI HỌC',
    'assertion_title': 'Chuẩn Đầu Ra 4 Khối Năng Lực Cốt Lõi Về Sàng Lọc Trước Sinh Và Sơ Sinh',
    'primary_claim': 'Trang bị phương pháp luận y học di truyền, quy trình sàng lọc 3 giai đoạn thai kỳ và kỹ thuật '
                     'lấy mẫu máu sơ sinh.',
    'visual_job': 'CONTAINER_BENTO_COMPLEX',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Khái Niệm & Khung Pháp Lý',
                 'text': 'Trình bày chuẩn xác khái niệm tầm soát, chẩn đoán trước sinh và sơ sinh theo Quyết định số '
                         '1807/QĐ-BYT ngày 21/04/2020.',
                 'icon': 'book-open'},
               { 'title': '2. Khách Hàng & Phân Tuyến Cơ Sở',
                 'text': 'Làm chủ 7 nhóm đối tượng thai phụ ưu tiên cao, tiêu chuẩn trẻ 24-72 giờ tuổi và mạng lưới 8 '
                         'trung tâm sàng lọc khu vực.',
                 'icon': 'users'},
               { 'title': '3. Kỹ Thuật Sàng Lọc Trước - Sau Sinh',
                 'text': 'Nắm vững kỹ thuật đo NT, Combined test, Triple test, NIPT, chọc ối và kỹ thuật lấy máu gót '
                         'chân sàng lọc 5 bệnh bẩm sinh.',
                 'icon': 'activity'},
               { 'title': '4. Quản Lý & Chỉ Tiêu Chiến Lược 2030',
                 'text': 'Vận hành hệ thống quản lý 4 tuyến, bảo đảm chỉ tiêu Nghị quyết 21: 70% trước sinh (4 bệnh) '
                         'và 90% sơ sinh (5 bệnh).',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Khung chuẩn đầu ra đào tạo sàng lọc trước sinh và sơ sinh',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_03',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Khung Pháp Lý Quyết Định 1807/QĐ-BYT: Định Nghĩa Tầm Soát & Chẩn Đoán Trước Sinh',
    'primary_claim': 'Phân định rõ ràng giữa việc phát hiện yếu tố nguy cơ (tầm soát) và xác định bản chất dị tật thai '
                     'nhi (chẩn đoán).',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tầm Soát Trước Sinh (Sàng Lọc)',
                 'text': 'Việc sử dụng các kỹ thuật không xâm lấn hoặc ít xâm lấn (siêu âm, xét nghiệm sinh hóa máu '
                         'mẹ, ADN tự do cfDNA) trong thời gian mang thai để phát hiện nhóm thai phụ có nguy cơ cao '
                         'mang thai dị tật.',
                 'icon': 'search'},
               { 'title': 'Chẩn Đoán Trước Sinh (Xác Định)',
                 'text': 'Việc sử dụng các kỹ thuật xâm lấn chuyên sâu (chọc ối, sinh thiết gai nhau, lấy máu cuống '
                         'rốn) kết hợp xét nghiệm di truyền tế bào/phân tử để chẩn đoán xác định dị tật ở các ca nghi '
                         'ngờ.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quyết định số 1807/QĐ-BYT ngày 21/04/2020 của Bộ Y tế',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_04',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Dị Tật Bào Thai: Bản Chất Bất Thường Cấu Trúc, Chức Năng & Chuyển Hóa',
    'primary_claim': 'Dị tật bẩm sinh hình thành từ giai đoạn phôi thai và có thể biểu hiện ngay sau sinh hoặc tiềm ẩn '
                     'nhiều năm.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Bất Thường Về Cấu Trúc Hình Thái',
                 'text': 'Khiếm khuyết giải phẫu nhìn thấy được: thai vô sọ, thoát vị rốn, sứt môi hở hàm ếch, tim bẩm '
                         'sinh, ngắn chi, dính ngón.',
                 'icon': 'alert-circle'},
               { 'title': 'Bất Thường Về Chức Năng Cơ Quan',
                 'text': 'Khiếm khuyết hoạt động sinh lý: điếc bẩm sinh, mù bẩm sinh, chậm phát triển tâm thần vận '
                         'động, suy tim bẩm sinh.',
                 'icon': 'activity'},
               { 'title': 'Rối Loạn Chuyển Hóa Tiềm Ẩn',
                 'text': 'Thiếu hụt enzyme chuyển hóa bẩm sinh: tích tụ axit amin độc hại (PKU), suy tuyến thượng thận '
                         'mất muối hoặc ứ đọng lipid thể tiêu bào.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 1 - Khái niệm dị tật bào thai',
    'illustration': 'illustration_bai_5.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_05',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Sàng Lọc Sơ Sinh: Phát Hiện Bệnh Lý Khi Chưa Có Dấu Hiệu Lâm Sàng',
    'primary_claim': 'Thời điểm trẻ sơ sinh vừa chào đời có vẻ hoàn toàn bình thường nhưng bệnh lý âm thầm tàn phá tế '
                     'bào não.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Giai Đoạn Tiền Triệu Chứng',
                 'text': 'Trẻ mới sinh bú tốt, hồng hào; các rối loạn chuyển hóa chưa bộc lộ triệu chứng ra ngoài nhờ '
                         'nồng độ hormone người mẹ còn lưu lại.',
                 'icon': 'clock'},
               { 'title': 'Kỹ Thuật Sàng Lọc Nhanh',
                 'text': 'Lấy vài giọt máu gót chân thấm lên giấy thấm chuyên dụng (Guthrie card) để định lượng enzyme '
                         'và hormone nội tiết.',
                 'icon': 'search'},
               { 'title': 'Ngăn Ngừa Tổn Thương Não Vĩnh Viễn',
                 'text': 'Phát hiện ngay trong tuần đầu đời giúp bổ sung thuốc hoặc điều chỉnh chế độ ăn trước khi tế '
                         'bào não bị hủy hoại không hồi phục.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 1 - Khái niệm sàng lọc sơ sinh',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_06',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Chẩn Đoán Sơ Sinh: Xác Lập Phác Đồ Can Thiệp Trị Liệu Sớm',
    'primary_claim': 'Sau khi có kết quả sàng lọc nguy cơ cao, trẻ được chuyển ngay đến tuyến chuyên khoa để chẩn đoán '
                     'xác định.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Quy Trình Xét Nghiệm Xác Định',
                 'text': 'Lấy mẫu máu tĩnh mạch định lượng chính xác hormone TSH, Free T4 (suy giáp), 17-OHP (tăng sản '
                         'thượng thận) hoặc đo hoạt độ enzyme G6PD bằng phương pháp quang phổ huỳnh quang.',
                 'icon': 'activity'},
               { 'title': 'Can Thiệp Điều Trị Kịp Thời',
                 'text': 'Bổ sung hormone tuyến giáp Levothyroxine, bù muối khoáng Corticoid hoặc thiết lập danh mục '
                         'thực phẩm kiêng khem nghiêm ngặt giúp trẻ lớn lên khỏe mạnh hoàn toàn như người bình thường.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 1 - Chẩn đoán sơ sinh',
    'illustration': 'ai_bai_5_sustainability.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_07',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Ý Nghĩa Toàn Diện: Giảm Thiểu Tàn Tật & Nâng Cao Tầm Vóc Giống Nòi',
    'primary_claim': 'Chương trình sàng lọc là mắt xích cốt lõi thực hiện mục tiêu nâng cao chất lượng dân số của Đảng '
                     'và Nhà nước.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Giảm Thiểu Tỷ Lệ Dị Tật Cộng Đồng',
                 'text': 'Chủ động phát hiện và đình chỉ thai nghén các thai nhi mắc dị tật bất thường nặng nề không '
                         'thể cứu chữa (vô sọ, Trisomy 18, 13).',
                 'icon': 'shield-check'},
               { 'title': 'Cứu Sống Cuộc Đời Trẻ Thơ',
                 'text': 'Biến một đứa trẻ có nguy cơ bị thiểu năng trí tuệ (suy giáp) hay tử vong do mất muối (CAH) '
                         'thành một công dân phát triển hoàn toàn bình thường.',
                 'icon': 'heart'},
               { 'title': 'Tiết Kiệm Hàng Ngàn Tỷ Đồng',
                 'text': 'Giảm chi phí nằm viện, điều trị y tế dài hạn và trợ cấp xã hội nuôi dưỡng người khuyết tật '
                         'cho ngân sách quốc gia.',
                 'icon': 'trending-up'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Ý nghĩa nhân văn và kinh tế y tế - BÀI 5',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_08',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Hai Phân Hệ Dịch Vụ Theo Trục Thời Gian: Trước Sinh Và Sơ Sinh',
    'primary_claim': 'Trục thời gian xuyên suốt từ khi thụ thai đến 72 giờ đầu đời bảo đảm sự che chắn liên tục cho '
                     'trẻ.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Phân Hệ Dịch Vụ Trước Sinh (Prenatal)',
                 'text': 'Thực hiện trong 9 tháng mang thai; bao gồm tư vấn thai kỳ, siêu âm đo độ mờ da gáy, siêu âm '
                         '4D, Double test, Triple test, NIPT, sàng lọc Thalassemia và thủ thuật chọc ối chẩn đoán.',
                 'icon': 'heart'},
               { 'title': 'Phân Hệ Dịch Vụ Sơ Sinh (Neonatal)',
                 'text': 'Thực hiện ngay sau khi trẻ chào đời (24-72 giờ); bao gồm lấy máu gót chân sàng lọc bệnh nội '
                         'tiết - chuyển hóa, đo thính lực và đo độ bão hòa oxy phát hiện tim bẩm sinh.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 2 - Phân loại theo thời gian',
    'illustration': 'cinematic_bai_5_forecast.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_09',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Phân Định Bản Chất: Kỹ Thuật Tầm Soát (Screening) Vs Kỹ Thuật Chẩn Đoán (Diagnostic)',
    'primary_claim': 'Hiểu rõ giá trị dự báo để không đưa ra quyết định đình chỉ thai nghén chỉ dựa trên xét nghiệm '
                     'sàng lọc.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Kỹ Thuật Tầm Soát (Sàng Lọc)',
                 'text': 'Độ nhạy cao, an toàn tuyệt đối cho mẹ và con nhưng chỉ mang tính chất ước tính XÁC SUẤT NGUY '
                         "CƠ (ví dụ nguy cơ 1/50). Kết quả 'Dương tính' không đồng nghĩa với thai chắc chắn bị bệnh.",
                 'icon': 'search'},
               { 'title': 'Kỹ Thuật Chẩn Đoán (Xác Định)',
                 'text': 'Xét nghiệm trực tiếp tế bào thai nhi qua chọc ối hoặc sinh thiết gai nhau; cho kết quả CHẮC '
                         'CHẮN 100% (bộ nhiễm sắc thể, đột biến gen). Đây là cơ sở pháp lý duy nhất để hội đồng y khoa '
                         'can thiệp.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Nguyên lý sàng lọc y học - BÀI 5',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_10',
    'role': 'CONTENT',
    'section': '3. KHÁCH HÀNG MỤC TIÊU',
    'assertion_title': 'Đối Tượng Khách Hàng Trước Sinh: Mọi Thai Phụ & 7 Nhóm Ưu Tiên Cao',
    'primary_claim': 'Khuyến khích 100% phụ nữ mang thai đi sàng lọc, trong đó bắt buộc chỉ định chặt chẽ cho 7 nhóm '
                     'nguy cơ cao.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tiếp Cận Phổ Cập Toàn Dân',
                 'text': 'Tất cả các phụ nữ mang thai khi đến khám tại các cơ sở sản khoa công lập hoặc tư nhân đều có '
                         'quyền được tư vấn sàng lọc trước sinh.',
                 'icon': 'users'},
               { 'title': '7 Nhóm Nguy Cơ Cao Trọng Điểm',
                 'text': 'Bao gồm tuổi mẹ cao, tiền sử sản khoa bất thường, gia đình mang gen bệnh, cận huyết, nhiễm '
                         'trùng thai kỳ, phơi nhiễm độc chất, siêu âm bất thường.',
                 'icon': 'alert-circle'},
               { 'title': 'Chiến Lược Phân Luồng Y Tế',
                 'text': 'Phân loại nguy cơ ngay từ lần khám đầu tiên tại trạm y tế xã để kịp thời chuyển tuyến trên '
                         'thực hiện các xét nghiệm chuyên sâu.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 3.1 - Khách hàng trước sinh',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_11',
    'role': 'CONTENT',
    'section': '3. KHÁCH HÀNG MỤC TIÊU',
    'assertion_title': 'Nhóm 1: Thai Phụ Từ 35 Tuổi Trở Lên & Nguy Cơ Lão Hóa Noãn Bào',
    'primary_claim': 'Tuổi mẹ tỷ lệ thuận với tần suất đột biến không phân ly nhiễm sắc thể trong quá trình giảm phân '
                     'tạo trứng.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Cơ Chế Lão Hóa Noãn Bào',
                 'text': 'Noãn bào của người phụ nữ tồn tại từ khi còn trong bụng mẹ; đến năm 35 tuổi, các thoi phân '
                         'bào thoái hóa dễ gây lỗi phân chia NST.',
                 'icon': 'clock'},
               { 'title': 'Nguy Cơ Hội Chứng Down Tăng Vọt',
                 'text': 'Mẹ 25 tuổi nguy cơ chỉ 1/1.300; mẹ 35 tuổi tăng lên 1/350; mẹ 40 tuổi tăng vọt lên 1/100 và '
                         'mẹ 45 tuổi nguy cơ lên tới 1/30.',
                 'icon': 'trending-up'},
               { 'title': 'Chỉ Định Tầm Soát Bắt Buộc',
                 'text': 'Bắt buộc làm xét nghiệm NIPT hoặc Combined test kết hợp siêu âm đo độ mờ da gáy để không bỏ '
                         'sót dị tật.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tương quan tuổi mẹ và dị tật NST - BÀI 5',
    'illustration': 'ai_bai_2_quality.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_12',
    'role': 'CONTENT',
    'section': '3. KHÁCH HÀNG MỤC TIÊU',
    'assertion_title': 'Nhóm 2: Tiền Sử Thai Sản Bất Thường (Sảy Thai, Lưu Thai, Con Chết Sớm)',
    'primary_claim': 'Sảy thai liên tiếp từ 2 lần trở lên là dấu hiệu cảnh báo mạnh mẽ về bất thường di truyền ở bố '
                     'hoặc mẹ.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Căn Nguyên Bất Thường Di Truyền',
                 'text': 'Khoảng 50-60% các ca sảy thai tự nhiên trong 3 tháng đầu là do phôi thai bị bất thường số '
                         'lượng hoặc cấu trúc nhiễm sắc thể (đột biến chuyển đoạn cân bằng từ cha mẹ).',
                 'icon': 'alert-circle'},
               { 'title': 'Quy Trình Sàng Lọc Toàn Diện',
                 'text': 'Cặp vợ chồng cần được lập karyotype di truyền tế bào trước khi mang thai; trong thai kỳ bắt '
                         'buộc phải theo dõi sát hình thái học thai nhi và làm chẩn đoán trước sinh sớm.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 3.1 - Nhóm tiền sử sản khoa nặng nề',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_13',
    'role': 'CONTENT',
    'section': '3. KHÁCH HÀNG MỤC TIÊU',
    'assertion_title': 'Nhóm 3: Tiền Sử Gia Đình Bất Thường Nhiễm Sắc Thể Hoặc Bệnh Di Truyền',
    'primary_claim': 'Gia đình có người mắc bệnh di truyền đòi hỏi phải truy nguyên cây phả hệ và xét nghiệm đột biến '
                     'gen đặc hiệu.',
    'visual_job': 'CHART_AND_INSIGHTS',
    'visual_anchor': 'CHART_AND_INSIGHTS',
    'atoms': [ { 'title': 'Bất Thường Nhiễm Sắc Thể',
                 'text': 'Tiền sử sinh con hoặc dòng họ có người mắc hội chứng Down (Trisomy 21), Edwards (Trisomy '
                         '18), Patau (Trisomy 13), Turner (45,X).',
                 'icon': 'activity'},
               { 'title': 'Bệnh Đột Biến Gen Thường Gặp',
                 'text': 'Tan máu bẩm sinh (Thalassemia), Tăng sản thượng thận bẩm sinh (CAH), Loạn dưỡng cơ Duchenne '
                         '(DMD), Teo cơ tủy (SMA).',
                 'icon': 'alert-circle'},
               { 'title': 'Chẩn Đoán Gen Trước Sinh',
                 'text': 'Tiến hành sinh thiết gai nhau lấy mẫu ADN thai nhi giải trình tự gen tìm đúng vị trí đột '
                         'biến điểm đã phát hiện ở người thân.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 3.1 - Nhóm tiền sử gia đình',
    'chart_type': 'LINE_MARKERS',
    'chart_file': 'chart_mortality_curve_gompertz_dark.png',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_14',
    'role': 'CONTENT',
    'section': '3. KHÁCH HÀNG MỤC TIÊU',
    'assertion_title': 'Nhóm 4 & 5: Hôn Nhân Cận Huyết Thống & Nhiễm Vi-rút Thai Kỳ',
    'primary_claim': 'Hai nhóm nguy cơ cao điển hình gây ra các dị tật đa cơ quan và hội chứng nhiễm trùng bẩm sinh.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Nhóm 4: Kết Hôn Cận Huyết Thống',
                 'text': 'Làm tăng nguy cơ con đồng hợp tử về các gen lặn đột biến gây Thalassemia thể nặng, câm điếc '
                         'bẩm sinh, mù bẩm sinh và các hội chứng rối loạn chuyển hóa hiếm gặp.',
                 'icon': 'users'},
               { 'title': 'Nhóm 5: Nhiễm Vi-rút (TORCH)',
                 'text': 'Mẹ nhiễm Rubella, CMV, Herpes, Toxoplasma trong 3 tháng đầu gây hội chứng nhiễm trùng bẩm '
                         'sinh: đục thủy tinh thể, điếc, tật đầu nhỏ, tim bẩm sinh phức tạp.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 3.1 - Cận huyết và nhiễm vi-rút',
    'illustration': 'illustration_bai_5.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_15',
    'role': 'CONTENT',
    'section': '3. KHÁCH HÀNG MỤC TIÊU',
    'assertion_title': 'Nhóm 6 & 7: Phơi Nhiễm Môi Trường Độc Hại & Nghi Ngờ Trên Siêu Âm',
    'primary_claim': 'Yếu tố ngoại lai độc chất và các dấu hiệu hình thái học bất thường trên siêu âm là chỉ báo chẩn '
                     'đoán tức thì.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Nhóm 6: Môi Trường Độc Hại & Thuốc Quái Thai',
                 'text': 'Thai phụ làm việc trong môi trường tiếp xúc hóa chất bảo vệ thực vật, kim loại nặng, tia xạ '
                         'hoặc sử dụng các loại thuốc chống chỉ định (Isotretinoin, Valproate, Methotrexate).',
                 'icon': 'shield'},
               { 'title': 'Nhóm 7: Nghi Ngờ Bất Thường Trên Siêu Âm',
                 'text': 'Siêu âm thai phát hiện độ mờ da gáy dày (>= 3.5mm), bất sản xương mũi, tim bẩm sinh, giãn '
                         'não thất, thoát vị rốn, ruột tăng âm vang, thiểu ối hoặc đa ối.',
                 'icon': 'search'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 3.1 - Phơi nhiễm độc chất và dấu hiệu siêu âm',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_16',
    'role': 'CONTENT',
    'section': '3. KHÁCH HÀNG MỤC TIÊU',
    'assertion_title': "Khách Hàng Sơ Sinh: Trẻ 24-72 Giờ Tuổi & 'Thời Điểm Vàng' 48-72 Giờ",
    'primary_claim': 'Lấy mẫu máu gót chân từ 48-72 giờ sau sinh là chuẩn mực sinh học đạt độ chính xác chẩn đoán cao '
                     'nhất.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Không Lấy Máu Quá Sớm (<24 Giờ)',
                 'text': 'Trong 24h đầu, nồng độ hormone TSH của trẻ sinh lý tăng cao sau sinh; lấy máu sớm sẽ gây kết '
                         'quả dương tính giả suy giáp bẩm sinh.',
                 'icon': 'clock'},
               { 'title': 'Thời Điểm Vàng 48 - 72 Giờ',
                 'text': 'Trẻ đã bú sữa mẹ ít nhất 24-48 giờ, quá trình chuyển hóa nội sinh bắt đầu vận hành đầy đủ; '
                         'các xét nghiệm enzyme và axit amin đạt độ chính xác tối ưu.',
                 'icon': 'award'},
               { 'title': 'Trường Hợp Trẻ Cần Truyền Máu',
                 'text': 'BẮT BUỘC PHẢI LẤY MẪU MÁU SÀNG LỌC TRƯỚC KHI TRUYỀN MÁU; nếu đã truyền máu, xét nghiệm men '
                         'G6PD và huyết sắc tố sẽ phản ánh máu của người cho.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 3.2 - Khách hàng sơ sinh và thời điểm lấy mẫu',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_17',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ CUNG CẤP',
    'assertion_title': 'Mạng Lưới 8 Trung Tâm Sàng Lọc, Chẩn Đoán Khu Vực Đầu Ngành',
    'primary_claim': 'Bộ Y tế giao nhiệm vụ cho 8 trung tâm vùng tiếp nhận mẫu xét nghiệm kỹ thuật cao và chỉ đạo '
                     'chuyên môn.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Khu Vực Phía Bắc',
                 'text': '1. Bệnh viện Phụ sản Trung ương; 2. Trường Đại học Y Hà Nội; 3. Bệnh viện Nhi Trung ương; 4. '
                         'Viện Huyết học - Truyền máu Trung ương.',
                 'icon': 'home'},
               { 'title': 'Khu Vực Miền Trung & Tây Nguyên',
                 'text': '5. Bệnh viện Sản Nhi Nghệ An; 6. Trường Đại học Y Dược - Đại học Huế.',
                 'icon': 'map-pin'},
               { 'title': 'Khu Vực Phía Nam & ĐBSCL',
                 'text': '7. Bệnh viện Từ Dũ (TP. Hồ Chí Minh); 8. Bệnh viện Phụ sản Thành phố Cần Thơ.',
                 'icon': 'globe'},
               { 'title': 'Trách Nhiệm Vùng',
                 'text': 'Tiếp nhận giấy thấm máu gót chân từ hàng chục tỉnh thành lân cận; chạy máy xét nghiệm tự '
                         'động Tandem Mass Spectrometry (MS/MS).',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 4 - Danh mục 8 trung tâm vùng',
    'illustration': 'ai_bai_5_sustainability.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_18',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ CUNG CẤP',
    'assertion_title': 'Năng Lực Kỹ Thuật Tuyến Tỉnh, Tuyến Huyện & Tuyến Xã',
    'primary_claim': 'Mô hình phối hợp phân tầng: Tuyến dưới thu thập mẫu, tuyến trên phân tích chẩn đoán chuyên sâu.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tuyến Tỉnh: BV Sản Nhi / BVĐK Tỉnh',
                 'text': 'Thực hiện siêu âm hình thái học 4D, xét nghiệm sàng lọc trước sinh, chọc ối, quản lý ngân '
                         'hàng máu và tiếp nhận điều trị ca bệnh.',
                 'icon': 'layers'},
               { 'title': 'Tuyến Huyện: TTYT / BVĐK Huyện',
                 'text': 'Siêu âm tầm soát cơ bản, tư vấn xét nghiệm NIPT/Combined test; lấy mẫu máu gót chân trẻ sơ '
                         'sinh chuyển về trung tâm khu vực.',
                 'icon': 'activity'},
               { 'title': 'Tuyến Xã: Trạm Y Tế Xã',
                 'text': 'Trực tiếp lấy mẫu máu gót chân trẻ sinh tại trạm hoặc tại nhà; làm khô mẫu giấy thấm, gửi '
                         'bưu điện và quản lý ca bệnh dương tính.',
                 'icon': 'home'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 4 - Phân công cơ sở cung cấp',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_19',
    'role': 'CONTENT',
    'section': '5.1. NỘI DUNG TRƯỚC SINH',
    'assertion_title': 'Tổng Quan Lộ Trình Sàng Lọc Trước Sinh Qua 3 Tam Cá Nguyệt Thai Kỳ',
    'primary_claim': 'Mỗi giai đoạn thai kỳ mang một sứ mệnh tầm soát chuyên biệt, không thể thay thế lẫn nhau.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': '1. Ba Tháng Đầu (11-13w6d)',
                 'text': 'Đo độ mờ da gáy (NT), Combined test, NIPT, sàng lọc Thalassemia; phát hiện sớm các lệch bội '
                         'NST 21, 18, 13.',
                 'icon': 'calendar'},
               { 'title': '2. Ba Tháng Giữa (15-22w)',
                 'text': 'Triple test (tuần 15-20), siêu âm 4D hình thái học (tuần 18-22); chọc ối chẩn đoán xác định '
                         'nếu nguy cơ cao.',
                 'icon': 'activity'},
               { 'title': '3. Ba Tháng Cuối (28-38w)',
                 'text': 'Siêu âm đánh giá tăng trưởng thai chậm trong tử cung, dị tật muộn hệ thần kinh, bánh nhau và '
                         'chuẩn bị cuộc đẻ an toàn.',
                 'icon': 'heart'},
               { 'title': '4. Hội Chẩn Đình Chỉ / Điều Trị',
                 'text': 'Hội đồng chuyên môn tư vấn gia đình hướng can thiệp: phẫu thuật sửa chữa sau sinh hoặc đình '
                         'chỉ thai nghén nhân đạo.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Lộ trình sàng lọc thai kỳ chuẩn Bộ Y tế',
    'illustration': 'cinematic_bai_5_forecast.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_20',
    'role': 'CONTENT',
    'section': '5.1.1. BA THÁNG ĐẦU THAI KỲ',
    'assertion_title': 'Siêu Âm Đo Độ Mờ Da Gáy (NT - Nuchal Translucency) Tuần 11 Đến 13 Tuần 6 Ngày',
    'primary_claim': 'Kỹ thuật đo bề dày lớp dịch dưới da sau gáy thai nhi là chỉ báo hàng đầu phát hiện hội chứng '
                     'Down.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Điều Kiện Kỹ Thuật Chuẩn',
                 'text': 'Thực hiện khi chiều dài đầu - mông (CRL) từ 45mm đến 84mm; bác sĩ siêu âm phải có chứng chỉ '
                         'FMF (Fetal Medicine Foundation).',
                 'icon': 'shield-check'},
               { 'title': 'Ngưỡng Giá Trị Bất Thường',
                 'text': 'NT < 2.5mm: Nguy cơ thấp; NT từ 2.5mm - 3.4mm: Cần phối hợp xét nghiệm sinh hóa; NT >= '
                         '3.5mm: Nguy cơ dị tật tim và NST rất cao.',
                 'icon': 'activity'},
               { 'title': 'Tầm Soát Dị Tật Tim Phức Tạp',
                 'text': 'Da gáy dày đơn độc ngay cả khi NST bình thường cũng cảnh báo nguy cơ cao mắc bệnh tim bẩm '
                         'sinh, thoát vị hoành.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Kỹ thuật đo độ mờ da gáy - BÀI 5. Mục 5.1.1',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_21',
    'role': 'CONTENT',
    'section': '5.1.1. BA THÁNG ĐẦU THAI KỲ',
    'assertion_title': 'Xét Nghiệm Sinh Hóa Combined Test: Phối Hợp PAPP-A & Free Beta-hCG',
    'primary_claim': 'Sự kết hợp giữa siêu âm da gáy và hai chỉ số huyết thanh mẹ nâng tỷ lệ phát hiện Down lên '
                     '85-90%.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Hai Chất Chỉ Điểm Huyết Thanh',
                 'text': '1. PAPP-A (Pregnancy-Associated Plasma Protein A): Giảm thấp ở thai Down; 2. Free Beta-hCG '
                         '(tiểu đơn vị tự do của hCG): Tăng cao gấp đôi ở thai mắc hội chứng Down.',
                 'icon': 'activity'},
               { 'title': 'Phần Mềm Tính Toán Nguy Cơ Tích Hợp',
                 'text': 'Dữ liệu PAPP-A, Beta-hCG, NT và tuổi mẹ được nạp vào phần mềm chuyên dụng tính toán chỉ số '
                         'MoM; nếu nguy cơ > 1/250 được xếp vào nhóm nguy cơ cao cần chẩn đoán tiếp.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Nguyên lý Combined test - BÀI 5',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_22',
    'role': 'CONTENT',
    'section': '5.1.1. BA THÁNG ĐẦU THAI KỲ',
    'assertion_title': 'Đột Phá NIPT: Sàng Lọc ADN Tự Do Của Thai Nhi Trong Máu Mẹ (cfDNA)',
    'primary_claim': 'Xét nghiệm không xâm lấn có độ nhạy và độ đặc hiệu đạt trên 99% đối với hội chứng Down từ tuần '
                     'thứ 9.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Bản Chất ADN Bánh Nhau (cfDNA)',
                 'text': 'Khoảng 5-15% ADN tự do lưu hành trong máu người mẹ bắt nguồn từ các tế bào lá nuôi bánh nhau '
                         'bị thoái hóa phóng thích ra.',
                 'icon': 'activity'},
               { 'title': 'Giải Trình Tự Gen Thế Hệ Mới (NGS)',
                 'text': 'Định lượng chính xác số lượng đoạn ADN của NST 21, 18, 13 và NST giới tính (X, Y) phát hiện '
                         'Down, Edwards, Patau, Turner.',
                 'icon': 'shield-check'},
               { 'title': 'Hạn Chế Bắt Buộc Nhớ',
                 'text': 'Vẫn là xét nghiệm SÀNG LỌC; nếu NIPT dương tính vẫn bắt buộc phải chọc ối làm Karyotype để '
                         'khẳng định trước khi đình chỉ thai.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Kỹ thuật NIPT sàng lọc ADN tự do - BÀI 5',
    'illustration': 'ai_bai_2_quality.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_23',
    'role': 'CONTENT',
    'section': '5.1.1. BA THÁNG ĐẦU THAI KỲ',
    'assertion_title': 'Quy Trình Sàng Lọc Thalassemia Trong 3 Tháng Đầu Bằng Tổng Phân Tích Máu',
    'primary_claim': 'Chỉ số hồng cầu nhỏ nhược màu (MCV < 80 fl, MCH < 27 pg) là chỉ báo nghi ngờ mang gen bệnh hàng '
                     'đầu.',
    'visual_job': 'PROCESS_DEVSECOPS_PIPELINE',
    'visual_anchor': 'PROCESS_CARDS',
    'atoms': [ { 'title': '1. Tổng Phân Tích Máu Mẹ',
                 'text': 'Thử máu thường quy lần khám thai đầu tiên; kiểm tra chỉ số thể tích hồng cầu (MCV) và lượng '
                         'huyết sắc tố (MCH).',
                 'icon': 'search'},
               { 'title': '2. Sàng Lọc Người Chồng',
                 'text': 'Nếu mẹ có MCV < 80 hoặc MCH < 27: Mời ngay người chồng đến làm xét nghiệm tổng phân tích máu '
                         'tương tự.',
                 'icon': 'users'},
               { 'title': '3. Điện Di Huyết Sắc Tố',
                 'text': 'Nếu cả hai vợ chồng đều có hồng cầu nhỏ nhược màu: Làm điện di Hb và xét nghiệm đột biến gen '
                         'Alpha/Beta Thalassemia.',
                 'icon': 'activity'},
               { 'title': '4. Chẩn Đoán Trước Sinh',
                 'text': 'Nếu cả hai cùng mang đột biến cùng loại: Bắt buộc sinh thiết gai nhau tuần 11-14 hoặc chọc '
                         'ối tuần 16 chẩn đoán thai nhi.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình sàng lọc Thalassemia quốc gia - BÀI 5',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_24',
    'role': 'CONTENT',
    'section': '5.1.1. BA THÁNG ĐẦU THAI KỲ',
    'assertion_title': 'Kỹ Thuật Chẩn Đoán Xâm Lấn: Sinh Thiết Gai Nhau (CVS) Tuần 11 Đến 14',
    'primary_claim': 'Kỹ thuật lấy mẫu mô bánh nhau qua thành bụng hoặc cổ tử cung cho phép chẩn đoán di truyền sớm '
                     'nhất.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Kỹ Thuật Thực Hiện Dưới Siêu Âm',
                 'text': 'Dưới sự dẫn đường của đầu dò siêu âm, bác sĩ luồn kim nhỏ qua thành bụng vào bánh nhau hút '
                         'lấy khoảng 10-20mg mô gai nhau để nuôi cấy tế bào và tách chiết ADN.',
                 'icon': 'activity'},
               { 'title': 'Ưu Điểm & Nguy Cơ Biến Chứng',
                 'text': 'Ưu điểm: Có kết quả chẩn đoán di truyền ngay trong 3 tháng đầu, nếu phải đình chỉ thai sẽ '
                         'nhẹ nhàng và ít tai biến; Nhược điểm: Nguy cơ sảy thai khoảng 0.5-1%, đòi hỏi bác sĩ tay '
                         'nghề cao.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Sinh thiết gai nhau CVS - BÀI 5. Mục 5.1.1',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_25',
    'role': 'CONTENT',
    'section': '5.1.2. BA THÁNG GIỮA THAI KỲ',
    'assertion_title': 'Siêu Âm Hình Thái Học 4D Đánh Giá Chi Tiết Dị Tật Thai Nhi (Tuần 18-22)',
    'primary_claim': 'Cửa sổ vàng tối ưu để khảo sát toàn bộ cấu trúc giải phẫu từng cơ quan từ đầu đến chân thai nhi.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Hệ Thần Kinh Trung Ương',
                 'text': 'Khảo sát vòm sọ, hai bán cầu đại não, đám rối màng mạch, tiểu não, hố sau; phát hiện giãn '
                         'não thất, nứt đốt sống (spina bifida).',
                 'icon': 'activity'},
               { 'title': 'Khuôn Mặt & Vòm Miệng',
                 'text': 'Hai hốc mắt, xương mũi, môi trên và vòm miệng; tầm soát dị tật sứt môi, hở hàm ếch và chồi '
                         'mặt bất thường.',
                 'icon': 'eye'},
               { 'title': 'Hệ Tim Mạch & Lồng Ngực',
                 'text': 'Mặt cắt 4 buồng tim, đường ra thất trái/thất phải, cung động mạch chủ; phát hiện thông liên '
                         'thất, tứ chứng Fallot, đảo gốc động mạch.',
                 'icon': 'heart'},
               { 'title': 'Hệ Tiêu Hóa, Tiết Niệu & Chi',
                 'text': 'Bóng dạ dày, hai thận, bàng quang, thành bụng rốn; đếm đủ các ngón tay ngón chân, phát hiện '
                         'khoèo chân, bất sản chi.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình siêu âm hình thái học 18-22 tuần - BÀI 5',
    'illustration': 'illustration_bai_5.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_26',
    'role': 'CONTENT',
    'section': '5.1.2. BA THÁNG GIỮA THAI KỲ',
    'assertion_title': 'Xét Nghiệm Sinh Hóa Triple Test (Tuần 15-20) Sàng Lọc Dị Tật Ống Thần Kinh',
    'primary_claim': 'Đo lường bộ 3 chỉ số huyết thanh mẹ tầm soát lệch bội NST và khiếm khuyết hở ống thần kinh.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Alpha-Fetoprotein (AFP)',
                 'text': 'Do gan thai nhi tiết; AFP tăng rất cao trong dị tật hở ống thần kinh (vô sọ, thoát vị màng '
                         'não) hoặc thoát vị thành bụng; giảm thấp trong hội chứng Down.',
                 'icon': 'activity'},
               { 'title': 'Beta-hCG & Unconjugated Estriol (uE3)',
                 'text': 'Beta-hCG tăng cao trong Down; uE3 (estriol tự do) do nhau thai tổng hợp suy giảm nghiêm '
                         'trọng khi thai có bất thường NST.',
                 'icon': 'file-text'},
               { 'title': 'Thời Điểm Tối Ưu Tuần 16 Đến 18',
                 'text': 'Áp dụng cho những thai phụ bỏ lỡ sàng lọc 3 tháng đầu; cung cấp chỉ số nguy cơ bổ trợ cho '
                         'siêu âm hình thái học.',
                 'icon': 'clock'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Nguyên lý Triple test - BÀI 5. Mục 5.1.2',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_27',
    'role': 'CONTENT',
    'section': '5.1.2. BA THÁNG GIỮA THAI KỲ',
    'assertion_title': 'Kỹ Thuật Chọc Hút Nước Ối (Amniocentesis) Tuần 16 Đến 20',
    'primary_claim': 'Tiêu chuẩn vàng chẩn đoán xác định bệnh lý di truyền trước sinh với độ an toàn cao.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Quy Trình Chọc Ối Vô Khuẩn',
                 'text': 'Sát khuẩn thành bụng, dưới hướng dẫn siêu âm liên tục, châm kim 22G qua buồng ối hút nhẹ '
                         '15-20ml dịch ối chứa tế bào thai nhi.',
                 'icon': 'shield-check'},
               { 'title': 'Các Kỹ Thuật Xét Nghiệm Mẫu Ối',
                 'text': '1. Xét nghiệm nhanh QF-PCR (trả kết quả sau 24h); 2. Nuôi cấy tế bào lập bộ NST Karyotype '
                         '(sau 14 ngày); 3. Microarray lai mảng gen (CMA).',
                 'icon': 'activity'},
               { 'title': 'Độ An Toàn Cao (Nguy Cơ Sảy <0.2%)',
                 'text': 'Tại các trung tâm chuyên khoa giàu kinh nghiệm, tỷ lệ biến chứng rỉ ối, nhiễm trùng hoặc sảy '
                         'thai chỉ khoảng 1 ca trên 500-1000 trường hợp.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Kỹ thuật chọc hút dịch ối - BÀI 5',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_28',
    'role': 'CONTENT',
    'section': '5.1.3. BA THÁNG CUỐI THAI KỲ',
    'assertion_title': 'Siêu Âm Ba Tháng Cuối (Tuần 28-38): Đánh Giá Tăng Trưởng & Tiên Lượng Cuộc Đẻ',
    'primary_claim': 'Khảo sát động học bánh nhau, nước ối và phát hiện các dị tật bẩm sinh biểu hiện muộn.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Phát Hiện Thai Chậm Tăng Trưởng (IUGR)',
                 'text': 'Đo chu vi vòng bụng (AC), ước tính cân nặng thai nhi; phát hiện tình trạng suy nhau thai, '
                         'thiếu oxy mãn tính trong tử cung.',
                 'icon': 'activity'},
               { 'title': 'Khảo Sát Dị Tật Biểu Hiện Muộn',
                 'text': 'Một số bất thường chỉ xuất hiện rõ ở quý 3: nhẵn não, hẹp tá tràng muộn, nang buồng trứng '
                         'thai nhi, tắc ruột phân su.',
                 'icon': 'alert-circle'},
               { 'title': 'Tiên Lượng Phương Thức Đẻ An Toàn',
                 'text': 'Đánh giá ngôi thai, độ trưởng thành bánh nhau, vị trí rau tiền đạo, thể tích nước ối để chủ '
                         'động mổ lấy thai hoặc hồi sức sơ sinh tại phòng đẻ.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 5.1.3 - Ba tháng cuối thai kỳ',
    'illustration': 'ai_bai_5_sustainability.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_29',
    'role': 'CONTENT',
    'section': '5.2. NỘI DUNG SƠ SINH',
    'assertion_title': 'Kỹ Thuật Lấy Mẫu Máu Gót Chân Trẻ Sơ Sinh Thấm Giấy Guthrie Chuẩn Hóa',
    'primary_claim': 'Thực hiện đúng kỹ thuật lấy mẫu bảo đảm chất lượng xét nghiệm và không gây tổn thương cho bé.',
    'visual_job': 'PROCESS_DEVSECOPS_PIPELINE',
    'visual_anchor': 'PROCESS_CARDS',
    'atoms': [ { 'title': '1. Làm Ấm & Sát Khuẩn',
                 'text': 'Ủ ấm gót chân trẻ bằng khăn ấm 3-5 phút tăng tưới máu; sát khuẩn vùng gót bằng cồn 70 độ và '
                         'để khô hoàn toàn.',
                 'icon': 'clock'},
               { 'title': '2. Chọn Vị Trí Chích Máu Chuẩn',
                 'text': 'Chích kim chuyên dụng (lancet sâu 2mm) vào bờ ngoài hoặc bờ trong mặt dưới gót chân; TUYỆT '
                         'ĐỐI KHÔNG chích vào chính giữa gót (tránh xương).',
                 'icon': 'shield'},
               { 'title': '3. Thấm Máu Vào Vòng Tròn',
                 'text': 'Bỏ giọt máu đầu tiên; để các giọt máu tiếp theo tự ngấm tròn đều và thấm xuyên qua mặt sau '
                         'của 5 vòng tròn giấy thấm chuyên dụng.',
                 'icon': 'activity'},
               { 'title': '4. Phơi Khô & Đóng Gói',
                 'text': 'Để khô tự nhiên trên giá nằm ngang ở nhiệt độ phòng 2-4 giờ (tránh ánh nắng); cho vào túi '
                         'zip có gói hút ẩm gửi bưu điện.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình kỹ thuật lấy máu gót chân - QĐ 1807/QĐ-BYT',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_30',
    'role': 'CONTENT',
    'section': '5.2. NỘI DUNG SƠ SINH',
    'assertion_title': 'Bệnh Sơ Sinh 1: Thiếu Men G6PD - Nguy Cơ Tan Máu Cấp & Vàng Da Nhân Não',
    'primary_claim': 'Bệnh di truyền liên kết NST X thường gặp nhất tại Việt Nam gây tan máu khi tiếp xúc chất oxy '
                     'hóa.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Cơ Chế Thiếu Enzyme Bảo Vệ',
                 'text': 'Hồng cầu thiếu enzyme Glucose-6-Phosphate Dehydrogenase không duy trì được màng tế bào, dễ '
                         'vỡ hàng loạt khi gặp chất oxy hóa.',
                 'icon': 'activity'},
               { 'title': 'Hiểm Họa Vàng Da Nhân Não (Kernicterus)',
                 'text': 'Hồng cầu vỡ giải phóng lượng lớn Bilirubin gián tiếp ngấm vào hạch nền não làm trẻ co giật, '
                         'hôn mê, bại não hoặc tử vong.',
                 'icon': 'alert-circle'},
               { 'title': 'Phòng Ngừa Đơn Giản & Hiệu Quả',
                 'text': 'Được phát hiện sớm: Phát thẻ theo dõi, tránh ăn đậu tằm (Fava beans), tránh dùng thuốc kháng '
                         'sinh chống sốt rét, long não (băng phiến).',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Sàng lọc thiếu men G6PD sơ sinh - BÀI 5',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_31',
    'role': 'CONTENT',
    'section': '5.2. NỘI DUNG SƠ SINH',
    'assertion_title': 'Bệnh Sơ Sinh 2: Suy Giáp Bẩm Sinh (CH) - Nguy Cơ Đần Độn & Bổ Sung T4 Sớm',
    'primary_claim': 'Bổ sung hormone tuyến giáp Levothyroxine trong 2 tuần đầu đời giúp cứu vãn 100% trí tuệ của trẻ.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Bản Chất Thiếu Hụt Thyroxine',
                 'text': 'Tuyến giáp không phát triển hoặc không tổng hợp đủ hormone T4 - hormone sống còn quyết định '
                         'sự myelin hóa tế bào thần kinh não bộ.',
                 'icon': 'activity'},
               { 'title': 'Hậu Quả Khi Phát Hiện Muộn (>1 Tháng)',
                 'text': 'Trẻ vàng da kéo dài, táo bón, lưỡi to dày thè ra ngoài, da khô lạnh; khi có triệu chứng rõ '
                         'thì trẻ đã bị thiểu năng trí tuệ vĩnh viễn (đần độn) và lùn tịt.',
                 'icon': 'alert-circle'},
               { 'title': 'Điều Trị Thần Kỳ Với Chi Phí Cực Thấp',
                 'text': 'Chỉ cần uống 1 viên thuốc Levothyroxine nghiền nhỏ mỗi ngày với giá vài trăm đồng, trẻ sẽ '
                         'phát triển trí tuệ và chiều cao hoàn toàn bình thường.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Sàng lọc suy giáp bẩm sinh sơ sinh - BÀI 5',
    'illustration': 'cinematic_bai_5_forecast.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_32',
    'role': 'CONTENT',
    'section': '5.2. NỘI DUNG SƠ SINH',
    'assertion_title': 'Bệnh Sơ Sinh 3: Tăng Sản Thượng Thận Bẩm Sinh (CAH) - Thể Mất Muối & Mơ Hồ Giới Tính',
    'primary_claim': 'Bệnh lý di truyền gen lặn gây suy thượng thận cấp tử vong và làm bé gái bị nam hóa bộ phận sinh '
                     'dục.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Cơ Chế Thiếu Men 21-Hydroxylase',
                 'text': 'Thiếu enzyme 21-OH làm tuyến thượng thận không sản xuất được Cortisol và Aldosterone, dẫn '
                         'đến tích tụ tiền chất 17-OHP và tăng sản xuất Androgen (hormone nam giới).',
                 'icon': 'activity'},
               { 'title': 'Hai Hiểm Họa Lâm Sàng Cấp Cứu',
                 'text': '1. Cơn suy thượng thận cấp mất muối vào ngày thứ 7-14 (nôn trớ, mất nước, trụy mạch tử vong '
                         'nhanh); 2. Bé gái sinh ra có âm vật phì đại như dương vật (mơ hồ giới tính, dễ bị khai sinh '
                         'nhầm thành con trai).',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Sàng lọc tăng sản thượng thận bẩm sinh CAH - BÀI 5',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_33',
    'role': 'CONTENT',
    'section': '5.2. NỘI DUNG SƠ SINH',
    'assertion_title': 'Bệnh Sơ Sinh 4 & 5: Thalassemia Sơ Sinh & Rối Loạn Chuyển Hóa Axit Amin (PKU)',
    'primary_claim': 'Mở rộng danh mục xét nghiệm phổ khối (MS/MS) phát hiện hàng chục bệnh chuyển hóa bẩm sinh hiếm '
                     'gặp.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Sàng Lọc Thalassemia Thể Nặng Sơ Sinh',
                 'text': "Xét nghiệm điện di mao quản trên mẫu máu gót chân phát hiện sớm trẻ mắc bệnh Bart's hydrops "
                         'fetalis (thể Alpha) hoặc Beta-Thalassemia nặng để có kế hoạch truyền máu bảo tồn sự sống.',
                 'icon': 'heart'},
               { 'title': 'Phenylketonuria (PKU) & Rối Loạn Axit Hữu Cơ',
                 'text': 'Thiếu enzyme chuyển hóa Phenylalanine trong sữa tích tụ gây độc não; sàng lọc phát hiện sớm '
                         'giúp đổi sang loại sữa công thức đặc biệt không chứa Phe, cứu trẻ khỏi bại não.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Sàng lọc Thalassemia và rối loạn chuyển hóa sơ sinh',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_34',
    'role': 'CONTENT',
    'section': '5.2. SÀNG LỌC CHỨC NĂNG SƠ SINH',
    'assertion_title': 'Đo Âm Ốc Tai (OAE): Tầm Soát Khiếm Thính Bẩm Sinh Trong 48 Giờ Đầu',
    'primary_claim': 'Phát hiện suy giảm thính lực sớm trong giai đoạn vàng giúp can thiệp đeo máy trợ thính để trẻ '
                     'học nói bình thường.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Nguyên Lý Đo Âm Ốc Tai Tự Động (OAE)',
                 'text': 'Đặt đầu dò mềm vào ống tai trẻ sơ sinh khi đang ngủ; máy phát âm thanh nhẹ và ghi lại sóng '
                         'phản xạ của tế bào lông ốc tai.',
                 'icon': 'activity'},
               { 'title': "Hai Kết Quả: 'Đạt' (Pass) Hoặc 'Nghi Ngờ' (Refer)",
                 'text': 'Thao tác chỉ mất 3-5 phút không đau; nếu kết quả Refer, trẻ sẽ được đo lại sau 1 tháng và '
                         'gửi đo điện thính giác thân não (AABR).',
                 'icon': 'search'},
               { 'title': 'Can Thiệp Sớm Trước 6 Tháng Tuổi',
                 'text': 'Trẻ khiếm thính được cấy ốc tai điện tử hoặc đeo máy trợ thính trước 6 tháng tuổi sẽ phát '
                         'triển ngôn ngữ, giao tiếp và học tập bình thường.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình đo âm ốc tai OAE sơ sinh - BÀI 5',
    'illustration': 'ai_bai_2_quality.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_35',
    'role': 'CONTENT',
    'section': '5.2. SÀNG LỌC CHỨC NĂNG SƠ SINH',
    'assertion_title': 'Đo Độ Bão Hòa Oxy (SpO2): Tầm Soát Tim Bẩm Sinh Nặng Ở Trẻ Sơ Sinh',
    'primary_claim': 'Phương pháp đo độ bão hòa oxy mạch nảy đơn giản, không xâm lấn phát hiện 7 bệnh tim bẩm sinh phụ '
                     'thuộc ống.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Kỹ Thuật Đo Đồng Thời Tay Phải & Chân',
                 'text': 'Thực hiện sau 24h tuổi; kẹp sensor SpO2 vào bàn tay phải (máu trước ống động mạch) và một '
                         'trong hai bàn chân (máu sau ống động mạch).',
                 'icon': 'activity'},
               { 'title': 'Tiêu Chuẩn Chẩn Đoán Dương Tính',
                 'text': 'SpO2 < 90% ở tay hoặc chân, hoặc SpO2 từ 90-94% đo lại 3 lần, hoặc chênh lệch giữa tay phải '
                         'và chân > 3% được coi là dương tính.',
                 'icon': 'alert-circle'},
               { 'title': 'Siêu Âm Tim Cấp Cứu Kịp Thời',
                 'text': 'Chuyển ngay sang khoa tim mạch siêu âm tim phát hiện chuyển gốc đại động mạch, hẹp eo động '
                         'mạch chủ để phẫu thuật cứu sống trẻ.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình sàng lọc tim bẩm sinh SpO2 sơ sinh',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_36',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Mục Tiêu Nghị Quyết 21-NQ/TW: 70% Trước Sinh & 90% Sơ Sinh Đến Năm 2030',
    'primary_claim': 'Chỉ tiêu pháp lệnh đột phá nhằm bảo đảm mọi trẻ em Việt Nam sinh ra đều được bảo vệ toàn diện.',
    'visual_job': 'CHART_AND_INSIGHTS',
    'visual_anchor': 'CHART_AND_INSIGHTS',
    'atoms': [ { 'title': 'Chỉ Tiêu Tầm Soát Trước Sinh (70% Mẹ)',
                 'text': '70% phụ nữ mang thai được tầm soát ít nhất 4 loại bệnh, tật bẩm sinh phổ biến nhất (Hội '
                         'chứng Down, Hội chứng Edwards, Thalassemia, dị tật ống thần kinh).',
                 'icon': 'target'},
               { 'title': 'Chỉ Tiêu Tầm Soát Sơ Sinh (90% Bé)',
                 'text': '90% trẻ sơ sinh được tầm soát ít nhất 5 bệnh bẩm sinh phổ biến nhất (Thiếu men G6PD, Suy '
                         'giáp bẩm sinh, Tăng sản thượng thận bẩm sinh, Thalassemia, khiếm thính/tim bẩm sinh).',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Nghị quyết số 21-NQ/TW và Chiến lược Dân số Việt Nam đến 2030',
    'chart_type': 'COLUMN_CLUSTERED',
    'chart_file': 'chart_population_forecast_scenarios_dark.png',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_37',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Chỉ Đạo & Điều Phối Tuyến Trung Ương: Cục Dân Số & Các Trung Tâm Vùng',
    'primary_claim': 'Cục Dân số giữ vai trò nhạc trưởng điều phối nguồn lực ngân sách và chuẩn hóa quy trình chuyên '
                     'môn.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Cục Dân Số (Bộ Y Tế)',
                 'text': 'Chỉ đạo và điều phối toàn bộ hoạt động của chương trình quốc gia; phân bổ vật tư giấy thấm '
                         'máu, sinh phẩm xét nghiệm và kiểm định chất lượng.',
                 'icon': 'shield-check'},
               { 'title': '8 Trung Tâm Sàng Lọc Khu Vực',
                 'text': 'Bảo đảm năng lực xét nghiệm sinh học phân tử, hội chẩn liên viện các ca bệnh khó và chịu '
                         'trách nhiệm đào tạo kỹ thuật cho tuyến tỉnh.',
                 'icon': 'layers'},
               { 'title': 'Đảm Bảo Chất Lượng Ngoại Kiểm',
                 'text': 'Tham gia các chương trình ngoại kiểm quốc tế định kỳ bảo đảm kết quả xét nghiệm sàng lọc đạt '
                         'độ tin cậy tuyệt đối.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 6.1 - Quản lý tuyến Trung ương',
    'illustration': 'illustration_bai_5.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_38',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Chuỗi Cung Ứng & Vận Chuyển Mẫu Máu Gót Chân Qua Đường Bưu Điện',
    'primary_claim': 'Liên kết chặt chẽ với Bưu điện Việt Nam (VNPost) bảo đảm mẫu máu đến trung tâm xét nghiệm trong '
                     '48 giờ.',
    'visual_job': 'PROCESS_DEVSECOPS_PIPELINE',
    'visual_anchor': 'PROCESS_CARDS',
    'atoms': [ { 'title': '1. Lấy Mẫu Tại Trạm Xã',
                 'text': 'Cán bộ trạm y tế lấy máu gót chân, ghi đầy đủ thông tin mẹ và bé trên phiếu giấy thấm '
                         'Guthrie card.',
                 'icon': 'home'},
               { 'title': '2. Thu Gom Qua Bưu Điện',
                 'text': 'Nhân viên bưu tá bưu điện văn hóa xã đến nhận phong bì mẫu máu định kỳ mỗi 2 ngày một lần.',
                 'icon': 'mail'},
               { 'title': '3. Chuyển Phát Hỏa Tốc',
                 'text': 'Chuyển phát nhanh theo quy trình an toàn sinh học về thẳng phòng xét nghiệm của Trung tâm '
                         'sàng lọc khu vực.',
                 'icon': 'trending-up'},
               { 'title': '4. Trả Kết Quả Điện Tử',
                 'text': 'Trung tâm trả kết quả qua phần mềm quản lý dân số điện tử và nhắn tin SMS thông báo kết quả '
                         'cho phụ huynh.',
                 'icon': 'globe'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình vận chuyển mẫu máu sàng lọc quốc gia',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_39',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Trách Nhiệm Quản Lý Ca Bệnh & Đồng Hành Trị Liệu Suốt Đời Tại Tuyến Xã',
    'primary_claim': 'Sàng lọc chỉ có giá trị thực tiễn khi trẻ mắc bệnh được quản lý hồ sơ và điều trị liên tục tại '
                     'cộng đồng.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Nhiệm Vụ Của Trạm Y Tế Xã',
                 'text': 'Khi nhận thông báo trẻ có kết quả dương tính: Mời ngay gia đình đến tư vấn, chuyển tuyến '
                         'trên làm xét nghiệm chẩn đoán xác định; lập hồ sơ theo dõi quản lý bệnh mạn tính tại trạm, '
                         'cấp phát thuốc bổ sung T4 hoặc Corticoid định kỳ.',
                 'icon': 'home'},
               { 'title': 'Nhiệm Vụ Của Cộng Tác Viên Dân Số',
                 'text': 'Đến tận hộ gia đình thăm hỏi, động viên tinh thần cha mẹ; giám sát việc cho trẻ uống thuốc '
                         'đúng giờ, hướng dẫn chế độ ăn kiêng và nhắc nhở lịch tái khám tại bệnh viện tuyến trên.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 5. Mục 6.5 - Tuyến xã và Cộng tác viên dân số',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_40',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Chính Sách Xã Hội Hóa & Hỗ Trợ Bảo Hiểm Y Tế Chi Trả Sàng Lọc',
    'primary_claim': 'Chuyển dịch cơ chế tài chính từ ngân sách bao cấp sang kết hợp bảo hiểm y tế và dịch vụ tự '
                     'nguyện.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Ngân Sách Nhà Nước Bảo Trợ',
                 'text': 'Cấp miễn phí 100% gói sàng lọc trước sinh và sơ sinh cơ bản cho hộ nghèo, cận nghèo, gia '
                         'đình chính sách và đồng bào dân tộc thiểu số.',
                 'icon': 'shield-check'},
               { 'title': 'Đề Xuất BHYT Đồng Chi Trả',
                 'text': 'Đưa gói xét nghiệm sàng lọc suy giáp bẩm sinh, thiếu men G6PD vào danh mục thanh toán của '
                         'Quỹ Bảo hiểm Y tế.',
                 'icon': 'heart'},
               { 'title': 'Xã Hội Hóa Gói Kỹ Thuật Cao',
                 'text': 'Khuyến khích các gia đình có điều kiện kinh tế tự nguyện đăng ký các gói sàng lọc mở rộng '
                         '(NIPT, sàng lọc 60 bệnh chuyển hóa).',
                 'icon': 'trending-up'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Cơ chế tài chính dịch vụ dân số - BÀI 5',
    'illustration': 'ai_bai_5_sustainability.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_41',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 1: Thứ Tự Ưu Tiên Của 7 Nhóm Đối Tượng Sàng Lọc Trước Sinh',
    'primary_claim': 'Phân tích mức độ rủi ro để bố trí nguồn lực can thiệp y tế hợp lý nhất trong điều kiện nguồn lực '
                     'hạn chế.',
    'visual_job': 'PROCESS_DEVSECOPS_PIPELINE',
    'visual_anchor': 'PROCESS_CARDS',
    'atoms': [ { 'title': 'Ưu Tiên 1: Siêu Âm Dị Tật',
                 'text': 'Thai nhi đã có dấu hiệu nghi ngờ hình thái trên siêu âm (da gáy dày, dị tật tim) bắt buộc '
                         'phải chẩn đoán xâm lấn ngay.',
                 'icon': 'alert-circle'},
               { 'title': 'Ưu Tiên 2: Tiền Sử Gia Đình & Cận Huyết',
                 'text': 'Cặp đôi cận huyết hoặc gia đình có người mắc bệnh di truyền (Thalassemia, Down, Duchenne) '
                         'cần xét nghiệm gen đặc hiệu.',
                 'icon': 'users'},
               { 'title': 'Ưu Tiên 3: Mẹ Lớn Tuổi & Tiền Sử Sảy Thai',
                 'text': 'Phụ nữ mang thai >= 35 tuổi hoặc sảy thai lưu liên tiếp cần sàng lọc lệch bội NST bằng '
                         'NIPT/Combined test.',
                 'icon': 'clock'},
               { 'title': 'Ưu Tiên 4: Phơi Nhiễm Độc Chất & Nhiễm Trùng',
                 'text': 'Mẹ nhiễm Rubella, CMV hoặc tiếp xúc thuốc trừ sâu, hóa chất độc hại cần làm xét nghiệm miễn '
                         'dịch và siêu âm chuyên sâu.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Câu hỏi lượng giá số 1 - BÀI 5',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_42',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 2: Danh Mục Bệnh Tật Bẩm Sinh Thường Gặp Nhất Tại Việt Nam',
    'primary_claim': 'Sắp xếp theo tần suất hiện hành dịch tễ học giúp cán bộ y tế tập trung mũi nhọn can thiệp.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': '1. Tan Máu Bẩm Sinh Thalassemia',
                 'text': 'Chiếm tỷ lệ cao nhất; trên 13% dân số Việt Nam mang gen bệnh (vùng dân tộc thiểu số lên tới '
                         '30-40%); gánh nặng bệnh tật hàng đầu.',
                 'icon': 'alert-circle'},
               { 'title': '2. Thiếu Men G6PD Sơ Sinh',
                 'text': 'Tần suất lưu hành từ 2% đến 5% ở trẻ sơ sinh; là nguyên nhân hàng đầu gây vàng da sơ sinh '
                         'nặng và tan máu cấp.',
                 'icon': 'activity'},
               { 'title': '3. Hội Chứng Down (Trisomy 21)',
                 'text': 'Tần suất xuất hiện xấp xỉ 1/700 trẻ sơ sinh sống; chiếm đa số các ca bất thường số lượng '
                         'nhiễm sắc thể.',
                 'icon': 'users'},
               { 'title': '4. Suy Giáp Bẩm Sinh & CAH',
                 'text': 'Suy giáp bẩm sinh tỷ lệ khoảng 1/3.000 - 1/4.000 trẻ; Tăng sản thượng thận bẩm sinh tỷ lệ '
                         'khoảng 1/10.000 trẻ.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Dịch tễ học bệnh tật bẩm sinh Việt Nam - BÀI 5 Câu 2',
    'illustration': 'cinematic_bai_5_forecast.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_43',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 3: Đề Án Địa Phương Đạt Mục Tiêu 70% Trước Sinh & 90% Sơ Sinh',
    'primary_claim': 'Xây dựng kế hoạch hành động toàn diện kết hợp truyền thông, đào tạo nhân lực và xã hội hóa kinh '
                     'phí.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Nâng Cao Năng Lực Trạm Y Tế',
                 'text': 'Tập huấn 100% nữ hộ sinh, y sĩ sản nhi xã thành thạo kỹ thuật lấy máu gót chân trẻ sơ sinh '
                         'đạt chuẩn vô khuẩn.',
                 'icon': 'shield-check'},
               { 'title': 'Liên Kết Bưu Điện Tối Ưu Logistics',
                 'text': 'Ký kết hợp đồng phối hợp với Bưu điện huyện vận chuyển mẫu máu nhanh chóng, không để mẫu bị '
                         'hỏng do ẩm mốc.',
                 'icon': 'mail'},
               { 'title': 'Chính Sách Hỗ Trợ Của Địa Phương',
                 'text': 'Tham mưu HĐND tỉnh ban hành nghị quyết hỗ trợ kinh phí sàng lọc cho các xã vùng 3 đặc biệt '
                         'khó khăn.',
                 'icon': 'award'},
               { 'title': 'Truyền Thông Chuyển Đổi Hành Vi',
                 'text': 'Cộng tác viên dân số tư vấn trực tiếp cho bà mẹ mang thai từ những tháng đầu, giải thích lợi '
                         'ích cứu sống con trẻ.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Kế hoạch hành động dân số 2030 - BÀI 5 Câu 3',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_44',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'Thông Điệp Cốt Lõi: Sàng Lọc Sớm - Can Thiệp Sớm - Vì Tương Lai Con Trẻ',
    'primary_claim': 'Một giọt máu gót chân hôm nay thắp sáng trọn vẹn tương lai và trí tuệ cho thế hệ ngày mai.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Trước Sinh: An Tâm Mang Thai',
                 'text': 'Siêu âm đo da gáy tuần 12 và sàng lọc máu giúp thai phụ yên tâm suốt 9 tháng thai kỳ khỏe '
                         'mạnh.',
                 'icon': 'heart'},
               { 'title': 'Sơ Sinh: Vững Bước Khôn Lớn',
                 'text': 'Lấy máu gót chân trong 48-72h phát hiện sớm bệnh lý giúp trẻ được điều trị kịp thời để phát '
                         'triển bình thường.',
                 'icon': 'award'},
               { 'title': 'Xã Hội: Giống Nòi Cường Thịnh',
                 'text': 'Chung tay loại bỏ tàn tật bẩm sinh, xây dựng nguồn nhân lực Việt Nam khỏe thể lực, sáng trí '
                         'tuệ.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Thông điệp chuyên đề Sàng lọc trước sinh và sơ sinh',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_45',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'Sơ Đồ Tích Hợp Can Thiệp Dịch Vụ Trước Sinh Và Sơ Sinh Tại Cơ Sở',
    'primary_claim': 'Bản đồ quy trình hướng dẫn tác nghiệp một cửa cho cán bộ y tế dân số tuyến cơ sở.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': '1. Đón Tiếp & Tư Vấn',
                 'text': 'Lập hồ sơ thai nghén, phân loại 7 nhóm nguy cơ tại trạm y tế.',
                 'icon': 'user-check'},
               { 'title': '2. Sàng Lọc 3 Tháng Đầu',
                 'text': 'Đo độ mờ da gáy, làm Combined/NIPT, xét nghiệm Thalassemia.',
                 'icon': 'search'},
               { 'title': '3. Sàng Lọc 3 Tháng Giữa',
                 'text': 'Siêu âm 4D tuần 20 khảo sát dị tật; chọc ối nếu nguy cơ cao.',
                 'icon': 'activity'},
               { 'title': '4. Lấy Máu Gót Chân',
                 'text': 'Lấy mẫu trong 48-72h sau sinh, gửi bưu điện, quản lý điều trị.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình tác nghiệp một cửa - BÀI 5',
    'illustration': 'ai_bai_2_quality.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_46',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'Vai Trò Của Công Nghệ Số Trong Theo Dõi Sàng Lọc Trước Sinh & Sơ Sinh',
    'primary_claim': 'Chuyển đổi số kết nối liền mạch dữ liệu bà mẹ - trẻ em từ trạm y tế đến viện Trung ương.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Sổ Sức Khỏe Điện Tử Mẹ & Bé',
                 'text': 'Tích hợp toàn bộ lịch sử siêu âm, kết quả xét nghiệm di truyền vào ứng dụng VNeID và hồ sơ '
                         'bệnh án điện tử.',
                 'icon': 'globe'},
               { 'title': 'Hệ Thống Mã QR Code Giấy Thấm',
                 'text': 'Mỗi thẻ giấy thấm Guthrie card được định danh bằng mã vạch QR code chống nhầm lẫn mẫu máu '
                         'giữa các trẻ.',
                 'icon': 'check-circle'},
               { 'title': 'Bản Đồ Dịch Tễ Bệnh Tật Bẩm Sinh',
                 'text': 'Phần mềm GIS định vị các chùm ca bệnh Thalassemia tại các xã vùng cao để ưu tiên bố trí kinh '
                         'phí can thiệp.',
                 'icon': 'map-pin'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Ứng dụng công nghệ thông tin trong sàng lọc dân số',
    'illustration': 'illustration_bai_5.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_47',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'Đạo Đức Sinh Học & Quyền Trẻ Em Trong Can Thiệp Y Học Di Truyền',
    'primary_claim': 'Mọi quyết định can thiệp trước sinh và sơ sinh phải đặt quyền lợi tối thượng của trẻ lên hàng '
                     'đầu.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tuyệt Đối Cấm Lựa Chọn Giới Tính Thai Nhi',
                 'text': 'Nghiêm cấm lợi dụng các kỹ thuật chẩn đoán trước sinh (siêu âm, NIPT, chọc ối) để chẩn đoán '
                         'giới tính thai nhi nhằm mục đích phá thai lựa chọn giới tính, làm mất cân bằng giới tính khi '
                         'sinh.',
                 'icon': 'alert-circle'},
               { 'title': 'Bảo Mật Thông Tin Di Truyền Đời Tư',
                 'text': 'Thông tin về gen bệnh của trẻ em phải được bảo mật nghiêm ngặt, tránh gây kỳ thị khi trẻ lớn '
                         'lên đi học, xin việc làm hoặc lập gia đình.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Đạo đức y sinh học trong sàng lọc di truyền - BÀI 5',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_48',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'Cam Kết Hành Động: Vì Một Thế Hệ Trẻ Thơ Việt Nam Phát Triển Toàn Diện',
    'primary_claim': 'Khép lại chuyên đề với lời hiệu triệu tinh thần trách nhiệm của đội ngũ cán bộ y tế dân số cả '
                     'nước.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Trách Nhiệm Nghề Nghiệp',
                 'text': 'Mỗi cán bộ y tế là một người lính xung kích đi đầu trong việc tuyên truyền, tư vấn và thực '
                         'hiện kỹ thuật sàng lọc chuẩn xác.',
                 'icon': 'award'},
               { 'title': 'Hạnh Phúc Gia Đình',
                 'text': 'Mỗi đứa trẻ chào đời khỏe mạnh là niềm hạnh phúc vô bờ của cha mẹ và là tế bào lành mạnh của '
                         'xã hội phồn vinh.',
                 'icon': 'heart'},
               { 'title': 'Khát Vọng Hùng Cường',
                 'text': 'Nâng cao chất lượng dân số về thể lực và trí tuệ là bệ phóng vững chắc để dân tộc Việt Nam '
                         'vươn mình bước vào kỷ nguyên mới.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Lời kết chuyên đề BÀI 5: Tầm soát, chẩn đoán trước sinh và sơ sinh',
    'v91_compliant': True}]
