# -*- coding: utf-8 -*-
"""
scripts/course2_data_bai1.py
Exhaustive Deep-Curriculum Slide Blueprints for BÀI 1 (Make Slide Pro V9.2).
Mega 165+ Archetypes Diversified, 30%-50% High-Resolution Visual Illustrations,
Native Charts, Zero AI Slop, Zero Watermarks.
"""

from typing import Any, Dict, List


def get_slides_bai_1() -> List[Dict[str, Any]]:
    return [ { 'slide_id': 'SLIDE_01',
    'role': 'COVER',
    'section': 'TỔNG QUAN CHUYÊN ĐỀ',
    'assertion_title': 'BÀI 1: TỔNG QUAN VỀ DỊCH VỤ DÂN SỐ',
    'primary_claim': 'Hệ thống lý luận nền tảng về bản chất dịch vụ, đặc thù dịch vụ dân số, cơ chế phân loại và định '
                     'hướng chiến lược quốc gia.',
    'visual_job': 'HERO_TITLE',
    'visual_anchor': 'BRAND_COVER',
    'transition': 'fade',
    'transition_duration': 0.65,
    'illustration': 'illustration_bai_1.jpg',
    'speaker_notes': 'Kính chào quý học viên, hôm nay chúng ta nghiên cứu chuyên đề BÀI 1: Tổng quan về dịch vụ dân '
                     'số.',
    'source_footer': 'Tài liệu đào tạo chuẩn hóa: BÀI 1. Tổng quan về dịch vụ dân số.docx',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_02',
    'role': 'CONTENT',
    'section': 'MỤC TIÊU BÀI HỌC',
    'assertion_title': 'Chuẩn Đầu Ra Khung Năng Lực Cốt Lõi Về Dịch Vụ Dân Số',
    'primary_claim': 'Trang bị cho học viên 4 khối năng lực toàn diện từ nhận thức lý luận, phân tích đặc trưng đến '
                     'phân loại và vận dụng thực tiễn.',
    'visual_job': 'CONTAINER_BENTO_COMPLEX',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Khái Niệm Cốt Lõi',
                 'text': 'Trình bày chính xác và phân biệt rành mạch khái niệm dịch vụ và dịch vụ dân số trong bối '
                         'cảnh kinh tế thị trường.',
                 'icon': 'book-open'},
               { 'title': '2. Đặc Điểm Bản Thể',
                 'text': 'Phân tích sâu sắc 5 đặc trưng cơ bản của dịch vụ và 5 thuộc tính chuyên biệt của dịch vụ dân '
                         'số.',
                 'icon': 'activity'},
               { 'title': '3. Cơ Chế Phân Loại',
                 'text': 'Làm chủ 3 trục phân loại: theo nội dung chuyên môn, theo chế độ chi trả và theo chủ sở hữu '
                         'cung cấp.',
                 'icon': 'layers'},
               { 'title': '4. Vận Dụng Thực Tiễn',
                 'text': 'Đánh giá các dịch vụ dân số trọng tâm trong Chiến lược Dân số Việt Nam đến năm 2030 tại địa '
                         'phương.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Mục tiêu đào tạo chuẩn hóa chuyên đề',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_03',
    'role': 'CONTENT',
    'section': '1. BẢN CHẤT DỊCH VỤ',
    'assertion_title': 'Sự Phát Triển Của Dịch Vụ Là Xu Thế Tất Yếu Trong Nền Kinh Tế',
    'primary_claim': 'Dịch vụ đã trở thành một bộ phận cấu thành hữu cơ trong đời sống xã hội và là thước đo trình độ '
                     'văn minh của nền kinh tế.',
    'visual_job': 'CONTAINER_MARQUEE_STATS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Xu Thế Khách Quan',
                 'text': 'Sự gia tăng tỷ trọng ngành dịch vụ gắn liền với quá trình công nghiệp hóa, đô thị hóa và '
                         'phân công lao động xã hội.',
                 'icon': 'trending-up'},
               { 'title': 'Hiện Diện Thường Nhật',
                 'text': 'Mỗi cá nhân trong xã hội hàng ngày đều đồng thời đóng vai trò là người thụ hưởng hoặc người '
                         'cung ứng dịch vụ.',
                 'icon': 'users'},
               { 'title': 'Thúc Đẩy Tăng Trưởng',
                 'text': 'Khu vực dịch vụ tạo ra giá trị gia tăng cao, giải quyết việc làm và nâng cao toàn diện chất '
                         'lượng cuộc sống con người.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Giáo trình Kinh tế học dịch vụ',
    'v91_compliant': True,
    'marquee_stats': [ {'val': '65%+', 'label': 'Tỷ Trọng GDP Toàn Cầu', 'badge': 'QUY MÔ VĨ MÔ', 'color': '#38BDF8'},
                       { 'val': '80%+',
                         'label': 'Việc Làm Mới Tạo Ra',
                         'badge': 'THỊ TRƯỜNG LAO ĐỘNG',
                         'color': '#10B981'},
                       { 'val': '4.0',
                         'label': 'Chuyển Đổi Số Dịch Vụ',
                         'badge': 'XU HƯỚNG CÔNG NGHỆ',
                         'color': '#F59E0B'}]},
  { 'slide_id': 'SLIDE_04',
    'role': 'CONTENT',
    'section': '1. BẢN CHẤT DỊCH VỤ',
    'assertion_title': 'Đa Dạng Góc Nhìn Lý Luận Về Khái Niệm Dịch Vụ',
    'primary_claim': 'Khái niệm dịch vụ được Phương pháp đa diện từ ngôn ngữ học dân dụng đến bản chất giao dịch kinh '
                     'tế pháp lý.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Góc Nhìn Xã Hội Dân Dụng',
                 'text': 'Từ điển Tiếng Việt (2004): Dịch vụ là công việc phục vụ trực tiếp cho những nhu cầu nhất '
                         'định của số đông, có tổ chức và được trả công.',
                 'icon': 'book-open'},
               { 'title': 'Góc Nhìn Kinh Tế Pháp Lý',
                 'text': 'Dịch vụ là quá trình giao dịch hàng hóa phi vật thể, chuyển giao đồng thời giữa người bán và '
                         'người mua nhằm thỏa mãn kỳ vọng khách hàng.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Từ điển Tiếng Việt & Cơ sở pháp lý kinh doanh dịch vụ',
    'illustration': 'bai1/bai1_slide_04_service_concept.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_05',
    'role': 'CONTENT',
    'section': '1. BẢN CHẤT DỊCH VỤ',
    'assertion_title': 'Định Nghĩa Chuẩn Hóa Về Dịch Vụ Trong Chương Trình Đào Tạo',
    'primary_claim': 'Dịch vụ là hoạt động có tổ chức phục vụ trực tiếp khách hàng nhằm thỏa mãn nhu cầu và được bù '
                     'đắp bằng thù lao.',
    'visual_job': 'CONTAINER_BENTO_COMPLEX',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tính Tổ Chức & Pháp Nhân',
                 'text': 'Hoạt động được thiết kế bài bản theo quy trình chuyên môn, được vận hành bởi các chủ thể có '
                         'tư cách và năng lực pháp lý.',
                 'icon': 'shield'},
               { 'title': 'Tác Động Trực Tiếp Khách Hàng',
                 'text': 'Đối tượng thụ hưởng là con người cụ thể với những nhu cầu thể chất, tinh thần hoặc xã hội '
                         'xác định.',
                 'icon': 'users'},
               { 'title': 'Bản Chất Cung Ứng Phi Vật Chất',
                 'text': 'Tập trung vào quá trình mang lại giá trị sử dụng và sự hài lòng, hoàn toàn phân biệt với sản '
                         'xuất hàng hóa vật chất hữu hình.',
                 'icon': 'award'},
               { 'title': 'Cơ Chế Bù Đắp Chi Phí',
                 'text': 'Được thanh toán bằng tiền công, giá dịch vụ hoặc được ngân sách nhà nước chi trả hỗ trợ theo '
                         'chế độ an sinh.',
                 'icon': 'calculator'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tài liệu chuẩn hóa chuyên đề Dịch vụ dân số',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_06',
    'role': 'CONTENT',
    'section': '1.2. ĐẶC ĐIỂM DỊCH VỤ',
    'assertion_title': 'Đặc Điểm 1: Tính Vô Hình - Bản Chất Phi Vật Thể Của Dịch Vụ',
    'primary_claim': 'Dịch vụ không tồn tại dưới dạng vật chất cụ thể, khách hàng không thể nhìn thấy, sờ nắn hay dùng '
                     'thử trước khi quyết định thụ hưởng.',
    'visual_job': 'CONTAINER_BEFORE_AFTER',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Hàng Hóa Hữu Hình (Goods)',
                 'text': 'Có kích thước, khối lượng, hình dáng, màu sắc và bao bì. Khách hàng có thể cân đong, đo đếm '
                         'và kiểm tra chất lượng trước khi mua.',
                 'icon': 'layers'},
               { 'title': 'Sản Phẩm Dịch Vụ (Services)',
                 'text': 'Mang tính trừu tượng và trải nghiệm. Người dùng chỉ có thể đánh giá mức độ hài lòng trong và '
                         'sau quá trình tiếp nhận dịch vụ.',
                 'icon': 'zap'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Lý thuyết Quản trị Marketing Dịch vụ',
    'v91_compliant': True,
    'contrast_data': { 'before_title': 'HÀNG HÓA HỮU HÌNH (GOODS)',
                       'before_pill': '✕ HÀNG HÓA HỮU HÌNH',
                       'before_badge': 'Chuẩn Mực Thực Thể Đo Lường Được',
                       'before_items': [ 'Hình Thái Vật Chất: Tồn tại dưới dạng vật thể rõ ràng, có kích thước, khối '
                                         'lượng, màu sắc và bao bì cụ thể.',
                                         'Kiểm Định Chất Lượng: Khách hàng có thể quan sát, cầm nắm, cân đong đo đếm '
                                         'và kiểm tra tính năng trước khi mua.',
                                         'Quyền Sở Hữu & Tồn Trữ: Được chuyển giao quyền sở hữu hoàn toàn sau giao '
                                         'dịch; có thể lưu trữ kho bãi dài hạn.'],
                       'after_title': 'SẢN PHẨM DỊCH VỤ (SERVICES)',
                       'after_pill': '✓ SẢN PHẨM DỊCH VỤ',
                       'after_badge': 'Chuẩn Mực Trải Nghiệm & Vô Hình',
                       'after_items': [ 'Bản Chất Phi Vật Thể: Không có hình thái vật lý, là chuỗi hoạt động chuyển '
                                        'giao đồng thời giữa người cung ứng và thụ hưởng.',
                                        'Kiểm Định Qua Trải Nghiệm: Chỉ có thể cảm nhận và đánh giá mức độ hài lòng '
                                        'trong và sau toàn bộ quá trình trực tiếp tiếp nhận.',
                                        'Quyền Thụ Hưởng Trải Nghiệm: Khách hàng chỉ sở hữu lợi ích chăm sóc sức khỏe '
                                        'và trải nghiệm dịch vụ, hoàn toàn không thể tồn kho.']}},
  { 'slide_id': 'SLIDE_07',
    'role': 'CONTENT',
    'section': '1.2. ĐẶC ĐIỂM DỊCH VỤ',
    'assertion_title': 'Hệ Quả Thực Tiễn Từ Tính Vô Hình Trong Lĩnh Vực Y Tế Dân Số',
    'primary_claim': 'Khách hàng mua dịch vụ y tế dân số dựa trên niềm tin vào uy tín chuyên môn và danh tiếng của đơn '
                     'vị cung cấp.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Rủi Ro Nhận Thức Cao',
                 'text': 'Người dân khó hình dung trước kết quả cụ thể khi đăng ký dịch vụ tầm soát trước sinh hoặc tư '
                         'vấn tiền hôn nhân.',
                 'icon': 'shield'},
               { 'title': 'Bằng Chứng Hữu Hình Hóa',
                 'text': 'Cơ sở dịch vụ phải củng cố niềm tin bằng phòng ốc sạch sẽ, trang thiết bị hiện đại, chứng '
                         'chỉ hành nghề và phong cách chuẩn mực.',
                 'icon': 'award'},
               { 'title': 'Giá Trị Thấu Cảm & Trải Nghiệm',
                 'text': 'Sự an tâm và thái độ ân cần của nhân viên y tế chính là sản phẩm quan trọng nhất mà khách '
                         'hàng cảm nhận được.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tài liệu chuẩn hóa chuyên đề Dịch vụ dân số',
    'illustration': 'bai1/bai1_slide_07_core_definition.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_08',
    'role': 'CONTENT',
    'section': '1.2. ĐẶC ĐIỂM DỊCH VỤ',
    'assertion_title': 'Đặc Điểm 2: Tính Không Thể Tách Rời Giữa Cung Cấp Và Tiêu Dùng',
    'primary_claim': 'Quá trình sản xuất và tiêu thụ dịch vụ diễn ra đồng thời trong cùng một không gian và thời gian '
                     'tương tác trực tiếp.',
    'visual_job': 'PROCESS_CHEVRON_LINEAR',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Khởi Tạo Tương Tác',
                 'text': 'Khách hàng xuất hiện tại cơ sở hoặc liên hệ trực tuyến để đặt lịch khám tư vấn.'},
               { 'title': '2. Cung Ứng Đồng Thời',
                 'text': 'Bác sĩ thăm khám, làm xét nghiệm trong khi khách hàng trực tiếp phối hợp tiếp nhận.'},
               { 'title': '3. Đánh Giá Trải Nghiệm',
                 'text': 'Khách hàng cảm nhận ngay chất lượng y tế và hiệu quả tư vấn ngay khi kết thúc buổi khám.'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Lý thuyết Quản trị Vận hành Dịch vụ',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_09',
    'role': 'CONTENT',
    'section': '1.2. ĐẶC ĐIỂM DỊCH VỤ',
    'assertion_title': 'Minh Họa Tính Không Thể Tách Rời Trong Chăm Sóc Sức Khỏe',
    'primary_claim': 'Dịch vụ nằm viện nội trú đòi hỏi sự đồng hiện diện và phối hợp liên tục giữa nhân viên y tế và '
                     'người bệnh.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Phía Nhà Cung Cấp',
                 'text': 'Bệnh viện cung cấp phòng bệnh, thiết bị theo dõi, y lệnh điều trị và chế độ dinh dưỡng chăm '
                         'sóc hàng giờ.',
                 'icon': 'shield'},
               { 'title': 'Phía Người Bệnh',
                 'text': 'Người bệnh trực tiếp cư trú, tuân thủ phác đồ và phối hợp phản hồi các dấu hiệu lâm sàng để '
                         'điều chỉnh can thiệp.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Thực tiễn quản trị bệnh viện & chăm sóc lâm sàng',
    'illustration': 'bai1/bai1_slide_09_intangibility.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_10',
    'role': 'CONTENT',
    'section': '1.2. ĐẶC ĐIỂM DỊCH VỤ',
    'assertion_title': 'Đặc Điểm 3: Tính Không Thể Tồn Kho Lưu Trữ (Perishability)',
    'primary_claim': 'Dịch vụ không thể sản xuất trước rồi cất giữ trong kho; công suất dịch vụ không sử dụng sẽ bị '
                     'triệt tiêu vĩnh viễn theo thời gian.',
    'visual_job': 'FRAMEWORK_PYRAMID_ASCENDING',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Sự Hao Phí Thời Gian',
                 'text': 'Một giờ làm việc trống của bác sĩ chuyên khoa hoặc một ngày giường bệnh trống không thể được '
                         'bảo lưu sang ngày mai.',
                 'icon': 'activity'},
               { 'title': 'Thách Thức Cung - Cầu',
                 'text': 'Nhu cầu dịch vụ thường dao động theo mùa vụ, ngày trong tuần, trong khi năng lực cung ứng '
                         'tại chỗ có giới hạn cố định.',
                 'icon': 'trending-up'},
               { 'title': 'Yêu Cầu Điều Phối Nguồn Lực',
                 'text': 'Đòi hỏi đơn vị phải áp dụng cơ chế đặt lịch hẹn, phân luồng linh hoạt và huy động nhân lực '
                         'tăng cường theo chiến dịch.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Lý thuyết Quản trị Vận hành Dịch vụ',
    'v91_compliant': True,
    'pyramid_layers': [ { 'tier': 'ĐỈNH CAO (ĐIỀU PHỐI)',
                          'title': 'Điều Phối Đặt Hẹn & Phân Luồng Linh Hoạt',
                          'desc': 'Tối ưu hóa thời gian chờ đợi và tránh lãng phí công suất khám'},
                        { 'tier': 'TẦNG 2 (CÂN BẰNG)',
                          'title': 'Cân Bằng Cung Cầu Mùa Vụ & Chiến Dịch',
                          'desc': 'Huy động đội ngũ y tế lưu động đáp ứng nhu cầu tăng vọt'},
                        { 'tier': 'NỀN TẢNG (CƠ SỞ)',
                          'title': 'Cơ Sở Vật Chất & Năng Lực Bác Sĩ Cố Định',
                          'desc': 'Hạ tầng phòng khám và giờ làm việc chuyên môn không thể lưu kho'}]},
  { 'slide_id': 'SLIDE_11',
    'role': 'CONTENT',
    'section': '1.2. ĐẶC ĐIỂM DỊCH VỤ',
    'assertion_title': 'Bài Học Điều Phối Chiến Dịch Truyền Thông & Cung Ứng Dịch Vụ',
    'primary_claim': 'Các chiến dịch chăm sóc SKSS tại xã phải chuẩn bị phương án huy động công suất tối đa để đáp ứng '
                     'nhu cầu tăng vọt.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Đặc Thù Chiến Dịch',
                 'text': 'Số lượng phụ nữ đến khám phụ khoa và nhận biện pháp tránh thai tăng gấp 5-10 lần ngày thường '
                         'trong thời gian chiến dịch.',
                 'icon': 'trending-up'},
               { 'title': 'Nguy Cơ Quá Tải Cục Bộ',
                 'text': 'Nếu không dự báo tốt, trạm y tế sẽ rơi vào tình trạng thiếu bàn khám, thiếu vật tư và gây '
                         'thời gian chờ đợi kéo dài.',
                 'icon': 'shield'},
               { 'title': 'Giải Pháp Điều Động Lưu Động',
                 'text': 'Trung tâm Y tế huyện tăng cường đội lưu động, máy siêu âm xách tay và hỗ trợ kỹ thuật trực '
                         'tiếp tại cơ sở.',
                 'icon': 'zap'},
               { 'title': 'Hiệu Quả Tiếp Cận Vùng Khó',
                 'text': 'Giúp người dân vùng sâu, vùng xa thụ hưởng dịch vụ chuyên khoa mà không phải di chuyển lên '
                         'tuyến trên.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Thực tiễn tổ chức chiến dịch truyền thông dân số',
    'illustration': 'bai1/bai1_slide_11_campaign_coordination.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_12',
    'role': 'CONTENT',
    'section': '1.2. ĐẶC ĐIỂM DỊCH VỤ',
    'assertion_title': 'Đặc Điểm 4: Tính Không Đồng Nhất Về Chất Lượng (Variability)',
    'primary_claim': 'Chất lượng dịch vụ thường biến thiên, phụ thuộc chặt chẽ vào người thực hiện, thời điểm và tâm '
                     'lý trong từng ca tiếp xúc.',
    'visual_job': 'PROCESS_CIRCULAR_CYCLE',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Yếu Tố Con Người Cung Ứng',
                 'text': 'Trình độ chuyên môn, kỹ năng giao tiếp, sức khỏe và trạng thái cảm xúc của cán bộ y tế ảnh '
                         'hưởng trực tiếp đến chất lượng.',
                 'icon': 'users'},
               { 'title': 'Bối Cảnh & Môi Trường',
                 'text': 'Cùng một bác sĩ khám vào đầu giờ sáng sẽ có sự tập trung và kiên nhẫn khác với thời điểm '
                         'cuối ca trực căng thẳng.',
                 'icon': 'activity'},
               { 'title': 'Tính Đa Dạng Của Khách Hàng',
                 'text': 'Mỗi người dân có trình độ nhận thức, khả năng hợp tác và kỳ vọng khác nhau, tạo ra các trải '
                         'nghiệm rất dị biệt.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Lý thuyết Quản trị Chất lượng Dịch vụ (SERVQUAL)',
    'v91_compliant': True,
    'process_data': { 'core_title': 'CHU TRÌNH PDCA\nCHUẨN HÓA DỊCH VỤ',
                      'nodes': [ { 'step': 'PLAN',
                                   'title': 'Xây Dựng Chuẩn SOP',
                                   'desc': 'Ban hành bảng kiểm và phác đồ kỹ thuật thống nhất.'},
                                 { 'step': 'DO',
                                   'title': 'Đào Tạo & Thực Thi',
                                   'desc': 'Huấn luyện bác sĩ và triển khai tiếp đón chuẩn mực.'},
                                 { 'step': 'CHECK',
                                   'title': 'Đo Lường Biến Thiên',
                                   'desc': 'Khảo sát sự hài lòng và kiểm tra chéo lâm sàng.'},
                                 { 'step': 'ACT',
                                   'title': 'Cải Tiến Quy Trình',
                                   'desc': 'Cập nhật phác đồ và loại bỏ sai số trong phục vụ.'}]}},
  { 'slide_id': 'SLIDE_13',
    'role': 'CONTENT',
    'section': '1.2. ĐẶC ĐIỂM DỊCH VỤ',
    'assertion_title': 'Chuẩn Hóa Quy Trình Kỹ Thuật Để Kiểm Soát Tính Biến Thiên',
    'primary_claim': 'Ban hành quy trình chuẩn (SOP) và bảng kiểm lâm sàng là giải pháp then chốt bảo đảm chất lượng '
                     'dịch vụ đồng đều.',
    'visual_job': 'CHART_AND_INSIGHTS',
    'visual_anchor': 'CHART_AND_INSIGHTS',
    'atoms': [ { 'title': 'Quy Trình Chuẩn (SOP)',
                 'text': 'Quy định rõ ràng từng bước khám, hỏi bệnh, tư vấn và kỹ thuật thực hiện cho từng loại dịch '
                         'vụ.',
                 'icon': 'book-open'},
               { 'title': 'Bảng Kiểm Lâm Sàng (Checklist)',
                 'text': 'Kiểm soát bắt buộc các tiêu chí vô khuẩn, chỉ định và chống chỉ định trước khi làm thủ '
                         'thuật.',
                 'icon': 'shield'},
               { 'title': 'Đào Tạo Kỹ Năng Mềm',
                 'text': 'Tập huấn kỹ năng giao tiếp, lắng nghe thấu cảm và giữ thái độ trung lập không phán xét đối '
                         'với khách hàng.',
                 'icon': 'award'},
               { 'title': 'Giám Sát Hỗ Trợ Định Kỳ',
                 'text': 'Tuyến trên kiểm tra, cầm tay chỉ việc và khắc phục sai sót chuyên môn trực tiếp tại trạm y '
                         'tế xã.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Hướng dẫn Quốc gia về các dịch vụ Chăm sóc SKSS',
    'chart_type': 'COLUMN_CLUSTERED',
    'chart_file': 'chart_dependency_ratio_trends_dark.png',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_14',
    'role': 'CONTENT',
    'section': '1.2. ĐẶC ĐIỂM DỊCH VỤ',
    'assertion_title': 'Đặc Điểm 5: Vai Trò Đồng Kiến Tạo Của Người Sử Dụng Dịch Vụ',
    'primary_claim': 'Khách hàng không chỉ là đối tượng thụ động mà là một chủ thể tham gia trực tiếp quyết định kết '
                     'quả của dịch vụ.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Sự Hợp Tác Cung Cấp Thông Tin',
                 'text': 'Khách hàng phải trung thực chia sẻ tiền sử bệnh tật, thói quen sinh hoạt và các dấu hiệu bất '
                         'thường để bác sĩ chẩn đoán đúng.',
                 'icon': 'users'},
               { 'title': 'Tuân Thủ Hướng Dẫn Chuyên Môn',
                 'text': 'Hiệu quả điều trị và an toàn sinh sản phụ thuộc vào việc người dùng thực hiện đúng chỉ định '
                         'thuốc và tái khám đúng hẹn.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tài liệu chuẩn hóa chuyên đề Dịch vụ dân số',
    'illustration': 'bai1/bai1_slide_14_logistics_inventory.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_15',
    'role': 'CONTENT',
    'section': '1.2. ĐẶC ĐIỂM DỊCH VỤ',
    'assertion_title': 'Bảng Tổng Hợp So Sánh Đối Trọng: Hàng Hóa Hữu Hình Vs Dịch Vụ',
    'primary_claim': 'Nhận thức rõ 5 điểm khác biệt cốt lõi giúp các nhà quản lý thiết kế cơ chế cung ứng và giám sát '
                     'phù hợp.',
    'visual_job': 'TABLE_COMPARISON_PRO',
    'visual_anchor': 'DATA_TABLE_MATRIX',
    'table_data': { 'headers': ['Tiêu Chí So Sánh', 'Hàng Hóa Hữu Hình (Goods)', 'Dịch Vụ (Services)'],
                    'rows': [ [ '1. Hình thái tồn tại',
                                'Vật thể cụ thể, nhìn thấy và cầm nắm được',
                                'Phi vật thể, trừu tượng, mang tính trải nghiệm'],
                              [ '2. Chu trình cung ứng',
                                'Sản xuất trước → Lưu kho → Bán → Tiêu dùng',
                                'Sản xuất và tiêu dùng diễn ra đồng thời'],
                              [ '3. Khả năng tồn kho',
                                'Có thể bảo quản trong kho dự trữ lâu dài',
                                'Không thể tồn kho, tiêu biến theo thời gian'],
                              [ '4. Tính đồng nhất',
                                'Quy chuẩn công nghiệp, độ đồng đều cao',
                                'Dị biệt, phụ thuộc con người và hoàn cảnh'],
                              [ '5. Quyền sở hữu',
                                'Chuyển giao quyền sở hữu tài sản hoàn toàn',
                                'Chỉ chuyển giao quyền thụ hưởng trong thời gian nhất định']]},
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tổng hợp lý thuyết quản trị dịch vụ hiện đại',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_16',
    'role': 'CONTENT',
    'section': '2. KHÁI NIỆM DỊCH VỤ DÂN SỐ',
    'assertion_title': 'Định Nghĩa Dịch Vụ Dân Số Theo Pháp Lệnh Dân Số Năm 2003',
    'primary_claim': 'Dịch vụ dân số là hệ thống các hoạt động phục vụ trực tiếp công tác quản lý và nâng cao chất '
                     'lượng dân số quốc gia.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Căn Cứ Pháp Lý Cao Nhất',
                 'text': 'Được định danh chính thức tại Pháp lệnh Dân số số 06/2003/PL-UBTVQH11 của Ủy ban Thường vụ '
                         'Quốc hội.',
                 'icon': 'shield'},
               { 'title': 'Mục Tiêu Quy Mô & Cơ Cấu',
                 'text': 'Thực hiện điều chỉnh mức sinh hợp lý, giảm thiểu mất cân bằng giới tính khi sinh và phân bố '
                         'dân cư hợp lý.',
                 'icon': 'trending-up'},
               { 'title': 'Nâng Cao Chất Lượng Dân Số',
                 'text': 'Can thiệp cải thiện thể chất, trí tuệ và tinh thần của người dân qua các dịch vụ y tế dự '
                         'phòng và chăm sóc ban đầu.',
                 'icon': 'award'},
               { 'title': 'Tính Toàn Diện Về Nội Hàm',
                 'text': 'Bao gồm cả dịch vụ truyền thông, tư vấn, hướng dẫn kỹ thuật và cung cấp các phương tiện '
                         'chuyên dụng.',
                 'icon': 'layers'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Pháp lệnh Dân số 2003 & Nghị định hướng dẫn thi hành',
    'illustration': 'bai1/bai1_slide_16_training_standardization.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_17',
    'role': 'CONTENT',
    'section': '2. KHÁI NIỆM DỊCH VỤ DÂN SỐ',
    'assertion_title': 'Dịch Vụ Dân Số Là Công Cụ Trực Tiếp Hiện Thực Hóa Chính Sách',
    'primary_claim': 'Chính sách dân số không thể thành công nếu thiếu mạng lưới cung ứng dịch vụ đến tận tay từng '
                     'người dân tại cơ sở.',
    'visual_job': 'FRAMEWORK_STRATEGY_HOUSE',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Chuyển Hóa Nghị Quyết',
                 'text': 'Đưa các chủ trương, đường lối và chỉ tiêu chiến lược thành các can thiệp y tế - xã hội cụ '
                         'thể hàng ngày.',
                 'icon': 'book-open'},
               { 'title': 'Bảo Đảm Quyền Con Người',
                 'text': 'Bảo đảm quyền tự do lựa chọn biện pháp tránh thai, chăm sóc sức khỏe sinh sản và tiếp cận '
                         'thông tin y tế bình đẳng.',
                 'icon': 'shield'},
               { 'title': 'Hiệu Quả Đầu Tư Xã Hội',
                 'text': 'Mỗi đồng ngân sách chi cho dịch vụ dân số dự phòng tiết kiệm hàng chục đồng chi phí điều trị '
                         'bệnh tật trong tương lai.',
                 'icon': 'calculator'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Báo cáo Đánh giá Tác động Chính sách Dân số',
    'v91_compliant': True,
    'house_data': { 'roof_title': 'HIỆN THỰC HÓA CHÍNH SÁCH DÂN SỐ QUỐC GIA ĐẾN NĂM 2030',
                    'pillars': [ { 'title': 'Chuyển Hóa Nghị Quyết',
                                   'desc': 'Đưa các chủ trương, đường lối và chỉ tiêu chiến lược thành can thiệp y tế cụ thể hàng ngày.',
                                   'kpi': 'Chỉ Tiêu: 100% Tuyến Xã'},
                                 { 'title': 'Bảo Đảm Quyền Con Người',
                                   'desc': 'Bảo đảm quyền tự do lựa chọn biện pháp tránh thai và tiếp cận thông tin y tế bình đẳng.',
                                   'kpi': 'Quyền Tự Quyết Y Tế'},
                                 { 'title': 'Hiệu Quả Đầu Tư Xã Hội',
                                   'desc': 'Mỗi đồng ngân sách chi cho dịch vụ dự phòng tiết kiệm hàng chục đồng điều trị tương lai.',
                                   'kpi': 'Tối Ưu Hóa Ngân Sách'}],
                    'foundation': 'NỀN MÓNG VỮNG CHẮC: MẠNG LƯỚI Y TẾ CƠ SỞ • ĐỘI NGŨ CÁN BỘ DÂN SỐ TẬN TỤY'}},
  { 'slide_id': 'SLIDE_18',
    'role': 'CONTENT',
    'section': '2.2. ĐẶC ĐIỂM DỊCH VỤ DÂN SỐ',
    'assertion_title': 'Đặc Trưng 1: Dịch Vụ Dân Số Có Liên Quan Đến Mọi Tầng Lớp Xã Hội',
    'primary_claim': 'Khách hàng của dịch vụ dân số bao phủ toàn bộ cộng đồng, từ trẻ sơ sinh, thanh thiếu niên đến '
                     'người cao tuổi.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Độ Phủ Dân Cư Rộng Lớn',
                 'text': 'Mọi cá nhân trong xã hội đều trải qua các giai đoạn vòng đời và có nhu cầu sử dụng các dịch '
                         'vụ dân số tương ứng.',
                 'icon': 'globe'},
               { 'title': 'Mạng Lưới Chân Rết Tận Thôn Bản',
                 'text': 'Hệ thống cộng tác viên dân số và y tế thôn bản trực tiếp đến từng hộ gia đình để rà soát, '
                         'vận động và cung cấp dịch vụ.',
                 'icon': 'users'},
               { 'title': 'Đa Dạng Hóa Kênh Tiếp Cận',
                 'text': 'Kết hợp tiếp cận tại cơ sở y tế cố định, đội lưu động, học đường, nhà máy và qua nền tảng số '
                         'hóa.',
                 'icon': 'zap'},
               { 'title': 'Tính Phổ Cập & Bình Đẳng',
                 'text': 'Không phân biệt thành phần xã hội, tôn giáo; ưu tiên đối tượng khó khăn, đồng bào dân tộc '
                         'thiểu số và vùng biển đảo.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tài liệu đào tạo Dân số học chuẩn quốc gia',
    'illustration': 'bai1/bai1_slide_18_citizen_satisfaction.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_19',
    'role': 'CONTENT',
    'section': '2.2. ĐẶC ĐIỂM DỊCH VỤ DÂN SỐ',
    'assertion_title': 'Đặc Trưng 2: Tác Động Trực Tiếp Đến Phong Tục Tập Quán Địa Phương',
    'primary_claim': 'Các hành vi dân số chịu sự chi phối sâu sắc của các quan niệm văn hóa truyền thống, định kiến '
                     'giới và tập quán dòng họ.',
    'visual_job': 'ARCH_SYSTEM_LAYERED_STACK',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tâm Lý Thích Đẻ Nhiều Con',
                 'text': 'Quan niệm đông con nhiều của, trời sinh voi trời sinh cỏ vẫn còn tồn tại dai dẳng ở một số '
                         'vùng nông thôn.',
                 'icon': 'users'},
               { 'title': 'Tâm Lý Nối Dõi Tông Đường',
                 'text': 'Định kiến phải có con trai để thờ cúng dẫn đến tình trạng lạm dụng kỹ thuật lựa chọn giới '
                         'tính thai nhi.',
                 'icon': 'shield'},
               { 'title': 'Sự E Ngại Bộc Lộ Riêng Tư',
                 'text': 'Các vấn đề về sinh sản, tình dục thường bị coi là nhạy cảm, người dân còn rụt rè khi tiếp '
                         'cận dịch vụ tư vấn chuyên nghiệp.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Nghiên cứu Văn hóa học và Hành vi sinh sản tại Việt Nam',
    'v91_compliant': True,
    'arch_data': { 'layers': [ { 'tier': 'TẦNG 1: HÀNH VI BỀ NỔI',
                                 'tech': 'Biểu Hiện Tiếp Nhận Dịch Vụ',
                                 'desc': 'Quyết định sử dụng biện pháp tránh thai và đăng ký dịch vụ y tế của người '
                                         'dân.'},
                               { 'tier': 'TẦNG 2: RÀO CẢN TÂM LÝ',
                                 'tech': 'Tâm Lý E Ngại & Khép Kín',
                                 'desc': 'Rụt rè khi chia sẻ các vấn đề sức khỏe sinh sản, tình dục và bệnh phụ khoa '
                                         'nhạy cảm.'},
                               { 'tier': 'TẦNG 3: ÁP LỰC DÒNG HỌ',
                                 'tech': 'Định Kiến Giới & Thờ Cúng',
                                 'desc': 'Tư tưởng phải có con trai nối dõi tông đường tạo áp lực lựa chọn giới tính '
                                         'thai nhi.'},
                               { 'tier': 'TẦNG 4: TẬP QUÁN GỐC RỄ',
                                 'tech': 'Quan Niệm Văn Hóa Truyền Thống',
                                 'desc': 'Tư tưởng đông con nhiều của, trời sinh voi trời sinh cỏ ăn sâu qua nhiều thế '
                                         'hệ.'}]}},
  { 'slide_id': 'SLIDE_20',
    'role': 'CONTENT',
    'section': '2.2. ĐẶC ĐIỂM DỊCH VỤ DÂN SỐ',
    'assertion_title': 'Nghệ Thuật Tư Vấn Kiên Trì Mưa Dầm Thấm Lâu Trong Dân Số',
    'primary_claim': 'Dịch vụ dân số đòi hỏi cán bộ phải có kỹ năng truyền thông thấu cảm để từng bước thay đổi định '
                     'kiến lạc hậu.',
    'visual_job': 'PROCESS_CHEVRON_LINEAR',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Giai Đoạn 1: Lắng Nghe Thấu Cảm',
                 'text': 'Tôn trọng niềm tin văn hóa của người dân, không chỉ trích thói quen mà tìm hiểu căn nguyên '
                         'tâm lý dòng họ.',
                 'icon': 'users'},
               { 'title': 'Giai Đoạn 2: Cung Cấp Bằng Chứng',
                 'text': 'Chỉ ra gánh nặng kinh tế khi sinh dày, rủi ro dị tật bẩm sinh và lợi ích của việc nuôi dạy '
                         'con khỏe mạnh.',
                 'icon': 'book-open'},
               { 'title': 'Giai Đoạn 3: Chuyển Hóa Hành Vi',
                 'text': 'Vận động các già làng, trưởng bản, người có uy tín đi đầu làm gương để tạo hiệu ứng lan tỏa '
                         'trong cộng đồng.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Sổ tay Kỹ năng Truyền thông Chuyển đổi Hành vi Dân số',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_21',
    'role': 'CONTENT',
    'section': '2.2. ĐẶC ĐIỂM DỊCH VỤ DÂN SỐ',
    'assertion_title': 'Đặc Trưng 3: Mối Tương Quan Chặt Chẽ Với Trình Độ Học Vấn',
    'primary_claim': 'Trình độ học vấn của người dân quyết định trực tiếp đến mức độ hiểu biết, nhu cầu và khả năng '
                     'tiếp cận dịch vụ dân số.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Nhóm Học Vấn Thấp / Khó Tiếp Cận',
                 'text': 'Thường có mức sinh cao, tỷ lệ sinh con thứ 3 trở lên cao; nhận thức hạn chế về sàng lọc dị '
                         'tật và phòng ngừa bệnh STIs.',
                 'icon': 'shield'},
               { 'title': 'Nhóm Học Vấn Cao / Chủ Động',
                 'text': 'Có xu hướng kết hôn muộn, sinh ít con, chủ động tìm kiếm các gói dịch vụ chất lượng cao '
                         'trước hôn nhân và thai kỳ.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tổng điều tra Dân số và Nhà ở Việt Nam',
    'illustration': 'bai1/bai1_slide_21_preventative_need.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_22',
    'role': 'CONTENT',
    'section': '2.2. ĐẶC ĐIỂM DỊCH VỤ DÂN SỐ',
    'assertion_title': 'Đặc Trưng 4: Phụ Thuộc Trình Độ Phát Triển Kinh Tế - Xã Hội',
    'primary_claim': 'Điều kiện kinh tế của từng vùng quyết định mức độ đầu tư hạ tầng y tế, trang thiết bị và khả '
                     'năng chi trả của người dân.',
    'visual_job': 'FRAMEWORK_MATRIX_2X2',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Đô Thị - Nâng Cao',
                 'text': 'Sàng lọc gen NIPT, tư vấn tiền hôn nhân chất lượng cao, người dân sẵn sàng chi trả dịch vụ '
                         'theo yêu cầu.',
                 'icon': 'trending-up'},
               { 'title': 'Đô Thị - Cơ Bản',
                 'text': 'Trạm y tế phường và BHYT chi trả dịch vụ sinh sản thông thường, tiêm chủng mở rộng.',
                 'icon': 'shield'},
               { 'title': 'Nông Thôn - Nâng Cao',
                 'text': 'Từng bước xã hội hóa dịch vụ tư nhân tại thị trấn, các phòng khám chuyên khoa liên kết.',
                 'icon': 'activity'},
               { 'title': 'Nông Thôn - Bảo Trợ',
                 'text': 'Ngân sách nhà nước cấp phát miễn phí 100% phương tiện tránh thai & tổ chức các đợt khám lưu '
                         'động.',
                 'icon': 'calculator'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chiến lược Dân số Việt Nam đến năm 2030',
    'v91_compliant': True,
    'matrix_data': { 'axis_x': 'Mức Thu Nhập & Điều Kiện Kinh Tế (Thấp/Nông thôn → Cao/Đô thị)',
                     'axis_y': 'Nhu Cầu Dịch Vụ Dân Số (Cơ Bản/Bảo Trợ ↔ Nâng Cao/Chuyên Sâu)',
                     'quadrants': [ { 'title': 'ĐÔ THỊ - NÂNG CAO',
                                      'desc': 'Sàng lọc gen NIPT, tư vấn tiền hôn nhân chất lượng cao, người dân sẵn '
                                              'sàng chi trả.',
                                      'highlight': True},
                                    { 'title': 'ĐÔ THỊ - CƠ BẢN',
                                      'desc': 'Trạm y tế phường, BHYT chi trả dịch vụ sinh sản thông thường và tiêm '
                                              'chủng.',
                                      'highlight': False},
                                    { 'title': 'NÔNG THÔN - NÂNG CAO',
                                      'desc': 'Từng bước xã hội hóa dịch vụ tư nhân tại thị trấn, phòng khám chuyên '
                                              'khoa liên kết.',
                                      'highlight': False},
                                    { 'title': 'NÔNG THÔN - BẢO TRỢ',
                                      'desc': 'Ngân sách nhà nước cấp phát miễn phí 100% phương tiện tránh thai & khám '
                                              'lưu động.',
                                      'highlight': False}]}},
  { 'slide_id': 'SLIDE_23',
    'role': 'CONTENT',
    'section': '2.2. ĐẶC ĐIỂM DỊCH VỤ DÂN SỐ',
    'assertion_title': 'Đặc Trưng 5: Dị Biệt Sâu Sắc Theo Giới Tính Và Nhóm Tuổi Vòng Đời',
    'primary_claim': 'Mỗi nhóm tuổi và mỗi giới tính có các đặc tính sinh học, tâm lý và nhu cầu can thiệp dân số hoàn '
                     'toàn chuyên biệt.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [
        {
            'title': 'Trẻ Vị Thành Niên & Thanh Niên',
            'text': 'Tư vấn sức khỏe sinh sản, tình dục an toàn, giáo dục giới tính học đường và ngừa mang thai ngoài ý muốn.',
            'icon': 'heart'
        },
        {
            'title': 'Nam & Nữ Độ Tuổi Sinh Đẻ',
            'text': 'Khám tiền hôn nhân, áp dụng biện pháp tránh thai hiện đại, tầm soát ung thư phụ khoa và sàng lọc sơ sinh.',
            'icon': 'shield'
        },
        {
            'title': 'Người Cao Tuổi (Nam & Nữ)',
            'text': 'Khám sức khỏe định kỳ, quản lý các bệnh mạn tính không lây và phát huy mô hình CLB Liên thế hệ tự giúp nhau.',
            'icon': 'activity'
        }
    ],
    'matrix_data': { 'axis_x': 'Độ Tuổi (Trẻ Vị Thành Niên → Người Cao Tuổi)',
                     'axis_y': 'Giới Tính (Nam Giới ↔ Nữ Giới)',
                     'quadrants': [ { 'title': 'NỮ GIỚI VTN & THANH NIÊN',
                                      'desc': 'Nhu cầu tư vấn dậy thì, tình dục an toàn, tránh thai khẩn cấp và ngừa '
                                              'viêm nhiễm phụ khoa.',
                                      'highlight': False},
                                    { 'title': 'NAM GIỚI TRƯỚC KẾT HÔN',
                                      'desc': 'Khám sức khỏe sinh sản nam, xét nghiệm tinh dịch đồ, phòng bệnh lây '
                                              'truyền qua đường tình dục.',
                                      'highlight': True},
                                    { 'title': 'NỮ GIỚI ĐỘ TUỔI SINH ĐẺ',
                                      'desc': 'Áp dụng biện pháp tránh thai dài hạn, tầm soát ung thư cổ tử cung và '
                                              'sàng lọc trước sinh.',
                                      'highlight': False},
                                    { 'title': 'NGƯỜI CAO TUỔI (NAM & NỮ)',
                                      'desc': 'Chăm sóc các bệnh mạn tính không lây, phục hồi chức năng và tư vấn tâm '
                                              'lý tuổi già.',
                                      'highlight': False}]},
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tiếp cận Dân số học theo vòng đời con người',
    'illustration': 'bai1/bai1_slide_23_cultural_sensitivity.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_24',
    'role': 'CONTENT',
    'section': '3. PHÂN LOẠI DỊCH VỤ DÂN SỐ',
    'assertion_title': '3 Trục Tiếp Cận Phân Loại Dịch Vụ Dân Số Toàn Diện',
    'primary_claim': 'Hệ thống dịch vụ dân số được quản lý và vận hành thông qua 3 khung phân loại chiến lược chuẩn '
                     'mực.',
    'visual_job': 'FRAMEWORK_ICEBERG_MODEL',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Trục 1: Theo Nội Dung Chuyên Môn',
                 'text': 'Phân chia theo các quá trình dân số cốt lõi: KHHGĐ, SKSS vị thành niên, tiền hôn nhân, sàng '
                         'lọc trước sinh/sơ sinh và người cao tuổi.',
                 'icon': 'layers'},
               { 'title': 'Trục 2: Theo Chế Độ Chi Trả',
                 'text': 'Phân chia theo cơ chế tài chính: Miễn phí hoàn toàn, miễn phí có hỗ trợ, tiếp thị xã hội giá '
                         'rẻ và dịch vụ thu phí thị trường.',
                 'icon': 'calculator'},
               { 'title': 'Trục 3: Theo Chủ Sở Hữu Cung Cấp',
                 'text': 'Phân chia theo nguồn gốc pháp nhân: Hệ thống công lập nhà nước, cơ sở y tế tư nhân và các tổ '
                         'chức quốc tế/phi chính phủ.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Khung Quản lý Dịch vụ Dân số Quốc gia',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_25',
    'role': 'CONTENT',
    'section': '3.1. PHÂN LOẠI THEO NỘI DUNG',
    'assertion_title': '5 Trụ Cột Dịch Vụ Dân Số Trọng Tâm Của Chính Sách Hiện Hành',
    'primary_claim': 'Chính sách dân số hiện nay tập trung nguồn lực vào 5 nhóm dịch vụ mang tính bước ngoặt cải thiện '
                     'chất lượng giống nòi.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': '1. Tiền Hôn Nhân',
                 'text': 'Tư vấn và khám sức khỏe trước khi kết hôn, phát hiện sớm các bệnh di truyền và chuẩn bị tâm '
                         'lý sinh sản.',
                 'icon': 'users'},
               { 'title': '2. KHHGĐ Bền Vững',
                 'text': 'Cung cấp đa dạng các biện pháp tránh thai hiện đại, giảm thiểu tối đa tình trạng mang thai '
                         'ngoài ý muốn.',
                 'icon': 'shield'},
               { 'title': '3. VTN & Thanh Niên',
                 'text': 'Chăm sóc sức khỏe sinh sản, giáo dục giới tính toàn diện và bảo vệ thanh thiếu niên khỏi các '
                         'nguy cơ xã hội.',
                 'icon': 'award'},
               { 'title': '4. Trước Sinh & Sơ Sinh',
                 'text': 'Tầm soát, chẩn đoán, điều trị sớm bệnh tật bẩm sinh nhằm hạ thấp tỷ lệ tàn tật và nâng cao '
                         'tầm vóc giống nòi.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Nghị quyết 21-NQ/TW về công tác dân số trong tình hình mới',
    'illustration': 'bai1/bai1_slide_25_community_mobilization.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_26',
    'role': 'CONTENT',
    'section': '3.1. PHÂN LOẠI THEO NỘI DUNG',
    'assertion_title': 'Trụ Cột 1: Dịch Vụ Tư Vấn Và Khám Sức Khỏe Trước Khi Kết Hôn',
    'primary_claim': 'Can thiệp nền tảng đầu tiên trong chuỗi bảo vệ sức khỏe gia đình, giúp các cặp đôi bước vào hôn '
                     'nhân vững vàng.',
    'visual_job': 'FRAMEWORK_HUB_SPOKE',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tư Vấn Y Tế & Di Truyền',
                 'text': 'Đánh giá phả hệ, phân tích nguy cơ đồng hợp tử bệnh tan máu bẩm sinh (Thalassemia) và các '
                         'rối loạn nhiễm sắc thể.',
                 'icon': 'book-open'},
               { 'title': 'Khám Lâm Sàng Cơ Quan Sinh Sản',
                 'text': 'Kiểm tra tổng thể chức năng sinh dục, phát hiện các dị tật giải phẫu hoặc viêm nhiễm để điều '
                         'trị kịp thời.',
                 'icon': 'activity'},
               { 'title': 'Xét Nghiệm Tầm Soát Bệnh STIs',
                 'text': 'Sàng lọc HIV, viêm gan B, giang mai nhằm áp dụng các biện pháp dự phòng lây truyền sang bạn '
                         'đời và con cái.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Thông tư số 30/2023/TT-BYT hướng dẫn khám tiền hôn nhân',
    'v91_compliant': True,
    'hub_data': { 'hub': 'GÓI DỊCH VỤ\nTIỀN HÔN NHÂN',
                  'spokes': [ { 'title': 'Tư Vấn Di Truyền',
                                'desc': 'Tầm soát bệnh tan máu Thalassemia và bất thường nhiễm sắc thể'},
                              { 'title': 'Khám Lâm Sàng',
                                'desc': 'Kiểm tra chức năng sinh dục và phát hiện dị tật giải phẫu'},
                              { 'title': 'Tầm Soát STIs',
                                'desc': 'Xét nghiệm HIV, viêm gan B, giang mai bảo vệ bạn đời'},
                              { 'title': 'Kế Hoạch Sinh Con',
                                'desc': 'Chuẩn bị tâm lý gia đình và dinh dưỡng trước mang thai'}]}},
  { 'slide_id': 'SLIDE_27',
    'role': 'CONTENT',
    'section': '3.1. PHÂN LOẠI THEO NỘI DUNG',
    'assertion_title': 'Trụ Cột 2: Dịch Vụ Kế Hoạch Hóa Gia Đình Trong Bối Cảnh Mới',
    'primary_claim': 'Chuyển trọng tâm từ giảm sinh đơn thuần sang bảo đảm quyền sinh sản, duy trì mức sinh thay thế '
                     'và phòng tránh vô sinh.',
    'visual_job': 'CONTAINER_BENTO_COMPLEX',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Đa Dạng Hóa Biện Pháp Hiện Đại',
                 'text': 'Cung cấp đầy đủ vòng tránh thai (DCTC), que cấy, thuốc tiêm, viên uống kết hợp và bao cao su '
                         'đạt chuẩn.',
                 'icon': 'layers'},
               { 'title': 'Tư Vấn Tự Nguyện Có Hiểu Biết',
                 'text': 'Khách hàng được giải thích rõ ràng về cơ chế, ưu điểm, tác dụng phụ và tự mình lựa chọn biện '
                         'pháp phù hợp nhất.',
                 'icon': 'users'},
               { 'title': 'Quản Lý An Toàn Sau Thủ Thuật',
                 'text': 'Theo dõi chặt chẽ, tái khám định kỳ và xử trí kịp thời các tác dụng phụ nhẹ để duy trì sự an '
                         'tâm cho người dùng.',
                 'icon': 'shield'},
               { 'title': 'Ngăn Ngừa Nạo Phá Thai Nguy Cơ',
                 'text': 'Hạ thấp tỷ lệ nạo phá thai, đặc biệt ở lứa tuổi thanh niên, bảo toàn khả năng sinh sản lâu '
                         'dài cho phụ nữ.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chiến lược Dân số Việt Nam đến năm 2030',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_28',
    'role': 'CONTENT',
    'section': '3.1. PHÂN LOẠI THEO NỘI DUNG',
    'assertion_title': 'Trụ Cột 3: Chăm Sóc Sức Khỏe Sinh Sản Vị Thành Niên & Thanh Niên',
    'primary_claim': 'Bảo vệ nhóm dân số tương lai trước các rủi ro quan hệ tình dục sớm, mang thai ngoài ý muốn và '
                     'bạo lực giới.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Mô Hình Thân Thiện Với Giới Trẻ',
                 'text': 'Thiết lập phòng khám và góc tư vấn thân thiện, bảo đảm sự riêng tư tuyệt đối, thái độ cởi mở '
                         'và không phán xét.',
                 'icon': 'award'},
               { 'title': 'Giáo Dục Kỹ Năng Sống & Giới Tính',
                 'text': 'Cung cấp kiến thức về thay đổi cơ thể tuổi dậy thì, kỹ năng từ chối, tình dục an toàn và '
                         'phòng ngừa xâm hại.',
                 'icon': 'book-open'},
               { 'title': 'Lồng Ghép Hệ Thống Học Đường',
                 'text': 'Phối hợp ngành giáo dục đưa nội dung SKSS vào chương trình ngoại khóa tại các trường trung '
                         'học và đại học.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Đề án Chăm sóc SKSS Vị thành niên, Thanh niên',
    'illustration': 'bai1/bai1_slide_28_payment_health_insurance.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_29',
    'role': 'CONTENT',
    'section': '3.1. PHÂN LOẠI THEO NỘI DUNG',
    'assertion_title': 'Trụ Cột 4: Tầm Soát, Chẩn Đoán Trước Sinh Và Sơ Sinh Toàn Diện',
    'primary_claim': 'Chương trình can thiệp kỹ thuật cao nhằm phát hiện sớm các dị tật bẩm sinh có thể điều trị hoặc '
                     'phòng ngừa được.',
    'visual_job': 'CONTAINER_PILLAR_4_COLUMNS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Sàng Lọc Trước Sinh (Prenatal Screening)',
                 'text': 'Siêu âm hình thái thai nhi đo độ mờ da gáy (quý I), xét nghiệm sinh hóa Double test, Triple '
                         'test hoặc NIPT phát hiện hội chứng Down, Edwards, Patau.',
                 'icon': 'activity'},
               { 'title': 'Sàng Lọc Sơ Sinh (Newborn Screening)',
                 'text': 'Lấy mẫu máu gót chân trẻ sơ sinh sau 48 giờ để xét nghiệm thiếu men G6PD, suy giáp bẩm sinh, '
                         'tăng sản thượng thận bẩm sinh và khiếm thính.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chương trình Mở rộng Tầm soát Trước sinh và Sơ sinh Quốc gia',
    'v91_compliant': True,
    'pillars': [ { 'num': 'TRỤ CỘT 01',
                   'title': 'Tiền Hôn Nhân',
                   'desc': 'Tư vấn và khám sức khỏe trước kết hôn, phát hiện sớm nguy cơ bệnh di truyền.',
                   'kpi': 'Phủ 90%'},
                 { 'num': 'TRỤ CỘT 02',
                   'title': 'KHHGĐ Bền Vững',
                   'desc': 'Cung cấp đa dạng biện pháp tránh thai hiện đại, giảm mang thai ngoài ý muốn.',
                   'kpi': 'TFR 2.1'},
                 { 'num': 'TRỤ CỘT 03',
                   'title': 'Trước & Sơ Sinh',
                   'desc': 'Tầm soát dị tật thai nhi và lấy máu gót chân phát hiện 5 bệnh bẩm sinh.',
                   'kpi': 'Sơ sinh 90%'},
                 { 'num': 'TRỤ CỘT 04',
                   'title': 'Chăm Sóc Người Cao Tuổi',
                   'desc': 'Quản lý bệnh mạn tính không lây và phát huy mô hình CLB Liên thế hệ.',
                   'kpi': 'Hồ sơ 100%'}]},
  { 'slide_id': 'SLIDE_30',
    'role': 'CONTENT',
    'section': '3.1. PHÂN LOẠI THEO NỘI DUNG',
    'assertion_title': 'Trụ Cột 5: Chăm Sóc Sức Khỏe Người Cao Tuổi Thích Ứng Già Hóa',
    'primary_claim': 'Chủ động chuẩn bị mạng lưới an sinh và y tế khi Việt Nam là một trong những quốc gia có tốc độ '
                     'già hóa nhanh nhất thế giới.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Khám Định Kỳ & Hồ Sơ Điện Tử',
                 'text': 'Lập hồ sơ sức khỏe điện tử theo dõi huyết áp, đái tháo đường, tim mạch tại trạm y tế cơ sở.',
                 'icon': 'activity'},
               { 'title': 'Chăm Sóc Dài Hạn Tại Cộng Đồng',
                 'text': 'Đào tạo người chăm sóc chuyên nghiệp và hỗ trợ gia đình chăm sóc người cao tuổi bị suy giảm '
                         'chức năng.',
                 'icon': 'users'},
               { 'title': 'Mạng Lưới Câu Lạc Bộ Liên Thế Hệ',
                 'text': 'Phát huy mô hình CLB Liên thế hệ tự giúp nhau, kết hợp chăm sóc sức khỏe với hỗ trợ sinh kế '
                         'và tinh thần.',
                 'icon': 'award'},
               { 'title': 'Thích Ứng Chủ Động & Già Hóa Khỏe',
                 'text': 'Khuyến khích lối sống vận động, dinh dưỡng hợp lý để người cao tuổi tiếp tục cống hiến cho '
                         'xã hội.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chương trình Chăm sóc Sức khỏe Người cao tuổi đến năm 2030',
    'illustration': 'bai1/bai1_slide_30_public_private_facilities.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_31',
    'role': 'CONTENT',
    'section': '3.2. PHÂN LOẠI THEO CHẾ ĐỘ CUNG CẤP',
    'assertion_title': '4 Hình Thức Cung Cấp Theo Cơ Chế Tài Chính Và Trợ Cấp',
    'primary_claim': 'Chuyển dịch linh hoạt từ bao cấp toàn diện sang đa dạng hóa nguồn tài chính kết hợp thị trường '
                     'và an sinh xã hội.',
    'visual_job': 'PROCESS_ASCENDING_STAIRS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Miễn Phí Hoàn Toàn',
                 'text': 'Ngân sách nhà nước đài thọ 100%, áp dụng cho đối tượng chính sách, người nghèo, vùng đồng '
                         'bào DTTS.',
                 'icon': 'shield'},
               { 'title': '2. Miễn Phí Có Hỗ Trợ',
                 'text': 'Cung cấp miễn phí kèm hỗ trợ kinh phí đi lại, ăn ở hoặc quà khuyến khích nhằm thúc đẩy đối '
                         'tượng tham gia.',
                 'icon': 'award'},
               { 'title': '3. Tiếp Thị Xã Hội (Giá Rẻ)',
                 'text': 'Nhà nước trợ giá một phần phương tiện tránh thai, người dân đóng góp một khoản chi phí nhỏ '
                         'mang tính trách nhiệm.',
                 'icon': 'calculator'},
               { 'title': '4. Thu Phí Thị Trường',
                 'text': 'Vận hành hoàn toàn theo quy luật thị trường, đáp ứng nhu cầu dịch vụ chất lượng cao, tiện '
                         'ích và theo yêu cầu.',
                 'icon': 'trending-up'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Cơ chế Tài chính Y tế & Dân số Việt Nam',
    'v91_compliant': True,
    'process_data': { 'stairs': [ { 'level': 'BẬC 1',
                                    'kpi': '100%',
                                    'title': 'Miễn Phí Hoàn Toàn',
                                    'desc': 'Ngân sách đài thọ trọn gói cho người nghèo, vùng đồng bào DTTS.'},
                                  { 'level': 'BẬC 2',
                                    'kpi': 'Hỗ Trợ',
                                    'title': 'Miễn Phí Có Hỗ Trợ',
                                    'desc': 'Cung cấp miễn phí kèm kinh phí đi lại và bồi dưỡng đối tượng tham gia.'},
                                  { 'level': 'BẬC 3',
                                    'kpi': 'Trợ Giá',
                                    'title': 'Tiếp Thị Xã Hội',
                                    'desc': 'Bán phương tiện tránh thai giá rẻ có trợ cấp, xây dựng ý thức trách '
                                            'nhiệm.'},
                                  { 'level': 'BẬC 4',
                                    'kpi': 'Thị Trường',
                                    'title': 'Thu Phí Dịch Vụ',
                                    'desc': 'Vận hành theo nhu cầu dịch vụ chất lượng cao, tự chi trả trọn gói.'}]}},
  { 'slide_id': 'SLIDE_32',
    'role': 'CONTENT',
    'section': '3.2. PHÂN LOẠI THEO CHẾ ĐỘ CUNG CẤP',
    'assertion_title': 'Phân Tích Ưu Điểm & Thách Thức Của Mô Hình Miễn Phí',
    'primary_claim': 'Dịch vụ miễn phí bảo đảm công bằng tiếp cận nhưng tạo áp lực lớn lên nguồn ngân sách nhà nước.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Mặt Thuận Lợi & Ý Nghĩa Xã Hội',
                 'text': 'Bảo đảm mọi người dân dù nghèo nhất cũng được tiếp cận các can thiệp dân số thiết yếu; nhanh '
                         'chóng mở rộng tỷ lệ bao phủ chính sách.',
                 'icon': 'award'},
               { 'title': 'Thách Thức Vận Hành & Bền Vững',
                 'text': 'Tâm lý ỷ lại vào bao cấp; nguồn lực ngân sách có hạn dễ dẫn đến thiếu hụt vật tư; người dân '
                         'đôi khi hoài nghi về chất lượng miễn phí.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tài liệu đào tạo chuẩn hóa chuyên đề',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_33',
    'role': 'CONTENT',
    'section': '3.2. PHÂN LOẠI THEO CHẾ ĐỘ CUNG CẤP',
    'assertion_title': 'Tiếp Thị Xã Hội - Cầu Nối Giữa Bao Cấp Và Cơ Chế Thị Trường',
    'primary_claim': 'Mô hình tiếp thị xã hội bán sản phẩm dân số với giá trợ cấp nhằm xây dựng ý thức trách nhiệm tự '
                     'chi trả của người dân.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Trợ Giá Một Phần',
                 'text': 'Nhà nước hoặc các tổ chức quốc tế tài trợ một phần chi phí sản xuất và nhập khẩu để giá bán '
                         'phù hợp túi tiền số đông.',
                 'icon': 'calculator'},
               { 'title': 'Thương Hiệu Chuyên Nghiệp',
                 'text': 'Sản phẩm (như bao cao su Night Happy, viên uống tránh thai New Choice) được đóng gói đẹp, '
                         'quảng bá văn minh.',
                 'icon': 'award'},
               { 'title': 'Tạo Nguồn Lực Tái Đầu Tư',
                 'text': 'Khoản thu từ tiếp thị xã hội được trích lại một phần bồi dưỡng mạng lưới cộng tác viên và '
                         'duy trì chuỗi cung ứng.',
                 'icon': 'trending-up'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Đề án Tiếp thị Xã hội Phương tiện Tránh thai',
    'illustration': 'bai1/bai1_slide_33_family_planning_care.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_34',
    'role': 'CONTENT',
    'section': '3.3. PHÂN LOẠI THEO CHỦ SỞ HỮU',
    'assertion_title': '3 Khối Chủ Thể Cung Cấp Dịch Vụ Dân Số Đang Vận Hành',
    'primary_claim': 'Cơ cấu hệ thống gồm mạng lưới y tế công lập giữ vai trò trụ cột, kết hợp y tế ngoài công lập và tổ chức xã hội hóa.',
    'visual_job': 'CONTAINER_PILLAR_3_COLUMNS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Khối Y Tế Công Lập Nhà Nước',
                 'text': 'Mạng lưới nòng cốt từ Trung ương đến trạm y tế xã, TTYT huyện và BV Phụ sản - Nhi; bảo đảm an sinh và cung cấp miễn phí cho diện chính sách.',
                 'icon': 'shield',
                 'badge': 'TRỤ CỘT AN SINH'},
               { 'title': '2. Khối Y Tế Ngoài Công Lập',
                 'text': 'Bệnh viện tư thục, phòng khám chuyên khoa và nhà thuốc; cung ứng dịch vụ kỹ thuật cao, đáp ứng linh hoạt nhu cầu tự chi trả của người dân.',
                 'icon': 'trending-up',
                 'badge': 'THEO YÊU CẦU'},
               { 'title': '3. Khối TTXH & Tổ Chức Phi Chính Phủ',
                 'text': 'Mạng lưới VINAFPA, DKT International, Marie Stopes; cung cấp sản phẩm tránh thai trợ giá và truyền thông thay đổi hành vi tại cộng đồng.',
                 'icon': 'globe',
                 'badge': 'TRỢ GIÁ CỘNG ĐỒNG'}],
    'pillars': [ { 'title': '1. Khối Y Tế Công Lập',
                   'sub': 'Mạng lưới nòng cốt từ Trung ương đến trạm y tế xã, TTYT huyện và BV Phụ sản - Nhi; bảo đảm an sinh và cung cấp miễn phí cho diện chính sách.',
                   'kpi': 'Trụ Cột An Sinh'},
                 { 'title': '2. Khối Ngoài Công Lập',
                   'sub': 'Bệnh viện tư thục, phòng khám chuyên khoa và nhà thuốc; cung ứng dịch vụ kỹ thuật cao, đáp ứng linh hoạt nhu cầu tự chi trả của người dân.',
                   'kpi': 'Dịch Vụ Theo Yêu Cầu'},
                 { 'title': '3. Khối TTXH & Tổ Chức NGO',
                   'sub': 'Mạng lưới VINAFPA, DKT International, Marie Stopes; cung cấp sản phẩm tránh thai trợ giá và truyền thông thay đổi hành vi tại cộng đồng.',
                   'kpi': 'Trợ Giá Cộng Đồng'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Báo cáo Thực trạng Hệ thống Dịch vụ Y tế Dân số',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_35',
    'role': 'CONTENT',
    'section': '3.3. PHÂN LOẠI THEO CHỦ SỞ HỮU',
    'assertion_title': 'Vai Trò Cốt Lõi Của Hệ Thống Y Tế Dân Số Công Lập',
    'primary_claim': 'Khối công lập bảo đảm tính công bằng, bao phủ phổ cập và thực hiện các chương trình y tế công '
                     'cộng phi lợi nhuận.',
    'visual_job': 'CONTAINER_BENTO_COMPLEX',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Phân Tuyến Kỹ Thuật Chặt Chẽ',
                 'text': 'Tuyến xã quản lý địa bàn, tư vấn ban đầu; tuyến huyện xử trí kỹ thuật phổ thông; tuyến tỉnh '
                         'và trung ương xử trí chuyên sâu.',
                 'icon': 'layers'},
               { 'title': 'Thực Thi Các Mục Tiêu An Sinh',
                 'text': 'Là địa chỉ tin cậy duy nhất tại các địa bàn vùng sâu, vùng xa, nơi y tế tư nhân không có '
                         'động lực đầu tư vì không có lợi nhuận.',
                 'icon': 'shield'},
               { 'title': 'Quản Lý Dữ Liệu & Hộ Tịch',
                 'text': 'Thu thập, tổng hợp báo cáo biến động dân số, tỷ số giới tính khi sinh phục vụ công tác điều '
                         'hành vĩ mô của nhà nước.',
                 'icon': 'calculator'},
               { 'title': 'Chuẩn Hóa Kỹ Thuật Quốc Gia',
                 'text': 'Xây dựng phác đồ, giám sát chuyên môn và cấp chứng chỉ hành nghề cho toàn bộ các cơ sở trên '
                         'địa bàn.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Nghị định quy định chức năng nhiệm vụ y tế cơ sở',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_36',
    'role': 'CONTENT',
    'section': '3.3. PHÂN LOẠI THEO CHỦ SỞ HỮU',
    'assertion_title': 'Tiềm Năng & Lợi Thế Cạnh Tranh Của Khối Y Tế Tư Nhân',
    'primary_claim': 'Y tế tư nhân phát huy thế mạnh về thời gian linh hoạt, trang thiết bị hiện đại và thái độ chăm '
                     'sóc khách hàng chuyên nghiệp.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Linh Hoạt Về Thời Gian Tiếp Nhận',
                 'text': 'Mở cửa ngoài giờ hành chính và các ngày nghỉ cuối tuần, rất thuận tiện cho công nhân, nhân '
                         'viên văn phòng bận rộn.',
                 'icon': 'activity'},
               { 'title': 'Đầu Tư Thiết Bị Công Nghệ Mới',
                 'text': 'Nhanh nhạy đầu tư máy siêu âm 4D/5D, máy xét nghiệm hiện đại và liên kết với các trung tâm '
                         'di truyền quốc tế.',
                 'icon': 'zap'},
               { 'title': 'Chất Lượng Chăm Sóc Khách Hàng',
                 'text': 'Không gian phòng chờ khang trang, thủ tục nhanh gọn, tư vấn chu đáo tạo tâm lý thoải mái, '
                         'giảm e ngại cho người bệnh.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Khảo sát Đánh giá Sự hài lòng của Người bệnh đối với Y tế Tư nhân',
    'illustration': 'bai1/bai1_slide_36_elderly_community_care.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_37',
    'role': 'CONTENT',
    'section': '4. CHIẾN LƯỢC DÂN SỐ ĐẾN 2030',
    'assertion_title': 'Bước Chuyển Chiến Lược: Từ KHHGĐ Sang Dân Số Và Phát Triển',
    'primary_claim': 'Nghị quyết số 21-NQ/TW đánh dấu bước ngoặt lịch sử mở rộng phạm vi chính sách sang chất lượng, '
                     'cơ cấu và già hóa.',
    'visual_job': 'CONTAINER_KPI_STAT_DELTA',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Giai Đoạn Trước: Trọng Tâm KHHGĐ',
                 'text': 'Tập trung cao độ vào mục tiêu giảm sinh, giảm tốc độ tăng dân số, chỉ tiêu gắn liền với số '
                         'cặp vợ chồng áp dụng BPTT.',
                 'icon': 'shield'},
               { 'title': 'Giai Đoạn Hiện Nay: Dân Số & Phát Triển',
                 'text': 'Duy trì mức sinh thay thế, đưa tỷ số giới tính khi sinh về mức tự nhiên, tận dụng cơ cấu dân '
                         'số vàng và nâng cao chất lượng giống nòi.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Nghị quyết 21-NQ/TW của Ban Chấp hành Trung ương Đảng',
    'v91_compliant': True,
    'kpi_stats': [ { 'metric': '2.10',
                     'delta': 'Duy trì vững chắc',
                     'is_positive': True,
                     'label': 'Mức Sinh Thay Thế (TFR)',
                     'desc': 'Chuyển trọng tâm từ giảm sinh sang ổn định quy mô, duy trì mức sinh thay thế 2,1 con trên toàn quốc.'},
                   { 'metric': '<109',
                     'delta': '-4.2 điểm vs 2020',
                     'is_positive': True,
                     'label': 'Tỷ Số Giới Tính (SRB)',
                     'desc': 'Đưa tỷ số giới tính khi sinh về mức cân bằng tự nhiên, ngăn chặn triệt để lựa chọn giới tính thai nhi.'},
                   { 'metric': '70%',
                     'delta': '+25% độ phủ',
                     'is_positive': True,
                     'label': 'Sàng Lọc Trước Sinh',
                     'desc': 'Tầm soát tối thiểu 4 bệnh tật di truyền phổ biến như Thalassemia, Hội chứng Down cho thai phụ.'},
                   { 'metric': '90%',
                     'delta': '+30% bao phủ',
                     'is_positive': True,
                     'label': 'Sàng Lọc Sơ Sinh',
                     'desc': 'Lấy mẫu máu gót chân tầm soát 5 bệnh rối loạn chuyển hóa và thiếu men G6PD ở trẻ sơ sinh.'}]},
  { 'slide_id': 'SLIDE_38',
    'role': 'CONTENT',
    'section': '4. CHIẾN LƯỢC DÂN SỐ ĐẾN 2030',
    'assertion_title': 'Các Mục Tiêu Định Lượng Then Chốt Của Chiến Lược Dân Số 2030',
    'primary_claim': 'Chính phủ đặt ra các chỉ tiêu cụ thể về tỷ lệ bao phủ dịch vụ dân số chất lượng cao trên toàn '
                     'quốc.',
    'visual_job': 'CHART_AND_INSIGHTS',
    'visual_anchor': 'CHART_AND_INSIGHTS',
    'atoms': [ { 'title': 'Duy Trì Mức Sinh Thay Thế',
                 'text': 'Tổng tỷ suất sinh (TFR) duy trì vững chắc ở mức 2,1 con/phụ nữ trên phạm vi cả nước.',
                 'icon': 'target'},
               { 'title': 'Cân Bằng Giới Tính Khi Sinh',
                 'text': 'Đưa tỷ số giới tính khi sinh (SRB) về mức cân bằng tự nhiên dưới 109 bé trai / 100 bé gái '
                         'sinh sống.',
                 'icon': 'shield'},
               { 'title': 'Tầm Soát Bệnh Tật Bẩm Sinh',
                 'text': '70% phụ nữ mang thai được sàng lọc 4 bệnh trước sinh; 90% trẻ sơ sinh được sàng lọc 5 bệnh '
                         'bẩm sinh.',
                 'icon': 'activity'},
               { 'title': 'Khám Sức Khỏe Tiền Hôn Nhân',
                 'text': '90% nam, nữ thanh niên được tư vấn, khám sức khỏe trước khi kết hôn; giảm mạnh hôn nhân cận '
                         'huyết.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quyết định số 1679/QĐ-TTg phê duyệt Chiến lược Dân số đến năm 2030',
    'chart_type': 'LINE_MARKERS',
    'chart_file': 'chart_hdi_dimensions_dark.png',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_39',
    'role': 'CONTENT',
    'section': 'THÁCH THỨC & GIẢI PHÁP',
    'assertion_title': 'Thách Thức Trong Cơ Chế Chuyển Đổi Nguồn Lực Tài Chính',
    'primary_claim': 'Cắt giảm bao cấp viện trợ quốc tế đòi hỏi các địa phương phải khẩn trương đẩy mạnh cơ chế xã hội '
                     'hóa dịch vụ.',
    'visual_job': 'PROCESS_SWIMLANE_TRACKS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Cắt Giảm Viện Trợ Quốc Tế',
                 'text': 'Khi Việt Nam trở thành quốc gia thu nhập trung bình, các tổ chức quốc tế đã dừng cung cấp '
                         'miễn phí phương tiện tránh thai.',
                 'icon': 'calculator'},
               { 'title': 'Áp Lực Ngân Sách Địa Phương',
                 'text': 'Ngân sách cấp tỉnh và huyện chưa kịp thời bố trí đủ nguồn kinh phí đối ứng mua sắm vật tư và '
                         'thù lao cộng tác viên.',
                 'icon': 'shield'},
               { 'title': 'Tâm Lý Trông Chờ Bao Cấp',
                 'text': 'Người dân ở nhiều nơi vẫn quen chờ đợi các đợt phát thuốc miễn phí, chưa sẵn sàng chi trả '
                         'tiền mua biện pháp tránh thai.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Báo cáo Tài chính Bền vững cho Chương trình Dân số',
    'v91_compliant': True,
    'process_data': { 'lanes': [ { 'dept': 'TRUNG ƯƠNG',
                                   'task': 'Ban hành chính sách xã hội hóa, phân bổ vốn mồi và tiêu chuẩn kỹ thuật '
                                           'quốc gia.'},
                                 { 'dept': 'TỈNH & HUYỆN',
                                   'task': 'Bố trí ngân sách đối ứng, tổ chức đấu thầu mua sắm vật tư và thanh tra '
                                           'giám sát.'},
                                 { 'dept': 'TRẠM Y TẾ XÃ',
                                   'task': 'Trực tiếp cung ứng dịch vụ, quản lý cộng tác viên và thực hiện tiếp thị xã '
                                           'hội.'},
                                 { 'dept': 'NGƯỜI DÂN',
                                   'task': 'Xóa bỏ tâm lý trông chờ bao cấp, chủ động tham gia BHYT và chi trả trách '
                                           'nhiệm.'}]}},
  { 'slide_id': 'SLIDE_40',
    'role': 'CONTENT',
    'section': 'THÁCH THỨC & GIẢI PHÁP',
    'assertion_title': 'Đẩy Mạnh Hợp Tác Công - Tư (PPP) Trong Cung Cấp Dịch Vụ',
    'primary_claim': 'Gắn kết cơ sở công lập với mạng lưới tư nhân để mở rộng độ phủ và nâng cao chất lượng phục vụ '
                     'nhân dân.',
    'visual_job': 'CONTAINER_BENTO_COMPLEX',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Liên Doanh Đặt Trang Thiết Bị',
                 'text': 'Doanh nghiệp tư nhân đầu tư máy siêu âm, máy xét nghiệm hiện đại đặt tại trạm y tế hoặc '
                         'trung tâm y tế huyện.',
                 'icon': 'zap'},
               { 'title': 'Hợp Đồng Đặt Hàng Dịch Vụ Công',
                 'text': 'Ngân sách nhà nước ký hợp đồng chi trả cho các cơ sở tư nhân thực hiện gói dịch vụ sàng lọc '
                         'cho người nghèo.',
                 'icon': 'calculator'},
               { 'title': 'Chia Sẻ Hạ Tầng Đào Tạo',
                 'text': 'Bệnh viện tuyến trên hỗ trợ đào tạo chuyển giao kỹ thuật cho bác sĩ phòng khám tư nhân trên '
                         'địa bàn.',
                 'icon': 'book-open'},
               { 'title': 'Kiểm Soát Chuẩn Mực Chung',
                 'text': 'Cơ quan quản lý nhà nước ban hành quy chuẩn kỹ thuật và giám sát chất lượng bình đẳng giữa '
                         'công và tư.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Đề án Đổi mới Cơ chế Tài chính Y tế & Dân số',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_41',
    'role': 'CONTENT',
    'section': 'THÁCH THỨC & GIẢI PHÁP',
    'assertion_title': 'Giải Pháp Thu Hẹp Khoảng Trống Tiếp Cận Vùng Khó Khăn',
    'primary_claim': 'Ưu tiên chính sách đặc thù nhằm bảo đảm đồng bào dân tộc thiểu số và vùng sâu, vùng xa không bị '
                     'bỏ lại phía sau.',
    'visual_job': 'ARCH_DATA_LAKEHOUSE_MEDALLION',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Duy Trì Gói Dịch Vụ Miễn Phí 100%',
                 'text': 'Tiếp tục bao cấp toàn bộ phương tiện tránh thai, khám phụ khoa và gói sàng lọc sơ sinh cơ '
                         'bản cho vùng nghèo.',
                 'icon': 'shield'},
               { 'title': 'Đội Dịch Vụ Y Tế Lưu Động',
                 'text': 'Định kỳ điều xe y tế lưu động chở máy móc và kíp bác sĩ lên các bản làng xa xôi để phục vụ '
                         'bà con tại chỗ.',
                 'icon': 'activity'},
               { 'title': 'Phát Huy Ngôn Ngữ Bản Địa',
                 'text': 'Biên soạn tài liệu truyền thông bằng tiếng dân tộc (Mông, Dao, Thái...) và sử dụng cán bộ '
                         'dân số người địa phương.',
                 'icon': 'book-open'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chương trình Phát triển KT-XH Vùng Đồng bào DTTS và Miền núi',
    'summary_strip': 'MÔ HÌNH LIÊN KẾT 3 TUYẾN: CHỈ ĐẠO LƯU ĐỘNG • CUNG ỨNG TRỰC TIẾP • VẬN ĐỘNG TẬN NHÀ',
    'v91_compliant': True,
    'medallion_tiers': [ { 'tier': 'TUYẾN HUYỆN CHỈ ĐẠO',
                           'sub': 'ĐIỀU PHỐI KỸ THUẬT LƯU ĐỘNG',
                           'color': '#0284C7',
                           'bg_tint': '#0B1E3B',
                           'specs': [ '• Đội ngũ: Bác sĩ sản nhi & kíp siêu âm lưu động',
                                      '• Thiết bị: Xe chuyên dụng, máy siêu âm xách tay',
                                      '• Kế hoạch: Tổ chức chiến dịch theo mùa vụ địa phương'],
                           'chip': 'Trách Nhiệm: Chỉ Đạo Toàn Tuyến'},
                         { 'tier': 'TRẠM Y TẾ XÃ CƠ SỞ',
                           'sub': 'CUNG ỨNG DỊCH VỤ TRỰC TIẾP',
                           'color': '#10B981',
                           'bg_tint': '#062E21',
                           'specs': [ '• Thường trực: Y sĩ, nữ hộ sinh trực tiếp tại xã',
                                      '• Chuyên môn: Khám phụ khoa, cấp phát BPTT chuẩn',
                                      '• Truyền thông: Tư vấn bằng tiếng dân tộc bản địa'],
                           'chip': 'Trách Nhiệm: Điểm Cung Cấp Cố Định'},
                         { 'tier': 'Y TẾ THÔN BẢN & CTV',
                           'sub': 'MẠNG LƯỚI CHÂN RẾT HỘ GIA ĐÌNH',
                           'color': '#F59E0B',
                           'bg_tint': '#2E1E05',
                           'specs': [ '• Tiếp cận: Đến từng hộ gia đình, gõ từng cửa bản làng',
                                      '• Giám sát: Nắm bắt biến động phụ nữ mang thai & trẻ sơ sinh',
                                      '• Vận động: Vận động người có uy tín, già làng đi đầu'],
                           'chip': 'Trách Nhiệm: Vận Động Cộng Đồng'}]},
  { 'slide_id': 'SLIDE_42',
    'role': 'CONTENT',
    'section': 'THÁCH THỨC & GIẢI PHÁP',
    'assertion_title': 'Ứng Dụng Công Nghệ Số Hóa Và Chuyển Đổi Số Trong Quản Lý',
    'primary_claim': 'Xây dựng hệ thống thông tin dân số điện tử kết nối liên thông để nâng cao hiệu lực quản lý dịch '
                     'vụ.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Hồ Sơ Sức Khỏe Điện Tử',
                 'text': 'Tích hợp lịch sử sàng lọc trước sinh, sơ sinh, biện pháp tránh thai và theo dõi sức khỏe NCT '
                         'vào mã định danh VNeID.',
                 'icon': 'shield'},
               { 'title': 'Ứng Dụng Đặt Lịch & Tư Vấn Từ Xa',
                 'text': 'Người dân dễ dàng đặt lịch khám tiền hôn nhân, nhận kết quả sàng lọc và được bác sĩ tư vấn '
                         'bảo mật qua App điện thoại.',
                 'icon': 'zap'},
               { 'title': 'Quản Lý Chuỗi Cung Ứng (LMIS)',
                 'text': 'Hệ thống quản lý trực tuyến theo dõi tồn kho phương tiện tránh thai theo thời gian thực, '
                         'chống đứt gãy nguồn cung.',
                 'icon': 'layers'},
               { 'title': 'Phân Tích Dữ Liệu Lớn (Big Data)',
                 'text': 'Cung cấp bản đồ dịch tễ sinh sản và dự báo xu hướng mức sinh phục vụ điều hành chính sách '
                         'tức thời.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Đề án Chuyển đổi số ngành Y tế và Dân số',
    'illustration': 'bai1/bai1_slide_42_commune_health_station.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_43',
    'role': 'CONTENT',
    'section': 'CÂU HỎI LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Thảo Luận 1: Vận Dụng 5 Đặc Điểm Dịch Vụ Vào Thực Tiễn Quản Lý',
    'primary_claim': 'Học viên phân tích những khó khăn gặp phải trong công tác quản lý dịch vụ dân số do 5 đặc tính '
                     'bản thể gây ra.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Nội Dung Thảo Luận',
                 'text': 'Hãy chọn một đặc tính (Tính vô hình, Không thể tách rời, Không thể lưu trữ, Không đồng nhất, '
                         'Người dùng tham gia) và nêu ví dụ thực tế.',
                 'icon': 'book-open'},
               { 'title': 'Gợi Ý Giải Pháp Hành Động',
                 'text': 'Đề xuất 3 giải pháp cải tiến quy trình đón tiếp và thực hiện kỹ thuật tại trạm y tế để giảm '
                         'bớt sự không đồng nhất về chất lượng.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Câu hỏi lượng giá cuối bài học - Bài 1',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_44',
    'role': 'CONTENT',
    'section': 'CÂU HỎI LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Thảo Luận 2: Tháo Gỡ Rào Cản Văn Hóa Địa Phương Khi Cung Cấp Dịch Vụ',
    'primary_claim': 'Phân tích tác động của phong tục tập quán dòng họ và đề xuất cách tiếp cận truyền thông thấu cảm '
                     'hiệu quả.',
    'visual_job': 'FRAMEWORK_SWOT_ANALYSIS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Điểm Mạnh (Strengths)',
                 'text': 'Mạng lưới trạm y tế và CTV dân số phủ kín 100% thôn bản, sự đồng thuận chính trị cao.',
                 'icon': 'award'},
               { 'title': 'Điểm Yếu (Weaknesses)',
                 'text': 'Thù lao cho đội ngũ CTV còn thấp, trang thiết bị chuyên sâu tuyến xã còn thiếu và xuống cấp.',
                 'icon': 'shield'},
               { 'title': 'Cơ Hội (Opportunities)',
                 'text': 'Chuyển đổi số liên thông VNeID và cơ chế hợp tác công tư (PPP) mở rộng nguồn vốn xã hội hóa.',
                 'icon': 'zap'},
               { 'title': 'Thách Thức (Threats)',
                 'text': 'Tốc độ già hóa dân số nhanh kỷ lục, tâm lý trông chờ bao cấp và cắt giảm viện trợ quốc tế.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Câu hỏi lượng giá cuối bài học - Bài 1',
    'v91_compliant': True,
    'swot_data': [ { 'letter': 'S',
                     'title': 'ĐIỂM MẠNH (STRENGTHS)',
                     'color': '#10B981',
                     'items': [ 'Mạng lưới trạm y tế và CTV dân số phủ kín 100% thôn bản',
                                'Sự đồng thuận chính trị và chỉ đạo quyết liệt từ cấp ủy chính quyền',
                                'Kinh nghiệm truyền thông chuyển đổi hành vi bền bỉ nhiều năm']},
                   { 'letter': 'W',
                     'title': 'ĐIỂM YẾU (WEAKNESSES)',
                     'color': '#EF4444',
                     'items': [ 'Thù lao cho đội ngũ cộng tác viên thôn bản còn rất khiêm tốn',
                                'Trang thiết bị chuyên sâu tại tuyến xã còn thiếu và xuống cấp',
                                'Kỹ năng tư vấn chuyên sâu của một bộ phận cán bộ còn hạn chế']},
                   { 'letter': 'O',
                     'title': 'CƠ HỘI (OPPORTUNITIES)',
                     'color': '#0284C7',
                     'items': [ 'Chuyển đổi số và ứng dụng VNeID giúp liên thông quản lý dân cư',
                                'Nhu cầu dịch vụ chăm sóc sức khỏe chất lượng cao ngày càng tăng',
                                'Cơ chế hợp tác công tư (PPP) mở ra nguồn vốn xã hội hóa lớn']},
                   { 'letter': 'T',
                     'title': 'THÁCH THỨC (THREATS)',
                     'color': '#F59E0B',
                     'items': [ 'Tốc độ già hóa dân số diễn ra nhanh chưa từng có trong lịch sử',
                                'Tâm lý trông chờ bao cấp và định kiến giới tính khi sinh còn nặng',
                                'Cắt giảm hoàn toàn các nguồn viện trợ quốc tế không hoàn lại']}]},
  { 'slide_id': 'SLIDE_45',
    'role': 'CONTENT',
    'section': 'CÂU HỎI LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Thảo Luận 3: Lựa Chọn Dịch Vụ Trọng Tâm Phù Hợp Với Nguồn Lực Cơ Sở',
    'primary_claim': 'Xác định thứ tự ưu tiên đầu tư trong 5 dịch vụ trọng tâm của Chiến lược 2030 căn cứ theo điều '
                     'kiện thực tế.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Đánh Giá Thực Trạng Địa Bàn',
                 'text': 'Mức sinh và cơ cấu tuổi tại địa phương anh/chị đang thuộc nhóm mức sinh cao, mức sinh thấp '
                         'hay già hóa sâu?',
                 'icon': 'activity'},
               { 'title': 'Xác Định Ưu Tiên Số 1',
                 'text': 'Nên tập trung ngân sách cho sàng lọc trước sinh/sơ sinh hay đẩy mạnh khám tiền hôn nhân và '
                         'CSSK người cao tuổi?',
                 'icon': 'target'},
               { 'title': 'Khả Năng Xã Hội Hóa',
                 'text': 'Người dân địa phương có khả năng chi trả ở mức nào cho các gói dịch vụ tiếp thị xã hội và '
                         'dịch vụ tự nguyện?',
                 'icon': 'calculator'},
               { 'title': 'Cam Kết Hành Động Cụ Thể',
                 'text': 'Xây dựng bản kế hoạch hành động 3 bước nâng cao chất lượng dịch vụ dân số cấp xã trong năm '
                         'tới.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Câu hỏi lượng giá cuối bài học - Bài 1',
    'illustration': 'bai1/bai1_slide_45_health_finance_modern.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_46',
    'role': 'CONTENT',
    'section': 'BÀI TẬP THỰC HÀNH',
    'assertion_title': 'Bài Tập Tình Huống: Thiết Kế Gói Dịch Vụ Dân Số Cấp Cơ Sở',
    'primary_claim': 'Thực hành lập kế hoạch cung cấp gói dịch vụ dân số lồng ghép tại một trạm y tế xã có 5000 dân.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Bước 1: Rà Soát Nhu Cầu',
                 'text': 'Thống kê số cặp vợ chồng mới kết hôn, phụ nữ có thai và người cao tuổi cần chăm sóc trên địa '
                         'bàn.',
                 'icon': 'calculator'},
               { 'title': 'Bước 2: Phân Bổ Nguồn Lực',
                 'text': 'Phối hợp nhân viên y tế trạm, cộng tác viên thôn bản và dự trù số lượng vật tư, que thử, máy '
                         'móc lưu động.',
                 'icon': 'layers'},
               { 'title': 'Bước 3: Tổ Chức Chiến Dịch',
                 'text': 'Truyền thông trước chiến dịch 1 tuần, bố trí phòng khám kín đáo, phân luồng đón tiếp chu đáo '
                         'và lập hồ sơ theo dõi.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tình huống thực hành kỹ năng quản lý dân số',
    'illustration': 'bai1/bai1_slide_46_digital_telemedicine.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_47',
    'role': 'CONTENT',
    'section': 'ĐÚC KẾT CHUYÊN ĐỀ',
    'assertion_title': '5 Thông Điệp Cốt Lõi Khắc Sâu Cho Cán Bộ Làm Công Tác Dân Số',
    'primary_claim': 'Tổng hợp tinh hoa lý luận và nguyên tắc hành động xuyên suốt toàn bộ chuyên đề tổng quan.',
    'visual_job': 'CONTAINER_BENTO_COMPLEX',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Dịch Vụ Là Quá Trình',
                 'text': 'Chất lượng dịch vụ được định đoạt bởi thái độ giao tiếp, sự tận tâm và trải nghiệm của người '
                         'dân trong từng phút tiếp xúc.',
                 'icon': 'activity'},
               { 'title': '2. Khách Hàng Đồng Kiến Tạo',
                 'text': 'Tôn trọng quyền tự quyết của người dân, xây dựng quan hệ bình đẳng và lắng nghe để tạo dựng '
                         'niềm tin bền vững.',
                 'icon': 'users'},
               { 'title': '3. Chuyển Đổi Sang Phát Triển',
                 'text': 'Mở rộng tầm nhìn từ KHHGĐ truyền thống sang nâng cao chất lượng giống nòi, cơ cấu và thích '
                         'ứng già hóa.',
                 'icon': 'trending-up'},
               { 'title': '4. Đa Dạng Hóa Nguồn Lực',
                 'text': 'Kết hợp hài hòa vai trò an sinh của nhà nước với tiềm năng năng động của y tế tư nhân và '
                         'tiếp thị xã hội.',
                 'icon': 'award'}],
    'source_footer': 'Đúc kết chuyên môn bài giảng Tổng quan dịch vụ dân số',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_48',
    'role': 'COVER',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'TỔNG KẾT BÀI 1: TỔNG QUAN VỀ DỊCH VỤ DÂN SỐ',
    'primary_claim': 'Làm chủ kiến thức tổng quan về dịch vụ dân số là chìa khóa để triển khai thành công 5 chuyên đề '
                     'nghiệp vụ chuyên sâu tiếp theo.',
    'visual_job': 'HERO_TITLE',
    'visual_anchor': 'BRAND_SUMMARY',
    'transition': 'fade',
    'transition_duration': 0.65,
    'speaker_notes': 'Cảm ơn quý học viên đã hoàn thành Bài 1. Chúng ta sẽ tiếp tục nghiên cứu chuyên đề Bài 2 về Tư '
                     'vấn, khám sức khỏe trước khi kết hôn.',
    'source_footer': 'Hoàn thành chuyên đề 1: BÀI 1. Tổng quan về dịch vụ dân số.docx',
    'v91_compliant': True}]
