# -*- coding: utf-8 -*-
"""
scripts/course2_data_bai6.py
Exhaustive Deep-Curriculum Slide Blueprints for BÀI 6 (Make Slide Pro V9.1).
30%-50% High-Resolution Visual Illustrations, Native Charts, Zero AI Slop, Zero Watermarks.
"""

from typing import Any, Dict, List


def get_slides_bai_6() -> List[Dict[str, Any]]:
    return [ { 'slide_id': 'SLIDE_01',
    'role': 'COVER',
    'section': 'TỔNG QUAN CHUYÊN ĐỀ',
    'assertion_title': 'BÀI 6: DỊCH VỤ CHĂM SÓC SỨC KHỎE NGƯỜI CAO TUỔI TẠI CỘNG ĐỒNG',
    'primary_claim': 'Khung nghiệp vụ y tế dân số toàn diện về thích ứng già hóa dân số, quản lý bệnh mãn tính tại '
                     'nhà, mô hình câu lạc bộ liên thế hệ và tổ chức mạng lưới chăm sóc dài hạn.',
    'visual_job': 'HERO_TITLE',
    'visual_anchor': 'BRAND_COVER',
    'transition': 'fade',
    'transition_duration': 0.65,
    'illustration': 'illustration_bai_6.jpg',
    'speaker_notes': 'Kính chào quý học viên, hôm nay chúng ta nghiên cứu chuyên đề Bài 6: Dịch vụ chăm sóc sức khỏe '
                     'người cao tuổi tại cộng đồng.',
    'source_footer': 'Tài liệu đào tạo chuẩn hóa: BÀI 6. Dịch vụ chăm sóc sức khỏe người cao tuổi.docx',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_02',
    'role': 'CONTENT',
    'section': 'MỤC TIÊU BÀI HỌC',
    'assertion_title': 'Chuẩn Đầu Ra 5 Khối Năng Lực Cốt Lõi Về Chăm Sóc Sức Khỏe Người Cao Tuổi',
    'primary_claim': 'Trang bị phương pháp luận thích ứng già hóa, kỹ năng chăm sóc thể chất - tinh thần và năng lực '
                     'quản lý chương trình QĐ 1579.',
    'visual_job': 'CONTAINER_BENTO_COMPLEX',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Khái Niệm & Phân Loại',
                 'text': 'Trình bày chuẩn xác khái niệm người cao tuổi (từ đủ 60 tuổi), bản chất dịch vụ cộng đồng và '
                         'phân loại theo chuyên môn y tế / mức độ hỗ trợ.',
                 'icon': 'book-open'},
               { 'title': '2. Khách Hàng & Năng Lực Cung Cấp',
                 'text': 'Phân tích mô hình bệnh tật kép của NCT sống tại gia đình, chuẩn hóa vai trò người nhà, cộng '
                         'tác viên dân số và trạm y tế xã.',
                 'icon': 'users'},
               { 'title': '3. Chăm Sóc Thể Chất & Tinh Thần',
                 'text': 'Làm chủ kỹ thuật chăm sóc bệnh mạn tính, vết loét tỳ đè, phục hồi chức năng, an toàn dùng '
                         'thuốc và liệu pháp chống cô đơn tuổi già.',
                 'icon': 'activity'},
               { 'title': '4. Mô Hình Câu Lạc Bộ Liên Thế Hệ',
                 'text': 'Vận hành hiệu quả mô hình CLB Liên thế hệ tự giúp nhau (ISHC) với 8 mảng hoạt động dựa vào '
                         'tình nguyện viên chăm sóc tại nhà.',
                 'icon': 'heart'},
               { 'title': '5. Quản Lý & Mục Tiêu QĐ 1579/QĐ-TTg',
                 'text': 'Tổ chức triển khai Chương trình Chăm sóc SK NCT đến năm 2030, lập hồ sơ sức khỏe điện tử và '
                         'thực hiện khám định kỳ đa tuyến.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Khung chuẩn đầu ra chuyên đề đào tạo chăm sóc NCT',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_03',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Khái Niệm Người Cao Tuổi: Chuẩn Mực Liên Hợp Quốc & Luật Người Cao Tuổi Việt Nam',
    'primary_claim': 'Luật Người cao tuổi năm 2009 xác định công dân Việt Nam từ đủ 60 tuổi trở lên thuộc diện thụ '
                     'hưởng chính sách.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tiêu Chuẩn Liên Hợp Quốc (UN)',
                 'text': 'Quy định người cao tuổi là những người từ 65 tuổi trở lên; thường áp dụng cho các quốc gia '
                         'phát triển có tuổi thọ bình quân rất cao.',
                 'icon': 'globe'},
               { 'title': 'Quy Định Pháp Luật Việt Nam (Luật 2009)',
                 'text': 'Theo Điều 2 Luật Người cao tuổi năm 2009: Người cao tuổi là công dân Việt Nam từ đủ 60 tuổi '
                         'trở lên; bảo đảm quyền được chăm sóc sức khỏe và phát huy vai trò.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Luật Người cao tuổi năm 2009 & Tài liệu BÀI 6. Mục 1.1',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_04',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Bản Chất Dịch Vụ Chăm Sóc Sức Khỏe Người Cao Tuổi Tại Cộng Đồng',
    'primary_claim': 'Là hệ thống các dịch vụ y tế và an sinh thực hiện ngay tại hộ gia đình hoặc thôn bản nơi người '
                     'cao tuổi sinh sống.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Theo Dõi & Rèn Luyện Thể Chất',
                 'text': 'Kiểm tra huyết áp, đường huyết, hướng dẫn bài tập dưỡng sinh, phòng ngừa các biến chứng suy '
                         'giảm chức năng của tuổi già.',
                 'icon': 'activity'},
               { 'title': 'Quản Lý Bệnh Mạn Tính Ngoại Trú',
                 'text': 'Thực hiện nghiêm ngặt các chỉ định, y lệnh của thầy thuốc trong thời gian điều trị ngoại '
                         'trú: uống thuốc đúng giờ, tiêm truyền, thay băng.',
                 'icon': 'shield-check'},
               { 'title': 'Tâm Lý & Hòa Nhập Xã Hội',
                 'text': 'Tư vấn tinh thần, trò chuyện tháo gỡ cảm giác cô đơn, tạo môi trường giao lưu sinh hoạt văn '
                         'hóa kết nối các thế hệ.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 1.2 - Khái niệm dịch vụ tại cộng đồng',
    'illustration': 'illustration_bai_6.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_05',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Ưu Thế Vượt Trội Của Chăm Sóc Tại Cộng Đồng So Với Nằm Viện Nội Trú',
    'primary_claim': 'Mang lại hiệu quả điều trị tương đương bệnh viện nhưng giảm thiểu áp lực tài chính và sang chấn '
                     'tâm lý.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tiết Kiệm Tối Đa Chi Phí',
                 'text': 'Loại bỏ chi phí giường bệnh, chi phí đi lại, ăn ở đắt đỏ tại các trung tâm đô thị lớn; giảm '
                         'gánh nặng viện phí cho gia đình.',
                 'icon': 'trending-up'},
               { 'title': 'Gần Gũi Không Gian Gia Đình',
                 'text': 'Người cao tuổi được ở trong ngôi nhà thân quen, được con cháu chăm sóc giúp tinh thần vui '
                         'vẻ, tránh hội chứng trầm cảm nằm viện.',
                 'icon': 'home'},
               { 'title': 'Phòng Nhiễm Khuẩn Bệnh Viện',
                 'text': 'Người già sức đề kháng yếu rất dễ nhiễm vi khuẩn đa kháng thuốc tại bệnh viện; ở nhà giúp '
                         'triệt tiêu hoàn toàn nguy cơ lây chéo.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Đánh giá hiệu quả kinh tế y tế chăm sóc tại cộng đồng - BÀI 6',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_06',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Triết Lý Cốt Lõi: Trợ Giúp Người Cao Tuổi Tự Lực Khai Thác Tiềm Năng Bản Thân',
    'primary_claim': 'Chăm sóc không phải là làm thay hoàn toàn mà là kích hoạt nội lực để người cao tuổi sống tự chủ, '
                     'có ích.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tôn Trọng Sự Tự Chủ Cá Nhân',
                 'text': 'Khuyến khích người cao tuổi tự thực hiện các hoạt động sinh hoạt thường ngày trong khả năng '
                         'cho phép; tránh tâm lý xem bản thân là gánh nặng ăn bám con cháu.',
                 'icon': 'user-check'},
               { 'title': 'Đào Tạo Kỹ Năng Cho Người Chăm Sóc',
                 'text': 'Tư vấn, chuyển giao phương pháp chăm sóc khoa học cho người thân trong gia đình để đồng hành '
                         'hỗ trợ người già một cách kiên nhẫn, yêu thương.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 1.2 - Trọng tâm dịch vụ chăm sóc',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_07',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Bối Cảnh Già Hóa Dân Số: Thách Thức Tốc Độ Nhanh Nhất Lịch Sử Tại Việt Nam',
    'primary_claim': 'Việt Nam bước vào giai đoạn già hóa dân số từ năm 2011 và sẽ chuyển sang dân số già chỉ trong '
                     'vòng 20 năm.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Tốc Độ Già Hóa Phi Mã',
                 'text': 'Trong khi các nước phát triển mất từ 50-100 năm (Pháp 115 năm, Thụy Điển 85 năm) thì Việt '
                         'Nam chỉ mất khoảng 20 năm để chuyển sang dân số già.',
                 'icon': 'clock'},
               { 'title': 'Già Hóa Trước Khi Giàu',
                 'text': 'Quy mô kinh tế còn ở mức thu nhập trung bình, mạng lưới an sinh xã hội chưa hoàn thiện tạo '
                         'áp lực cực lớn lên hệ thống y tế công cộng.',
                 'icon': 'alert-circle'},
               { 'title': 'Đòi Hỏi Thích Ứng Chủ Động',
                 'text': 'Chuyển đổi căn bản hệ thống y tế từ chữa bệnh cấp tính sang quản lý bệnh mãn tính kéo dài '
                         'tại trạm y tế và hộ gia đình.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tổng cục Dân số - Báo cáo già hóa dân số Việt Nam',
    'illustration': 'ai_bai_2_aging.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_08',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Hai Trục Phân Loại Hệ Thống Chăm Sóc Sức Khỏe Người Cao Tuổi',
    'primary_claim': 'Phân định theo chuyên môn kỹ thuật y tế và theo mức độ phụ thuộc chăm sóc của người cao tuổi.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Trục 1: Theo Trình Độ Chuyên Môn Y Tế',
                 'text': 'Phân tách rành mạch giữa: 1. Dịch vụ không cần chuyên môn y tế (trò chuyện, ăn uống, vệ '
                         'sinh, tập luyện) vs 2. Dịch vụ cần chuyên môn y tế (tiêm truyền, thay băng, theo dõi chỉ số '
                         'sinh tồn, y lệnh ngoại trú).',
                 'icon': 'layers'},
               { 'title': 'Trục 2: Theo Mức Độ Cần Trợ Giúp',
                 'text': 'Phân nhóm theo thể trạng: 1. Dịch vụ chăm sóc hỗ trợ một phần (dành cho người còn tự chủ vận '
                         'động) vs 2. Dịch vụ chăm sóc toàn diện (dành cho người già ốm liệt giường, phụ thuộc 100%).',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 2 - Phân loại dịch vụ',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_09',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Phân Loại Theo Chuyên Môn: Dịch Vụ Phi Y Tế Vs Dịch Vụ Y Tế Chuyên Sâu',
    'primary_claim': 'Sự kết hợp nhịp nhàng giữa chăm sóc đời sống thường nhật và can thiệp y khoa chuẩn xác.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Dịch Vụ Không Cần Chuyên Môn Y Tế',
                 'text': 'Trò chuyện, tâm sự, bầu bạn mỗi ngày; trợ giúp ăn uống, nấu các món dinh dưỡng dễ nuốt; hỗ '
                         'trợ tắm rửa, gội đầu; dắt đi dạo và hướng dẫn tập các động tác thể dục dưỡng sinh nhẹ nhàng.',
                 'icon': 'heart'},
               { 'title': 'Dịch Vụ Cần Đến Chuyên Môn Y Tế',
                 'text': 'Đo huyết áp, thử đường huyết mao mạch, quản lý hộp chia liều thuốc; chăm sóc vết loét tỳ đè '
                         'vùng cùng cụt; đặt ống thông dạ dày (Sonde Nelaton), ống thông tiểu và thực hiện tiêm '
                         'truyền.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 2 - Dịch vụ có và không có chuyên môn y tế',
    'illustration': 'cinematic_bai_1_hero.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_10',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Phân Loại Theo Mức Độ Hỗ Trợ: Chăm Sóc Toàn Diện Vs Hỗ Trợ Một Phần',
    'primary_claim': 'Cá nhân hóa gói dịch vụ theo thang điểm suy giảm chức năng sinh hoạt thường ngày.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Chăm Sóc Hỗ Trợ Một Phần (Semi-Care)',
                 'text': 'Người cao tuổi vẫn minh mẫn, còn khả năng tự đi lại hoặc dùng gậy; chỉ cần hỗ trợ một số '
                         'khâu nặng nhọc như đi chợ, nấu nướng, dọn dẹp nhà cửa, lấy thuốc định kỳ hoặc đưa đi khám '
                         'viện.',
                 'icon': 'user-check'},
               { 'title': 'Chăm Sóc Toàn Diện (Full-Care)',
                 'text': 'Áp dụng cho người cao tuổi bị di chứng tai biến mạch máu não liệt nửa người, sa sút trí tuệ '
                         'Alzheimer nặng; phụ thuộc hoàn toàn vào người chăm sóc trong ăn uống, đại tiểu tiện và xoay '
                         'trở mình.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 2 - Mức độ hỗ trợ chăm sóc',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_11',
    'role': 'CONTENT',
    'section': '3. ĐẶC ĐIỂM KHÁCH HÀNG',
    'assertion_title': 'Khách Hàng Mục Tiêu: Người Cao Tuổi Đang Sinh Sống Tại Gia Đình',
    'primary_claim': 'Đối tượng phục vụ là người già sống trong vòng tay gia đình, không nằm điều trị nội trú tại bệnh '
                     'viện.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Sinh Sống Tại Hộ Gia Đình',
                 'text': 'Gồm các cụ già sống cùng con cháu trong gia đình tam đại, tứ đại đồng đường hoặc các cặp vợ '
                         'chồng già sống đơn thân.',
                 'icon': 'home'},
               { 'title': 'Không Nằm Viện Nội Trú',
                 'text': 'Sức khỏe tương đối ổn định sau giai đoạn cấp tính, đang trong quá trình dưỡng bệnh, phục hồi '
                         'chức năng hoặc điều trị ngoại trú dài hạn.',
                 'icon': 'shield'},
               { 'title': 'Gắn Bó Với Thôn Xóm',
                 'text': 'Có nhu cầu giao lưu chòm xóm, tham gia sinh hoạt tổ dân phố, hội người cao tuổi và các phong '
                         'trào văn hóa làng quê.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 3 - Khách hàng mục tiêu',
    'illustration': 'ai_bai_1_community.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_12',
    'role': 'CONTENT',
    'section': '3. ĐẶC ĐIỂM KHÁCH HÀNG',
    'assertion_title': 'Mô Hình Bệnh Tật Kép: Trung Bình Mỗi Người Già Mắc Từ 3 Đến 4 Bệnh',
    'primary_claim': 'Bệnh cảnh đa bệnh lý mạn tính đòi hỏi sự theo dõi phối hợp nhiều chuyên khoa cùng lúc.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Bệnh Tim Mạch & Tăng Huyết Áp',
                 'text': 'Chiếm trên 60% NCT; nguy cơ cao xảy ra tai biến đột quỵ não, nhồi máu cơ tim nếu huyết áp '
                         'không được kiểm soát chặt chẽ.',
                 'icon': 'heart'},
               { 'title': 'Đái Tháo Đường Type 2',
                 'text': 'Gây biến chứng suy thận mạn, mờ mắt võng mạc, tê bì mất cảm giác đầu chi và nguy cơ loét '
                         'hoại tử bàn chân cắt cụt.',
                 'icon': 'activity'},
               { 'title': 'Thoái Hóa Khớp & Loãng Xương',
                 'text': 'Đau nhức khớp gối, thoái hóa cột sống cổ thắt lưng, giòn xương; chỉ cần một cú vấp ngã nhẹ '
                         'cũng gây gãy cổ xương đùi.',
                 'icon': 'alert-circle'},
               { 'title': 'Sa Sút Trí Tuệ & Bệnh Phổi Mãn',
                 'text': 'Suy giảm trí nhớ, lú lẫn lẫn lộn ngày đêm, bệnh phổi tắc nghẽn mãn tính (COPD) do tiền sử '
                         'hút thuốc lá nhiều năm.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Mô hình bệnh tật người cao tuổi Việt Nam - BÀI 6',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_13',
    'role': 'CONTENT',
    'section': '3. ĐẶC ĐIỂM KHÁCH HÀNG',
    'assertion_title': 'Bốn Nhóm Khách Hàng Phân Theo Mức Độ Tự Lập & Năng Lực Tài Chính',
    'primary_claim': 'Cơ sở để thiết kế các chính sách bảo trợ xã hội và dịch vụ tiếp cận phù hợp nguồn lực.',
    'visual_job': 'CHART_AND_INSIGHTS',
    'visual_anchor': 'CHART_AND_INSIGHTS',
    'atoms': [ { 'title': 'Nhóm Tự Chăm Sóc Được',
                 'text': 'Còn khỏe mạnh, tự sinh hoạt cá nhân; có nhu cầu tham gia câu lạc bộ dưỡng sinh, văn nghệ, tư '
                         'vấn phòng ngừa bệnh tật.',
                 'icon': 'user-check'},
               { 'title': 'Nhóm Bắt Buộc Có Người Hỗ Trợ',
                 'text': 'Bị suy giảm thể lực, di chứng liệt hoặc mù lòa; cần người trợ giúp việc di chuyển, ăn uống '
                         'và giám sát uống thuốc.',
                 'icon': 'activity'},
               { 'title': 'Nhóm Tự Trang Trải Kinh Phí',
                 'text': 'Có lương hưu, có tích lũy tài chính hoặc con cái khá giả; sẵn sàng chi trả tiền thuê người '
                         'chăm sóc chuyên nghiệp tại nhà.',
                 'icon': 'award'},
               { 'title': 'Nhóm Cần Bảo Trợ Xã Hội',
                 'text': 'Người già cô đơn không nơi nương tựa, thuộc hộ nghèo; phụ thuộc 100% vào trợ cấp xã hội và '
                         'sự chăm sóc tình nguyện của xóm làng.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 3 - Bốn nhóm khách hàng cộng đồng',
    'chart_type': 'RADAR_FILLED',
    'chart_file': 'chart_age_structure_radar_dark.png',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_14',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ & CUNG CẤP',
    'assertion_title': 'Đội Ngũ Cung Cấp Dịch Vụ Phi Y Tế: Người Thân, Người Giúp Việc & CTV Dân Số',
    'primary_claim': 'Gia đình là pháo đài vững chắc nhất, kết hợp với mạng lưới cộng tác viên dân số am hiểu từng ngõ '
                     'xóm.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Con Cháu Trong Gia Đình',
                 'text': 'Lực lượng chăm sóc chủ đạo, giàu tình cảm nhất nhưng thường thiếu kỹ năng y tế và chịu áp '
                         'lực công việc bận rộn.',
                 'icon': 'heart'},
               { 'title': 'Người Giúp Việc Kiêm Chăm Sóc',
                 'text': 'Được các gia đình khá giả thuê về nhà; cần được bồi dưỡng kỹ năng giao tiếp, thái độ tôn '
                         'trọng và sơ cấp cứu cơ bản.',
                 'icon': 'users'},
               { 'title': 'Cộng Tác Viên Dân Số Thôn Bản',
                 'text': 'Từ nhiệm vụ KHHGĐ chuyển sang sứ mệnh mới: thường xuyên thăm hộ, rà soát nhu cầu, hướng dẫn '
                         'bài tập và phát tài liệu chăm sóc.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 4 - Người cung cấp phi y tế',
    'illustration': 'illustration_bai_6.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_15',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ & CUNG CẤP',
    'assertion_title': 'Đội Ngũ Cung Cấp Dịch Vụ Y Tế: Trạm Y Tế Xã & Khám Chữa Bệnh Tại Nhà',
    'primary_claim': 'Trạm y tế xã là hạt nhân y tế chuyên nghiệp trực tiếp quản lý hồ sơ và chăm sóc tận giường bệnh.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Nhân Viên Trạm Y Tế Xã',
                 'text': 'Lập hồ sơ quản lý bệnh mãn tính, cấp phát thuốc tăng huyết áp/tiểu đường bảo hiểm y tế hàng '
                         'tháng; tổ chức các đợt khám bệnh đến tận nhà cho các cụ già yếu không đi lại được.',
                 'icon': 'home'},
               { 'title': 'Dịch Vụ Y Tế Ngoại Viễn (Home-Care)',
                 'text': 'Nhiều bệnh viện đa khoa tuyến huyện, phòng khám tư nhân cử bác sĩ, điều dưỡng đến tận nhà '
                         'thực hiện truyền dịch, thay sonde, xét nghiệm máu tại chỗ theo yêu cầu.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 4 - Người cung cấp dịch vụ y tế',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_16',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ & CUNG CẤP',
    'assertion_title': "Mô Hình Thí Điểm: 'Điểm Chăm Sóc Sức Khỏe Ban Ngày Tại Cộng Đồng'",
    'primary_claim': 'Giải pháp dung hòa tuyệt vời giúp con cái yên tâm đi làm trong khi cha mẹ già được chăm sóc chu '
                     'đáo.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Tổ Chức Tại Nhà Văn Hóa Thôn',
                 'text': 'Sử dụng nhà văn hóa thôn, trạm y tế hoặc điểm sinh hoạt cộng đồng làm điểm đón tiếp các cụ '
                         'vào ban ngày (từ 7h30 đến 17h00).',
                 'icon': 'home'},
               { 'title': 'Lực Lượng Phục Vụ Hỗn Hợp',
                 'text': 'Gồm nhân viên y tế cơ sở, tình nguyện viên Hội Chữ thập đỏ, Hội Người cao tuổi, Đoàn thanh '
                         'niên và cộng tác viên dân số.',
                 'icon': 'users'},
               { 'title': 'Nội Dung Phục Vụ Đa Dạng',
                 'text': 'Đo huyết áp buổi sáng, tập dưỡng sinh, ăn trưa dinh dưỡng, ngủ trưa, đọc báo, đánh cờ và '
                         'kiểm tra thuốc men trước khi về nhà.',
                 'icon': 'smile'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 4 - Mô hình điểm chăm sóc ban ngày',
    'illustration': 'ai_bai_2_aging.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_17',
    'role': 'CONTENT',
    'section': '5. NỘI DUNG DỊCH VỤ',
    'assertion_title': 'Danh Mục Toàn Diện Các Hoạt Động Chuyên Môn Chăm Sóc Tại Nhà',
    'primary_claim': 'Bao phủ từ hỗ trợ sinh hoạt tối thiểu đến các kỹ thuật y tế phục hồi chức năng phức tạp.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Theo Dõi Thể Trạng & Bệnh Mạn',
                 'text': 'Đo mạch, nhiệt độ, huyết áp, nhịp thở, theo dõi chỉ số đường huyết định kỳ; phát hiện sớm '
                         'cơn thiếu máu não thoáng qua.',
                 'icon': 'activity'},
               { 'title': '2. Chăm Sóc Vết Thương & Phẫu Thuật',
                 'text': 'Rửa vết thương hở vô khuẩn, thay băng cắt chỉ sau mổ, chăm sóc vết loét tỳ đè sâu và dẫn lưu '
                         'dịch an toàn.',
                 'icon': 'shield'},
               { 'title': '3. Thực Hiện Y Lệnh Ngoại Trú',
                 'text': 'Tiêm bắp, tiêm dưới da (Insulin), truyền dịch theo đơn bác sĩ; tuyệt đối không tự ý dùng '
                         'kháng sinh bừa bãi.',
                 'icon': 'check-circle'},
               { 'title': '4. Hỗ Trợ Sinh Hoạt Thường Nhật',
                 'text': 'Giúp đỡ ăn uống, bón cháo súp, hỗ trợ vệ sinh cá nhân, thay tã bỉm, tắm gội tại giường cho '
                         'người bệnh nặng.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 5 - Nội dung dịch vụ chăm sóc tại nhà',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_18',
    'role': 'CONTENT',
    'section': '5.1. NỘI DUNG Y TẾ',
    'assertion_title': 'Quản Lý Bệnh Tăng Huyết Áp & Đái Tháo Đường Tại Hộ Gia Đình',
    'primary_claim': 'Kiểm soát mục tiêu huyết áp dưới 140/90 mmHg và HbA1c dưới 7% để chặn đứng biến chứng đột quỵ.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Quản Lý Huyết Áp Tại Nhà',
                 'text': 'Đo huyết áp vào khung giờ cố định buổi sáng trước khi uống thuốc; ghi nhật ký huyết áp; ăn '
                         'nhạt (dưới 5g muối/ngày); tuân thủ uống thuốc hạ áp liên tục suốt đời, tuyệt đối không tự ý '
                         'bỏ thuốc khi thấy huyết áp bình thường.',
                 'icon': 'heart'},
               { 'title': 'Quản Lý Đường Huyết & Bàn Chân',
                 'text': 'Thử đường huyết mao mạch trước ăn; tuân thủ tiêm Insulin hoặc uống thuốc hạ đường; kiểm tra '
                         'bàn chân mỗi tối tìm vết xước, vết chai; rửa chân nước ấm, lau khô kẽ ngón và đi dép mềm '
                         'trong nhà.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Phác đồ quản lý bệnh không lây nhiễm tại trạm y tế',
    'illustration': 'cinematic_bai_1_hero.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_19',
    'role': 'CONTENT',
    'section': '5.1. NỘI DUNG Y TẾ',
    'assertion_title': 'Phòng Chống & Xử Trí Vết Loét Tỳ Đè (Decubitus) Ở Người Nằm Bất Động',
    'primary_claim': 'Vết loét tỳ đè hình thành chỉ sau 2 giờ bị đè cấn liên tục, dẫn đến nhiễm trùng huyết tử vong '
                     'nhanh.',
    'visual_job': 'PROCESS_DEVSECOPS_PIPELINE',
    'visual_anchor': 'PROCESS_CARDS',
    'atoms': [ { 'title': '1. Lật Trở Mình Mỗi 2 Giờ',
                 'text': 'Quy tắc sống còn: Lật nghiêng trái, nghiêng phải, nằm ngửa định kỳ mỗi 2 giờ/lần cả ngày lẫn '
                         'đêm.',
                 'icon': 'clock'},
               { 'title': '2. Dùng Đệm Khí Chống Loét',
                 'text': 'Trang bị đệm hơi có máy bơm đảo luồng khí liên tục giúp phân tán áp lực lên các vùng xương '
                         'nhô.',
                 'icon': 'shield'},
               { 'title': '3. Xoa Bóp Vùng Tỳ Đè',
                 'text': 'Xoa bóp nhẹ nhàng bằng cồn xoa hoặc dầu massage tại vùng cùng cụt, hai mông, mắt cá chân, '
                         'gót chân.',
                 'icon': 'heart'},
               { 'title': '4. Rửa Vết Loét Vô Khuẩn',
                 'text': 'Nếu đã loét: Cắt lọc mô hoại tử, rửa nước muối sinh lý 0.9%, rắc bột kháng khuẩn và đắp gạc '
                         'xốp hydrocolloid.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình chăm sóc loét tỳ đè - BÀI 6',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_20',
    'role': 'CONTENT',
    'section': '5.1. NỘI DUNG Y TẾ',
    'assertion_title': 'Quản Trị An Toàn Dùng Thuốc: Hộp Chia Liều & Phòng Tránh Nhầm Lẫn Thuốc',
    'primary_claim': 'Người già mắt kém, hay quên rất dễ uống nhầm thuốc hoặc uống gấp đôi liều gây ngộ độc cấp cứu.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Sử Dụng Hộp Chia Thuốc 7 Ngày',
                 'text': 'Trang bị hộp nhựa chia 7 ngày trong tuần, mỗi ngày có 3-4 ngăn (Sáng - Trưa - Chiều - Tối); '
                         'người nhà chia sẵn thuốc vào đầu tuần.',
                 'icon': 'check-circle'},
               { 'title': 'Dán Nhãn Chữ To Rõ Ràng',
                 'text': 'Ghi chú công dụng và liều lượng bằng chữ in hoa to màu đậm (ví dụ: THUỐC HUYẾT ÁP - UỐNG 1 '
                         'VIÊN SAU ĂN SÁNG).',
                 'icon': 'book-open'},
               { 'title': 'Loại Bỏ Thuốc Hết Hạn',
                 'text': 'Định kỳ kiểm tra tủ thuốc gia đình, vứt bỏ các loại thuốc quá hạn dùng, thuốc mất nhãn hoặc '
                         'ẩm mốc để phòng ngộ độc.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 5 - Theo dõi và nhắc nhở uống thuốc',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_21',
    'role': 'CONTENT',
    'section': '5.1. NỘI DUNG Y TẾ',
    'assertion_title': 'Kỹ Thuật Xoa Bóp Bấm Huyệt & Phục Hồi Chức Năng Giảm Đau Khớp',
    'primary_claim': 'Y học cổ truyền kết hợp vận động liệu pháp giúp lưu thông khí huyết và duy trì tầm vận động '
                     'khớp.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Xoa Bóp Cơ Khớp Nhẹ Nhàng',
                 'text': 'Sử dụng các thủ thuật xoa, vuốt, miết, day, nhào cơ tại các vùng hay nhức mỏi: khớp gối, cổ '
                         'gáy, thắt lưng, bắp chân.',
                 'icon': 'activity'},
               { 'title': 'Day Ấn Các Huyệt Đạo Cơ Bản',
                 'text': 'Day ấn nhẹ nhàng các huyệt Phong trì (đau đầu), Hợp cốc, Dũng tuyền (mất ngủ), Độc tỵ (đau '
                         'khớp gối), Thận du (đau lưng).',
                 'icon': 'award'},
               { 'title': 'Tập Vận Động Chống Cứng Khớp',
                 'text': 'Hướng dẫn người bệnh tự co duỗi các ngón tay, xoay cổ tay, gập duỗi khớp gối 15-20 phút mỗi '
                         'buổi sáng khi thức dậy.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 5 - Kỹ thuật massage chuyên môn',
    'illustration': 'ai_bai_1_community.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_22',
    'role': 'CONTENT',
    'section': '5.2. NỘI DUNG SINH HOẠT',
    'assertion_title': 'Hỗ Trợ Dinh Dưỡng Khoa Học: Chế Độ Ăn Mềm, Dễ Tiêu & Cân Đối Vi Chất',
    'primary_claim': 'Răng yếu và men tiêu hóa suy giảm đòi hỏi thức ăn phải được chế biến nhỏ mềm, giàu canxi và chất '
                     'xơ.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Thức Ăn Mềm, Nấu Nhừ',
                 'text': 'Ưu tiên các món cháo, súp, canh hầm nhừ, thịt cá băm nhỏ giúp người già nhai nuốt dễ dàng, '
                         'tránh nghẹn và sặc đường thở.',
                 'icon': 'heart'},
               { 'title': 'Chia Nhỏ Nhiều Bữa Ăn',
                 'text': 'Chia khẩu phần ăn thành 4-5 bữa nhỏ trong ngày; không ăn quá no vào bữa tối để tránh đầy '
                         'bụng, khó ngủ và trào ngược dạ dày.',
                 'icon': 'clock'},
               { 'title': 'Bổ Sung Canxi & Vitamin D',
                 'text': 'Uống 1-2 ly sữa dành riêng cho người cao tuổi mỗi ngày; ăn tôm tép nhỏ cả vỏ, rau xanh đậm '
                         'để chống loãng xương.',
                 'icon': 'shield-check'},
               { 'title': 'Uống Đủ Nước Ấm',
                 'text': 'Khuyến khích uống đủ 1.5 - 2 lít nước ấm mỗi ngày; uống từng ngụm nhỏ; hạn chế uống nhiều '
                         'nước sau 20h tối để tránh tiểu đêm.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Hướng dẫn dinh dưỡng tiết chế người cao tuổi - BÀI 6',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_23',
    'role': 'CONTENT',
    'section': '5.2. NỘI DUNG SINH HOẠT',
    'assertion_title': 'Cải Tạo Môi Trường Sống An Toàn: Phòng Ngừa Té Ngã Trong Nhà',
    'primary_claim': 'Té ngã là nguyên nhân hàng đầu gây tàn phế và tử vong ở người cao tuổi; 70% các vụ ngã xảy ra '
                     'ngay tại nhà.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Lắp Đặt Tay Vịn Nhà Tắm',
                 'text': 'Gắn thanh tay vịn inox chắc chắn cạnh bồn cầu và vòi sen tắm; bố trí ghế ngồi tắm chuyên '
                         'dụng chống trơn trượt.',
                 'icon': 'shield-check'},
               { 'title': 'Sàn Nhà Luôn Khô Ráo',
                 'text': 'Trải thảm cao su chống trượt trong nhà vệ sinh; lau khô sàn ngay lập tức; không để dây điện '
                         'hay thảm vụn vướng lối đi.',
                 'icon': 'check-circle'},
               { 'title': 'Hệ Thống Chiếu Sáng Đầy Đủ',
                 'text': 'Lắp đèn cảm ứng ban đêm dọc hành lang từ giường ngủ ra nhà vệ sinh; công tắc đèn đặt ở vị '
                         'trí thuận tay với tới.',
                 'icon': 'sun'},
               { 'title': 'Giày Dép Chống Trượt',
                 'text': 'Trang bị dép đi trong nhà có đế cao su ma sát tốt; hướng dẫn các cụ bước đi chậm rãi, không '
                         'đứng lên đột ngột tránh tụt huyết áp tư thế.',
                 'icon': 'user-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Hướng dẫn phòng ngừa té ngã người cao tuổi - WHO & Bộ Y tế',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_24',
    'role': 'CONTENT',
    'section': '5.3. SỨC KHỎE TINH THẦN',
    'assertion_title': 'Tầm Quan Trọng Sống Còn Của Sức Khỏe Tinh Thần & Chống Cô Đơn Tuổi Già',
    'primary_claim': 'Cô đơn và trầm cảm tàn phá sức khỏe người già nhanh hơn cả các căn bệnh thể xác mãn tính.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': "Hội Chứng 'Tổ Trống' (Empty Nest)",
                 'text': 'Con cái trưởng thành đi làm xa, người bạn đời qua đời làm người già rơi vào hụt hẫng, mặc '
                         'cảm bị bỏ rơi và chán sống.',
                 'icon': 'alert-circle'},
               { 'title': 'Suy Giảm Miễn Dịch Do U Buồn',
                 'text': 'Tâm lý u sầu, lo âu làm tăng tiết hormone Cortisol ức chế hệ miễn dịch, làm bùng phát các '
                         'cơn đau tim và tai biến mạch máu não.',
                 'icon': 'activity'},
               { 'title': 'Sự Lắng Nghe Là Liều Thuốc Bổ',
                 'text': 'Mỗi ngày con cháu chỉ cần dành 15-30 phút trò chuyện chân thành sẽ mang lại sự hồi sinh tinh '
                         'thần kỳ diệu cho ông bà.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 5 - Tầm quan trọng của sức khỏe tinh thần',
    'illustration': 'illustration_bai_6.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_25',
    'role': 'CONTENT',
    'section': '5.3. SỨC KHỎE TINH THẦN',
    'assertion_title': 'Phát Triển Phong Trào Câu Lạc Bộ Thể Thao Dưỡng Sinh & Khiêu Vũ',
    'primary_claim': 'Hoạt động thể chất tập thể vừa rèn luyện độ dẻo dai cơ bắp, vừa mở rộng giao lưu bạn hữu.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Câu Lạc Bộ Dưỡng Sinh Tâm Thể',
                 'text': 'Tập các bài thái cực quyền, dịch cân kinh, thái cực kiếm vào buổi sáng sớm tại sân đình, '
                         'công viên giúp điều hòa hơi thở.',
                 'icon': 'sun'},
               { 'title': 'Bóng Chuyền Hơi & Bóng Bàn',
                 'text': 'Môn thể thao nhẹ nhàng, an toàn, không va chạm mạnh; rèn luyện phản xạ nhanh nhạy và tạo '
                         'không khí thi đấu hào hứng.',
                 'icon': 'award'},
               { 'title': 'Khiêu Vũ Dưỡng Sinh NCT',
                 'text': 'Vận động theo điệu nhạc Val-xơ, Cha-cha-cha êm dịu kích thích não bộ tiết Dopamine mang lại '
                         'niềm vui tươi trẻ cho tâm hồn.',
                 'icon': 'music'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 5 - Các câu lạc bộ thể dục thể thao',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_26',
    'role': 'CONTENT',
    'section': '5.3. SỨC KHỎE TINH THẦN',
    'assertion_title': 'Đời Sống Văn Hóa Phong Phú: Thơ Ca, Sinh Vật Cảnh & Làm Vườn Trị Liệu',
    'primary_claim': 'Thú vui tao nhã nuôi dưỡng tâm hồn bình an và phát huy vốn sống giàu kinh nghiệm của người già.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Câu Lạc Bộ Thơ Ca, Ca Hát',
                 'text': 'Sáng tác thơ, hát quan họ, ca trù, văn nghệ quần chúng; tổ chức giao lưu mừng thọ đầu xuân '
                         'đem lại nụ cười rạng rỡ.',
                 'icon': 'smile'},
               { 'title': 'Thú Vui Sinh Vật Cảnh & Trồng Hoa',
                 'text': 'Chăm sóc cây cảnh bonsai, hòn non bộ, nuôi chim cảnh, cá cảnh giúp tinh thần thư thái, gần '
                         'gũi với thiên nhiên trong lành.',
                 'icon': 'heart'},
               { 'title': 'Làm Vườn Trị Liệu (Horticulture)',
                 'text': 'Trồng luống rau sạch, giàn mướp quanh nhà; vận động chân tay nhẹ nhàng vừa tạo nguồn thực '
                         'phẩm sạch cho gia đình.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 5 - Câu lạc bộ sinh vật cảnh và văn hóa',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_27',
    'role': 'CONTENT',
    'section': '5.3. SỨC KHỎE TINH THẦN',
    'assertion_title': "Phát Huy Vai Trò Trưởng Bối: 'Tuổi Cao - Gương Sáng' Trong Cộng Đồng",
    'primary_claim': 'Người cao tuổi là kho tàng trí tuệ, rường cột đạo đức giáo dục con cháu giữ gìn gia phong truyền '
                     'thống.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Gia Đình Hòa Thuận, Kiểu Mẫu',
                 'text': 'Nêu gương sáng về lối sống mực thước, cần kiệm liêm chính; khuyên răn con cháu tránh xa tệ '
                         'nạn xã hội, chăm ngoan hiếu thảo.',
                 'icon': 'award'},
               { 'title': 'Công Tác Khuyến Học & Khuyến Tài',
                 'text': 'Xây dựng quỹ khuyến học dòng họ, khuyến khích con em hiếu học đỗ đạt thành tài cống hiến cho '
                         'quê hương đất nước.',
                 'icon': 'book-open'},
               { 'title': 'Hòa Giải Mâu Thuẫn Thôn Xóm',
                 'text': 'Tham gia tổ hòa giải cơ sở; tiếng nói uy tín của người già giúp tháo gỡ nhiều xích mích chòm '
                         'xóm êm thấm, thắt chặt tình làng nghĩa xóm.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Phong trào Tuổi cao - Gương sáng Hội NCT Việt Nam',
    'illustration': 'ai_bai_2_aging.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_28',
    'role': 'CONTENT',
    'section': '5.4. CÂU LẠC BỘ LIÊN THẾ HỆ',
    'assertion_title': 'Mô Hình Câu Lạc Bộ Liên Thế Hệ Tự Giúp Nhau (ISHC): Đổi mới trọng tâm',
    'primary_claim': 'Mô hình được Thủ tướng Chính phủ nhân rộng toàn quốc nhờ tính bền vững, tự chủ và hiệu quả đa '
                     'ngành.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Chăm Sóc Sức Khỏe Tại Nhà',
                 'text': 'Tình nguyện viên được tập huấn định kỳ đến thăm hộ, xoa bóp, đo huyết áp và dọn dẹp vệ sinh '
                         'cho các cụ ốm liệt giường.',
                 'icon': 'heart'},
               { 'title': '2. Tăng Thu Nhập & Vay Vốn',
                 'text': 'Quỹ tín dụng nhỏ của CLB cho các thành viên vay vốn lãi suất thấp phát triển chăn nuôi, '
                         'trồng trọt, tăng thu nhập gia đình.',
                 'icon': 'trending-up'},
               { 'title': '3. Tự Giúp Nhau & Tình Nguyện',
                 'text': 'Thành viên khỏe mạnh giúp thành viên yếu thế; cùng nhau nấu ăn, đi chợ, giúp đỡ nhau lúc '
                         'tang ma ốm đau hoạn nạn.',
                 'icon': 'users'},
               { 'title': '4. Giao Lưu Liên Thế Hệ',
                 'text': 'Thu hút cả thanh niên, phụ nữ cùng tham gia; con cháu học hỏi kinh nghiệm của ông bà và hỗ '
                         'trợ người già ứng dụng công nghệ.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 5 - Câu lạc bộ Liên thế hệ tự giúp nhau',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_29',
    'role': 'CONTENT',
    'section': '5.4. CÂU LẠC BỘ LIÊN THẾ HỆ',
    'assertion_title': 'Mạng Lưới Tình Nguyện Viên Chăm Sóc Tại Nhà Dựa Vào Cộng Đồng Của ISHC',
    'primary_claim': 'Mỗi tình nguyện viên phụ trách chăm sóc thường xuyên từ 1 đến 2 người cao tuổi có hoàn cảnh đặc '
                     'biệt khó khăn.',
    'visual_job': 'PROCESS_DEVSECOPS_PIPELINE',
    'visual_anchor': 'PROCESS_CARDS',
    'atoms': [ { 'title': '1. Khảo Sát & Lập Danh Sách',
                 'text': 'Ban chủ nhiệm CLB rà soát toàn bộ người cao tuổi neo đơn, tàn tật, ốm liệt giường trên địa '
                         'bàn thôn xóm.',
                 'icon': 'search'},
               { 'title': '2. Phân Công Tình Nguyện Viên',
                 'text': 'Cắt cử tình nguyện viên sống gần nhà nhất để tiện thăm hỏi thường xuyên ít nhất 2 lần mỗi '
                         'tuần.',
                 'icon': 'users'},
               { 'title': '3. Thực Hiện Gói Chăm Sóc',
                 'text': 'Nấu cơm nóng, bón cháo, thay quần áo, giặt giũ, xoa bóp tay chân và trò chuyện giải tỏa nỗi '
                         'buồn cô quạnh.',
                 'icon': 'heart'},
               { 'title': '4. Báo Cáo Y Tế Cơ Sở',
                 'text': 'Kịp thời thông báo cho trạm y tế xã khi phát hiện người cao tuổi có dấu hiệu sốt cao, tụt '
                         'huyết áp hoặc trở bệnh nặng.',
                 'icon': 'phone'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Sổ tay hướng dẫn vận hành CLB ISHC - HelpAge International',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_30',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Chương Trình Chăm Sóc Sức Khỏe Người Cao Tuổi Đến 2030 (QĐ 1579/QĐ-TTg)',
    'primary_claim': 'Chiến lược hành động quốc gia ban hành ngày 13/10/2020 đặt mục tiêu thích ứng toàn diện với kỷ '
                     'nguyên già hóa.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Mục Tiêu Tổng Quát',
                 'text': 'Chăm sóc, nâng cao sức khỏe người cao tuổi bảo đảm thích ứng với già hóa dân số; tăng số năm '
                         'sống khỏe mạnh và nâng cao chất lượng cuộc sống.',
                 'icon': 'target'},
               { 'title': 'Đầu Tư Công Trung Hạn',
                 'text': 'Chính phủ bố trí các dự án xây dựng bệnh viện lão khoa, khoa lão tại các bệnh viện đa khoa '
                         'và nâng cấp trạm y tế vào kế hoạch đầu tư công.',
                 'icon': 'trending-up'},
               { 'title': 'Xã Hội Hóa Nguồn Lực',
                 'text': 'Khuyến khích doanh nghiệp, tổ chức xã hội đầu tư xây dựng các trung tâm dưỡng lão, điểm chăm '
                         'sóc ban ngày và dịch vụ y tế tại nhà.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quyết định số 1579/QĐ-TTg ngày 13/10/2020 của Thủ tướng Chính phủ',
    'illustration': 'cinematic_bai_1_hero.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_31',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Các Chỉ Tiêu Chiến Lược Cốt Lõi Về Chăm Sóc NCT Đến Năm 2030',
    'primary_claim': 'Hệ thống chỉ số pháp lệnh đo lường mức độ bao phủ dịch vụ y tế cho người cao tuổi cả nước.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '100% NCT Có Thẻ BHYT',
                 'text': 'Bảo đảm 100% người cao tuổi có thẻ Bảo hiểm y tế và được khám chữa bệnh định kỳ tại tuyến y '
                         'tế cơ sở.',
                 'icon': 'shield-check'},
               { 'title': 'Ít Nhất 90% Được Khám Định Kỳ',
                 'text': 'Tối thiểu 90% người cao tuổi được khám sức khỏe định kỳ ít nhất 1 lần/năm và được lập hồ sơ '
                         'theo dõi sức khỏe điện tử.',
                 'icon': 'activity'},
               { 'title': '95% NCT Bệnh Mãn Tính Được Quản Lý',
                 'text': '95% người cao tuổi mắc các bệnh mãn tính (tăng huyết áp, đái tháo đường...) được quản lý, '
                         'điều trị tại trạm y tế xã.',
                 'icon': 'check-circle'},
               { 'title': '100% NCT Không Tự Chăm Sóc Được Hỗ Trợ',
                 'text': '100% người cao tuổi ốm liệt giường, cô đơn không tự chăm sóc được hỗ trợ chăm sóc y tế tại '
                         'hộ gia đình.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Hệ thống chỉ tiêu Quyết định 1579/QĐ-TTg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_32',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Chỉ Đạo & Điều Phối Tuyến Trung Ương: Cục Dân Số (Bộ Y Tế)',
    'primary_claim': 'Cục Dân số chủ trì xây dựng kế hoạch, bố trí nhân lực, kiểm tra giám sát và hướng dẫn toàn quốc.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Chủ Trì Điều Phối Quốc Gia',
                 'text': 'Phối hợp liên ngành với Trung ương Hội Người cao tuổi, Bộ LĐ-TB&XH, Bộ Tài chính phân bổ '
                         'ngân sách triển khai QĐ 1579.',
                 'icon': 'shield-check'},
               { 'title': 'Chiến Dịch Khám Sức Khỏe Định Kỳ',
                 'text': 'Chỉ đạo tổ chức các chiến dịch truyền thông lồng ghép dịch vụ khám sàng lọc các bệnh mắt '
                         '(đục thủy tinh thể), tim mạch, đái tháo đường.',
                 'icon': 'activity'},
               { 'title': 'Cơ Sở Dữ Liệu Quốc Gia Về NCT',
                 'text': 'Xây dựng hệ thống thông tin thống kê, cơ sở dữ liệu chuyên ngành về thể trạng sức khỏe người '
                         'cao tuổi kết nối VNeID.',
                 'icon': 'globe'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 6.1 - Tuyến Trung ương',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_33',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Tổ Chức Triển Khai Thực Địa Tại Tuyến Tỉnh & Tuyến Huyện',
    'primary_claim': 'Cơ quan chuyên môn cấp tỉnh và huyện bảo đảm đào tạo kỹ năng và hỗ trợ kỹ thuật liên tục cho '
                     'tuyến xã.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Tuyến Tỉnh: Sở Y Tế (Chi Cục Dân Số)',
                 'text': 'Tham mưu UBND tỉnh ban hành Kế hoạch hành động cấp tỉnh; chỉ đạo Bệnh viện Đa khoa tỉnh '
                         'thành lập Khoa Lão học; tổ chức tập huấn chuyên môn kỹ năng chăm sóc người cao tuổi cho cán '
                         'bộ y tế toàn tỉnh.',
                 'icon': 'layers'},
               { 'title': 'Tuyến Huyện: Trung Tâm Y Tế / BVĐK Huyện',
                 'text': 'Bố trí buồng khám lão khoa tại khoa khám bệnh; thành lập các đội khám lưu động về tận các xã '
                         'vùng sâu tổ chức khám sức khỏe, siêu âm, đo điện tim và cấp thuốc miễn phí cho người già neo '
                         'đơn.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 6.2 & 6.3 - Tuyến Tỉnh và Huyện',
    'illustration': 'ai_bai_1_community.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_34',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Mũi Nhọn Thực Thi Tuyến Xã: Trạm Y Tế & Mạng Lưới CTV Thôn Bản',
    'primary_claim': 'Gắn liền việc quản lý hồ sơ sức khỏe điện tử với các buổi sinh hoạt Hội Người cao tuổi cơ sở.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Nhiệm Vụ Trạm Y Tế Xã',
                 'text': 'Trực tiếp tổ chức khám sức khỏe định kỳ hàng năm cho 100% cụ già trên địa bàn; lập hồ sơ '
                         'bệnh án ngoại trú tăng huyết áp, tiểu đường; phân công y bác sĩ đến tận giường bệnh khám cho '
                         'các cụ già yếu không đi lại được.',
                 'icon': 'home'},
               { 'title': 'Nhiệm Vụ Cộng Tác Viên Dân Số',
                 'text': 'Đi từng ngõ, gõ từng nhà lập danh sách NCT theo 4 nhóm đối tượng; tư vấn người nhà chế độ '
                         'dinh dưỡng, nhắc lịch khám định kỳ và vận động các cụ tham gia câu lạc bộ dưỡng sinh, văn '
                         'nghệ.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 6. Mục 6.4 - Tuyến Xã và Cộng tác viên',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_35',
    'role': 'CONTENT',
    'section': 'LẬP KẾ HOẠCH CHĂM SÓC',
    'assertion_title': 'Quy Trình 5 Bước Lập Kế Hoạch Chăm Sóc Sức Khỏe Cá Nhân Hóa Cho NCT',
    'primary_claim': 'Phương pháp luận khoa học giúp người chăm sóc xác định đúng trọng tâm và tối ưu hóa nguồn lực.',
    'visual_job': 'CHART_AND_INSIGHTS',
    'visual_anchor': 'CHART_AND_INSIGHTS',
    'atoms': [ { 'title': '1. Đánh Giá Toàn Diện',
                 'text': 'Đánh giá chức năng ADL/IADL, tiền sử bệnh mạn, thị lực, thính lực và tâm lý.',
                 'icon': 'search'},
               { 'title': '2. Xác Định Vấn Đề',
                 'text': 'Nhận diện nguy cơ hàng đầu: nguy cơ ngã, biến chứng đường huyết hay cô đơn.',
                 'icon': 'alert-circle'},
               { 'title': '3. Thiết Lập Mục Tiêu',
                 'text': 'Mục tiêu cụ thể: ổn định huyết áp <130/80, tập đi lại 20m, tham gia 1 CLB.',
                 'icon': 'target'},
               { 'title': '4. Thực Hiện Can Thiệp',
                 'text': 'Phân công người nhà, y tá trạm hỗ trợ ăn uống, uống thuốc, cải tạo nhà cửa.',
                 'icon': 'activity'},
               { 'title': '5. Đánh Giá & Điều Chỉnh',
                 'text': 'Đánh giá lại sau mỗi tháng; điều chỉnh phác đồ phù hợp với tiến triển bệnh.',
                 'icon': 'refresh-cw'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình lập kế hoạch chăm sóc cá nhân hóa - BÀI 6 Câu 2',
    'chart_type': 'WATERFALL',
    'chart_file': 'chart_life_expectancy_waterfall_dark.png',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_36',
    'role': 'CONTENT',
    'section': 'LẬP KẾ HOẠCH CHĂM SÓC',
    'assertion_title': 'Đánh Giá Thang Điểm Chức Năng Sinh Hoạt Hàng Ngày (ADL & IADL)',
    'primary_claim': 'Công cụ lượng giá chuẩn mực quốc tế xác định chính xác mức độ phụ thuộc chăm sóc của người già.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Thang Điểm ADL Cơ Bản (Katz Index)',
                 'text': 'Đánh giá 6 chức năng sinh tồn tối thiểu: 1. Tự tắm rửa; 2. Tự mặc quần áo; 3. Tự đi vệ sinh; '
                         '4. Tự di chuyển từ giường ra ghế; 5. Tự chủ đại tiểu tiện; 6. Tự xúc ăn. Nếu suy giảm từ 2 '
                         'chức năng trở lên: Bắt buộc phải có người trợ giúp.',
                 'icon': 'activity'},
               { 'title': 'Thang Điểm IADL Nâng Cao (Lawton)',
                 'text': 'Đánh giá khả năng sống độc lập ngoài xã hội: 1. Sử dụng điện thoại; 2. Tự đi chợ mua sắm; 3. '
                         'Tự nấu nướng; 4. Dọn dẹp nhà cửa; 5. Giặt giũ; 6. Sử dụng phương tiện giao thông; 7. Tự quản '
                         'lý tiền bạc; 8. Tự uống thuốc đúng đơn.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Thang điểm chuẩn mực ADL & IADL Lão khoa',
    'illustration': 'illustration_bai_6.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_37',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 1: Lợi Ích Ba Chiều Của Dịch Vụ Chăm Sóc NCT Tại Cộng Đồng',
    'primary_claim': 'Học viên phân tích giá trị nhân văn và kinh tế xã hội sâu sắc đối với 3 chủ thể trung tâm.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Đối Với Người Cao Tuổi',
                 'text': 'Được sống vui, sống khỏe, sống có ích tại ngôi nhà thân yêu; bảo tồn lòng tự trọng, không bị '
                         'cô lập khỏi dòng chảy gia đình.',
                 'icon': 'heart'},
               { 'title': '2. Đối Với Gia Đình Con Cháu',
                 'text': 'Giảm bớt gánh nặng tâm lý và kiệt sức chăm sóc; con cái an tâm công tác đóng góp cho xã hội '
                         'khi cha mẹ được chăm lo chu đáo.',
                 'icon': 'smile'},
               { 'title': '3. Đối Với Hệ Thống Y Tế & Xã Hội',
                 'text': 'Giảm quá tải trầm trọng cho các bệnh viện tuyến trên; xây dựng một cộng đồng giàu lòng nhân '
                         'ái, kính lão đắc thọ.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Câu hỏi lượng giá số 1 - BÀI 6',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_38',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 2: Tại Sao Phải Chuẩn Bị Già Hóa Từ Sớm Khi Đang Trong Tuổi Lao Động?',
    'primary_claim': 'Già hóa thành công (Active Ageing) bắt đầu từ lối sống lành mạnh và tích lũy an sinh từ tuổi '
                     'thanh xuân.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tích Lũy Sức Khỏe Thể Chất',
                 'text': 'Phòng chống tăng huyết áp, tiểu đường từ tuổi 30-40 bằng chế độ ăn giảm muối, hạn chế rượu '
                         'bia, tập thể thao hằng ngày.',
                 'icon': 'activity'},
               { 'title': 'Tích Lũy Tài Chính An Sinh',
                 'text': 'Tham gia Bảo hiểm xã hội bắt buộc hoặc tự nguyện để có lương hưu; mua Bảo hiểm y tế liên tục '
                         'bảo vệ tài chính khi về già.',
                 'icon': 'award'},
               { 'title': 'Tích Lũy Kỹ Năng & Tâm Lý',
                 'text': 'Xây dựng các mối quan hệ bạn bè gắn kết, chuẩn bị tâm lý đón nhận tuổi hưu, học hỏi các sở '
                         'thích tao nhã như đọc sách, làm vườn.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Lý luận già hóa chủ động - BÀI 6 Câu 2',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_39',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 3a: Thuận Lợi & Khó Khăn Triển Khai Quyết Định 1579 Tại Địa Phương',
    'primary_claim': 'Nhìn nhận khách quan thực trạng cơ sở để xác định những điểm nghẽn cần khơi thông.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Những Thuận Lợi Cơ Bản',
                 'text': "Đảng và Nhà nước ban hành đầy đủ khung chính sách đồng bộ; đạo lý 'Kính già, trọng lão' ăn "
                         'sâu vào văn hóa người Việt; mạng lưới Hội Người cao tuổi phủ kín 100% thôn xóm.',
                 'icon': 'check-circle'},
               { 'title': 'Những Rào Cản Thách Thức',
                 'text': 'Nguồn kinh phí y tế cơ sở còn hạn hẹp; trạm y tế thiếu bác sĩ chuyên khoa lão; con cái đi '
                         'làm ăn xa để lại người già neo đơn; dịch vụ chăm sóc người già tư nhân chưa phát triển ở '
                         'nông thôn.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Câu hỏi lượng giá số 3a - BÀI 6',
    'illustration': 'ai_bai_2_aging.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_40',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 3b: Nhóm Giải Pháp Đột Phá Đạt Mục Tiêu Quyết Định 1579 Đến 2030',
    'primary_claim': 'Đề xuất các sáng kiến thực tiễn kết hợp ngân sách, bảo hiểm y tế và phát huy nội lực cộng đồng.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Đào Tạo Kỹ Năng Cho Người Nhà',
                 'text': 'Mở các lớp tập huấn ngắn ngày tại trạm y tế hướng dẫn con cháu kỹ thuật lật trở mình, sơ cứu '
                         'nghẹn sặc, chống loét tỳ đè.',
                 'icon': 'book-open'},
               { 'title': 'Nhân Rộng Mô Hình CLB ISHC',
                 'text': 'Tham mưu cấp ủy, chính quyền trích quỹ hỗ trợ ban đầu để thành lập mới các CLB Liên thế hệ '
                         'tự giúp nhau tại 100% thôn.',
                 'icon': 'heart'},
               { 'title': 'Bảo Hiểm Y Tế Chi Trả Tại Nhà',
                 'text': 'Đề xuất cơ chế thanh toán BHYT cho dịch vụ bác sĩ gia đình và điều dưỡng trạm y tế đến khám '
                         'bệnh, cấp thuốc tại nhà cho NCT.',
                 'icon': 'award'},
               { 'title': 'Ưu Đãi Thuế Cho Doanh Nghiệp Lão Khoa',
                 'text': 'Miễn giảm thuế, giao đất sạch cho các tổ chức, doanh nghiệp đầu tư viện dưỡng lão, trung tâm '
                         'sinh hoạt ban ngày cho NCT.',
                 'icon': 'trending-up'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Kế hoạch giải pháp thực thi QĐ 1579 - BÀI 6 Câu 3b',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_41',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'Khung Kiến Trúc Hệ Thống Chăm Sóc Dài Hạn (LTC) Thích Ứng Già Hóa Dân Số',
    'primary_claim': 'Mô hình kim tự tháp 3 tầng bảo đảm mọi người cao tuổi đều được tiếp cận dịch vụ phù hợp.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tầng 1: Tự Chăm Sóc & Gia Đình (80%)',
                 'text': 'NCT tự chăm sóc kết hợp hỗ trợ của con cháu tại nhà; tham gia CLB thể thao dưỡng sinh, CLB '
                         'Liên thế hệ tự giúp nhau.',
                 'icon': 'home'},
               { 'title': 'Tầng 2: Dịch Vụ Bán Bán Trú & Trạm Xã (15%)',
                 'text': 'Trạm y tế quản lý bệnh mạn tính; điểm chăm sóc sức khỏe ban ngày tại nhà văn hóa thôn; nhân '
                         'viên y tế đến thăm hộ.',
                 'icon': 'activity'},
               { 'title': 'Tầng 3: Cơ Sở Chăm Sóc Tập Trung (5%)',
                 'text': 'Viện dưỡng lão chuyên nghiệp, khoa lão bệnh viện tiếp nhận người già bệnh nặng giai đoạn '
                         'cuối hoặc không còn người thân.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Mô hình hệ thống chăm sóc dài hạn (Long-term Care)',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_42',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'Chuyển Đổi Số: Hồ Sơ Sức Khỏe Điện Tử Quản Lý Người Cao Tuổi Tại Trạm Xã',
    'primary_claim': 'Ứng dụng phần mềm dân số y tế số hóa toàn bộ dữ liệu khám chữa bệnh của người cao tuổi.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Sổ Sức Khỏe Điện Tử VNeID',
                 'text': 'Tích hợp toàn bộ lịch sử khám bệnh, đơn thuốc, chỉ số huyết áp vào ứng dụng định danh điện '
                         'tử công dân.',
                 'icon': 'globe'},
               { 'title': 'Cảnh Báo Tự Động Uống Thuốc',
                 'text': 'Hệ thống tin nhắn SMS, Zalo nhắc nhở lịch uống thuốc hằng ngày và thông báo ngày hẹn tái '
                         'khám tại trạm y tế.',
                 'icon': 'clock'},
               { 'title': 'Thiết Bị Đeo Y Tế Thông Minh (Wearables)',
                 'text': 'Thí điểm đồng hồ thông minh đo nhịp tim, phát hiện té ngã tự động gọi cấp cứu 115 cho người '
                         'già sống đơn thân.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chuyển đổi số trong quản lý sức khỏe người cao tuổi',
    'illustration': 'cinematic_bai_1_hero.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_43',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'Sơ Đồ Quy Trình Phối Hợp 4 Bên Chăm Sóc NCT Tại Thôn Xóm',
    'primary_claim': 'Mối liên kết chặt chẽ tạo thành lưới an sinh khép kín che chở cho người cao tuổi.',
    'visual_job': 'PROCESS_STEPS_HORIZONTAL',
    'visual_anchor': 'PROCESS_CARDS',
    'atoms': [ { 'title': '1. Gia Đình Con Cháu',
                 'text': 'Yêu thương, nấu ăn, nhắc uống thuốc và hỗ trợ sinh hoạt hàng ngày.',
                 'icon': 'heart'},
               { 'title': '2. CTV Dân Số',
                 'text': 'Thăm hộ thường xuyên, nắm bắt nhu cầu và vận động tham gia CLB.',
                 'icon': 'users'},
               { 'title': '3. Trạm Y Tế Xã',
                 'text': 'Khám định kỳ, cấp thuốc mãn tính, khám tại giường cho cụ già yếu.',
                 'icon': 'home'},
               { 'title': '4. CLB Liên Thế Hệ',
                 'text': 'Tình nguyện viên thăm sóc, hỗ trợ vay vốn và giao lưu văn nghệ.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Sơ đồ mạng lưới chăm sóc cơ sở - BÀI 6',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_44',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': "Đạo Lý Dân Tộc: 'Kính Lão Đắc Thọ' - Tài Sản Tinh Thần Vô Giá Của Xã Hội",
    'primary_claim': 'Chăm lo cho người già không chỉ là trách nhiệm y tế mà là thước đo nhân văn và văn minh của đất '
                     'nước.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Truyền Thống Uống Nước Nhớ Nguồn',
                 'text': 'Tri ân công lao sinh thành dưỡng dục và những cống hiến trọn đời của thế hệ cha anh cho độc '
                         'lập và phát triển đất nước.',
                 'icon': 'award'},
               { 'title': 'Gia Phong Hòa Thuận',
                 'text': 'Gia đình có ông bà mạnh khỏe, vui vẻ là phước báu lớn nhất; con cháu được sống trong tình '
                         'yêu thương và rèn luyện nhân cách.',
                 'icon': 'heart'},
               { 'title': 'Xã Hội Bình An, Nhân Ái',
                 'text': 'Một cộng đồng biết chăm sóc, tôn vinh người cao tuổi là một xã hội nhân văn, tiến bộ và phát '
                         'triển bền vững.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Giá trị đạo lý văn hóa truyền thống Việt Nam',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_45',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'Tác Động Lan Tỏa Của Chăm Sóc Người Cao Tuổi Đến Chiến Lược Dân Số',
    'primary_claim': 'Gắn kết hữu cơ giữa chăm sóc người già với duy trì mức sinh thay thế và nâng cao chất lượng '
                     'nguồn nhân lực.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Giải Tỏa Áp Lực Cho Thế Hệ Trẻ',
                 'text': 'Khi người già được hệ thống dịch vụ cộng đồng hỗ trợ chăm sóc tốt, các cặp vợ chồng trẻ sẽ '
                         'giảm bớt gánh nặng kiệt sức, yên tâm sinh đủ 2 con và tích cực cống hiến lao động.',
                 'icon': 'trending-up'},
               { 'title': 'Hiện Thực Hóa Mục Tiêu Nghị Quyết 21',
                 'text': 'Chuyển trọng tâm chính sách dân số sang Dân số và Phát triển: giải quyết đồng bộ quy mô, cơ '
                         'cấu, phân bố và chủ động thích ứng với già hóa dân số nhanh chóng.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chiến lược Dân số Việt Nam đến năm 2030',
    'illustration': 'ai_bai_1_community.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_46',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'Bài Học Kinh Nghiệm Quốc Tế Về Thích Ứng Già Hóa Dân Số (Nhật Bản, Đức)',
    'primary_claim': 'Những bài học thực tiễn quý báu từ các quốc gia siêu già về bảo hiểm chăm sóc dài hạn (LTCI).',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Mô Hình Bảo Hiểm Chăm Sóc (LTCI)',
                 'text': 'Người dân đóng bảo hiểm chăm sóc từ tuổi 40; khi về già nếu bị suy giảm chức năng sẽ được '
                         'chi trả 90% chi phí người chăm sóc tại nhà.',
                 'icon': 'shield-check'},
               { 'title': 'Đô Thị Thân Thiện Với Người Già',
                 'text': 'Thiết kế vỉa hè phẳng, xe buýt sàn thấp, công viên có đường dạo bộ và ghế nghỉ; không để rào '
                         'cản cản trở người già di chuyển.',
                 'icon': 'globe'},
               { 'title': 'Việc Làm Linh Hoạt Cho NCT',
                 'text': 'Khuyến khích người cao tuổi còn sức khỏe làm các công việc bán thời gian phù hợp (trông giữ '
                         'trẻ, thủ thư, bảo vệ) để duy trì sự nhanh nhẹn.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Kinh nghiệm quốc tế thích ứng già hóa dân số',
    'illustration': 'illustration_bai_6.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_47',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'Sứ Mệnh Của Cán Bộ Y Tế Dân Số Trong Kỷ Nguyên Mới',
    'primary_claim': 'Người tiên phong chuyển tải tình thương và nghiệp vụ y tế chuẩn mực đến từng mái ấm gia đình.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tâm Huyết & Thấu Cảm',
                 'text': 'Đến với người cao tuổi bằng sự kính trọng, lắng nghe nhẫn nại, xem nỗi đau bệnh tật của các '
                         'cụ như của chính cha mẹ mình.',
                 'icon': 'heart'},
               { 'title': 'Chuyên Nghiệp Về Kỹ Năng',
                 'text': 'Thành thạo kỹ năng tư vấn, quy trình chăm sóc y tế tại nhà, kỹ năng hướng dẫn vận động và sơ '
                         'cứu khẩn cấp tuổi già.',
                 'icon': 'shield-check'},
               { 'title': 'Kết Nối Xã Hội Hóa',
                 'text': 'Khéo léo vận động các nhà hảo tâm, đoàn thể, thanh niên cùng chung tay xây dựng quỹ và hỗ '
                         'trợ các cụ già có hoàn cảnh éo le.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Sứ mệnh người cán bộ y tế dân số',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_48',
    'role': 'CONTENT',
    'section': 'TỔNG KẾT BÀI HỌC',
    'assertion_title': 'Thông Điệp Khép Lại Khóa Học: Vì Một Xã Hội Thích Ứng Già Hóa Nhân Văn, Bền Vững',
    'primary_claim': 'Khép lại chuỗi 6 chuyên đề Dịch vụ Dân số với niềm tin son sắt vào chất lượng giống nòi Việt '
                     'Nam.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Đầu Vòng Đời: Định hướng phát triển',
                 'text': 'Từ khám sức khỏe tiền hôn nhân (Bài 2), KHHGĐ (Bài 3), chăm sóc thanh thiếu niên (Bài 4) đến '
                         'sàng lọc trước sinh và sơ sinh (Bài 5).',
                 'icon': 'award'},
               { 'title': 'Cuối Vòng Đời: An Nhiên Tuổi Vàng',
                 'text': 'Đến chăm sóc toàn diện người cao tuổi tại cộng đồng (Bài 6), bảo đảm mỗi công dân sinh ra '
                         'khỏe mạnh và về già được an dưỡng thanh nhàn.',
                 'icon': 'heart'},
               { 'title': 'Dân Tộc Việt Nam Cường Thịnh',
                 'text': 'Xây dựng quy mô dân số hợp lý, cơ cấu vàng bền vững, chất lượng giống nòi nâng cao đưa đất '
                         'nước vươn mình hùng cường trong kỷ nguyên mới.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Lời kết toàn khóa học Dịch vụ Dân số - Make Slide Pro V8.6.0',
    'v91_compliant': True}]
