# -*- coding: utf-8 -*-
"""
scripts/course2_data_bai2.py
Exhaustive Deep-Curriculum Slide Blueprints for BÀI 2 (Make Slide Pro V9.1).
30%-50% High-Resolution Visual Illustrations, Native Charts, Zero AI Slop, Zero Watermarks.
"""

from typing import Any, Dict, List


def get_slides_bai_2() -> List[Dict[str, Any]]:
    return [ { 'slide_id': 'SLIDE_01',
    'role': 'COVER',
    'section': 'TỔNG QUAN CHUYÊN ĐỀ',
    'assertion_title': 'BÀI 2: DỊCH VỤ TƯ VẤN, KHÁM SỨC KHỎE TRƯỚC KHI KẾT HÔN',
    'primary_claim': 'Khung nghiệp vụ y tế dân số toàn diện về chăm sóc tiền hôn nhân, phòng ngừa bệnh di truyền, bảo '
                     'đảm hôn nhân bền vững và nâng cao chất lượng giống nòi.',
    'visual_job': 'HERO_TITLE',
    'visual_anchor': 'BRAND_COVER',
    'transition': 'fade',
    'transition_duration': 0.65,
    'illustration': 'illustration_bai_2.jpg',
    'speaker_notes': 'Kính chào quý học viên, hôm nay chúng ta nghiên cứu chuyên đề Bài 2: Dịch vụ tư vấn, khám sức '
                     'khỏe trước khi kết hôn.',
    'source_footer': 'Tài liệu đào tạo chuẩn hóa: BÀI 2. Dịch vụ tư vấn, khám sức khỏe trước khi kết hôn.docx',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_02',
    'role': 'CONTENT',
    'section': 'MỤC TIÊU BÀI HỌC',
    'assertion_title': 'Chuẩn Đầu Ra 5 Khối Năng Lực Cốt Lõi Về Khám Sức Khỏe Tiền Hôn Nhân',
    'primary_claim': 'Trang bị cho cán bộ dân số - y tế phương pháp luận và kỹ năng tác nghiệp từ lý luận phân loại '
                     'đến quản lý thực địa.',
    'visual_job': 'CONTAINER_BENTO_COMPLEX',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': '1. Khái Niệm & Phân Loại',
                 'text': 'Trình bày chính xác bản chất giai đoạn trước kết hôn, phân biệt rành mạch tư vấn và khám sức '
                         'khỏe theo 3 trục hệ thống.',
                 'icon': 'book-open'},
               { 'title': '2. Khách Hàng & Pháp Lý',
                 'text': 'Làm chủ đặc điểm tâm sinh lý, khung pháp lý độ tuổi Luật Hôn nhân & Gia đình 2014 và nhu cầu '
                         'đa dạng của thanh niên.',
                 'icon': 'users'},
               { 'title': '3. Chuẩn Hóa Cơ Sở Cung Cấp',
                 'text': 'Nắm vững tiêu chuẩn cơ sở vật chất, trang thiết bị y tế và chuẩn năng lực chuyên môn của cán '
                         'bộ tư vấn - khám sức khỏe.',
                 'icon': 'shield-check'},
               { 'title': '4. Quy Trình Nghiệp Vụ 2 Giai Đoạn',
                 'text': 'Thực hiện thành thạo gói can thiệp tư vấn trước - sau khám, khám thể lực, khám lâm sàng '
                         'nam/nữ và bộ 4 kỹ thuật cận lâm sàng.',
                 'icon': 'activity'},
               { 'title': '5. Quản Lý Hệ Thống 4 Tuyến',
                 'text': 'Triển khai điều hành, giám sát theo Quyết định 25/QĐ-BYT nhằm đạt mục tiêu 90% cặp đôi tiền '
                         'hôn nhân của Chiến lược 2030.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Khung chuẩn đầu ra chuyên đề đào tạo dịch vụ dân số',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_03',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Giai Đoạn Trước Kết Hôn Và Quá Trình Trưởng Thành Nhân Khẩu Học',
    'primary_claim': 'Trước kết hôn là quãng thời gian chuyển tiếp quyết định chất lượng nguồn nhân lực và sự bền vững '
                     'của đơn vị gia đình.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Mốc Thời Gian Sinh Học',
                 'text': 'Tính từ thời điểm một cá nhân bắt đầu bước vào giai đoạn trưởng thành sinh học cho đến khi '
                         'chính thức xác lập hôn nhân pháp lý.',
                 'icon': 'clock'},
               { 'title': 'Nhóm Vị Thành Niên',
                 'text': 'Bao gồm cả trẻ vị thành niên (10-19 tuổi) dù chưa hoàn thiện về mặt tâm lý - xã hội nhưng bộ '
                         'máy sinh sản đã bắt đầu hoạt động.',
                 'icon': 'heart'},
               { 'title': 'Ý Nghĩa Nhân Khẩu',
                 'text': 'Là giai đoạn bản lề chuẩn bị tri thức, thể chất và tâm lý trước khi bước vào chu kỳ tái sản '
                         'xuất dân số mới.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tài liệu Dịch vụ Dân số - Khái niệm trước kết hôn',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_04',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Bản Chất Và Mục Tiêu Cốt Lõi Của Hoạt Động Tư Vấn Sức Khỏe',
    'primary_claim': 'Tư vấn không phải là ban hành mệnh lệnh y khoa mà là quá trình tương tác hỗ trợ khách hàng tự '
                     'đưa ra quyết định tối ưu.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': '1. Thiết Lập Tin Cậy',
                 'text': 'Cán bộ tư vấn tạo dựng mối quan hệ tương tác bình đẳng, thấu cảm và bảo đảm tuyệt đối bí mật '
                         'riêng tư.',
                 'icon': 'user-check'},
               { 'title': '2. Cung Cấp Tri Thức',
                 'text': 'Truyền tải các chứng cứ y học chính xác về SKSS/SKTD, các bệnh di truyền và nguy cơ tiềm ẩn '
                         'một cách dễ hiểu.',
                 'icon': 'book-open'},
               { 'title': '3. Giải Tỏa Rào Cản',
                 'text': 'Lắng nghe, tháo gỡ lo âu tâm lý, định kiến giới hoặc sự mặc cảm cá nhân của các bạn trẻ '
                         'trước ngưỡng cửa hôn nhân.',
                 'icon': 'shield'},
               { 'title': '4. Tự Chủ Quyết Định',
                 'text': 'Trang bị đầy đủ dữ liệu giúp khách hàng tự lựa chọn giải pháp chăm sóc y tế phù hợp nhất cho '
                         'hạnh phúc lứa đôi.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Nguyên lý truyền thông chuyển đổi hành vi y tế dân số',
    'illustration': 'illustration_bai_2.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_05',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Tư Vấn Sức Khỏe Trước Kết Hôn Là Loại Hình Tư Vấn Chuyên Biệt',
    'primary_claim': 'Được thiết kế riêng biệt cho các cặp đôi chuẩn bị lập gia đình nhằm giải quyết hài hòa ba mục '
                     'tiêu gia đình và xã hội.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Kiến Thức Y Khoa Thực Chứng',
                 'text': 'Cung cấp hiểu biết khoa học về sinh lý sinh dục, vệ sinh tình dục an toàn và các thời điểm '
                         'sinh con lý tưởng.',
                 'icon': 'file-text'},
               { 'title': 'Bảo Đảm Hôn Nhân Bền Vững',
                 'text': 'Phòng ngừa mâu thuẫn gia đình do trục trặc chức năng tình dục, vô sinh - hiếm muộn hoặc các '
                         'cú sốc bệnh tật sau cưới.',
                 'icon': 'heart'},
               { 'title': 'Nâng Cao Chất Lượng Giống Nòi',
                 'text': 'Chặn đứng các chuỗi truyền bệnh tật di truyền nguy hiểm, bảo đảm trẻ em sinh ra phát triển '
                         'toàn diện thể chất và trí tuệ.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Dịch vụ tư vấn, khám sức khỏe trước khi kết hôn',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_06',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Khám Sức Khỏe Trước Kết Hôn: Hai Trụ Cột Đánh Giá Lâm Sàng',
    'primary_claim': 'Khám sức khỏe tiền hôn nhân là sự tích hợp hữu cơ giữa sàng lọc toàn diện cơ thể và chuyên sâu '
                     'cơ quan sinh sản.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Trụ Cột 1: Khám Sức Khỏe Tổng Thể',
                 'text': 'Đánh giá chức năng tim mạch, hô hấp, gan, thận, nội tiết và tầm soát các bệnh lý mạn tính có '
                         'thể chuyển nặng khi mang thai như đái tháo đường, suy tim, thiếu máu.',
                 'icon': 'activity'},
               { 'title': 'Trụ Cột 2: Khám Cơ Quan Sinh Sản',
                 'text': 'Khám chi tiết cấu trúc giải phẫu hệ sinh dục nam (tinh hoàn, dương vật, tuyến tiền liệt) và '
                         'nữ (tử cung, buồng trứng, âm đạo) nhằm phát hiện sớm dị tật hoặc viêm nhiễm.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Hướng dẫn chuyên môn khám sức khỏe tiền hôn nhân - Bộ Y tế',
    'illustration': 'illustration_bai_2_structure.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_07',
    'role': 'CONTENT',
    'section': '1. KHÁI NIỆM NỀN TẢNG',
    'assertion_title': 'Định Nghĩa Toàn Diện Về Dịch Vụ Tư Vấn, Khám Sức Khỏe Trước Kết Hôn',
    'primary_claim': 'Là chuỗi dịch vụ y tế dự phòng chủ động dành cho nam, nữ nhằm bảo vệ chức năng sinh sản và sàng '
                     'lọc phôi thai.',
    'visual_job': 'CONTAINER_CALLOUT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Đối Tượng Trọng Tâm',
                 'text': 'Dành cho nam, nữ chuẩn bị kết hôn, đặc biệt mở rộng đến lứa tuổi vị thành niên và thanh niên '
                         'trong độ tuổi sinh sản.',
                 'icon': 'users'},
               { 'title': 'Nhiệm Vụ Y Học Cốt Lõi',
                 'text': 'Phát hiện sớm, phòng ngừa và hướng dẫn điều trị kịp thời các bệnh lý ảnh hưởng đến mang '
                         'thai, sinh nở và nuôi con bằng sữa mẹ.',
                 'icon': 'shield-check'},
               { 'title': 'Giá Trị Gia Đình & Dân Tộc',
                 'text': 'Loại trừ rủi ro sinh con mắc bệnh tật bẩm sinh, bảo đảm hạnh phúc hôn nhân bền vững và củng '
                         'cố vững chắc chất lượng giống nòi.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Khái niệm chuẩn tắc - BÀI 2. Mục 1',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_08',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Ba Trục Phân Loại Hệ Thống Dịch Vụ Tiền Hôn Nhân',
    'primary_claim': 'Việc phân loại khoa học tạo tiền đề xây dựng danh mục dịch vụ kỹ thuật, định mức tài chính và '
                     'phân công quản lý.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': '1. Theo Tiêu Chí Giới Tính',
                 'text': 'Chia tách dịch vụ dành riêng cho nam giới (Nam học) và nữ giới (Sản phụ khoa) phù hợp với '
                         'giải phẫu sinh sản.',
                 'icon': 'users'},
               { 'title': '2. Theo Nội Dung Kỹ Thuật',
                 'text': 'Phân tầng từ tư vấn giáo dục tâm lý, khám lâm sàng thể lực tổng quát đến các xét nghiệm cận '
                         'lâm sàng chuyên sâu.',
                 'icon': 'layers'},
               { 'title': '3. Theo Chủ Sở Hữu Cơ Sở',
                 'text': 'Phân định giữa mạng lưới bệnh viện, trung tâm y tế Nhà nước (công lập) và các bệnh viện, '
                         'phòng khám tư nhân.',
                 'icon': 'home'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tài liệu đào tạo chuẩn hóa BÀI 2 - Mục 2',
    'illustration': 'ai_bai_2_golden.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_09',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Phân Loại Theo Giới Tính: Khác Biệt Trọng Tâm Can Thiệp Nam Và Nữ',
    'primary_claim': 'Tiếp cận y học giới tính bảo đảm tính chuẩn xác và sự thoải mái tế nhị tối đa cho từng nhóm đối '
                     'tượng.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Dịch Vụ Dành Cho Nam Giới',
                 'text': 'Tập trung tư vấn tâm lý tính dục phái mạnh; khám cơ quan sinh dục ngoài, tinh hoàn, mào '
                         'tinh; phân tích tinh dịch đồ, xét nghiệm dịch niệu đạo và chức năng cương dương.',
                 'icon': 'shield'},
               { 'title': 'Dịch Vụ Dành Cho Nữ Giới',
                 'text': 'Tập trung tư vấn chu kỳ kinh nguyệt, khả năng thụ thai; khám vú, cơ quan sinh dục ngoài, '
                         'tầng sinh môn; siêu âm tử cung - buồng trứng và soi tươi dịch âm đạo.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình lâm sàng nam - nữ học Bộ Y tế',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_10',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Phân Loại Theo Nội Dung Kỹ Thuật: 3 Cấp Độ Can Thiệp Bổ Trợ Nhau',
    'primary_claim': 'Khách hàng được tiếp cận theo lộ trình từ tư vấn nhận thức đến chẩn đoán xác định bệnh lý.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Cấp Độ 1: Dịch Vụ Tư Vấn',
                 'text': 'Trao đổi thông tin, giải đáp thắc mắc về giới tính, tình bạn, tình yêu, KHHGĐ và chuẩn bị '
                         'tâm lý xây dựng tổ ấm.',
                 'icon': 'message-circle'},
               { 'title': 'Cấp Độ 2: Khám Tổng Quát',
                 'text': 'Đo lường thể lực cơ bản, khám tim mạch, huyết áp, chụp X-quang phổi và xét nghiệm huyết học, '
                         'sinh hóa thường quy.',
                 'icon': 'activity'},
               { 'title': 'Cấp Độ 3: Khám Chuyên Khoa Sâu',
                 'text': 'Xét nghiệm gen di truyền (Thalassemia), giải trình tự gen, xét nghiệm miễn dịch vi-rút và '
                         'thăm dò chức năng chuyên sâu.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Phân loại theo nội dung dịch vụ',
    'illustration': 'ai_bai_2_quality.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_11',
    'role': 'CONTENT',
    'section': '2. PHÂN LOẠI DỊCH VỤ',
    'assertion_title': 'Phân Loại Theo Chủ Sở Hữu: Phối Hợp Công Lập Và Tư Nhân',
    'primary_claim': 'Huy động đa dạng các thành phần kinh tế tham gia xã hội hóa dịch vụ chăm sóc sức khỏe tiền hôn '
                     'nhân.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Cơ Sở Y Tế Nhà Nước (Công Lập)',
                 'text': 'Hệ thống Bệnh viện Phụ sản, Bệnh viện Đa khoa, Trung tâm Y tế huyện và Trạm y tế xã; thế '
                         'mạnh là độ bao phủ rộng khắp, chi phí hợp lý và gắn liền với các chương trình mục tiêu quốc '
                         'gia.',
                 'icon': 'shield-check'},
               { 'title': 'Cơ Sở Y Tế Tư Nhân (Xã Hội Hóa)',
                 'text': 'Các phòng khám đa khoa, bệnh viện quốc tế tư nhân; thế mạnh là cơ sở vật chất hiện đại, dịch '
                         'vụ linh hoạt, đặt lịch hẹn trực tuyến nhanh chóng nhưng chi phí chi trả cao hơn.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Phân loại theo chủ sở hữu cung cấp dịch vụ',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_12',
    'role': 'CONTENT',
    'section': '3. ĐẶC ĐIỂM KHÁCH HÀNG',
    'assertion_title': 'Khách Hàng Mục Tiêu Của Dịch Vụ Trước Kết Hôn',
    'primary_claim': 'Đối tượng trọng tâm là nam, nữ thanh niên chuẩn bị bước vào cuộc sống hôn nhân và tái sản xuất '
                     'gia đình.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Nam Nữ Chuẩn Bị Kết Hôn',
                 'text': 'Các cặp đôi đang trong giai đoạn tìm hiểu, đính hôn hoặc chuẩn bị đăng ký kết hôn tại chính '
                         'quyền địa phương.',
                 'icon': 'heart'},
               { 'title': 'Vị Thành Niên & Thanh Niên',
                 'text': 'Các bạn trẻ muốn chủ động trang bị kiến thức chăm sóc bản thân, kiểm tra sức khỏe sinh sản '
                         'trước khi có kế hoạch lập gia đình.',
                 'icon': 'users'},
               { 'title': 'Cặp Đôi Có Tiền Sử Bệnh Tật',
                 'text': 'Những người bản thân hoặc gia đình có tiền sử mắc dị tật bẩm sinh, bệnh di truyền cần được '
                         'tư vấn sàng lọc chuyên biệt.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Khách hàng mục tiêu',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_13',
    'role': 'CONTENT',
    'section': '3. ĐẶC ĐIỂM KHÁCH HÀNG',
    'assertion_title': 'Khung Pháp Lý Về Độ Tuổi Kết Hôn Theo Luật Hôn Nhân & Gia Đình 2014',
    'primary_claim': 'Pháp luật quy định độ tuổi tối thiểu nhằm bảo đảm sự trưởng thành sinh học và năng lực hành vi '
                     'dân sự.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Độ Tuổi Kết Hôn Pháp Định (Điều 8)',
                 'text': 'Nam từ đủ 20 tuổi trở lên; Nữ từ đủ 18 tuổi trở lên. Pháp luật nghiêm cấm hành vi tảo hôn '
                         'hoặc ép buộc kết hôn khi chưa đủ tuổi luật định.',
                 'icon': 'award'},
               { 'title': 'Quyền Tự Quyết Hôn Nhân Hiện Đại',
                 'text': 'Luật không quy định độ tuổi tối đa và không quy định khoảng cách tuổi giữa hai bên. Mỗi công '
                         'dân có toàn quyền lựa chọn người bạn đời phù hợp với chuẩn mực cá nhân.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Luật Hôn nhân và gia đình năm 2014 - Điều 8',
    'illustration': 'cinematic_bai_1_hero.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_14',
    'role': 'CONTENT',
    'section': '3. ĐẶC ĐIỂM KHÁCH HÀNG',
    'assertion_title': 'Tính Đa Dạng Của Khách Hàng Trong Xã Hội Hiện Đại',
    'primary_claim': 'Sự đa dạng về độ tuổi, học vấn và điều kiện kinh tế đòi hỏi công tác dân số phải cá nhân hóa gói '
                     'dịch vụ.',
    'visual_job': 'CHART_AND_INSIGHTS',
    'visual_anchor': 'CHART_AND_INSIGHTS',
    'atoms': [ { 'title': 'Đa Dạng Về Độ Tuổi',
                 'text': 'Trải rộng từ độ tuổi vị thành niên (sớm nhất) đến thanh niên trưởng thành và cả những đối '
                         'tượng kết hôn muộn.',
                 'icon': 'clock'},
               { 'title': 'Khác Biệt Nhận Thức',
                 'text': 'Trình độ học vấn không đồng đều; một bộ phận còn e ngại, xem việc khám sức khỏe sinh sản là '
                         'biểu hiện thiếu tin tưởng bạn đời.',
                 'icon': 'book-open'},
               { 'title': 'Phân Hóa Kinh Tế',
                 'text': 'Khả năng chi trả khác biệt giữa khu vực đô thị phát triển và vùng sâu, vùng xa, đồng bào dân '
                         'tộc thiểu số.',
                 'icon': 'trending-up'},
               { 'title': 'Đòi Hỏi Đáp Ứng Linh Hoạt',
                 'text': 'Cơ quan dân số cần phát triển nhiều gói dịch vụ từ miễn phí công lập đến dịch vụ theo yêu '
                         'cầu chất lượng cao.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tài liệu phân tích đối tượng dịch vụ dân số',
    'chart_type': 'BAR_CLUSTERED',
    'chart_file': 'chart_sex_ratio_birth_heatmap_dark.png',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_15',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ & NGƯỜI CUNG CẤP',
    'assertion_title': 'Tiêu Chuẩn Cơ Sở Vật Chất Cung Cấp Dịch Vụ Tư Vấn',
    'primary_claim': 'Cơ sở tư vấn phải đáp ứng nghiêm ngặt tính riêng tư, bảo mật và khả năng kết nối đa kênh truyền '
                     'thông.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tư Vấn Trực Tiếp (Face-to-Face)',
                 'text': 'Phòng tư vấn riêng tư, cách âm, ấm cúng, có góc truyền thông và trang bị đầy đủ tài liệu '
                         'trực quan, mô hình giải phẫu.',
                 'icon': 'user-check'},
               { 'title': 'Tư Vấn Tổng Đài Điện Thoại',
                 'text': 'Đường dây nóng kết nối thông suốt, trực 24/7 giải đáp nhanh các tình huống khẩn cấp về '
                         'SKSS/KHHGĐ.',
                 'icon': 'phone'},
               { 'title': 'Tư Vấn Trực Tuyến Internet',
                 'text': 'Hệ thống Cổng thông tin, website, ứng dụng di động và mạng xã hội tiếp cận thân thiện giới '
                         'trẻ hiện đại.',
                 'icon': 'globe'},
               { 'title': 'Tư Vấn Chuyên Sâu Qua Thư',
                 'text': 'Hòm thư tư vấn chuyên đề giải đáp cặn kẽ những câu hỏi thầm kín mang tính cá nhân nhạy cảm.',
                 'icon': 'mail'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy định cơ sở tư vấn tiền hôn nhân - BÀI 2. Mục 4',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_16',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ & NGƯỜI CUNG CẤP',
    'assertion_title': 'Tiêu Chuẩn Năng Lực Chuyên Môn Của Cán Bộ Tư Vấn Tiền Hôn Nhân',
    'primary_claim': 'Cán bộ tư vấn là linh hồn của dịch vụ, đòi hỏi sự kết hợp giữa tri thức y khoa và nghệ thuật '
                     'giao tiếp.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Chứng Chỉ Chuyên Môn SKSS',
                 'text': 'Được đào tạo, cấp chứng chỉ bài bản về Sức khỏe tình dục, Sức khỏe sinh sản và Dân số - Kế '
                         'hoạch hóa gia đình.',
                 'icon': 'award'},
               { 'title': 'Am Hiểu Bệnh Lý Di Truyền',
                 'text': 'Có kiến thức sâu sắc về các loại bệnh, tật bẩm sinh ở trẻ sơ sinh, quy luật di truyền Mendel '
                         'và dịch tễ học Thalassemia.',
                 'icon': 'activity'},
               { 'title': 'Kỹ Năng Giao Tiếp Thấu Cảm',
                 'text': 'Lắng nghe không phán xét, tôn trọng quyền lựa chọn cá nhân và giữ cam kết bảo mật thông tin '
                         'khách hàng tuyệt đối.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Chuẩn năng lực cán bộ tư vấn - Quyết định số 25/QĐ-BYT',
    'illustration': 'illustration_bai_2.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_17',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ & NGƯỜI CUNG CẤP',
    'assertion_title': 'Tiêu Chuẩn Kỹ Thuật Cơ Sở Khám Sức Khỏe Trước Kết Hôn',
    'primary_claim': 'Cơ sở thực hiện thăm khám bắt buộc phải có giấy phép hoạt động và trang thiết bị lâm sàng chuẩn '
                     'mực.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Cơ Sở Vật Chất Y Tế Chuẩn',
                 'text': 'Đầy đủ phòng khám thể lực, buồng khám sản phụ khoa, buồng khám nam khoa riêng biệt bảo đảm '
                         'quy chế vệ sinh vô khuẩn.',
                 'icon': 'shield-check'},
               { 'title': 'Trang Thiết Bị Cơ Bản',
                 'text': 'Máy đo huyết áp, ống nghe, cân thước đo thể lực, máy chụp X-quang tim phổi, máy siêu âm màu '
                         'tổng quát và phụ khoa.',
                 'icon': 'activity'},
               { 'title': 'Hệ Thống Xét Nghiệm Đạt Chuẩn',
                 'text': 'Máy phân tích huyết học tự động, máy sinh hóa nước tiểu, kính hiển vi soi tươi và sinh phẩm '
                         'xét nghiệm vi-rút.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy chế chuyên môn kỹ thuật - Bộ Y tế',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_18',
    'role': 'CONTENT',
    'section': '4. CƠ SỞ & NGƯỜI CUNG CẤP',
    'assertion_title': 'Mô Hình Tích Hợp: Tư Vấn Đi Liền Với Khám Lâm Sàng',
    'primary_claim': 'Hiệu quả cao nhất đạt được khi cơ sở cung cấp dịch vụ kết hợp trọn vẹn cả tư vấn tâm lý và khám '
                     'kỹ thuật.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Lợi Thế Của Khám Chữa Bệnh',
                 'text': 'Cơ sở khám có đầy đủ phương tiện chẩn đoán xác định, nhưng thường chú trọng xử lý bệnh lý kỹ '
                         'thuật thuần túy mà ít thời gian trao đổi tâm lý.',
                 'icon': 'activity'},
               { 'title': 'Giá Trị Cộng Hưởng Của Tư Vấn',
                 'text': 'Bổ sung khâu tư vấn giúp giải tỏa căng thẳng trước khi khám và định hướng thay đổi hành vi '
                         'lối sống sau khi có kết quả xét nghiệm.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Kết hợp cả tư vấn và khám sức khỏe',
    'illustration': 'illustration_bai_2_structure.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_19',
    'role': 'CONTENT',
    'section': '5. NỘI DUNG DỊCH VỤ',
    'assertion_title': 'Tầm Quan Trọng Toàn Diện Của Khám Tiền Hôn Nhân',
    'primary_claim': 'Là hành động thể hiện trách nhiệm đạo đức và tình yêu cao nhất đối với bạn đời và con cái tương '
                     'lai.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Trách Nhiệm Bản Thân',
                 'text': 'Chủ động kiểm soát thể trạng, phát hiện sớm các bệnh mãn tính hoặc rối loạn chuyển hóa để '
                         'điều trị kịp thời.',
                 'icon': 'user-check'},
               { 'title': 'Trách Nhiệm Bạn Đời',
                 'text': 'Minh bạch về tình trạng sức khỏe, tránh lây nhiễm các bệnh LTQĐTD và chuẩn bị đời sống tình '
                         'dục hòa hợp viên mãn.',
                 'icon': 'heart'},
               { 'title': 'Trách Nhiệm Con Cháu',
                 'text': 'Loại bỏ triệt để nguy cơ truyền gen bệnh dị tật bẩm sinh, bảo đảm thai nhi ra đời khỏe mạnh '
                         'và phát triển tối ưu.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Mục 5 - Ý nghĩa nội dung dịch vụ',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_20',
    'role': 'CONTENT',
    'section': '5.1. TƯ VẤN TRƯỚC KHI KHÁM',
    'assertion_title': 'Nhóm 1: Tư Vấn Sức Khỏe Sinh Sản Vị Thành Niên & Thanh Niên',
    'primary_claim': 'Khởi đầu từ việc trang bị nhận thức khoa học về sự thay đổi tâm sinh lý và xây dựng tình yêu '
                     'lành mạnh.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tâm Sinh Lý & Tình Bạn Tình Yêu',
                 'text': 'Giải thích quá trình dậy thì, nhận thức giới tính, kiểm soát cảm xúc lãng mạn, phân biệt '
                         'tình bạn trong sáng với tình yêu chân chính.',
                 'icon': 'heart'},
               { 'title': 'Tình Dục An Toàn Tuổi Trẻ',
                 'text': 'Khái niệm tình dục đồng thuận, trách nhiệm phòng tránh mang thai sớm ngoài ý muốn và sử dụng '
                         'biện pháp bảo vệ để ngăn ngừa lây nhiễm.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Mục 5.1 - Tư vấn trước khi khám',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_21',
    'role': 'CONTENT',
    'section': '5.1. TƯ VẤN TRƯỚC KHI KHÁM',
    'assertion_title': 'Nhóm 2: Tư Vấn KHHGĐ, Làm Mẹ An Toàn & Chăm Sóc Sơ Sinh',
    'primary_claim': 'Định hình kế hoạch sinh con chủ động và các biện pháp chăm sóc bà mẹ mang thai chu đáo.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Biện Pháp KHHGĐ Phù Hợp',
                 'text': 'Tư vấn ưu nhược điểm của bao cao su, thuốc viên tránh thai kết hợp hoặc phương pháp tính '
                         'ngày đối với cặp đôi mới cưới.',
                 'icon': 'check-circle'},
               { 'title': 'Làm Mẹ An Toàn & Dưỡng Thai',
                 'text': 'Chuẩn bị dinh dưỡng tiền mang thai (axit folic), tiêm phòng uốn ván/rubella, theo dõi thai '
                         'nghén định kỳ tại trạm y tế.',
                 'icon': 'heart'},
               { 'title': 'Chăm Sóc & Nuôi Con Bằng Sữa Mẹ',
                 'text': 'Hướng dẫn kỹ năng cho con bú sớm trong giờ đầu sau sinh, nuôi con hoàn toàn bằng sữa mẹ '
                         'trong 6 tháng đầu đời.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tài liệu đào tạo KHHGĐ và chăm sóc sơ sinh',
    'illustration': 'ai_bai_2_golden.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_22',
    'role': 'CONTENT',
    'section': '5.1. TƯ VẤN TRƯỚC KHI KHÁM',
    'assertion_title': 'Nhóm 3: Phòng Ngừa Bệnh Lây Truyền Qua Đường Tình Dục & HIV',
    'primary_claim': 'Phá vỡ rào cản e ngại để đối diện thẳng thắn với nguy cơ viêm nhiễm đường sinh sản và HIV/AIDS.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Viêm Nhiễm Sinh Dục Thường Gặp',
                 'text': 'Hướng dẫn nhận biết dấu hiệu nấm Candida, trùng roi Trichomonas, vi khuẩn Chlamydia và '
                         'phương pháp vệ sinh vùng kín chuẩn khoa học.',
                 'icon': 'alert-circle'},
               { 'title': 'Bệnh Lây Tình Dục Nguy Hiểm',
                 'text': 'Cung cấp kiến thức bệnh lậu, giang mai, sùi mào gà (HPV), mụn rộp sinh dục và nguy cơ dẫn '
                         'đến vô sinh thứ phát.',
                 'icon': 'shield'},
               { 'title': 'Phòng Ngừa HIV/AIDS Toàn Diện',
                 'text': 'Đường lây truyền HIV, nguyên tắc sử dụng bao cao su đúng cách, xét nghiệm sàng lọc tự nguyện '
                         'và điều trị dự phòng trước phơi nhiễm.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Mục 5.1(2) - Phòng tránh STIs & HIV',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_23',
    'role': 'CONTENT',
    'section': '5.1. TƯ VẤN TRƯỚC KHI KHÁM',
    'assertion_title': 'Nhóm 4: Phòng Ngừa Bạo Lực Tình Dục & Tôn Trọng Quyền Tự Chủ Thân Thể',
    'primary_claim': 'Xây dựng mối quan hệ vợ chồng bình đẳng trên cơ sở tôn trọng tự nguyện và không bạo lực.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Nhận Diện Bạo Lực Tình Dục',
                 'text': 'Bao gồm cưỡng ép quan hệ khi bạn đời không đồng ý, bạo lực thể xác trong quan hệ tình dục, '
                         'xúc phạm tinh thần hoặc kiểm soát hành vi sinh sản.',
                 'icon': 'alert-circle'},
               { 'title': 'Kỹ Năng Ứng Phó & Hỗ Trợ Pháp Lý',
                 'text': 'Trang bị kỹ năng giải quyết bất đồng, tham vấn gia đình, địa chỉ các đường dây nóng hỗ trợ '
                         'nạn nhân bạo lực gia đình và căn cứ bảo vệ của pháp luật.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Mục 5.1(3) - Tư vấn phòng ngừa bạo lực tình dục',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_24',
    'role': 'CONTENT',
    'section': '5.1. TƯ VẤN TRƯỚC KHI KHÁM',
    'assertion_title': 'Nhóm 5: Tư Vấn Các Bệnh Di Truyền Thường Gặp Trong Cộng Đồng',
    'primary_claim': 'Giúp các cặp đôi chủ động nhận diện tiền sử bệnh lý gia đình để có chiến lược xét nghiệm gen phù '
                     'hợp.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Khai Thác Cây Phả Hệ Gia Đình',
                 'text': 'Trao đổi về tiền sử dòng họ 3 đời: có ai mắc bệnh di truyền, sinh con dị tật, sảy thai liên '
                         'tiếp, chậm phát triển trí tuệ không.',
                 'icon': 'users'},
               { 'title': 'Nhận Thức Về Gen Lặn Bệnh Lý',
                 'text': 'Giải thích rõ ràng: người mang gen lặn hoàn toàn khỏe mạnh bình thường nhưng nếu lấy người '
                         'cùng mang gen sẽ sinh con mắc bệnh hiểm nghèo.',
                 'icon': 'activity'},
               { 'title': 'Các Bệnh Di Truyền Phổ Biến',
                 'text': 'Nhấn mạnh bệnh Tan máu bẩm sinh (Thalassemia), bệnh mù màu, bệnh ưa chảy máu (Hemophilia) và '
                         'hội chứng teo cơ tủy.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Mục 5.1(4) - Tư vấn bệnh di truyền',
    'illustration': 'ai_bai_2_quality.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_25',
    'role': 'CONTENT',
    'section': '5.1. TƯ VẤN TRƯỚC KHI KHÁM',
    'assertion_title': 'Nhóm 6: Tác Động Sức Khỏe Bố Mẹ Đến Dị Tật Bẩm Sinh Của Thai Nhi',
    'primary_claim': 'Sức khỏe thể chất, lối sống và bệnh lý nội khoa của bố mẹ quyết định trực tiếp chất lượng phôi '
                     'thai.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Bệnh Lý Nội Khoa Của Người Mẹ',
                 'text': 'Bệnh đái tháo đường, suy tuyến giáp, bệnh tim mạch, lupus ban đỏ nếu chưa được kiểm soát ổn '
                         'định sẽ gây sảy thai hoặc dị tật tim thai nhi.',
                 'icon': 'activity'},
               { 'title': 'Nhiễm Trùng Trong Thai Kỳ',
                 'text': 'Nhiễm Rubella, CMV, Toxoplasma, Giang mai, Viêm gan B trước hoặc trong mang thai gây hội '
                         'chứng dị tật bẩm sinh nặng nề.',
                 'icon': 'alert-circle'},
               { 'title': 'Tác Nhân Môi Trường & Lối Sống',
                 'text': 'Thuốc lá, rượu bia, tiếp xúc hóa chất độc hại, thuốc trừ sâu, bức xạ ion hóa làm tổn thương '
                         'chất lượng tinh trùng và noãn bào.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Mục 5.1(5) - Bệnh bố mẹ liên quan dị tật con',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_26',
    'role': 'CONTENT',
    'section': '5.1. TƯ VẤN SAU KHI KHÁM',
    'assertion_title': 'Ba Kịch Bản Trả Kết Quả Khám Sức Khỏe Tiền Hôn Nhân',
    'primary_claim': 'Sau khi có kết quả khám, cán bộ tư vấn phải phân nhóm chính xác để áp dụng quy trình can thiệp '
                     'tương ứng.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Kịch Bản 1: Kết Quả Bình Thường',
                 'text': 'Thông báo tin vui, giải tỏa áp lực tâm lý; chúc mừng cặp đôi an tâm tiến hành kết hôn và tư '
                         'vấn chế độ dinh dưỡng dưỡng thai.',
                 'icon': 'check-circle'},
               { 'title': 'Kịch Bản 2: Kết Quả Nghi Ngờ',
                 'text': 'Giải thích nhẹ nhàng tính chất nghi ngờ; thuyết phục khách hàng tiếp tục làm các xét nghiệm '
                         'chuyên khoa sâu để xác định chính xác.',
                 'icon': 'help-circle'},
               { 'title': 'Kịch Bản 3: Chẩn Đoán Xác Định',
                 'text': 'Cung cấp trung thực tình trạng bệnh; tư vấn phác đồ điều trị triệt để hoặc các biện pháp '
                         'phòng ngừa biến chứng khi mang thai.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Mục 5.1 - Sau khi khám sức khỏe',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_27',
    'role': 'CONTENT',
    'section': '5.1. TƯ VẤN SAU KHI KHÁM',
    'assertion_title': 'Đồng Hành Hỗ Trợ Khách Hàng Tự Quyết Định Giải Pháp',
    'primary_claim': 'Tôn trọng tuyệt đối quyền tự quyết của khách hàng, đóng vai trò người tư vấn định hướng khách '
                     'quan.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Điều Trị Bệnh Tật Vì Hôn Nhân Bền Vững',
                 'text': 'Đối với các bệnh viêm nhiễm, bệnh phụ khoa, nam khoa có thể chữa khỏi: Động viên cả hai cùng '
                         'điều trị dứt điểm trước khi tổ chức đám cưới để bảo đảm cuộc sống hạnh phúc.',
                 'icon': 'heart'},
               { 'title': 'Tâm Lý Thấu Cảm Và Chia Sẻ',
                 'text': 'Tránh thái độ kỳ thị hoặc làm trầm trọng hóa vấn đề; giúp bạn đời thấu hiểu, thông cảm và '
                         'đồng hành hỗ trợ người yêu vượt qua thử thách bệnh tật.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Sau khi khám - Trao đổi tự quyết định',
    'illustration': 'cinematic_bai_1_hero.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_28',
    'role': 'CONTENT',
    'section': '5.1. TƯ VẤN SAU KHI KHÁM',
    'assertion_title': 'Tư Vấn Tình Huống Đặc Biệt: Gen Bệnh Lý, Bệnh Tim Mạch, HIV',
    'primary_claim': 'Đòi hỏi chuyên môn y học sâu sắc và sự thận trọng cao độ khi tham vấn các bệnh cảnh nguy cơ cao.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Cùng Mang Gen Lặn Bệnh Lý',
                 'text': 'Giải thích nguy cơ 25% con sinh ra bị bệnh thể nặng; hướng dẫn các kỹ thuật chẩn đoán trước '
                         'chuyển phôi (PGD) hoặc chẩn đoán trước sinh.',
                 'icon': 'alert-circle'},
               { 'title': 'Người Nữ Mắc Bệnh Tim Nặng',
                 'text': 'Đánh giá mức độ suy tim (NYHA); cảnh báo nguy cơ tử vong mẹ khi chuyển dạ; tư vấn thời điểm '
                         'sinh con hoặc áp dụng biện pháp tránh thai thích hợp.',
                 'icon': 'activity'},
               { 'title': 'Một Hoặc Cả Hai Nhiễm HIV',
                 'text': 'Tư vấn điều trị thuốc kháng vi-rút ARV đạt tải lượng dưới ngưỡng phát hiện (K=K) và các biện '
                         'pháp can thiệp dự phòng lây truyền sang con.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Trường hợp đặc biệt sau khi khám',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_29',
    'role': 'CONTENT',
    'section': '5.1. TƯ VẤN SAU KHI KHÁM',
    'assertion_title': 'Quy Trình Kết Nối Và Giới Thiệu Chuyển Tuyến Chuyên Khoa',
    'primary_claim': 'Bảo đảm khách hàng tiếp cận đúng cơ sở y tế chuyên khoa sâu để điều trị an toàn, hiệu quả.',
    'visual_job': 'PROCESS_STEPS_HORIZONTAL',
    'visual_anchor': 'PROCESS_CARDS',
    'atoms': [ { 'title': '1. Tổng Hợp Hồ Sơ',
                 'text': 'Tóm tắt đầy đủ kết quả khám lâm sàng, kết quả cận lâm sàng và các chẩn đoán nghi ngờ vào '
                         'giấy giới thiệu.',
                 'icon': 'file-text'},
               { 'title': '2. Cung Cấp Địa Chỉ Uy Tín',
                 'text': 'Cung cấp danh mục các bệnh viện chuyên khoa phụ sản, nam học, viện huyết học truyền máu hoặc '
                         'trung tâm di truyền.',
                 'icon': 'map-pin'},
               { 'title': '3. Hướng Dẫn Thủ Tục',
                 'text': 'Giải thích quy trình đăng ký khám, sử dụng bảo hiểm y tế và các khoản chi phí dự kiến để '
                         'khách hàng chủ động chuẩn bị.',
                 'icon': 'book-open'},
               { 'title': '4. Theo Dõi Phản Hồi',
                 'text': 'Cán bộ y tế cơ sở thiết lập kênh liên lạc để tiếp tục theo dõi tiến độ điều trị và hỗ trợ '
                         'tâm lý dài hạn.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Giới thiệu cơ sở dịch vụ chuyên sâu',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_30',
    'role': 'CONTENT',
    'section': '5.2. KHÁM THỰC THỂ TIỀN HÔN NHÂN',
    'assertion_title': 'Khám Thể Lực: Đo Lường 8 Chỉ Số Sinh Tồn & Thể Lực Nền Tảng',
    'primary_claim': 'Khám thể lực phản ánh sức khỏe tổng thể, khả năng thích ứng lao động và mang thai an toàn.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Chiều Cao, Cân Nặng, Vòng Ngực',
                 'text': 'Đánh giá sự cân đối cơ thể; phụ nữ có chiều cao dưới 145cm hoặc khung chậu hẹp có nguy cơ đẻ '
                         'khó, cần lưu ý.',
                 'icon': 'activity'},
               { 'title': 'Chỉ Số Khối Cơ Thể (BMI)',
                 'text': 'BMI chuẩn (18.5 - 22.9 kg/m2); phát hiện tình trạng gầy còm suy dinh dưỡng hoặc béo phì có '
                         'nguy cơ rối loạn rụng trứng.',
                 'icon': 'trending-up'},
               { 'title': 'Mạch & Huyết Áp',
                 'text': 'Đo huyết áp động mạch phát hiện sớm tiền tăng huyết áp hoặc bệnh lý tim mạch tiềm ẩn trước '
                         'khi mang thai.',
                 'icon': 'heart'},
               { 'title': 'Nhiệt Độ & Nhịp Thở',
                 'text': 'Xác định thân nhiệt và tần số hô hấp nhằm sàng lọc các tình trạng nhiễm trùng cấp tính hoặc '
                         'bệnh phổi mãn tính.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Mục 5.2 - a. Khám thể lực',
    'illustration': 'illustration_bai_2.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_31',
    'role': 'CONTENT',
    'section': '5.2. KHÁM LÂM SÀNG NỮ GIỚI',
    'assertion_title': 'Khám Phát Hiện Dấu Hiệu Cơ Năng & Khai Thác Tiền Sử Ở Nữ',
    'primary_claim': 'Khai thác tiền sử kỹ lưỡng giúp gợi mở các bệnh lý sản phụ khoa tiềm ẩn mà khám thực thể có thể '
                     'bỏ sót.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tiền Sử Bệnh Nội - Ngoại Khoa',
                 'text': 'Hỏi rõ tiền sử mắc bệnh tim mạch, tăng huyết áp, viêm gan, bệnh thận, lao phổi, động kinh '
                         'hoặc các phẫu thuật vùng bụng trước đây.',
                 'icon': 'file-text'},
               { 'title': 'Tiền Sử Sản Khoa Cụ Thể',
                 'text': 'Đã từng mang thai, sảy thai, thai lưu, nạo hút thai hoặc có tiền sử thai ngoài tử cung, đẻ '
                         'non, nhiễm độc thai nghén hay không.',
                 'icon': 'clock'},
               { 'title': 'Tiền Sử Phụ Khoa & Kinh Nguyệt',
                 'text': 'Tuổi bắt đầu có kinh, chu kỳ kinh (đều hay không đều), thời gian hành kinh, lượng máu kinh, '
                         'hiện tượng đau bụng kinh và khí hư bất thường.',
                 'icon': 'calendar'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Mục 5.2 - Khám nữ giới: dấu hiệu cơ năng',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_32',
    'role': 'CONTENT',
    'section': '5.2. KHÁM LÂM SÀNG NỮ GIỚI',
    'assertion_title': 'Thăm Khám Tuyến Vú & Bộ Phận Sinh Dục Ngoài Ở Nữ',
    'primary_claim': 'Đánh giá hình thái cơ thể và phát hiện sớm các dị tật bẩm sinh hoặc viêm nhiễm sinh dục.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Khám Tuyến Vú Toàn Diện',
                 'text': 'Quan sát độ cân đối hai bên vú, núm vú tụt; sờ nắn nhẹ nhàng theo 4 góc phần tư để tầm soát '
                         'khối u vú, nang vú, tiết dịch đầu vú.',
                 'icon': 'activity'},
               { 'title': 'Khám Bộ Phận Sinh Dục Ngoài',
                 'text': 'Quan sát phân bố lông mu, hình thái âm hộ, môi lớn, môi bé; phát hiện sớm tình trạng dính '
                         'môi bé, u nang tuyến Bartholin.',
                 'icon': 'shield'},
               { 'title': 'Màng Trinh & Dịch Âm Đạo',
                 'text': 'Kiểm tra tình trạng màng trinh (nguyên vẹn hay rách, màng trinh không thủng), quan sát màu '
                         'sắc, mùi và độ sánh của dịch âm đạo.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Khám vú và bộ phận sinh dục ngoài nữ',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_33',
    'role': 'CONTENT',
    'section': '5.2. KHÁM LÂM SÀNG NỮ GIỚI',
    'assertion_title': 'Nguyên Tắc Đạo Đức & Kỹ Thuật Thăm Khám Âm Đạo Ở Nữ',
    'primary_claim': 'Bắt buộc phải có sự đồng ý của khách hàng và tuyệt đối tôn trọng yếu tố văn hóa tâm lý truyền '
                     'thống.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Thăm Khám Âm Đạo (Có Điều Kiện)',
                 'text': 'Chỉ thực hiện thăm khám âm đạo bằng mỏ vịt và lấy dịch khi có chỉ định chẩn đoán xác định và '
                         'BẮT BUỘC PHẢI ĐƯỢC SỰ ĐỒNG Ý của khách hàng (thường áp dụng cho người đã có quan hệ tình '
                         'dục).',
                 'icon': 'shield-check'},
               { 'title': 'Phương Án Thay Thế Qua Trực Tràng',
                 'text': 'Nếu khách hàng chưa từng quan hệ tình dục hoặc không đồng ý khám âm đạo: Bác sĩ giải thích '
                         'lý do và thay thế bằng thăm khám phụ khoa qua đường hậu môn - trực tràng để kiểm tra tử '
                         'cung, phần phụ.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy tắc đạo đức y khoa trong khám sản phụ khoa - BÀI 2',
    'illustration': 'illustration_bai_2_structure.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_34',
    'role': 'CONTENT',
    'section': '5.2. KHÁM LÂM SÀNG NAM GIỚI',
    'assertion_title': 'Khám Dấu Hiệu Cơ Năng & Tiền Sử Bệnh Nam Khoa',
    'primary_claim': 'Khai thác cởi mở tiền sử sinh lý giúp phát hiện nguyên nhân gây suy giảm sinh tinh và rối loạn '
                     'tình dục.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tiền Sử Bệnh Nội Ngoại & Quai Bị',
                 'text': 'Hỏi rõ tiền sử quai bị có biến chứng viêm teo tinh hoàn không, chấn thương tầng sinh môn, '
                         'phẫu thuật thoát vị bẹn.',
                 'icon': 'file-text'},
               { 'title': 'Tiền Sử Bệnh LTQĐTD',
                 'text': 'Đã từng mắc lậu, giang mai, tiểu buốt, tiểu rắt, chảy mủ niệu đạo hoặc các vết loét sinh dục '
                         'trong quá khứ hay chưa.',
                 'icon': 'alert-circle'},
               { 'title': 'Chức Năng Cương Dương & Xuất Tinh',
                 'text': 'Tìm hiểu tình trạng rối loạn cương dương, xuất tinh sớm, xuất tinh ngược dòng hoặc hiện '
                         'tượng đau buốt khi quan hệ tình dục.',
                 'icon': 'activity'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Mục 5.2 - Khám nam giới: dấu hiệu cơ năng',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_35',
    'role': 'CONTENT',
    'section': '5.2. KHÁM LÂM SÀNG NAM GIỚI',
    'assertion_title': 'Thăm Khám Bộ Phận Sinh Dục & Cơ Quan Sinh Dục Nam',
    'primary_claim': 'Khám thực thể nam học đánh giá trực tiếp hình thái giải phẫu và khả năng sinh sản của phái mạnh.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Khám Dương Vật & Bao Quy Đầu',
                 'text': 'Phát hiện tình trạng hẹp bao quy đầu, nghẹt bao quy đầu, viêm quy đầu, lỗ tiểu đóng thấp '
                         'hoặc cong vẹo dương vật.',
                 'icon': 'shield'},
               { 'title': 'Khám Tinh Hoàn & Mào Tinh',
                 'text': 'Sờ nắn hai bên tinh hoàn xác định kích thước, mật độ, vị trí trong bìu; phát hiện tinh hoàn '
                         'ẩn, teo tinh hoàn hoặc u tinh hoàn.',
                 'icon': 'activity'},
               { 'title': 'Thừng Tinh & Giãn Tĩnh Mạch Thừng Tinh',
                 'text': 'Sờ nắn thừng tinh tư thế đứng và nằm để phát hiện giãn tĩnh mạch thừng tinh (nguyên nhân '
                         'hàng đầu gây vô sinh nam).',
                 'icon': 'trending-up'},
               { 'title': 'Lấy Dịch Niệu Đạo & Khám Trực Tràng',
                 'text': 'Lấy bệnh phẩm dịch niệu đạo làm xét nghiệm; thăm khám trực tràng đánh giá tuyến tiền liệt '
                         'khi có chỉ định chuyên môn.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Quy trình khám nam khoa chuẩn y khoa - BÀI 2',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_36',
    'role': 'CONTENT',
    'section': '5.2. CẬN LÂM SÀNG TIÊU CHUẨN',
    'assertion_title': 'Bộ 4 Kỹ Thuật Cận Lâm Sàng Tiêu Chuẩn Cho Cặp Đôi Tiền Hôn Nhân',
    'primary_claim': 'Các kỹ thuật xét nghiệm và chẩn đoán hình ảnh khách quan cung cấp bằng chứng y học chuẩn xác.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': '1. Chụp X-quang Tim Phổi',
                 'text': 'Chụp phim tư thế thẳng hoặc nghiêng nhằm tầm soát sớm bệnh lao phổi tiến triển, tổn thương '
                         'nhu mô và bóng tim to.',
                 'icon': 'activity'},
               { 'title': '2. Xét Nghiệm Máu Nền Tảng',
                 'text': 'Tổng phân tích tế bào máu ngoại vi (Hb, MCV, MCH), định lượng đường huyết (Glucose) phát '
                         'hiện đái tháo đường và thiếu máu.',
                 'icon': 'file-text'},
               { 'title': '3. Tổng Phân Tích Nước Tiểu',
                 'text': 'Xét nghiệm que thử 10 thông số: đường niệu, protein niệu, hồng cầu, bạch cầu nhằm phát hiện '
                         'bệnh lý cầu thận, nhiễm trùng tiết niệu.',
                 'icon': 'check-circle'},
               { 'title': '4. Soi Tươi Dịch Sinh Dục',
                 'text': 'Soi tươi dịch âm đạo ở nữ và dịch niệu đạo ở nam dưới kính hiển vi phát hiện nấm, trùng roi, '
                         'vi khuẩn Gram âm/dương.',
                 'icon': 'search'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Mục 5.2 - c. Khám cận lâm sàng',
    'illustration': 'ai_bai_2_golden.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_37',
    'role': 'CONTENT',
    'section': '5.3. BỆNH TẬT BẨM SINH & DI TRUYỀN',
    'assertion_title': 'Cấu Trúc Căn Nguyên Gây Dị Tật Bẩm Sinh Ở Trẻ Em',
    'primary_claim': 'Nghiên cứu di truyền học khẳng định vai trò phức hợp của gen, nhiễm sắc thể và môi trường thai '
                     'kỳ.',
    'visual_job': 'CHART_AND_INSIGHTS',
    'visual_anchor': 'CHART_AND_INSIGHTS',
    'atoms': [ { 'title': '5% Do Đột Biến Gen Đơn Chiếc',
                 'text': 'Các bệnh lý do đột biến trên từng gen cụ thể, di truyền theo quy luật Mendel như '
                         'Thalassemia, mù màu, Hemophilia.',
                 'icon': 'activity'},
               { 'title': '5% Bất Thường Nhiễm Sắc Thể',
                 'text': 'Đột biến số lượng hoặc cấu trúc NST: Hội chứng Down (Trisomy 21), Edwards (Trisomy 18), '
                         'Patau (Trisomy 13), Turner.',
                 'icon': 'alert-circle'},
               { 'title': '90% Do Đa Yếu Tố (Tương Tác Gen - Môi Trường)',
                 'text': 'Kết hợp giữa cơ địa nhạy cảm di truyền với tác nhân môi trường (hóa chất, dinh dưỡng thiếu '
                         'hụt axit folic, nhiễm khuẩn, thuốc).',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Số liệu dịch tễ học di truyền - BÀI 2. Mục 5.2',
    'chart_type': 'COLUMN_CLUSTERED',
    'chart_file': 'chart_fertility_trends_dark.png',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_38',
    'role': 'CONTENT',
    'section': '5.3. BỆNH TẬT BẨM SINH & DI TRUYỀN',
    'assertion_title': 'Hệ Lụy Bi Kịch Của Thiếu Hiểu Biết Về Sức Khỏe Sinh Sản',
    'primary_claim': 'Không khám tiền hôn nhân dẫn đến nhiều đứa trẻ sinh ra mắc dị tật nặng nề, là nỗi đau suốt đời '
                     'cho gia đình.',
    'visual_job': 'CONTAINER_HERO_SPLIT_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Dị Tật Ống Thần Kinh Tử Vong Ngay Sau Sinh',
                 'text': 'Thiếu hụt axit folic và không tầm soát trước kết hôn dẫn đến thai vô sọ (không có não), '
                         'thoát vị não - màng não, não úng thủy, trẻ tử vong ngay khi chào đời.',
                 'icon': 'alert-circle'},
               { 'title': 'Dị Tật Hình Thái & Nỗi Đau Kéo Dài',
                 'text': 'Trẻ sống sót nhưng phải gánh chịu tật sứt môi hở hàm ếch, teo cơ tứ chi, dính ngón, dị tật '
                         'cơ quan sinh dục không rõ giới tính, bại não, tạo gánh nặng chăm sóc khổng lồ.',
                 'icon': 'heart'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Khảo sát lâm sàng dị tật bẩm sinh - BÀI 2',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_39',
    'role': 'CONTENT',
    'section': '5.3. BỆNH TẬT BẨM SINH & DI TRUYỀN',
    'assertion_title': 'Hội Chứng Down (Trisomy 21): Bất Thường Nhiễm Sắc Thể Phổ Biến Nhất',
    'primary_claim': 'Hội chứng xuất hiện với tần suất cao và có tương quan mật thiết với độ tuổi mang thai của người '
                     'mẹ.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Tần Suất 1/700 Trẻ Sơ Sinh',
                 'text': 'Hội chứng Down là bất thường số lượng NST thường gặp nhất trong cộng đồng, do thừa một nhiễm '
                         'sắc thể số 21.',
                 'icon': 'trending-up'},
               { 'title': 'Tương Quan Thuận Với Tuổi Mẹ',
                 'text': 'Mẹ dưới 30 tuổi nguy cơ 1/1.000; mẹ 35 tuổi tăng lên 1/350; mẹ trên 40 tuổi nguy cơ lên tới '
                         '1/100 do noãn bào lão hóa.',
                 'icon': 'clock'},
               { 'title': 'Đặc Điểm Lâm Sàng Trẻ Mắc Bệnh',
                 'text': 'Khuôn mặt đặc trưng (mắt xếch, mũi tẹt, lưỡi to dày), chậm phát triển trí tuệ nặng và kèm '
                         'theo 50% dị tật tim bẩm sinh.',
                 'icon': 'alert-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Dịch tễ học Hội chứng Down - BÀI 2',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_40',
    'role': 'CONTENT',
    'section': '5.3. BỆNH TẬT BẨM SINH & DI TRUYỀN',
    'assertion_title': 'Thalassemia (Tan Máu Bẩm Sinh): Quy Luật Di Truyền Gen Lặn',
    'primary_claim': 'Bệnh lưu hành âm thầm qua nhiều thế hệ và chỉ bùng phát khi hai người cùng mang gen kết hôn với '
                     'nhau.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Ẩn Tàng Qua Nhiều Thế Hệ',
                 'text': 'Người mang gen thể lặn hoàn toàn khỏe mạnh bình thường; dòng họ có thể mang gen qua nhiều '
                         'đời mà không phát hiện.',
                 'icon': 'users'},
               { 'title': 'Quy Luật Xác Suất Mendel',
                 'text': 'Khi cả hai vợ chồng đều mang gen lặn: 25% con sinh ra hoàn toàn bình thường, 50% con mang '
                         'gen lặn, 25% con bị bệnh THỂ NẶNG.',
                 'icon': 'activity'},
               { 'title': 'Ý Nghĩa Của Khám Sàng Lọc',
                 'text': 'Xét nghiệm công thức máu kiểm tra MCV, MCH giúp sàng lọc mang gen với chi phí rất thấp trước '
                         'khi đăng ký kết hôn.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Cơ chế di truyền Thalassemia - BÀI 2',
    'illustration': 'ai_bai_2_quality.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_41',
    'role': 'CONTENT',
    'section': '5.3. BỆNH TẬT BẨM SINH & DI TRUYỀN',
    'assertion_title': 'Biến Chứng Lâm Sàng Nặng Nề Của Bệnh Nhân Thalassemia Thể Nặng',
    'primary_claim': 'Bệnh nhân phải điều trị truyền máu và thải sắt suốt đời, biến dạng cơ thể và giảm sút tuổi thọ '
                     'nghiêm trọng.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Truyền Máu & Thải Sắt Định Kỳ',
                 'text': 'Hồng cầu vỡ sớm gây thiếu máu mạn tính nặng nề; bệnh nhân phải nhập viện truyền khối hồng '
                         'cầu và tiêm thuốc thải sắt suốt đời.',
                 'icon': 'activity'},
               { 'title': 'Biến Dạng Xương Mặt Đặc Trưng',
                 'text': 'Tủy xương tăng sinh phản ứng làm trán dô, gò má cao, mũi tẹt, răng hô vẩu (khuôn mặt '
                         'Thalassemia đặc trưng).',
                 'icon': 'alert-circle'},
               { 'title': 'Suy Đa Tạng & Gan Lách To',
                 'text': 'Lắng đọng sắt gây xơ gan, suy tim ứ huyết, suy tuyến nội tiết (đái tháo đường, suy giáp) dẫn '
                         'đến tử vong sớm ở tuổi thanh xuân.',
                 'icon': 'heart'},
               { 'title': 'Gánh Nặng Tài Chính Khổng Lồ',
                 'text': 'Chi phí điều trị ước tính hàng tỷ đồng cho một bệnh nhân, tạo áp lực kiệt quệ cho gia đình '
                         'và quỹ bảo hiểm y tế.',
                 'icon': 'trending-up'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Gánh nặng bệnh tật Thalassemia - BÀI 2',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_42',
    'role': 'CONTENT',
    'section': '5.4. BỆNH TRUYỀN NHIỄM NGUY HIỂM',
    'assertion_title': 'Sàng Lọc HIV Trước Kết Hôn & Can Thiệp Dự Phòng Lây Truyền Mẹ - Con',
    'primary_claim': 'Tư vấn và điều trị ARV sớm giúp giảm tỷ lệ lây truyền từ mẹ sang con từ trên 30% xuống dưới 2%.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Thực Trạng Phát Hiện Muộn',
                 'text': 'Nhiều phụ nữ chỉ phát hiện nhiễm HIV khi đến viện sinh con do trước kết hôn không đi khám '
                         'sức khỏe, không rõ tình trạng bạn đời.',
                 'icon': 'alert-circle'},
               { 'title': 'Tỷ Lệ Lây Nhiễm Tự Nhiên (>30%)',
                 'text': 'Nếu không được điều trị can thiệp, cứ 3 người mẹ nhiễm HIV sinh con sẽ có 1 trẻ bị nhiễm '
                         'vi-rút từ trong tử cung, lúc sinh hoặc cho bú.',
                 'icon': 'trending-up'},
               { 'title': 'Kỳ Tích Điều Trị Can Thiệp (<2%)',
                 'text': 'Được khám trước kết hôn, điều trị thuốc ARV tải lượng dưới ngưỡng ức chế giúp mẹ sinh con '
                         'khỏe mạnh hoàn toàn với tỷ lệ lây <2%.',
                 'icon': 'shield-check'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Dự phòng lây truyền HIV từ mẹ sang con - BÀI 2',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_43',
    'role': 'CONTENT',
    'section': '5.4. BỆNH TRUYỀN NHIỄM NGUY HIỂM',
    'assertion_title': 'Động Học Lây Truyền Viêm Gan B Từ Mẹ Sang Con Theo 3 Giai Đoạn Thai Kỳ',
    'primary_claim': 'Nguy cơ lây nhiễm tăng vọt vào 3 tháng cuối và có thể lên tới 90% nếu không bảo vệ sau sinh.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': '3 Tháng Đầu Thai Kỳ (1%)',
                 'text': 'Hàng rào nhau thai bảo vệ tốt, tỷ lệ vi-rút truyền sang phôi thai chỉ xấp xỉ 1%.',
                 'icon': 'clock'},
               { 'title': '3 Tháng Giữa Thai Kỳ (10%)',
                 'text': 'Bánh nhau phát triển và mỏng dần, tỷ lệ lây truyền vi-rút từ mẹ sang con tăng lên khoảng '
                         '10%.',
                 'icon': 'trending-up'},
               { 'title': '3 Tháng Cuối Thai Kỳ (60 - 70%)',
                 'text': 'Tổ chức bánh nhau suy giảm độ dày, xuất hiện các vết nứt vi thể làm tỷ lệ lây nhiễm tăng vọt '
                         'lên 60 - 70%.',
                 'icon': 'alert-circle'},
               { 'title': '90% Trẻ Mắc Nếu Không Tiêm',
                 'text': 'Không tiêm kháng huyết thanh (HBIG) và vắc xin trong 24h đầu: 90% trẻ nhiễm, 50% tiến triển '
                         'thành viêm gan mạn và xơ gan.',
                 'icon': 'shield'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Động học lây truyền viêm gan B - BÀI 2',
    'illustration': 'cinematic_bai_1_hero.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_44',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Mục Tiêu Nghị Quyết 21-NQ/TW & Chiến Lược Dân Số Việt Nam Đến Năm 2030',
    'primary_claim': 'Chỉ tiêu pháp lệnh đòi hỏi 90% cặp nam, nữ thanh niên được tư vấn, khám sức khỏe trước khi kết '
                     'hôn.',
    'visual_job': 'CONTAINER_THREE_PILLARS_CARDS',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Chỉ Tiêu Chiến Lược 90%',
                 'text': 'Đến năm 2030, tỷ lệ cặp nam, nữ thanh niên được tư vấn, khám sức khỏe trước khi kết hôn đạt '
                         'mức 90% trên toàn quốc.',
                 'icon': 'target'},
               { 'title': 'Quyết Định Số 25/QĐ-BYT',
                 'text': 'Khung pháp lý chuyên môn của Bộ Y tế ban hành ngày 07/01/2011 hướng dẫn chuẩn hóa quy trình '
                         'kỹ thuật khám tiền hôn nhân.',
                 'icon': 'file-text'},
               { 'title': 'Chuyển Trọng Tâm Chính Sách',
                 'text': 'Chuyển mạnh từ Kế hoạch hóa gia đình đơn thuần sang Dân số và Phát triển, lấy nâng cao chất '
                         'lượng dân số làm trọng tâm cốt lõi.',
                 'icon': 'award'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Nghị quyết số 21-NQ/TW và Chiến lược Dân số Việt Nam đến 2030',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_45',
    'role': 'CONTENT',
    'section': '6. CÔNG TÁC QUẢN LÝ',
    'assertion_title': 'Phân Cấp Quản Lý Và Tác Nghiệp Hệ Thống Y Tế 4 Tuyến',
    'primary_claim': 'Mô hình vận hành đồng bộ từ cơ quan tham mưu chính sách Trung ương đến cộng tác viên cơ sở.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Tuyến Trung Ương: Bộ Y Tế (Cục Dân Số)',
                 'text': 'Chủ trì xây dựng kế hoạch quốc gia, bố trí nguồn lực, ban hành quy chế chuyên môn, kiểm tra '
                         'giám sát và tổng hợp báo cáo định kỳ.',
                 'icon': 'shield-check'},
               { 'title': 'Tuyến Tỉnh: Sở Y Tế (Chi Cục Dân Số)',
                 'text': 'Chỉ đạo, giám sát trên địa bàn tỉnh; các bệnh viện tỉnh thực hiện đào tạo kỹ thuật, xét '
                         'nghiệm chuyên sâu và hỗ trợ tuyến dưới.',
                 'icon': 'layers'},
               { 'title': 'Tuyến Huyện: Trung Tâm Y Tế / BVĐK',
                 'text': 'Tổ chức khám lâm sàng, cận lâm sàng cơ bản, tập huấn kỹ thuật cho trạm y tế và giám sát hoạt '
                         'động tư vấn tiền hôn nhân toàn huyện.',
                 'icon': 'activity'},
               { 'title': 'Tuyến Xã: Trạm Y Tế & CTV Thôn Bản',
                 'text': 'Truyền thông trực tiếp tại cộng đồng, rà soát thanh niên đến tuổi kết hôn, hướng dẫn đến cơ '
                         'sở khám và theo dõi ca bệnh di truyền.',
                 'icon': 'users'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'BÀI 2. Mục 6 - Công tác quản lý dịch vụ 4 tuyến',
    'illustration': 'illustration_bai_2.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_46',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 1: Ý Nghĩa Sư Phạm Của Việc Tách Biệt Tư Vấn Trước Và Sau Khám',
    'primary_claim': 'Học viên phân tích cấu trúc tâm lý khách hàng để thấu hiểu sự cần thiết của quy trình 2 giai '
                     'đoạn.',
    'visual_job': 'EDITORIAL_HERO',
    'visual_anchor': 'EDITORIAL_HERO',
    'atoms': [ { 'title': 'Giai Đoạn Trước Khám: Khơi Mở Nhận Thức',
                 'text': 'Cung cấp tri thức nền tảng, giải tỏa áp lực e ngại, giải thích ý nghĩa từng hạng mục xét '
                         'nghiệm giúp khách hàng tự nguyện và hợp tác tối đa khi thăm khám.',
                 'icon': 'book-open'},
               { 'title': 'Giai Đoạn Sau Khám: Định Hướng Quyết Định',
                 'text': 'Dựa trên chứng cứ xét nghiệm xác thực để tham vấn giải pháp điều trị, tư vấn hôn nhân, hỗ '
                         'trợ tâm lý và lập kế hoạch sinh nở an toàn phù hợp thực tế.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Câu hỏi lượng giá số 1 - BÀI 2',
    'illustration': 'illustration_bai_2_structure.jpg',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_47',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 2: Kịch Bản Xử Trí Khi Cặp Đôi Cùng Phát Hiện Mang Gen Thalassemia',
    'primary_claim': 'Tình huống thực tế thử thách bản lĩnh chuyên môn và kỹ năng giao tiếp y khoa nhân văn của học '
                     'viên.',
    'visual_job': 'PROCESS_DEVSECOPS_PIPELINE',
    'visual_anchor': 'PROCESS_CARDS',
    'atoms': [ { 'title': '1. Trấn An Tâm Lý',
                 'text': 'Khẳng định cả hai vẫn hoàn toàn khỏe mạnh; mang gen thể lặn không làm giảm sút chức năng '
                         'sống hay tình yêu đôi lứa.',
                 'icon': 'heart'},
               { 'title': '2. Giải Thích Xác Suất',
                 'text': 'Minh họa khoa học xác suất sinh con: 75% thai nhi không bị bệnh thể nặng (25% hoàn toàn '
                         'khỏe, 50% mang gen lặn).',
                 'icon': 'activity'},
               { 'title': '3. Giới Thiệu Giải Pháp',
                 'text': 'Tư vấn phương pháp thụ tinh trong ống nghiệm kết hợp chẩn đoán di truyền phôi (PGD) để chọn '
                         'phôi hoàn toàn khỏe mạnh.',
                 'icon': 'shield-check'},
               { 'title': '4. Chẩn Đoán Trước Sinh',
                 'text': 'Nếu mang thai tự nhiên: Hướng dẫn chọc ối hoặc sinh thiết gai nhau ở tuần 12-16 thai kỳ để '
                         'chẩn đoán xác định sớm tình trạng phôi thai.',
                 'icon': 'target'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Tình huống lâm sàng Thalassemia - BÀI 2 Câu 2',
    'v91_compliant': True},
  { 'slide_id': 'SLIDE_48',
    'role': 'CONTENT',
    'section': 'LƯỢNG GIÁ & THẢO LUẬN',
    'assertion_title': 'Câu Hỏi 3: Kế Hoạch Hành Động Địa Phương Đạt Chỉ Tiêu 90% Vào Năm 2030',
    'primary_claim': 'Tổng kết chuyên đề bằng đề án thực thi liên ngành, sáng tạo truyền thông và xã hội hóa nguồn '
                     'lực.',
    'visual_job': 'CONTAINER_FOUR_CARDS_GRID',
    'visual_anchor': 'SECTION_CARDS',
    'atoms': [ { 'title': 'Liên Ngành Tư Pháp - Y Tế',
                 'text': 'Phối hợp chặt chẽ với bộ phận Tư pháp cấp xã: lồng ghép tư vấn khám sức khỏe khi công dân '
                         'đến làm thủ tục đăng ký kết hôn.',
                 'icon': 'file-text'},
               { 'title': 'Chính Sách Hỗ Trợ Kinh Phí',
                 'text': 'Tham mưu Hội đồng nhân dân địa phương ban hành nghị quyết hỗ trợ 100% kinh phí xét nghiệm '
                         'cho đối tượng nghèo, cận nghèo.',
                 'icon': 'award'},
               { 'title': 'Chuyển Đổi Số Truyền Thông',
                 'text': 'Tận dụng mạng xã hội (TikTok, Zalo, Facebook) và các ứng dụng thanh niên để truyền thông xóa '
                         'bỏ tâm lý e ngại của giới trẻ.',
                 'icon': 'globe'},
               { 'title': 'Nâng Cao Chất Lượng Dịch Vụ',
                 'text': 'Cải cách thủ tục hành chính, hẹn giờ khám trực tuyến, bảo đảm không gian riêng tư và thái độ '
                         'phục vụ văn minh, tận tụy.',
                 'icon': 'check-circle'}],
    'transition': 'morph',
    'transition_duration': 0.85,
    'atomic_card': True,
    'safe_group': True,
    'source_footer': 'Kế hoạch hành động dân số 2030 - BÀI 2 Câu 3',
    'v91_compliant': True}]
